{
  "hash": "9dca682d52cb5dcb21a3ba29c4fdcfc0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Linear Regression\"\nsubtitle: \"CRJU 705 · Session 10 · Fall 2026\"\nauthor: \"Scott M. Mourtgos\"\nformat:\n  revealjs:\n    slide-number: true\n    preview-links: auto\n    chalkboard: true\n    footer: \"CRJU 705 · Session 10\"\n    theme: [default, custom-slides.scss]\n    fig-align: center\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n## This Week\n\n- **Least squares**, the line of best fit, and **R²**\n- Two predictors: the best-fitting **plane**, and you'll spin it with your mouse\n- *\"Holding the others constant\"*: reading coefficients honestly\n- Diagnostics: the residual plot and **VIF**\n- The **Bayesian version** with `brms`; reporting both traditions\n\n**Learning goals:** fit, interpret, and diagnose `lm()` with several predictors, and say what a coefficient does *and doesn't* mean.\n\n**Project:** Homework 10 contains **Checkpoint 3**: your first regression on *your* data.\n\n## Where We've Been\n\n::: incremental\n- **Session 8:** correlation: *r* measured how tightly two variables move together; *r²* was the variance they share\n- Two humility rules came with it: **correlation is not causation**, and **area-level patterns are not people-level claims** (the ecological fallacy)\n- **Today:** correlation says *that* two variables travel together. Regression answers the sharper question: **how much**, and with several predictors, how much does each matter *after accounting for the others*?\n:::\n\n## The New Question\n\nCorrelation is a **one-lane road** between two variables.\n\nMultiple regression adds more lanes, but all the traffic still arrives at one place: the outcome, $Y$. Each predictor lane contributes part of how we got there.\n\n. . .\n\nThe question multiple regression answers:\n\n> **\"How much does Y change when $X_1$ changes by one unit, *holding $X_2$ constant*?\"**\n\n. . .\n\nThat phrase, *holding constant*, is the entire value added today. We'll earn it slowly.\n\n# One Predictor, One Line {background-color=\"#73000A\"}\n\n## The Model, With One Predictor\n\n$$Y = a + bX + e$$\n\n| Piece | Name | Meaning |\n|-------|------|---------|\n| $Y$ | outcome | the thing we're predicting (DV) |\n| $a$ | intercept | predicted $Y$ when $X = 0$ |\n| $b$ | slope | change in predicted $Y$ per one-unit change in $X$ |\n| $e$ | error | what the line leaves unexplained |\n\nThe model is a claim: *knowing X, here's my best guess at Y, plus some miss.*\n\nThe **residual** is each observation's miss: actual $Y$ minus predicted $Y$.\n\n## Ten Students, Hours and Scores\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\n# seed 1 kept from the 2025 deck: the three\n# candidate lines coming up were tuned to this draw\nset.seed(1)\nstudents <- tibble(\n  hours = 1:10,\n  score = 40 + 5 * hours + rnorm(10, 0, 5)\n)\n\nggplot(students, aes(hours, score)) +\n  geom_point(size = 4, color = crju_colors[\"navy\"]) +\n  labs(x = \"Hours studied\", y = \"Exam score\")\n```\n\n::: {.cell-output-display}\n![](week-11-regression_files/figure-revealjs/ls-data-1.png){width=576}\n:::\n:::\n\n\nSome line through this cloud is the \"best\" one. **Best by what ruler?**\n\n## Three Candidate Lines\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-11-regression_files/figure-revealjs/ls-candidates-1.png){width=960}\n:::\n:::\n\n\n## The Ruler: Sum of Squared Residuals\n\nFor any candidate line, measure every vertical miss, square it (so misses above and below don't cancel), and add them up:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSSR <- function(a, b) {\n  predicted <- a + b * students$hours\n  sum((students$score - predicted)^2)\n}\n\nSSR(20, 5)      # too low\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4405.871\n```\n\n\n:::\n\n```{.r .cell-code}\nSSR(50, 3)      # too flat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 584.9933\n```\n\n\n:::\n\n```{.r .cell-code}\nSSR(37, 5.2)    # roughly right\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 196.9529\n```\n\n\n:::\n:::\n\n\n. . .\n\nSmaller total = better line. **Least squares** = find the line with the smallest total of all.\n\n## `lm()` Finds the Winner\n\nNo trial and error: `lm()` solves for the one line that minimizes SSR:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_hours <- lm(score ~ hours, data = students)\ncoef(fit_hours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       hours \n   39.15588     5.27366 \n```\n\n\n:::\n\n```{.r .cell-code}\nSSR(coef(fit_hours)[1], coef(fit_hours)[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 130.9173\n```\n\n\n:::\n:::\n\n\n. . .\n\nOur best hand-picked guess left 197 in squared misses; `lm()` gets it down to 131, and **no other line does better**.\n\nRead the slope: each additional hour of studying predicts about **5.3 more points**, in this sample.\n\n## Watching the Search Land\n\n![](../media/week-11/BestFit.gif)\n\nThe line tilts until the SSR stops shrinking, then it's *the* least-squares line.\n\n## What the Line Leaves Behind\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-11-regression_files/figure-revealjs/ls-residuals-1.png){width=960}\n:::\n:::\n\n\n## R²: How Much Did We Explain?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_hours)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9460216\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(students$hours, students$score)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9460216\n```\n\n\n:::\n:::\n\n\n::: incremental\n- **R² = the proportion of the outcome's variance the model accounts for.** Here, hours studied explain ~95% of the spread in scores (it's simulated data: real life will humble us shortly).\n- Notice the second line: with one predictor, **R² is just Session 8's correlation, squared**. Same quantity, new outfit.\n- With *multiple* predictors, R² keeps the same meaning (variance explained by the whole team), but no single correlation owns it anymore.\n:::\n\n# More Lanes: Multiple Predictors {background-color=\"#1B2A4A\"}\n\n## The Model, Full Form\n\n$$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\cdots + \\beta_k X_k + e$$\n\n- $\\beta_0$ (intercept): predicted $Y$ when **every** $X$ is zero (often a nonsense scenario; it anchors the model, it doesn't need to be meaningful)\n- $\\beta_1 \\ldots \\beta_k$ (slopes): the effect of each $X$ ***holding the others constant***\n- $e$ (error): what's still unexplained\n\n. . .\n\nEach $\\beta$ is conceptually a **partial** relationship: how $X_1$ relates to $Y$ *after removing the overlap* with the other predictors. That's what makes multiple regression more than a stack of correlations.\n\n## From Line to Plane\n\n::: incremental\n- One predictor: the model is a **line** through a 2-D cloud\n- Two predictors: the model is a **plane** floating in a 3-D cloud, with one slope along each predictor's axis\n- The ruler never changes: **least squares**, which minimizes the total squared vertical distance from every point to the surface\n- Three or more predictors: a *hyperplane* in a space we can't draw. The math shrugs; only our eyes give out.\n:::\n\n. . .\n\nTwo predictors is the last stop where we can actually **see** the model. So let's look at it properly.\n\n## The Best-Fitting Plane, Live\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-cf63773417a5f3d493ca\" style=\"width:950px;height:520px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-cf63773417a5f3d493ca\">{\"x\":{\"visdat\":{\"b88b41fb61d9\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"b88b41fb61d9\",\"attrs\":{\"b88b41fb61d9\":{\"x\":{},\"y\":{},\"z\":{},\"mode\":\"markers\",\"marker\":{\"size\":4,\"color\":\"blue\"},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\"},\"b88b41fb61d9.1\":{\"x\":[[0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389],[0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726],[1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447],[1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102],[2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595],[2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171],[3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742],[3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317],[4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892],[4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463],[5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043],[5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614],[6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185],[6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765],[7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336],[7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915],[8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486],[8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066],[9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628],[9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208]],\"y\":[[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907]],\"z\":[[9.8485748553746078,11.376697550763465,12.904820246152322,14.43294294154118,15.961065636930037,17.489188332318893,19.017311027707752,20.545433723096608,22.073556418485467,23.601679113874322,25.129801809263181,26.657924504652037,28.186047200040896,29.714169895429752,31.242292590818611,32.770415286207466,34.298537981596326,35.826660676985185,37.354783372374037,38.882906067762903],[10.880934703428242,12.409057398817099,13.937180094205956,15.465302789594814,16.993425484983671,18.521548180372527,20.049670875761386,21.577793571150242,23.105916266539101,24.634038961927956,26.162161657316815,27.690284352705671,29.21840704809453,30.746529743483386,32.274652438872245,33.802775134261104,35.330897829649956,36.859020525038815,38.387143220427674,39.915265915816533],[11.913294551481876,13.441417246870733,14.969539942259591,16.497662637648446,18.025785333037305,19.553908028426161,21.08203072381502,22.610153419203876,24.138276114592735,25.66639880998159,27.194521505370449,28.722644200759305,30.250766896148164,31.77888959153702,33.307012286925875,34.835134982314734,36.363257677703594,37.891380373092453,39.419503068481305,40.947625763870171],[12.94565439953551,14.473777094924367,16.001899790313225,17.53002248570208,19.058145181090939,20.586267876479795,22.114390571868654,23.64251326725751,25.170635962646369,26.698758658035224,28.226881353424083,29.755004048812939,31.283126744201798,32.811249439590654,34.339372134979513,35.867494830368372,37.395617525757224,38.923740221146083,40.451862916534942,41.979985611923802],[13.978014247589144,15.506136942978001,17.034259638366859,18.562382333755714,20.090505029144573,21.618627724533429,23.146750419922288,24.674873115311144,26.202995810700003,27.731118506088858,29.259241201477717,30.787363896866573,32.315486592255432,33.843609287644291,35.371731983033143,36.899854678422003,38.427977373810862,39.956100069199721,41.484222764588573,43.012345459977439],[15.010374095642778,16.538496791031633,18.066619486420493,19.594742181809348,21.122864877198207,22.650987572587063,24.179110267975922,25.707232963364778,27.235355658753637,28.763478354142492,30.291601049531351,31.819723744920207,33.347846440309063,34.875969135697922,36.404091831086781,37.93221452647564,39.460337221864492,40.988459917253351,42.51658261264221,44.044705308031077],[16.042733943696412,17.570856639085271,19.098979334474127,20.627102029862986,22.155224725251841,23.6833474206407,25.211470116029556,26.739592811418415,28.267715506807271,29.79583820219613,31.323960897584989,32.852083592973841,34.3802062883627,35.908328983751559,37.436451679140418,38.964574374529278,40.49269706991813,42.020819765306989,43.548942460695841,45.077065156084707],[17.075093791750046,18.603216487138905,20.131339182527761,21.65946187791662,23.187584573305475,24.715707268694334,26.24382996408319,27.771952659472049,29.300075354860905,30.828198050249764,32.356320745638619,33.884443441027479,35.412566136416338,36.94068883180519,38.468811527194049,39.996934222582908,41.525056917971767,43.053179613360619,44.581302308749478,46.109425004138345],[18.10745363980368,19.635576335192539,21.163699030581395,22.691821725970254,24.219944421359109,25.748067116747968,27.276189812136824,28.804312507525683,30.332435202914539,31.860557898303398,33.388680593692257,34.916803289081109,36.444925984469968,37.973048679858827,39.501171375247687,41.029294070636546,42.557416766025398,44.085539461414257,45.613662156803109,47.141784852191975],[19.139813487857314,20.667936183246173,22.196058878635029,23.724181574023888,25.252304269412743,26.780426964801602,28.308549660190458,29.836672355579317,31.364795050968173,32.892917746357028,34.421040441745888,35.949163137134747,37.477285832523606,39.005408527912458,40.533531223301317,42.061653918690176,43.589776614079035,45.117899309467887,46.646022004856746,48.174144700245606],[20.172173335910948,21.700296031299807,23.228418726688663,24.756541422077522,26.284664117466377,27.812786812855236,29.340909508244092,30.869032203632951,32.397154899021807,33.925277594410666,35.453400289799525,36.981522985188377,38.509645680577236,40.037768375966095,41.565891071354955,43.094013766743814,44.622136462132666,46.150259157521525,47.678381852910377,49.206504548299243],[21.204533183964582,22.732655879353441,24.260778574742297,25.788901270131156,27.317023965520011,28.84514666090887,30.373269356297726,31.901392051686585,33.429514747075444,34.957637442464296,36.485760137853156,38.013882833242015,39.542005528630874,41.070128224019726,42.598250919408585,44.126373614797444,45.654496310186303,47.182619005575155,48.710741700964014,50.238864396352881],[22.236893032018216,23.765015727407075,25.293138422795931,26.82126111818479,28.349383813573645,29.877506508962504,31.40562920435136,32.933751899740216,34.461874595129075,35.989997290517934,37.518119985906793,39.046242681295645,40.574365376684504,42.102488072073363,43.630610767462223,45.158733462851082,46.686856158239934,48.214978853628793,49.743101549017645,51.271224244406511],[23.26925288007185,24.797375575460709,26.325498270849565,27.853620966238424,29.381743661627279,30.909866357016138,32.437989052404994,33.966111747793853,35.494234443182712,37.022357138571564,38.550479833960424,40.078602529349283,41.606725224738142,43.134847920126994,44.662970615515853,46.191093310904712,47.719216006293571,49.247338701682423,50.775461397071282,52.303584092460149],[24.301612728125484,25.829735423514343,27.357858118903199,28.885980814292058,30.414103509680913,31.942226205069773,33.470348900458632,34.998471595847484,36.526594291236343,38.054716986625202,39.582839682014061,41.110962377402913,42.639085072791772,44.167207768180631,45.695330463569491,47.22345315895835,48.751575854347202,50.279698549736061,51.807821245124913,53.335943940513779],[25.333972576179118,26.862095271567977,28.390217966956833,29.918340662345692,31.446463357734547,32.974586053123403,34.502708748512262,36.030831443901121,37.55895413928998,39.087076834678832,40.615199530067692,42.143322225456551,43.67144492084541,45.199567616234262,46.727690311623121,48.25581300701198,49.783935702400839,51.312058397789691,52.84018109317855,54.368303788567417],[26.366332424232752,27.894455119621611,29.422577815010467,30.950700510399326,32.478823205788181,34.006945901177041,35.5350685965659,37.063191291954752,38.591313987343611,40.11943668273247,41.647559378121329,43.175682073510181,44.70380476889904,46.231927464287899,47.760050159676759,49.288172855065618,50.81629555045447,52.344418245843329,53.872540941232181,55.400663636621047],[27.398692272286386,28.926814967675245,30.454937663064101,31.98306035845296,33.511183053841819,35.039305749230671,36.56742844461953,38.095551140008389,39.623673835397248,41.1517965307861,42.67991922617496,44.208041921563819,45.736164616952678,47.26428731234153,48.792410007730389,50.320532703119248,51.848655398508107,53.376778093896959,54.904900789285819,56.433023484674685],[28.43105212034002,29.959174815728879,31.487297511117735,33.01542020650659,34.543542901895449,36.071665597284309,37.599788292673168,39.12791098806202,40.656033683450879,42.184156378839738,43.712279074228597,45.240401769617449,46.768524465006308,48.296647160395167,49.824769855784027,51.352892551172886,52.881015246561738,54.409137941950597,55.937260637339449,57.465383332728315],[29.463411968393654,30.991534663782513,32.519657359171369,34.047780054560228,35.575902749949087,37.104025445337939,38.632148140726798,40.160270836115657,41.688393531504516,43.216516226893368,44.744638922282228,46.272761617671087,47.800884313059946,49.329007008448798,50.857129703837657,52.385252399226516,53.913375094615375,55.441497790004227,56.969620485393087,58.497743180781953]],\"mode\":\"markers\",\"marker\":{\"size\":4,\"color\":\"blue\"},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"surface\",\"showscale\":false,\"opacity\":0.59999999999999998,\"inherit\":true}},\"layout\":{\"width\":950,\"height\":520,\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"X1\"},\"yaxis\":{\"title\":\"X2\"},\"zaxis\":{\"title\":\"Y (Outcome)\"}},\"title\":\"Multiple Regression: Best-Fitting Plane in 3D\",\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[9.1480604349635541,9.3707541329786181,2.8613953478634357,8.3044762606732547,6.4174551889300346,5.1909594913013279,7.3658831464126706,1.3466659723781049,6.5699229040183127,7.0506478403694928,4.5774177624844015,7.1911225165240467,9.3467224715277553,2.5542882434092462,4.6229282254353166,9.4001452275551856,9.7822642838582397,1.1748736165463924,4.7499708156101406,5.6033274624496698,9.0403138729743659,1.3871016772463918,9.8889172892086208,9.4666823255829513,0.82437558099627495,5.1421178434975445,3.9020346710458398,9.0573813091032207,4.4696962810121477,8.3600425999611616,7.3759561777114868,8.1105514126829803,3.8810828281566501,6.8516972940415144,0.0394833879545331,8.3291608025319874,0.073341468814760447,2.0765897282399237,9.0660140779800713,6.1177864344790578,3.7955924053676426,4.3577158497646451,0.37431032862514257,9.7353991377167404,4.3175124889239669,9.575765966437757,8.8775490550324321,6.3997876946814358,9.7096661035902798,6.1883820733055472,3.3342721126973629,3.4674824820831418,3.9848541142418981,7.846927756909281,0.38936491124331951,7.4879538617096841,6.7727683018893003,1.7126433039084077,2.6108796382322907,5.1441293465904891,6.756072745192796,9.8281719791702926,7.5954426755197346,5.6648842408321798,8.4968971856869757,1.8947393540292978,2.7128661470487714,8.2815848523750901,6.9320482038892806,2.4054473964497447,0.42988796019926667,1.4047909411601722,2.1638541505672038,4.7939856420271099,1.9741034228354692,7.1935583767481148,0.078847387339919806,3.7548996461555362,5.1440770830959082,0.015705542173236609,5.8160400250926614,1.579052081797272,3.5902830585837364,6.4563187840394676,7.7582336263731122,5.6364684156142175,2.3370339861139655,0.89980516349896789,0.85612064925953746,3.0521836946718395,6.6742651467211545,0.0023889658041298389,2.0856995694339275,9.3303412734530866,9.2564474861137569,7.340943010058254,3.3307198341935873,5.1506332983262837,7.4397464632056653,6.1915924004279077],\"y\":[6.2624534452334046,2.1715769823640585,2.1656731097027659,3.8894502865150571,9.4245569198392332,9.6260801376774907,7.3985527921468019,7.3324590572156012,5.3576128999702632,0.022729660850018263,6.0893745254725218,8.3680155943147838,7.5152256269939244,4.5273157255724072,5.3578999382443726,5.373766953125596,0.013808435760438442,3.5566595382988453,6.1213309015147388,8.2894213055260479,3.5672199935652316,4.1063512582331896,5.7347589894197881,5.8967830357141793,7.1965729235671461,3.9497304521501064,9.1920392913743854,9.6257029357366264,2.335235255304724,7.2449759999290109,9.0363452513702214,6.0347408475354314,6.3150729890912771,9.3738584965467453,8.504827506840229,5.7982089905999601,8.2140392391011119,1.1371860909275711,7.6450775866396725,6.236134571954608,1.4844660670496523,0.80264466581866145,4.6406955132260919,7.7936816145665944,7.3352795955725014,8.1723044440150261,1.7016248125582933,9.4472032552585006,2.9362384136766195,1.4907205244526267,7.193785912822932,3.2408595248125494,7.7880949852988124,3.9444100181572139,6.785928679164499,7.7582504274323583,1.8786904402077198,0.29085818910971284,1.3571379706263542,6.8016417813487351,9.348229537717998,5.5049408436752856,6.0176623542793095,1.9699448812752962,5.3523661056533456,1.7955573927611113,4.5188649441115558,3.1705335178412497,1.1617467040196061,1.8610215676017106,7.2973009664565325,4.1187207121402025,4.1404968174174428,4.8031012900173664,4.2749446560628712,1.3649036013521254,8.2467940635979176,5.9230424254201353,7.9439697763882577,7.6903242571279407,9.180564172565937,8.6262977705337107,3.1697523780167103,2.5926057598553598,7.4226645193994045,7.4736111680977046,9.1790403402410448,7.9319120920263231,1.3332961825653911,2.8774975216947496,1.9467614381574094,7.8410938265733421,1.2887216173112392,1.2908928352408111,0.72253111284226179,0.53129483480006456,5.318744364194572,1.1230824165977538,7.4318771972320974,7.3131547728553414],\"z\":[49.485411956824308,37.345741387384862,20.213392731155473,41.974267184237171,49.775034319862137,49.471187020547269,46.082912905528033,34.446008772493073,39.589070576950412,24.407806579283054,37.372773999651564,49.702437271876512,50.268251352343945,27.682089402159907,31.997358105774126,44.156923860739525,28.580653359242195,28.423507848678916,35.139701873385057,46.3494312785947,35.795037592011845,22.152385646318759,47.231516319070622,44.630435488540364,33.234824704084573,31.276909280593777,44.152844003315849,52.942515734578109,23.495602427218493,48.814046081945229,52.996189298380706,43.339570660865306,36.707510391717832,54.070749364483198,38.473160782382131,41.85872104005221,34.554161534432502,19.967734531101964,50.127801754746557,40.839037614943948,21.872368415410062,19.34800766117241,23.781339187159084,52.792953360956787,39.813126066449591,55.895217311656999,31.897986864431779,50.274847089936912,39.621772601314625,24.736188893627158,38.168505013561095,23.554453893908754,43.668332282851594,36.979794165542046,30.200825210635628,45.774154349744016,29.166083856847106,12.697296819242634,18.226188528442773,43.268534528396358,51.205782363055334,44.027601721065089,43.570286178812161,26.514126294234348,44.230919784308668,22.040994741803907,26.996942104213225,36.984070853434496,27.519132637194353,22.185090660233712,32.292122541875599,26.83898215566218,23.259087030713349,37.376192996733067,28.502596770896709,28.18027557978111,32.000062705195255,36.564943968655442,45.086451222986128,33.089672602887518,49.476684353607986,37.86877953449607,27.427436716478088,31.279763527084047,47.225942064259286,41.021297025735244,43.612686629831131,36.703739847624973,14.039516660612419,21.547683630415442,29.598731769089806,32.837883455382503,18.542787397530482,29.945356121659501,28.762147421993575,28.447320231876503,33.425222570402319,24.843488919884425,50.805581410415527,44.580291976626604],\"mode\":\"markers\",\"marker\":{\"color\":\"blue\",\"size\":4,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"type\":\"scatter3d\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"colorbar\":{\"title\":\"y\",\"ticklen\":2},\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":false,\"x\":[[0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389,0.0023889658041298389],[0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726,0.52273256177278726],[1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447,1.0430761577414447],[1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102,1.563419753710102],[2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595,2.0837633496787595],[2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171,2.6041069456474171],[3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742,3.1244505416160742],[3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317,3.6447941375847317],[4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892,4.1651377335533892],[4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463,4.6854813295220463],[5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043,5.2058249254907043],[5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614,5.7261685214593614],[6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185,6.2465121174280185],[6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765,6.7668557133966765],[7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336,7.2871993093653336],[7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915,7.8075429053339915],[8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486,8.3278865013026486],[8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066,8.8482300972713066],[9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628,9.3685736932399628],[9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208,9.8889172892086208]],\"y\":[[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907],[0.013808435760438442,0.51971747270344115,1.0256265096464439,1.5315355465894465,2.0374445835324493,2.5433536204754521,3.0492626574184545,3.5551716943614573,4.0610807313044601,4.5669897682474625,5.0728988051904658,5.5788078421334681,6.0847168790764705,6.5906259160194738,7.0965349529624762,7.6024439899054794,8.1083530268484818,8.6142620637914842,9.1201711007344866,9.6260801376774907]],\"z\":[[9.8485748553746078,11.376697550763465,12.904820246152322,14.43294294154118,15.961065636930037,17.489188332318893,19.017311027707752,20.545433723096608,22.073556418485467,23.601679113874322,25.129801809263181,26.657924504652037,28.186047200040896,29.714169895429752,31.242292590818611,32.770415286207466,34.298537981596326,35.826660676985185,37.354783372374037,38.882906067762903],[10.880934703428242,12.409057398817099,13.937180094205956,15.465302789594814,16.993425484983671,18.521548180372527,20.049670875761386,21.577793571150242,23.105916266539101,24.634038961927956,26.162161657316815,27.690284352705671,29.21840704809453,30.746529743483386,32.274652438872245,33.802775134261104,35.330897829649956,36.859020525038815,38.387143220427674,39.915265915816533],[11.913294551481876,13.441417246870733,14.969539942259591,16.497662637648446,18.025785333037305,19.553908028426161,21.08203072381502,22.610153419203876,24.138276114592735,25.66639880998159,27.194521505370449,28.722644200759305,30.250766896148164,31.77888959153702,33.307012286925875,34.835134982314734,36.363257677703594,37.891380373092453,39.419503068481305,40.947625763870171],[12.94565439953551,14.473777094924367,16.001899790313225,17.53002248570208,19.058145181090939,20.586267876479795,22.114390571868654,23.64251326725751,25.170635962646369,26.698758658035224,28.226881353424083,29.755004048812939,31.283126744201798,32.811249439590654,34.339372134979513,35.867494830368372,37.395617525757224,38.923740221146083,40.451862916534942,41.979985611923802],[13.978014247589144,15.506136942978001,17.034259638366859,18.562382333755714,20.090505029144573,21.618627724533429,23.146750419922288,24.674873115311144,26.202995810700003,27.731118506088858,29.259241201477717,30.787363896866573,32.315486592255432,33.843609287644291,35.371731983033143,36.899854678422003,38.427977373810862,39.956100069199721,41.484222764588573,43.012345459977439],[15.010374095642778,16.538496791031633,18.066619486420493,19.594742181809348,21.122864877198207,22.650987572587063,24.179110267975922,25.707232963364778,27.235355658753637,28.763478354142492,30.291601049531351,31.819723744920207,33.347846440309063,34.875969135697922,36.404091831086781,37.93221452647564,39.460337221864492,40.988459917253351,42.51658261264221,44.044705308031077],[16.042733943696412,17.570856639085271,19.098979334474127,20.627102029862986,22.155224725251841,23.6833474206407,25.211470116029556,26.739592811418415,28.267715506807271,29.79583820219613,31.323960897584989,32.852083592973841,34.3802062883627,35.908328983751559,37.436451679140418,38.964574374529278,40.49269706991813,42.020819765306989,43.548942460695841,45.077065156084707],[17.075093791750046,18.603216487138905,20.131339182527761,21.65946187791662,23.187584573305475,24.715707268694334,26.24382996408319,27.771952659472049,29.300075354860905,30.828198050249764,32.356320745638619,33.884443441027479,35.412566136416338,36.94068883180519,38.468811527194049,39.996934222582908,41.525056917971767,43.053179613360619,44.581302308749478,46.109425004138345],[18.10745363980368,19.635576335192539,21.163699030581395,22.691821725970254,24.219944421359109,25.748067116747968,27.276189812136824,28.804312507525683,30.332435202914539,31.860557898303398,33.388680593692257,34.916803289081109,36.444925984469968,37.973048679858827,39.501171375247687,41.029294070636546,42.557416766025398,44.085539461414257,45.613662156803109,47.141784852191975],[19.139813487857314,20.667936183246173,22.196058878635029,23.724181574023888,25.252304269412743,26.780426964801602,28.308549660190458,29.836672355579317,31.364795050968173,32.892917746357028,34.421040441745888,35.949163137134747,37.477285832523606,39.005408527912458,40.533531223301317,42.061653918690176,43.589776614079035,45.117899309467887,46.646022004856746,48.174144700245606],[20.172173335910948,21.700296031299807,23.228418726688663,24.756541422077522,26.284664117466377,27.812786812855236,29.340909508244092,30.869032203632951,32.397154899021807,33.925277594410666,35.453400289799525,36.981522985188377,38.509645680577236,40.037768375966095,41.565891071354955,43.094013766743814,44.622136462132666,46.150259157521525,47.678381852910377,49.206504548299243],[21.204533183964582,22.732655879353441,24.260778574742297,25.788901270131156,27.317023965520011,28.84514666090887,30.373269356297726,31.901392051686585,33.429514747075444,34.957637442464296,36.485760137853156,38.013882833242015,39.542005528630874,41.070128224019726,42.598250919408585,44.126373614797444,45.654496310186303,47.182619005575155,48.710741700964014,50.238864396352881],[22.236893032018216,23.765015727407075,25.293138422795931,26.82126111818479,28.349383813573645,29.877506508962504,31.40562920435136,32.933751899740216,34.461874595129075,35.989997290517934,37.518119985906793,39.046242681295645,40.574365376684504,42.102488072073363,43.630610767462223,45.158733462851082,46.686856158239934,48.214978853628793,49.743101549017645,51.271224244406511],[23.26925288007185,24.797375575460709,26.325498270849565,27.853620966238424,29.381743661627279,30.909866357016138,32.437989052404994,33.966111747793853,35.494234443182712,37.022357138571564,38.550479833960424,40.078602529349283,41.606725224738142,43.134847920126994,44.662970615515853,46.191093310904712,47.719216006293571,49.247338701682423,50.775461397071282,52.303584092460149],[24.301612728125484,25.829735423514343,27.357858118903199,28.885980814292058,30.414103509680913,31.942226205069773,33.470348900458632,34.998471595847484,36.526594291236343,38.054716986625202,39.582839682014061,41.110962377402913,42.639085072791772,44.167207768180631,45.695330463569491,47.22345315895835,48.751575854347202,50.279698549736061,51.807821245124913,53.335943940513779],[25.333972576179118,26.862095271567977,28.390217966956833,29.918340662345692,31.446463357734547,32.974586053123403,34.502708748512262,36.030831443901121,37.55895413928998,39.087076834678832,40.615199530067692,42.143322225456551,43.67144492084541,45.199567616234262,46.727690311623121,48.25581300701198,49.783935702400839,51.312058397789691,52.84018109317855,54.368303788567417],[26.366332424232752,27.894455119621611,29.422577815010467,30.950700510399326,32.478823205788181,34.006945901177041,35.5350685965659,37.063191291954752,38.591313987343611,40.11943668273247,41.647559378121329,43.175682073510181,44.70380476889904,46.231927464287899,47.760050159676759,49.288172855065618,50.81629555045447,52.344418245843329,53.872540941232181,55.400663636621047],[27.398692272286386,28.926814967675245,30.454937663064101,31.98306035845296,33.511183053841819,35.039305749230671,36.56742844461953,38.095551140008389,39.623673835397248,41.1517965307861,42.67991922617496,44.208041921563819,45.736164616952678,47.26428731234153,48.792410007730389,50.320532703119248,51.848655398508107,53.376778093896959,54.904900789285819,56.433023484674685],[28.43105212034002,29.959174815728879,31.487297511117735,33.01542020650659,34.543542901895449,36.071665597284309,37.599788292673168,39.12791098806202,40.656033683450879,42.184156378839738,43.712279074228597,45.240401769617449,46.768524465006308,48.296647160395167,49.824769855784027,51.352892551172886,52.881015246561738,54.409137941950597,55.937260637339449,57.465383332728315],[29.463411968393654,30.991534663782513,32.519657359171369,34.047780054560228,35.575902749949087,37.104025445337939,38.632148140726798,40.160270836115657,41.688393531504516,43.216516226893368,44.744638922282228,46.272761617671087,47.800884313059946,49.329007008448798,50.857129703837657,52.385252399226516,53.913375094615375,55.441497790004227,56.969620485393087,58.497743180781953]],\"mode\":\"markers\",\"marker\":{\"size\":4,\"color\":\"blue\"},\"type\":\"surface\",\"opacity\":0.59999999999999998,\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nGrab it and spin it.\n\n## The Guided Tour\n\nPoints above the plane are positive residuals; below, negative. For the walkthrough again later: same plane, narrated:\n\n<video src=\"../media/week-11/regression-plane.mp4\" controls preload=\"metadata\"></video>\n\n# The Lurking Third Variable {background-color=\"#73000A\"}\n\n## Remember the Lurker?\n\nIce cream sales and drowning deaths are strongly correlated. Every summer. Reliably.\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nset.seed(705)\nlurk <- tibble(\n  temperature    = runif(100, 60, 100),\n  icecream_sales = 20 + 5 * temperature + rnorm(100, 0, 30),\n  drownings      = -10 + 0.8 * temperature + rnorm(100, 0, 10)\n)\n\nggplot(lurk, aes(icecream_sales, drownings)) +\n  geom_point(color = crju_colors[\"navy\"], size = 2.5) +\n  geom_smooth(method = \"lm\", se = FALSE, color = crju_colors[\"garnet\"]) +\n  labs(title = paste0(\"r = \", round(cor(lurk$icecream_sales, lurk$drownings), 2),\n                      \". Ban ice cream?\"),\n       x = \"Ice cream sales\", y = \"Drownings\")\n```\n\n::: {.cell-output-display}\n![](week-11-regression_files/figure-revealjs/lurk-data-1.png){width=960}\n:::\n:::\n\n\n## Model 1: Ice Cream \"Predicts\" Drownings\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlurk_m1 <- lm(drownings ~ icecream_sales, data = lurk)\nsummary(lurk_m1)$coefficients |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error t value Pr(>|t|)\n(Intercept)     -0.3876     7.5245 -0.0515    0.959\nicecream_sales   0.1315     0.0175  7.5165    0.000\n```\n\n\n:::\n:::\n\n\n::: incremental\n- The coefficient is positive and the p-value has ten zeros in it\n- It's statistically significant. The model says it's real.\n- **Do we believe it?** No, but notice that *nothing in this output warns us*. The model can only see the variables we gave it.\n:::\n\n## Model 2: Give the Model the Lurker\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlurk_m2 <- lm(drownings ~ icecream_sales + temperature, data = lurk)\nsummary(lurk_m2)$coefficients |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error t value Pr(>|t|)\n(Intercept)    -10.0979     6.5333 -1.5456   0.1255\nicecream_sales  -0.0339     0.0299 -1.1352   0.2591\ntemperature      0.9884     0.1553  6.3634   0.0000\n```\n\n\n:::\n:::\n\n\n. . .\n\nHolding temperature constant, ice cream's coefficient collapses to ~0 (and goes nonsignificant). Temperature was driving **both** variables the whole time.\n\nThis is *holding constant* doing real work: comparing days with the **same temperature**, ice cream tells you nothing about drownings.\n\n## Side by Side\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|model                              | icecream coef|icecream p     |temperature coef |   R²|\n|:----------------------------------|-------------:|:--------------|:----------------|----:|\n|drownings ~ icecream               |         0.132|0.000000000027 |n/a              | 0.37|\n|drownings ~ icecream + temperature |        -0.034|0.26           |0.99             | 0.55|\n\n\n:::\n:::\n\n\n::: incremental\n- A \"significant\" bivariate relationship **evaporated** once the right third variable entered\n- Beware the evil lurking third variable. It does not announce itself.\n:::\n\n## Seeing \"Holding Constant\"\n\nAn **added-variable plot** shows the relationship between ice cream and drownings *after* temperature's contribution is removed from both:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-11-regression_files/figure-revealjs/lurk-avplot-1.png){width=960}\n:::\n:::\n\n\nFlat. That flat line *is* the multiple-regression coefficient for ice cream.\n\n## The Moral\n\n::: incremental\n- Multiple regression can hold constant **only the variables you measured and included**\n- Every observational model has *potential* lurkers you didn't measure, so coefficients are **adjusted associations, not causal effects**\n- \"Holding constant\" is a statistical operation, not a controlled experiment\n- This is why theory matters: *which* variables belong in the model is a substantive question, not a statistical one\n:::\n\n. . .\n\nKeep this loaded. We're about to fit real Chicago models, and the temptation to talk causally will be enormous.\n\n# Real Data: Violence Across Chicago's 77 Areas {background-color=\"#1B2A4A\"}\n\n## Look First. Always.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-11-regression_files/figure-revealjs/chi-scatter-1.png){width=960}\n:::\n:::\n\n\n## One Predictor First\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nchi_m1 <- lm(violent_rate ~ unemployment_rate, data = areas)\nsummary(chi_m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = violent_rate ~ unemployment_rate, data = areas)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-32.137  -6.340  -2.670   5.843  43.339 \n\nCoefficients:\n                  Estimate Std. Error t value            Pr(>|t|)    \n(Intercept)        -2.7444     2.8629  -0.959               0.341    \nunemployment_rate   3.3007     0.2463  13.400 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.27 on 75 degrees of freedom\nMultiple R-squared:  0.7054,\tAdjusted R-squared:  0.7014 \nF-statistic: 179.5 on 1 and 75 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n. . .\n\nEach additional percentage point of unemployment is associated with **3.3 more violent crimes per 1,000 residents**, and unemployment alone accounts for **71%** of the between-area variance. Strong, but is unemployment getting credit for other disadvantage it travels with?\n\n## Add a Second Predictor: Vacant Housing\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nchi_m2 <- lm(violent_rate ~ unemployment_rate + pct_vacant, data = areas)\nsummary(chi_m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = violent_rate ~ unemployment_rate + pct_vacant, data = areas)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-27.6759  -5.8167  -0.9943   4.5144  26.7266 \n\nCoefficients:\n                  Estimate Std. Error t value         Pr(>|t|)    \n(Intercept)        -9.2679     2.4616  -3.765         0.000332 ***\nunemployment_rate   2.1156     0.2620   8.075 0.00000000000935 ***\npct_vacant          1.9352     0.2859   6.769 0.00000000264664 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.708 on 74 degrees of freedom\nMultiple R-squared:  0.818,\tAdjusted R-squared:  0.8131 \nF-statistic: 166.3 on 2 and 74 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n. . .\n\nBoth predictors earn significant coefficients, and R² climbs from 0.71 to **0.82**.\n\nWatch unemployment's slope: **3.3 → 2.1**. Some of what looked like \"unemployment\" in the simple model was shared with vacancy. That shrinkage *is* \"holding constant\": the lurker lesson, on real data.\n\n## Reading the Coefficients Out Loud\n\n- **Intercept (-9.3):** predicted rate when both predictors are 0: no Chicago area looks like that; it anchors the plane, nothing more\n\n- **`unemployment_rate` (2.12):** +1 point of unemployment ↔ ~2.1 more violent crimes per 1,000 residents, **vacancy held fixed**\n\n- **`pct_vacant` (1.94):** +1 point of vacancy ↔ ~1.9 more violent crimes per 1,000 residents, **unemployment held fixed**\n\n## What These Coefficients Are *Not*\n\n::: incremental\n- **Not causal effects.** Adjusted associations between *areas*, and every lurker we didn't measure is still at large\n- **Not people-level claims.** An unemployed *person* is not \"2.1 crimes more dangerous.\" Area-level in, area-level out: Session 8's ecological fallacy rides along with every coefficient today\n- **Not the full story.** The model holds constant *only what's in the model*\n:::\n\n## Watch the Units\n\nCoefficient *size* is meaningless until you check the predictor's units. Median income, in **dollars**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(violent_rate ~ median_income, data = areas))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) median_income \n68.5585257487 -0.0005221118 \n```\n\n\n:::\n\n```{.r .cell-code}\nareas |>\n  mutate(income_10k = median_income / 10000) |>\n  lm(violent_rate ~ income_10k, data = _) |>\n  coef()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  income_10k \n  68.558526   -5.221118 \n```\n\n\n:::\n:::\n\n\n. . .\n\nSame model, same fit. But -0.0005 \"looks like\" nothing; the honest reading is **about 5 *fewer* violent crimes per 1,000 residents per $10,000 of median income**. Rescale before you interpret.\n\n## Does a Third Predictor Earn Its Keep?\n\nAdd the share of adults without a high-school diploma:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_m3 <- lm(violent_rate ~ unemployment_rate + pct_vacant + pct_no_hs_diploma,\n             data = areas)\nsummary(chi_m3)$coefficients |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Estimate Std. Error t value Pr(>|t|)\n(Intercept)         -8.853      2.862  -3.093    0.003\nunemployment_rate    2.140      0.276   7.741    0.000\npct_vacant           1.923      0.291   6.613    0.000\npct_no_hs_diploma   -0.039      0.135  -0.290    0.773\n```\n\n\n:::\n:::\n\n\n::: incremental\n- Coefficient ≈ 0, p ≈ 0.77: with unemployment and vacancy already in, it adds nothing detectable; **adjusted R²** (R² with a per-predictor penalty) actually *falls*: 0.813 → 0.811\n- More predictors ≠ more truth. Every variable argues its way in: theory first, fit second\n:::\n\n# Checking the Model: Diagnostics {background-color=\"#73000A\"}\n\n## The Residual Plot\n\nRegression assumes the misses are patternless. So **look at the misses**:\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nchi_diag <- tibble(fitted = fitted(chi_m2), residual = resid(chi_m2))\n\nggplot(chi_diag, aes(fitted, residual)) +\n  geom_hline(yintercept = 0, linetype = 2) +\n  geom_point(color = crju_colors[\"navy\"], size = 2.5, alpha = 0.8) +\n  labs(title = \"Residuals vs. fitted values: the all-purpose diagnostic\",\n       x = \"Fitted violent-crime rate\", y = \"Residual\")\n```\n\n::: {.cell-output-display}\n![](week-11-regression_files/figure-revealjs/chi-resid-1.png){width=960}\n:::\n:::\n\n\n## Reading Our Residual Plot Honestly\n\n::: incremental\n- **What we want:** a patternless horizontal band around zero\n- **What we have:** centered on zero with no obvious curve (good: the straight-plane assumption isn't visibly wrong), but the **spread widens** at higher fitted values, so the model misses by more in high-violence areas\n- That fanning (*heteroscedasticity*) is common with rate outcomes. It doesn't bias the coefficients, but it makes the SEs less trustworthy at the extremes: worth a sentence when you report\n- A **curve** in this plot would be worse news: it would say the model's *shape* is wrong, not just its noise\n:::\n\n## Multicollinearity: When Predictors Tell the Same Story\n\nIf two predictors move in near-lockstep, the model can't tell **whose** coefficient the shared variance belongs to: estimates get wobbly and standard errors balloon.\n\n. . .\n\n**VIF** (variance inflation factor, from the `car` package) measures how redundant each predictor is with all the others.\n\nCommon rules of thumb: **VIF > 5**, pay attention; **VIF > 10**, you have a problem.\n\n## VIF on Our Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(chi_m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nunemployment_rate        pct_vacant \n         1.807177          1.807177 \n```\n\n\n:::\n:::\n\n\n::: incremental\n- ~1.8: unemployment and vacancy are correlated (r ≈ 0.67), but each still carries plenty of its own information\n- If VIF *were* high: drop one predictor, combine them into an index, or accept wide intervals; you cannot p-value your way out\n:::\n\n# The Bayesian Version {background-color=\"#1B2A4A\"}\n\n## Two Traditions, One Formula\n\n| Approach | What it estimates | The 95% statement |\n|----------|-------------------|-------------------|\n| **Frequentist** | Point estimates and confidence intervals | \"If we repeated this study many times, 95% of such intervals would contain the true β.\" |\n| **Bayesian** | A full posterior distribution for each β | \"Given the data and priors, there's a 95% probability β lies in this range.\" |\n\n. . .\n\nSame formula, same data, but the Bayesian statement is the one everyone *wants* to make (remember Session 5's forbidden sentence? Here it's allowed).\n\n## Meet `brms`\n\n- **brms**: **B**ayesian **R**egression **M**odels using **S**tan. It writes the model, compiles it, and samples the posterior\n- You installed it for **Project Checkpoint 2** and ran one test fit. If that test fit failed, flag me down now\n- `bayesplot` came along with it: that's where today's posterior plots come from\n\n::: {.callout-warning appearance=\"simple\"}\n`brms` compiles models with your computer's C++ toolchain. Expect the *first* model of each R session to pause about a minute at \"Compiling Stan program...\": that's normal, not a crash.\n:::\n\n## Fitting It: `brm()`\n\nIdentical formula, Bayesian machinery:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_bayes <- brm(violent_rate ~ unemployment_rate + pct_vacant,\n                 data = areas,\n                 chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n::: incremental\n- Same formula syntax as `lm()`: this pattern carries through the rest of the course\n- `chains = 2, iter = 2000`: two independent samplers, 2,000 steps each (the first half is warm-up) → a full **posterior distribution** for every coefficient\n- `seed = 705` makes your numbers match mine; `refresh = 0` just silences the sampling progress log\n- Priors: we didn't state any, so `brms` used its **defaults**. Next slide\n:::\n\n## The Posterior, and the Prior We Used\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixef(chi_bayes) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Estimate Est.Error   Q2.5 Q97.5\nIntercept            -9.25      2.42 -13.93 -4.68\nunemployment_rate     2.12      0.27   1.58  2.64\npct_vacant            1.92      0.29   1.36  2.48\n```\n\n\n:::\n:::\n\n\n::: incremental\n- Posterior means land almost exactly on the `lm()` estimates: with decent *n* and default priors, they should. (Full `summary()` in today's lab.)\n- **Default priors:** essentially flat on the coefficients, weakly informative on the intercept and spread. \"The data do the talking,\" but *say so*: **\"we used brms default priors\"** belongs in any write-up\n- **The rule, from here on:** a 95% credible interval that **crosses 0** → no credible effect; **excludes 0** → credible effect\n:::\n\n## The Posteriors, Seen\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_areas(chi_bayes, pars = c(\"b_unemployment_rate\", \"b_pct_vacant\"),\n           prob = 0.95) +\n  labs(title = \"Posterior distributions: predictors of violent-crime rate\",\n       subtitle = \"Shaded = central 95% credible interval: both sit clear of zero\")\n```\n\n::: {.cell-output-display}\n![](week-11-regression_files/figure-revealjs/chi-mcmc-areas-1.png){width=960}\n:::\n:::\n\n\n## Saying It in Each Tradition\n\n**Frequentist:**\n\n> \"Holding vacancy constant, each percentage point of unemployment was associated with 2.1 more violent crimes per 1,000 residents (b = 2.12, 95% CI [1.6, 2.6], p < .001).\"\n\n**Bayesian:**\n\n> \"Given the data and priors, there is a 95% probability the unemployment coefficient lies between 1.6 and 2.6: zero is not a credible value.\"\n\n**Both** are area-level, adjusted **associations**: neither sentence licenses \"unemployment causes violence.\"\n\n## Your Turn (5 minutes, with a neighbor)\n\nThe fitted model:\n\n$$\\widehat{\\text{violent rate}} = -9.3 + 2.12\\,(\\text{unemployment}) + 1.94\\,(\\text{vacancy})$$\n\n1. Predict the rate for an area with **10% unemployment, 10% vacancy**, then **23% and 25%** (roughly Englewood). Which prediction does the residual plot say to trust more?\n\n2. Write **one defensible sentence** interpreting the vacancy coefficient. Swap and audit: does it say *holding unemployment constant*? Any smuggled causal verbs (\"drives,\" \"increases\")? Fix what you catch.\n\n## Today's Lab & Homework\n\n- **Lab 10:** the full regression workflow: Chicago's 77 areas start to finish (fit → interpret → diagnose → Bayesian), then your own model on 500 simulated neighborhoods ([lab page](../labs/lab-11-regression.qmd))\n- **Homework 10:** cleaning data *for* regression (you'll meet some 999s), regression on the cleaned file, **plus Project Checkpoint 3**: the first regression model on *your* project data (posted on the [Session 10 page](../weeks/week-11.qmd))\n- **Read before Session 11:** Stanton **Ch. 10**: logistic regression, for when your outcome is a yes/no. If your project outcome is binary, next session is your session.\n",
    "supporting": [
      "week-11-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}