{
  "hash": "694f3ce3a0e98d190506e6db05ebd107",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Comparing Groups and Analyzing Experiments\"\nsubtitle: \"CRJU 705 · Session 8 · Fall 2026\"\nauthor: \"Scott M. Mourtgos\"\nformat:\n  revealjs:\n    slide-number: true\n    preview-links: auto\n    chalkboard: true\n    footer: \"CRJU 705 · Session 8\"\n    theme: [default, custom-slides.scss]\n    fig-align: center\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n## This Week {.smaller}\n\n**Topic:** comparing three or more group means — and your first Bayesian model workflow\n\n- Why \"just run a bunch of t-tests\" backfires\n- The core idea: two kinds of variance and their ratio, F\n- `aov()` + Tukey's HSD — enough to read the output you'll meet in the literature\n- **`brms` + `emmeans`** — the workflow you'll reuse in every remaining session\n- Real data: does Chicago's clock differ by crime category?\n\n**Learning goals:** explain what F compares; read a one-way ANOVA in both traditions; run the posterior workflow you'll use for the rest of the course.\n\n**Also this week:** Homework 8 includes **Project Checkpoint 1** — your first graded step on your final-project dataset.\n\n## Where We've Been\n\n::: incremental\n- **Session 6:** two groups — is *this* mean different from *that* one? t-tests, in both the frequentist and Bayesian traditions\n- **Session 7:** the applied workshop — you took a messy file through the whole pipeline and **picked your final-project dataset**\n- **Today:** the question that comes up constantly in real research — what if there are *three* groups? Or six?\n:::\n\n# Experiments and Group Comparisons {background-color=\"#73000A\"}\n\n## Experiments: IVs and DVs\n\n**Independent variable (IV):** what we change or compare — the *groups*.\n\n**Dependent variable (DV):** what we measure — the *outcome* that (maybe) depends on the IV.\n\n| Independent variable | Dependent variable |\n|---|---|\n| Type of training program | Test score |\n| Type of fertilizer | Plant height |\n| Region of the country | Annual precipitation |\n| Patrol strategy assigned to a beat | Response time (minutes) |\n\n: {tbl-colwidths=\"[50,50]\"}\n\n## Why ANOVA?\n\n::: incremental\n- A **t-test** compares **2** means\n- **ANOVA** compares **3+** means\n- Use it when the **IV is categorical** (the groups) and the **DV is numeric** (the outcome)\n- The name is strange: **AN**alysis **O**f **VA**riance — we're asking about *means*, but the test works by comparing *variances*. That's the whole trick, and it's coming up.\n:::\n\n## Why Not Just Run a Pile of t-Tests?\n\nThree groups means 3 pairwise tests. Six groups means 15. Each test carries its own 5% false-alarm risk, and the risks pile up:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(groups = c(2, 3, 4, 6, 10)) |>\n  mutate(\n    pairwise_tests   = choose(groups, 2),\n    p_false_alarm    = round(1 - 0.95^pairwise_tests, 2)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  groups pairwise_tests p_false_alarm\n   <dbl>          <dbl>         <dbl>\n1      2              1          0.05\n2      3              3          0.14\n3      4              6          0.26\n4      6             15          0.54\n5     10             45          0.9 \n```\n\n\n:::\n:::\n\n\n## ANOVA's Answer: One Omnibus Question\n\nBy six groups you have a coin-flip's chance of at least one bogus \"significant\" difference.\n\n. . .\n\nANOVA asks **one omnibus question** — *are all the group means plausibly equal?* — at a single 5% risk. (When we go pairwise afterward, we'll adjust for this. Hold that thought.)\n\n## Where ANOVA Actually Lives\n\n::: incremental\n- ANOVA is **standard in experiments** — assign units to conditions, compare outcomes. That is what it was built for.\n- But open a criminology journal and you'll rarely see it as a **final model**. Observational CJ research runs on **regression**.\n- **So why learn it? You will read it.** Older literature, program evaluations, and lab studies are full of ANOVA tables — and output you can't read is output you have to take on faith.\n- **And it is regression in disguise.** The between/within logic you build today is the machinery behind R², the F-test, and every categorical predictor from Session 11 on. We'll prove it before class ends.\n:::\n\n# The Core Idea: Two Kinds of Variance {background-color=\"#1B2A4A\"}\n\n## Imagine Three Classrooms\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclassrooms <- tibble(\n  score     = c(75, 80, 78, 74, 77,    # Class 1\n                88, 90, 92, 85, 87,    # Class 2\n                70, 65, 68, 72, 66),   # Class 3\n  classroom = factor(rep(c(\"Class 1\", \"Class 2\", \"Class 3\"), each = 5))\n)\n\nclass_stats <- classrooms |>\n  summarize(class_mean = mean(score), class_var = var(score), .by = classroom)\nclass_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  classroom class_mean class_var\n  <fct>          <dbl>     <dbl>\n1 Class 1         76.8       5.7\n2 Class 2         88.4       7.3\n3 Class 3         68.2       8.2\n```\n\n\n:::\n:::\n\n\nTwo different kinds of \"spread\" are hiding in this table.\n\n## Two Kinds of Variance\n\n**Within-group variance:** how much scores bounce around *inside* each classroom.\n\n**Between-group variance:** how much the classroom *averages* differ from each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(class_stats$class_var)   # WITHIN: average spread inside a class\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.066667\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(class_stats$class_mean)   # BETWEEN: spread of the class means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102.76\n```\n\n\n:::\n:::\n\n\n. . .\n\nBetween (**102.8**) dwarfs within (**7.1**) — the class averages are far more spread out than chance bouncing inside classes would suggest. Signal-to-noise ratio ≈ 14.5. These classes look genuinely different.\n\n## The Picture\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-08-anova_files/figure-revealjs/classrooms-plot-1.png){width=960}\n:::\n:::\n\n\n## Stanton's Rain Example (From the Book)\n\nNow flip the situation: three groups where **nothing differs** — by construction. `precip` holds annual precipitation for 70 U.S. cities. Draw three random groups of 20 from the *same* 70 cities:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"precip\")\nset.seed(705)   # so we all draw the same \"random\" groups\ngroup1 <- sample(precip, 20)\ngroup2 <- sample(precip, 20)\ngroup3 <- sample(precip, 20)\n\nc(mean(group1), mean(group2), mean(group3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 34.100 31.835 31.255\n```\n\n\n:::\n:::\n\n\n. . .\n\nThe means differ a little — but any differences here are **pure sampling luck**. The null hypothesis is *true by construction*.\n\n## Rain: Within vs. Between\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(c(var(group1), var(group2), var(group3)))    # WITHIN\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 132.6697\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(c(mean(group1), mean(group2), mean(group3)))  # BETWEEN\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.260108\n```\n\n\n:::\n:::\n\n\n. . .\n\nWithin ≈ **133**, between ≈ **2.3**. The classrooms gave us 7.1 vs. 102.8 — completely flipped. Why?\n\n## Why So Lopsided?\n\n::: incremental\n- City-to-city rainfall varies a *lot* (Phoenix vs. Mobile) → big **within**-group variance. But each group's **mean** averages 20 cities, and Session 4 taught us means fluctuate far less than raw values ($SE = \\sigma/\\sqrt{n}$).\n- With no real group differences, between-group variance is nothing but the tiny sampling noise of three means.\n- The diagnostic: **between ≫ within → something real separates the groups. Between ≪ within → noise.** All we need is a ruler for \"how much bigger is big enough\" —\n:::\n\n## The F-Statistic\n\n$$F \\;=\\; \\frac{\\text{between-group variance}}{\\text{within-group variance}} \\;=\\; \\frac{\\text{signal}}{\\text{noise}}$$\n\n::: incremental\n- When the null is true, F bounces around low values by luck of the draw\n- If our F lands **far in the tail** of the F distribution → our data are *unlikely under the null* — same logic as every test we've run\n- The **F distribution** describes the F values a null world produces. Its shape depends on two df: **groups − 1** and **N − groups**\n:::\n\n## What F Looks Like When the Null Is True\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nset.seed(705)\nf_null <- tibble(\n  design = rep(c(\"F(2, 57) — our rain design\",\n                 \"F(8, 101) — more groups, bigger N\"), each = 10000) |> fct_inorder(),\n  f      = c(rf(10000, df1 = 2, df2 = 57), rf(10000, df1 = 8, df2 = 101))\n)\ncutoffs <- f_null |> summarize(cut = quantile(f, 0.95), .by = design)\n\nggplot(f_null, aes(f)) +\n  geom_histogram(bins = 60, fill = crju_colors[\"blue\"], color = \"white\") +\n  geom_vline(data = cutoffs, aes(xintercept = cut),\n             color = crju_colors[\"garnet\"], linewidth = 1.1) +\n  facet_wrap(~design, ncol = 1) +\n  labs(title = \"10,000 F values from a null world, for two designs\",\n       subtitle = \"Garnet line = 95th percentile — F values beyond it are rare when nothing differs\",\n       x = \"F value\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](week-08-anova_files/figure-revealjs/f-dist-1.png){width=960}\n:::\n:::\n\n\n# Running the ANOVA {background-color=\"#73000A\"}\n\n## First, We Need a Data Frame\n\n`aov()` wants the data in the long format we've used all semester — one row per observation, one column saying which group it belongs to:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrain <- tibble(\n  rainfall = c(group1, group2, group3),\n  group    = factor(rep(c(\"Group 1\", \"Group 2\", \"Group 3\"), each = 20))\n)\nrain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 60 × 2\n  rainfall group  \n     <dbl> <fct>  \n1     49.2 Group 1\n2     35.1 Group 1\n3     31.7 Group 1\n4     30.8 Group 1\n5     34.4 Group 1\n6     17.4 Group 1\n# ℹ 54 more rows\n```\n\n\n:::\n:::\n\n\n## `aov()` Does the Whole Thing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrain_model <- aov(rainfall ~ group, data = rain)\nsummary(rain_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\ngroup        2     90    45.2   0.341  0.713\nResiduals   57   7562   132.7               \n```\n\n\n:::\n:::\n\n\n. . .\n\n**F = 0.34, p = 0.71.** That F sits squarely in the fat part of F(2, 57) — nowhere near the 95% cutoff (≈ 3.2). No evidence the groups differ. *Correct answer* — they're the same population by construction.\n\n## The Table Is Our Two Variances, Dressed Up\n\n::: incremental\n- **Mean Sq Residuals = 132.7** — exactly the within-group variance we computed by hand ✓\n- **Mean Sq group = 45.2** — our between-group variance (2.26), scaled by the group size. **F = 45.2 / 132.7 = 0.34.**\n:::\n\n. . .\n\n*Why the scaling? A 2-inch gap between means built on 20 cities each is stronger evidence than the same gap built on 2, so `aov()` bakes sample size into the signal. That's the only reason your hand-computed ratio and R's F won't match — same logic, different units. You do not need to reproduce this by hand; you need to read the table.*\n\n## Let's Make a Difference Artificially\n\nShift Group 3 down 15 inches — now there *is* a real difference, and we know exactly where it lives:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrain_shifted <- rain |>\n  mutate(rainfall = if_else(group == \"Group 3\", rainfall - 15, rainfall))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-08-anova_files/figure-revealjs/rain-shift-plot-1.png){width=960}\n:::\n:::\n\n\n## Redo the ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshifted_model <- aov(rainfall ~ group, data = rain_shifted)\nsummary(shifted_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value     Pr(>F)    \ngroup        2   3775  1887.7   14.23 0.00000972 ***\nResiduals   57   7562   132.7                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n. . .\n\nThe within-group noise didn't move (132.7 — shifting a whole group doesn't change the spread *inside* it). The between-group signal exploded. **F = 14.2, p ≈ 0.00001** — deep in the tail.\n\n## A Significant F Only Says \"*Something* Differs\"\n\nWhich pairs? **Tukey's HSD**: all pairwise comparisons, with the family-wise 5% false-alarm rate restored — the fix for the t-test pile-up problem from the top of class:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(shifted_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = rainfall ~ group, data = rain_shifted)\n\n$group\n                   diff      lwr       upr     p adj\nGroup 2-Group 1  -2.265 -11.0301  6.500103 0.8087836\nGroup 3-Group 1 -17.845 -26.6101 -9.079897 0.0000246\nGroup 3-Group 2 -15.580 -24.3451 -6.814897 0.0002129\n```\n\n\n:::\n:::\n\n\n## Reading the Tukey Output\n\n::: incremental\n- **Group 3 differs from both others** — intervals exclude 0, adjusted p-values tiny. Exactly where we put the difference.\n- **Group 1 vs. Group 2:** interval spans 0, p = 0.81 — no evidence, *as designed*\n- The omnibus F said \"something's there\"; Tukey pointed at *what*, without inflating the false-alarm rate\n:::\n\n# The Bayesian Version {background-color=\"#1B2A4A\"}\n\n## Two New Packages\n\n- **brms** — **B**ayesian **R**egression **M**odels using **S**tan: writes the model, compiles it, samples the posterior\n- **emmeans** — **e**stimated **m**arginal **means**: takes any fitted model and returns group means and group *differences*\n\n```r\ninstall.packages(c(\"emmeans\", \"brms\"))\n```\n\n::: {.callout-warning appearance=\"simple\"}\n`brms` compiles models with your computer's C++ toolchain. Install **before** the lab, and expect the *first* model of each session to pause ~a minute at \"Compiling Stan program...\" — that's normal, not a crash.\n:::\n\n## Same Formula, Bayesian Machinery\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_rain <- brm(rainfall ~ group, data = rain,\n                  chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n::: incremental\n- Identical formula syntax to `aov()` — this pattern carries through the rest of the course\n- Priors: we didn't state any, so `brms` used its **defaults** — more on what that means on the next slide\n- `chains = 2, iter = 2000`: two independent MCMC runs, 2,000 draws each → a full **posterior distribution** for every group mean\n- `refresh = 0` just silences the sampling progress log\n:::\n\n## The Prior We Just Used\n\n::: incremental\n- `brms`'s defaults: essentially **flat on the group coefficients**, weakly informative on the intercept and spread\n- Flat priors = \"the data do the talking.\" Fine at this *n* — but *say so*: **\"we used brms default priors\"** belongs in any writeup that reports a posterior\n- One logic, several badges: `ttestBF()` (S6), `brm()` (today), `correlation` (S10) — **different interfaces, same move**: prior + likelihood → posterior\n- Session 10 shows what happens when you deliberately *change* the prior — and when it matters\n:::\n\n## Posterior Group Means\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrain_post <- emmeans(bayes_rain, ~ group)\nrain_post\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n group   emmean lower.HPD upper.HPD\n Group 1   34.2      28.8      38.9\n Group 2   32.0      27.1      37.1\n Group 3   31.4      26.5      36.5\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n:::\n\n\n. . .\n\nOne row per group: the posterior median and a 95% **HPD interval** — the range holding the most credible values for that group's mean, given the data.\n\n## Posterior Means, Seen\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(rain_post) +\n  geom_vline(xintercept = mean(rain$rainfall),\n             linetype = 2, color = crju_colors[\"garnet\"]) +\n  labs(x = \"Posterior mean rainfall (inches)\", y = NULL)\n```\n\n::: {.cell-output-display}\n![](week-08-anova_files/figure-revealjs/plot-emmeans-rain-1.png){width=960}\n:::\n:::\n\n\nAll three intervals swallow the grand mean (dashed line). No group separates from the pack.\n\n## What We Really Care About Are Differences\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(rain_post)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate lower.HPD upper.HPD\n Group 1 - Group 2    2.233     -5.05      9.20\n Group 1 - Group 3    2.733     -4.34      9.93\n Group 2 - Group 3    0.506     -7.00      7.57\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n:::\n\n\n::: incremental\n- Every 95% HPD interval for a pairwise difference **crosses 0**\n- Bayesian reading: *zero — \"no difference\" — remains a credible value for every contrast*. No credible difference between any pair.\n- Same verdict as F = 0.34, p = 0.71. Two traditions, one conclusion.\n:::\n\n## Differences, Seen\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pairs(rain_post)) +\n  geom_vline(xintercept = 0, linetype = 2, color = crju_colors[\"garnet\"])\n```\n\n::: {.cell-output-display}\n![](week-08-anova_files/figure-revealjs/plot-pairs-rain-1.png){width=960}\n:::\n:::\n\n\nZero sits comfortably inside every interval. When a difference is *real*, its interval abandons 0 — watch what real data do next.\n\n## This Workflow Is the Point\n\nThe four lines you just ran are the ones you keep:\n\n```r\nmodel <- brm(outcome ~ predictor, data = df)   # fit\npost  <- emmeans(model, ~ predictor)           # posterior summaries\nplot(post); pairs(post)                        # see it; compare\n```\n\n::: incremental\n- **Session 10** — the same `brm()` call, a numeric predictor\n- **Sessions 11–12** — the same call again, several predictors, then a binary outcome\n- **Your final project** — the Bayesian half of your both-traditions model\n- The ANOVA was the *excuse* to learn this. The workflow is the thing you keep. Also true of the interval rule: **crosses 0 → not credible; excludes 0 → credible**, forever after.\n:::\n\n# Real Data: Does the Clock Differ by Crime Type? {background-color=\"#73000A\"}\n\n## The Question\n\nIn Session 5 we found violent crimes average slightly *later* in the day than property crimes — two groups. But our Chicago data sort every incident into **three** categories. ANOVA takes all three in one shot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrimes |> summarize(mean_hour = mean(hour), sd_hour = sd(hour),\n                    n = n(), .by = crime_category)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  crime_category mean_hour sd_hour     n\n  <chr>              <dbl>   <dbl> <int>\n1 Violent             12.8    6.87  9148\n2 Other               12.1    6.95 10481\n3 Property            12.5    6.63 10371\n```\n\n\n:::\n:::\n\n\n. . .\n\nViolent runs latest (12.8), Other earliest (12.1). Gaps of fractions of an hour, with SDs near 7. Real structure, or noise? And remember: n = 30,000 — big samples detect *tiny* things.\n\n## Look First\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-08-anova_files/figure-revealjs/chicago-box-1.png){width=960}\n:::\n:::\n\n\n## Frequentist: `aov()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchicago_model <- aov(hour ~ crime_category, data = crimes)\nsummary(chicago_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Df  Sum Sq Mean Sq F value          Pr(>F)    \ncrime_category     2    2351  1175.3    25.3 0.0000000000105 ***\nResiduals      29997 1393374    46.5                            \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n. . .\n\n**F(2, 29997) = 25.3, p ≈ 10⁻¹¹.** *Something* differs, emphatically. But that's all the omnibus F will ever tell us — which pairs, and by how much?\n\n## Which Pairs? Tukey\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(chicago_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = hour ~ crime_category, data = crimes)\n\n$crime_category\n                      diff        lwr       upr     p adj\nProperty-Other   0.4285629 0.20732516 0.6498006 0.0000168\nViolent-Other    0.6812419 0.45269164 0.9097921 0.0000000\nViolent-Property 0.2526790 0.02356458 0.4817934 0.0263613\n```\n\n\n:::\n:::\n\n\n. . .\n\nAll three intervals exclude 0 — every category differs from every other. Now look at the **sizes**: 0.25 to 0.68 hours. That's **15 to 41 minutes**.\n\n## Bayesian: Same Workflow, Real Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_chicago <- brm(hour ~ crime_category, data = crimes,\n                     chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\nThe exact pattern from the rain example — `brm()`, then `emmeans()`, then `pairs()`. Nothing new to learn; only the data changed.\n\n## Bayesian Differences\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchicago_post <- emmeans(bayes_chicago, ~ crime_category)\npairs(chicago_post)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast           estimate lower.HPD upper.HPD\n Other - Property     -0.427    -0.610    -0.248\n Other - Violent      -0.681    -0.858    -0.487\n Property - Violent   -0.256    -0.454    -0.065\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n:::\n\n\n. . .\n\nEvery HPD interval **excludes 0** — all three differences are credible. (Watch the signs: `emmeans` orders groups alphabetically, so these are Other − Property, Other − Violent, Property − Violent — the mirror image of Tukey's table. Same gaps.)\n\n## Detectable ≠ Dramatic (Reprise)\n\n::: incremental\n- Both traditions agree: mean incident hour genuinely differs across all three categories\n- But the biggest gap is **41 minutes** and the smallest is **15 minutes** — on a 24-hour clock, with SDs near 7 hours\n- 30,000 incidents give us the power to detect differences this small. Detecting them is not the same as their *mattering*.\n- Your job as the analyst: report **direction** *and* **size**, every time. \"Significant\" without magnitude is malpractice — Session 6's lesson, now with three groups.\n:::\n\n## It Was Regression All Along\n\nPromised at the top of class. Same data, same question, one function swapped:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(lm(hour ~ crime_category, data = crimes))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: hour\n                  Df  Sum Sq Mean Sq F value           Pr(>F)    \ncrime_category     2    2351 1175.31  25.302 0.00000000001048 ***\nResiduals      29997 1393374   46.45                             \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n. . .\n\n**The identical F and p-value.** `aov()` is a thin wrapper around `lm()` — ANOVA *is* a regression with one categorical predictor. In Session 11 you'll fit that same model and read its coefficients as differences between groups, which is what Tukey was showing you all along.\n\n## How to Report It\n\n> **Frequentist:** \"Mean incident hour differed across crime categories, F(2, 29997) = 25.3, p < .001. Tukey's HSD: violent crimes averaged 0.25 hours (≈ 15 minutes) later than property crimes, 95% CI [0.02, 0.48], with similarly small gaps for the other pairs.\"\n\n> **Bayesian:** \"The posterior difference in mean hour (Violent − Property) was 0.26 hours, 95% HPD [0.06, 0.45], excluding zero — a credible but small difference.\"\n\nBoth sentences state the difference, the uncertainty, **and the magnitude**.\n\n## Today's Lab & Homework\n\n- **Lab 8:** the full ANOVA workflow, both traditions — three classrooms, then Alaska crash data ([lab page](../labs/lab-08-anova.qmd))\n- **Homework 8:** ANOVA on Stanton's `chickwts` data — *plus* **Project Checkpoint 1**: descriptive statistics and one plot on **your** final-project dataset ([Session 8 page](../weeks/week-08.qmd))\n- **Session 9 is the MIDTERM** — covers Sessions 1–8. Study guide on the site; no new reading. Review Stanton Ch. 1–6, the session pages, and your labs and homework.\n",
    "supporting": [
      "week-08-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}