{
  "hash": "03c965b12131f7c3ad04dc6504ff022d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 6 · One Question, Two Tests\"\nsubtitle: \"CRJU 705 · Session 6\"\n---\n\n**Goal:** by the end of this lab you can take one yes/no question about two groups and answer it twice: with a **p-value** from `prop.test()`, and with a **posterior** from `bayes_prop_test()`. Same four numbers go into both. What changes is the sentence each one lets you say.\n\n**How labs work:** run the Setup chunk as-is, follow the Walkthrough along with me, then complete the **Your Turn** tasks in your own script. That script is what you submit to Canvas before you leave.\n\n## Setup\n\nOpen RStudio, start a new R script, and run:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nsource(\"https://smourtgos.github.io/crju705/R/bayes.R\")\n\nofficers <- read_csv(\"https://smourtgos.github.io/crju705/data/officers.csv\",\n                     show_col_types = FALSE) |>\n  filter(!is.na(ptsd_screen)) |>\n  mutate(ptsd_screen = factor(ptsd_screen, levels = c(\"Positive\", \"Negative\")))\n```\n:::\n\n\nThese are last week's correctional officers, set up exactly the same way: the eight officers with no PTSD screen on file are dropped (we say so out loud), which leaves 192, and Positive comes first.\n\nOne line is new. `source()` runs an R file from the course website, and that file gives you one new function, `bayes_prop_test()`. There is nothing to install. If you ever see `could not find function \"bayes_prop_test\"`, you skipped this line.\n\n## Walkthrough\n\n### Count first\n\nOur question: **do male and female officers screen positive for PTSD at different rates?** Every test today starts from a count, just like last week:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nofficers |> count(gender, ptsd_screen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  gender          ptsd_screen     n\n  <chr>           <fct>       <int>\n1 Female          Positive        8\n2 Female          Negative       37\n3 Male            Positive       33\n4 Male            Negative      111\n5 Nonbinary/Other Positive        1\n6 Nonbinary/Other Negative        2\n```\n\n\n:::\n:::\n\n\nRead four numbers off that table, two per group: how many screened positive, out of how many.\n\n- **Male:** 33 positive, out of 33 + 111 = **144**\n- **Female:** 8 positive, out of 8 + 37 = **45**\n\n(Three officers are listed as Nonbinary/Other. Three people is too few to compare with anyone, so we leave that row alone and say so.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n33 / 144\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2291667\n```\n\n\n:::\n\n```{.r .cell-code}\n8 / 45\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1777778\n```\n\n\n:::\n:::\n\n\nAbout **23%** of the men and **18%** of the women. A gap of about 5 percentage points. Male goes first all the way through, so every difference reads **Male minus Female**.\n\nIs a 5-point gap real, or is it the kind of gap you get by luck with only 45 women in the sample?\n\n### The frequentist test: `prop.test()` with two groups\n\nLast week you typed one \"how many\" and one \"out of how many.\" With two groups you type two of each, wrapped in `c()`. Male first, both times:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(33, 8), n = c(144, 45))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(33, 8) out of c(144, 45)\nX-squared = 0.27341, df = 1, p-value = 0.6011\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.09430734  0.19708512\nsample estimates:\n   prop 1    prop 2 \n0.2291667 0.1777778 \n```\n\n\n:::\n:::\n\n\nRead it from the bottom up.\n\n- **`prop 1` and `prop 2`** are the two rates, 0.229 and 0.178. Male is `prop 1` because we typed it first.\n- **`95 percent confidence interval`** is for the *difference*, Male minus Female: about **-0.09 to +0.20**, or 9 points lower to 20 points higher. Zero is inside it. That is last week's skill.\n- **`p-value = 0.6011`** is tonight's new line. If men and women truly screened positive at the *same* rate, a gap this big or bigger would still turn up about **60%** of the time, just from the luck of who landed in the sample.\n\nA p-value of 0.60 is nowhere near 0.05. The verdict is **\"fail to reject the null.\"**\n\n### Saying it out loud without lying\n\nHere is the sentence I want:\n\n> In this sample, 23% of male officers and 18% of female officers screened positive. A gap that size is well within what chance alone produces (p = 0.60), so these data cannot tell us whether the true rates differ.\n\nAnd here is what not to say:\n\n- ~~\"There is a 60% chance that men and women have the same rate.\"~~ The p-value is about the *data*, assuming the null is true. It is never the probability that the null is true.\n- ~~\"We proved there is no difference.\"~~ Failing to reject is not proving. The interval allows anything from 9 points lower to 20 points higher.\n- ~~\"Men have higher PTSD rates (23% vs 18%).\"~~ That is the estimate with the uncertainty deleted.\n\n### The Bayesian test: same four numbers\n\nNow hand the same four numbers to `bayes_prop_test()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(33, 8), n = c(144, 45))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  33 of 144 (22.9%)\ndata, group 2:  8 of 45 (17.8%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  23.3%         16.8% to 30.5%\ngroup 2                  19.1%         9.4% to 31.4%\ndifference (1 minus 2)   4.2 points    -9.6 to 16.4 points\n\nProbability group 1 is higher than group 2: 0.74 \nProbability group 1 is lower than group 2:  0.26 \n```\n\n\n:::\n:::\n\n\nRead it top to bottom.\n\n- The first lines repeat your data back to you, so you can check your typing.\n- **`prior`** says \"know-nothing.\" We did not tell it what we believed beforehand, so it started from a blank slate.\n- **`estimate`** is the best single guess for each group's true rate, and each group gets its own **credible interval**.\n- **`difference (1 minus 2)`** is Male minus Female: about **4 points**, with a 95% credible interval of roughly **-10 to +16 points**.\n- The last two lines answer the question directly: the probability that the male rate is higher is about **0.74**.\n\nHere is the sentence this one lets you say, and it is the sentence we were *forbidden* to say about a confidence interval last week:\n\n> Given these data, there is a 95% probability that the true difference is between 10 points lower and 16 points higher for men, and about a 74% probability that the male rate is the higher one.\n\nNotice the two tests do not disagree. Both intervals run from roughly -10 to somewhere between +16 and +20. One stops at \"not significant.\" The other tells you *how probable* each direction is: 74% is better than a coin flip, and a long way from sure.\n\n### Adding what you knew beforehand\n\nA Bayesian can bring in earlier knowledge, as long as they say it out loud. Suppose earlier surveys at these facilities found about **1 officer in 5** screening positive, and you trust that about as much as you would trust having already seen **20 officers: 4 positive, 16 negative**. That belief is two numbers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(33, 8), n = c(144, 45), prior = c(4, 16))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  33 of 144 (22.9%)\ndata, group 2:  8 of 45 (17.8%)\nprior:          4 yes, 16 no (about 20%, worth 20 cases), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  22.6%         16.5% to 29.2%\ngroup 2                  18.5%         10.1% to 28.7%\ndifference (1 minus 2)   4.1 points    -7.6 to 15.0 points\n\nProbability group 1 is higher than group 2: 0.77 \nProbability group 1 is lower than group 2:  0.23 \n```\n\n\n:::\n:::\n\n\nLook at the `prior` line, then at what changed: almost nothing. The probability moved from 0.74 to 0.77. With 189 real officers in the data, 20 imaginary ones do not carry much weight. A prior matters most when you have very little data.\n\n### The p-value was in `t.test()` the whole time\n\nLast week you ran this line and read the interval. Look one line higher:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(sleep_hours ~ ptsd_screen, data = officers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  sleep_hours by ptsd_screen\nt = 1.0014, df = 60.499, p-value = 0.3206\nalternative hypothesis: true difference in means between group Positive and group Negative is not equal to 0\n95 percent confidence interval:\n -0.2568901  0.7721282\nsample estimates:\nmean in group Positive mean in group Negative \n              6.580952               6.323333 \n```\n\n\n:::\n:::\n\n\n`p-value = 0.3206`. If officers who screen positive and negative truly slept the same amount, a gap as big as ours (about 15 minutes) would turn up about a third of the time by luck. Fail to reject. It is the same conclusion the interval gave you last week, because zero was inside it.\n\n## Your Turn\n\nSame moves, new question: **do officers at the North Unit and the Central Unit screen positive at different rates?** Work in your own script and comment each answer. North goes first all the way through.\n\n**1.** Count. Run `officers |> count(facility, ptsd_screen)`. In a comment, write the four numbers you need: how many screened positive at North, out of how many, and the same for Central. Then compute the two rates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n**2.** The frequentist test. Put your four numbers into `prop.test(x = c(__, __), n = c(__, __))`, North first. In a comment, report the confidence interval for the difference and the p-value. Do you reject the null or fail to reject it?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n**3.** Write the sentence. In a comment, state your Task 2 result the way I did in the walkthrough. Then write one *wrong* sentence about your p-value underneath it, and label what is wrong with it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# a comment-only task\n```\n:::\n\n\n**4.** The Bayesian test. Put the same four numbers into `bayes_prop_test()`. In a comment, report the credible interval for the difference and the probability that North's rate is higher. Then write the sentence this output lets you say that Task 2's output does not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n**5.** The p-value in `t.test()`. Run `t.test(job_satisfaction ~ ptsd_screen, data = officers)`, the line from last week's Your Turn. In a comment: what is the p-value, do you reject or fail to reject, and how does that match what the interval told you last week?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n**6.** *(Stretch)* Rerun Task 4 with the walkthrough's prior, `prior = c(4, 16)`. In a comment: how much did the probability move, and why so little?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\nWhen you are done, submit your script to Canvas. The in-class exercise is graded on completing it.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}