<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Scott M. Mourtgos">
  <title>CRJU 705 – Correlation, Then Midterm Review</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-46fe9194c7aa732e2eafbd472d3cb092.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Correlation, Then Midterm Review</h1>
  <p class="subtitle">CRJU 705 · Session 8 · Fall 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Scott M. Mourtgos 
</div>
</div>
</div>

</section>
<section id="this-week" class="slide level2">
<h2>This Week</h2>
<p><strong>Topic:</strong> one new tool, then we get ready for next week’s midterm.</p>
<ul>
<li><strong>First half:</strong> correlation. Both variables are numbers, no groups. Do two measures <strong>move together</strong>?</li>
<li><strong>Lab 8:</strong> you run the correlation recipe yourself</li>
<li><strong>Second half:</strong> midterm review, part by part</li>
</ul>
<p><strong>Learning goals:</strong> read r’s sign and strength; test it with <code>cor.test()</code>; explain why a correlation between <strong>areas</strong> says nothing about <strong>people</strong>.</p>
</section>
<section id="how-today-works" class="slide level2">
<h2>How Today Works</h2>
<div class="columns">
<div class="column" style="width:33%;">
<p><strong>Lecture</strong></p>
<p>Correlation: what r is, what it cannot see, and how to test it</p>
</div><div class="column" style="width:33%;">
<p><strong>Lab 8</strong></p>
<p>The recipe on two datasets, and you write the code</p>
</div><div class="column" style="width:33%;">
<p><strong>Midterm review</strong></p>
<p>What’s on the exam, and one practice problem per part</p>
</div></div>
<p>Everything I run tonight is written up in the <a href="../demos/demo-10-correlation.html">demo walkthrough</a>.</p>
</section>
<section id="which-test-one-new-row" class="slide level2">
<h2>Which Test? One New Row</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>The outcome is…</th>
<th>Compared across…</th>
<th>Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>yes/no</strong></td>
<td>two groups</td>
<td><code>prop.test()</code> and <code>bayes_prop_test()</code></td>
</tr>
<tr class="even">
<td><strong>a number</strong></td>
<td>two groups</td>
<td><code>t.test(outcome ~ group, data = )</code></td>
</tr>
<tr class="odd">
<td><strong>a number</strong></td>
<td><strong>another number</strong></td>
<td><code>cor.test(x, y)</code></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Sessions 5 to 7 were all about groups. Tonight every row has two numbers: do they rise and fall together? This is the doorway to regression (Sessions 10 and 11).</p>
</div>
</section>
<section>
<section id="a-new-kind-of-question" class="title-slide slide level1 center" data-background-color="#73000A">
<h1>A New Kind of Question</h1>

</section>
<section id="what-does-correlation-tell-us" class="slide level2">
<h2>What Does Correlation Tell Us?</h2>
<p>When two variables move together, how can we describe that relationship?</p>
<ul>
<li>One goes up when the other goes up: <strong>positive correlation</strong></li>
<li>One goes up when the other goes down: <strong>negative correlation</strong></li>
<li>Changes in one don’t track changes in the other: <strong>no correlation</strong></li>
</ul>
<div class="fragment">
<p>Direction is only half the story. The <strong>strength</strong> of the relationship tells how tightly the changes are linked. That’s the number we build today.</p>
</div>
</section>
<section id="which-is-which" class="slide level2">
<h2>Which Is Which?</h2>
<p>Positive, negative, or nothing? Make your call for each panel:</p>

<img data-src="week-10-correlation_files/figure-revealjs/guess-panels-1.png" width="960" class="r-stretch"></section>
<section id="which-is-which-revealed" class="slide level2">
<h2>Which Is Which? Revealed</h2>

<img data-src="week-10-correlation_files/figure-revealjs/guess-reveal-1.png" width="960" class="r-stretch"><div class="fragment">
<p>The lines make it obvious, and the r values put a number on what your eye already knew.</p>
</div>
</section>
<section id="real-world-examples" class="slide level2">
<h2>Real-World Examples</h2>
<ul>
<li><strong>Positive:</strong> hours studied ↑, exam scores ↑</li>
<li><strong>Negative:</strong> officers on shift ↑, response times ↓</li>
<li><strong>Near zero:</strong> shoe size and GPA</li>
</ul>
<div class="fragment">
<p><strong>Your turn:</strong> give me a CJ example of each, <em>and</em> one pair you suspect people <strong>believe</strong> is correlated but isn’t.</p>
</div>
</section>
<section id="correlation-does-not-mean-causation" class="slide level2">
<h2>Correlation Does NOT Mean Causation</h2>
<ul>
<li class="fragment">Correlation shows <strong>association</strong>, not cause and effect</li>
<li class="fragment">Ice cream sales and violent crime rise together every year. Does ice cream cause violence?</li>
<li class="fragment">Two variables can move together because of a <strong>third variable</strong> (summer heat drives both), or by pure coincidence</li>
<li class="fragment">When you see a correlation, ask: does X cause Y? Y cause X? Does something else drive both? Or is it luck?</li>
<li class="fragment">Correlation is a <strong>pattern</strong>, not proof of cause. <strong>Beware the lurking third variable!</strong></li>
</ul>
</section></section>
<section>
<section id="from-covariance-to-r" class="title-slide slide level1 center" data-background-color="#1B2A4A">
<h1>From Covariance to r</h1>

</section>
<section id="covariance-moving-together-in-raw-units" class="slide level2">
<h2>Covariance: Moving Together, in Raw Units</h2>
<p>Row by row: do x and y sit on the <em>same side</em> of their averages?</p>
<p><span class="math display">\[\text{cov}(x, y) \;=\; \frac{\sum_i (x_i - \bar{x})(y_i - \bar{y})}{n - 1}\]</span></p>
<ul>
<li class="fragment">Both above average (or both below): positive products, <strong>positive covariance</strong>. Opposite sides: <strong>negative covariance</strong></li>
<li class="fragment">The <strong>sign</strong> is trustworthy: covariance tells you <em>whether</em> two variables move together</li>
<li class="fragment">The <strong>size</strong> is not. Watch what happens on real data</li>
</ul>
</section>
<section id="the-units-problem" class="slide level2">
<h2>The Units Problem</h2>
<p>Two covariances with violent crime, from Chicago’s 77 community areas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">cov</span>(areas<span class="sc">$</span>unemployment_rate, areas<span class="sc">$</span>violent_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107.7543</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">cov</span>(areas<span class="sc">$</span>median_income,     areas<span class="sc">$</span>violent_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -482660.1</code></pre>
</div>
</div>
<div class="fragment">
<p>Is -482,660 a “stronger” relationship than 108? No idea. The first number is in <em>dollars times crimes per 1,000</em>; the second in <em>percentage points times crimes per 1,000</em>. <strong>Covariance is glued to its units</strong>, so you can’t compare across pairs.</p>
</div>
</section>
<section id="correlation-rescales-it" class="slide level2">
<h2>Correlation Rescales It</h2>
<p>Divide the covariance by both standard deviations and the units cancel:</p>
<p><span class="math display">\[r \;=\; \frac{\text{cov}(x, y)}{s_x \, s_y}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">cov</span>(areas<span class="sc">$</span>unemployment_rate, areas<span class="sc">$</span>violent_rate) <span class="sc">/</span></span>
<span id="cb5-2"><a></a>  (<span class="fu">sd</span>(areas<span class="sc">$</span>unemployment_rate) <span class="sc">*</span> <span class="fu">sd</span>(areas<span class="sc">$</span>violent_rate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8398579</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">cor</span>(areas<span class="sc">$</span>unemployment_rate, areas<span class="sc">$</span>violent_rate)   <span class="co"># same thing, one function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8398579</code></pre>
</div>
</div>
<div class="fragment">
<p>Always between <strong>-1 and +1</strong>, no units, comparable. Income runs r = -0.71 with violence, so unemployment (0.84) tracks violence more tightly than income does, direction aside.</p>
</div>
</section>
<section id="reading-r" class="slide level2 smaller">
<h2>Reading r</h2>
<table class="caption-top">
<colgroup>
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>r (either sign)</th>
<th>Strength</th>
<th>What the scatterplot looks like</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.8 to 1.0</td>
<td>Very strong</td>
<td>Dots hug a line</td>
</tr>
<tr class="even">
<td>0.4 to 0.7</td>
<td>Moderate</td>
<td>A clear trend, with plenty of scatter</td>
</tr>
<tr class="odd">
<td>0.1 to 0.3</td>
<td>Weak</td>
<td>A slight tilt you might not see without the line</td>
</tr>
<tr class="even">
<td>about 0</td>
<td>None (no <em>straight-line</em> pattern)</td>
<td>A shapeless cloud</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>The <strong>sign</strong> gives the direction: + means both rise together; - means one rises as the other falls. These bands are <strong>conventions, not laws</strong>: in messy social-science data, a “moderate” r can be a major finding.</p>
</div>
</section>
<section id="calibrate-your-eye" class="slide level2">
<h2>Calibrate Your Eye</h2>

<img data-src="week-10-correlation_files/figure-revealjs/r-grid-1.png" width="960" class="r-stretch"><p>By 0.5 (either sign) the trend is visible; below 0.2 your eye mostly sees noise, and it’s right.</p>
</section></section>
<section>
<section id="what-r-cannot-see" class="title-slide slide level1 center" data-background-color="#73000A">
<h1>What r Cannot See</h1>

</section>
<section id="anscombes-quartet-four-identical-summaries" class="slide level2">
<h2>Anscombe’s Quartet: Four Identical Summaries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>anscombe_long <span class="ot">&lt;-</span> anscombe <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="fu">c</span>(<span class="st">".value"</span>, <span class="st">"set"</span>), <span class="at">names_pattern =</span> <span class="st">"(.)(.)"</span>)</span>
<span id="cb9-3"><a></a></span>
<span id="cb9-4"><a></a>anscombe_long <span class="sc">|&gt;</span></span>
<span id="cb9-5"><a></a>  <span class="fu">summarize</span>(<span class="at">mean_x =</span> <span class="fu">mean</span>(x), <span class="at">mean_y =</span> <span class="fu">mean</span>(y), <span class="at">r =</span> <span class="fu">cor</span>(x, y), <span class="at">.by =</span> set)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  set   mean_x mean_y     r
  &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 1          9   7.50 0.816
2 2          9   7.50 0.816
3 3          9   7.5  0.816
4 4          9   7.50 0.817</code></pre>
</div>
</div>
<div class="fragment">
<p>Four little datasets that ship with R (Anscombe, 1973). Same averages, same r = 0.82. Statistically interchangeable. Right?</p>
</div>
</section>
<section id="anscombes-quartet-seen" class="slide level2">
<h2>Anscombe’s Quartet, Seen</h2>

<img data-src="week-10-correlation_files/figure-revealjs/anscombe-plot-1.png" width="960" class="r-stretch"><p>Only Set 1 is what you picture when someone says “r = 0.82.” <strong>Always plot before you correlate.</strong></p>
</section>
<section id="limitation-1-r-only-sees-straight-lines" class="slide level2">
<h2>Limitation 1: r Only Sees Straight Lines</h2>

<img data-src="week-10-correlation_files/figure-revealjs/u-shape-1.png" width="960" class="r-stretch"><p>Think stress and performance: an upside-down U. r near 0 means no <strong>straight-line</strong> relationship, not no relationship.</p>
</section>
<section id="limitation-2-one-point-can-manufacture-a-correlation" class="slide level2">
<h2>Limitation 2: One Point Can Manufacture a Correlation</h2>

<img data-src="week-10-correlation_files/figure-revealjs/outlier-demo-1.png" width="960" class="r-stretch"></section>
<section id="what-just-happened" class="slide level2">
<h2>What Just Happened</h2>
<ul>
<li class="fragment">Twenty points of pure noise happened to give r = -0.28. <strong>Small samples produce correlations out of nothing</strong>; that’s why we test, not just compute</li>
<li class="fragment">Adding <strong>one</strong> extreme point swung r to <strong>+0.42</strong>: it flipped the sign <em>and</em> manufactured a “moderate positive” correlation</li>
<li class="fragment">Neither number describes a real relationship</li>
<li class="fragment">Outliers can also work the other way, <em>hiding</em> a real correlation</li>
<li class="fragment">Defenses: <strong>plot first</strong> (you’d catch this instantly), and a correlation that doesn’t care about wild values…</li>
</ul>
</section>
<section id="a-rank-based-backup-spearmans-rho" class="slide level2">
<h2>A Rank-Based Backup: Spearman’s rho</h2>
<p>Replace each value with its <strong>rank</strong> (1st, 2nd, 3rd…), then correlate the ranks. Spearman asks only: <em>is the relationship consistently up, or consistently down?</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">c</span>(<span class="at">pearson  =</span> <span class="fu">cor</span>(outlier_data<span class="sc">$</span>x, outlier_data<span class="sc">$</span>y),</span>
<span id="cb11-2"><a></a>  <span class="at">spearman =</span> <span class="fu">cor</span>(outlier_data<span class="sc">$</span>x, outlier_data<span class="sc">$</span>y, <span class="at">method =</span> <span class="st">"spearman"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   pearson   spearman 
 0.4235804 -0.1142857 </code></pre>
</div>
</div>
<div class="fragment">
<p>To Spearman, the wild point is just “rank 21”: rho drifts from -0.29 to -0.11, still weak, while Pearson flipped sign. When data are skewed or have wild values, check Spearman alongside Pearson.</p>
</div>
</section></section>
<section>
<section id="real-data-structure-and-violence-across-chicago" class="title-slide slide level1 center" data-background-color="#1B2A4A">
<h1>Real Data: Structure and Violence Across Chicago</h1>

</section>
<section id="from-incidents-to-areas" class="slide level2">
<h2>From Incidents to Areas</h2>
<p>The anchor data’s <strong>second level</strong> (<a href="../chicago-data.html">codebook</a>): all 237,472 of 2025’s incidents, added up to the <strong>77 community areas</strong> and joined with Census measures:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>areas <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a></a>  <span class="fu">select</span>(community, violent_rate, unemployment_rate, median_income, pct_vacant) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a></a>  <span class="fu">head</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  community   violent_rate unemployment_rate median_income pct_vacant
  &lt;chr&gt;              &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;
1 Rogers Park         21.7               7.1         60916        9.5
2 West Ridge          12.2               7.3         70823        7.7
3 Uptown              22.8               4.7         70067        9.1</code></pre>
</div>
</div>
<div class="fragment">
<p>A classic question about places: <strong>which features of a neighborhood track its violence?</strong> Correlation is the right first tool.</p>
</div>
</section>
<section id="look-first-unemployment-and-violence" class="slide level2">
<h2>Look First: Unemployment and Violence</h2>

<img data-src="week-10-correlation_files/figure-revealjs/unemp-scatter-1.png" width="960" class="r-stretch"><p>One dot = one community area. This is about as strong as area-level associations get in criminology.</p>
</section>
<section id="the-full-menu-in-one-dataset" class="slide level2">
<h2>The Full Menu, in One Dataset</h2>

<img data-src="week-10-correlation_files/figure-revealjs/four-covariates-1.png" width="960" class="r-stretch"><p>Strong positive, moderate positive, strong negative, and one genuine <em>nothing</em> (median age). Real data span the whole menu.</p>
</section>
<section id="these-are-areas-not-people" class="slide level2">
<h2>These Are Areas, Not People</h2>
<p>Our r = 0.84 says: <strong>community areas</strong> with higher unemployment rates record more violent crime per 1,000 residents.</p>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>The ecological fallacy:</strong> using an association between <em>groups</em> (areas, states, cities) to make claims about <em>individuals</em>. Our data contain <strong>no individuals</strong>. Nothing here says <em>unemployed people</em> commit violence.</p>
</div>
</div>
</div>
<div class="fragment">
<p>The classic example (Robinson, 1950): across U.S. <strong>states</strong>, more immigrants went with <em>higher</em> literacy. Across <strong>individuals</strong>, immigrants had <em>lower</em> literacy. Immigrants had settled in states with high literacy. Adding people up into areas can weaken, exaggerate, or even <strong>flip</strong> a relationship.</p>
</div>
</section>
<section id="saying-it-out-loud-area-data" class="slide level2">
<h2>Saying It Out Loud (Area Data)</h2>
<p>✅ <strong>Defensible:</strong></p>
<blockquote>
<p>“Community areas with higher unemployment rates recorded higher violent-crime rates (r = 0.84).”</p>
</blockquote>
<p>❌ <strong>Not defensible:</strong></p>
<blockquote>
<p>“Unemployed residents commit more violent crime.” <em>(A claim about individuals. These data can’t see individuals.)</em></p>
</blockquote>
<blockquote>
<p>“Unemployment drives up violence.” <em>(A claim about cause. Concentrated poverty, disinvestment, and policing patterns all lurk behind both variables.)</em></p>
</blockquote>
</section></section>
<section>
<section id="putting-uncertainty-on-r" class="title-slide slide level1 center" data-background-color="#73000A">
<h1>Putting Uncertainty on r</h1>

</section>
<section id="from-description-to-a-test" class="slide level2">
<h2>From Description to a Test</h2>
<p>We can <em>see</em> r = 0.84. The same question as every test since Session 6:</p>
<ul>
<li class="fragment"><strong>Null hypothesis:</strong> the true correlation is 0. No straight-line association in the process that produced these data</li>
<li class="fragment"><em>If</em> it were 0, how surprising would an r like ours be, with 77 areas?</li>
<li class="fragment">One wrinkle: these 77 areas are <strong>all of Chicago</strong>, not a sample. Read the null as a claim about the <em>process</em> that produces neighborhood outcomes, not about a bigger population we sampled from</li>
</ul>
</section>
<section id="cor.test" class="slide level2">
<h2><code>cor.test()</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="fu">cor.test</span>(areas<span class="sc">$</span>unemployment_rate, areas<span class="sc">$</span>violent_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  areas$unemployment_rate and areas$violent_rate
t = 13.4, df = 75, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.7585749 0.8954023
sample estimates:
      cor 
0.8398579 </code></pre>
</div>
</div>
</section>
<section id="reading-it" class="slide level2">
<h2>Reading It</h2>
<ul>
<li class="fragment"><strong>cor = 0.84</strong> at the bottom: that’s r</li>
<li class="fragment"><strong>95% confidence interval: 0.76 to 0.90.</strong> An interval for the <em>correlation</em>, so it lives between -1 and +1. <strong>Where is zero?</strong> Far outside it</li>
<li class="fragment"><strong>p-value &lt; 2.2e-16:</strong> reject the null. A world with no correlation essentially never lines up 77 areas this tightly</li>
<li class="fragment">With 77 areas, any r above about <strong>0.22</strong> (either sign) clears p &lt; 0.05. Passing the test is a low bar; <strong>the strength is the story</strong></li>
<li class="fragment">Nothing in this output turns association into cause, or areas into individuals</li>
</ul>
</section>
<section id="when-the-answer-is-nothing-here" class="slide level2">
<h2>When the Answer Is “Nothing Here”</h2>
<p>Median age and violence, from the menu slide:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">cor.test</span>(areas<span class="sc">$</span>median_age, areas<span class="sc">$</span>violent_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  areas$median_age and areas$violent_rate
t = -0.1336, df = 75, p-value = 0.8941
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.2385791  0.2092774
sample estimates:
        cor 
-0.01542445 </code></pre>
</div>
</div>
<div class="fragment">
<p>Interval -0.24 to +0.21: <strong>zero is inside</strong>. Fail to reject. Say <em>no evidence of a straight-line association</em>, which is <strong>not</strong> proof there is none.</p>
</div>
</section>
<section id="several-pairs-at-once" class="slide level2">
<h2>Several Pairs at Once</h2>
<p>Real analyses rarely stop at one pair. <code>cor()</code> takes every numeric column you give it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>areas <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a></a>  <span class="fu">select</span>(violent_rate, unemployment_rate, median_income, pct_vacant) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a></a>  <span class="fu">cor</span>() <span class="sc">|&gt;</span></span>
<span id="cb19-4"><a></a>  <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  violent_rate unemployment_rate median_income pct_vacant
violent_rate              1.00              0.84         -0.71       0.81
unemployment_rate         0.84              1.00         -0.81       0.67
median_income            -0.71             -0.81          1.00      -0.55
pct_vacant                0.81              0.67         -0.55       1.00</code></pre>
</div>
</div>
<div class="fragment">
<p>Read it like a mileage chart: each pair appears twice, and the 1s down the diagonal are each variable with itself. Handy for a first look at your project variables. Then plot and <code>cor.test()</code> the pairs that matter.</p>
</div>
</section>
<section id="how-to-report-it" class="slide level2">
<h2>How to Report It</h2>
<blockquote>
<p>“Across Chicago’s 77 community areas, unemployment was strongly associated with the violent-crime rate, r = 0.84, 95% CI 0.76 to 0.90, p &lt; 0.001. This is an area-level association; it does not speak to individuals.”</p>
</blockquote>
<p>Direction, strength, uncertainty, and the level of analysis. Every time.</p>
</section>
<section id="your-turn-5-minutes" class="slide level2">
<h2>Your Turn (5 Minutes)</h2>
<p><code>pct_no_hs_diploma</code> is the share of an area’s adults without a high-school diploma. <strong>Before you compute anything:</strong> write down your guess for the sign and rough size of its correlation with <code>violent_rate</code>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>areas <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://smourtgos.github.io/crju705/data/chicago-areas.csv"</span>)</span>
<span id="cb21-2"><a></a></span>
<span id="cb21-3"><a></a><span class="fu">ggplot</span>(areas, <span class="fu">aes</span>(pct_no_hs_diploma, violent_rate)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb21-4"><a></a><span class="fu">cor.test</span>(areas<span class="sc">$</span>pct_no_hs_diploma, areas<span class="sc">$</span>violent_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="fragment">
<p>Most people guess a strong positive. The data: <strong>r = 0.17, p = 0.13</strong>, no evidence of an association. Yet <code>pct_bachelors</code> runs <strong>-0.45</strong>. Sensible-sounding measures can fail, and related measures tangle together. Untangling them is <em>exactly</em> what regression does in Session 10.</p>
</div>
</section></section>
<section>
<section id="now-you-lab-8" class="title-slide slide level1 center" data-background-color="#1B2A4A">
<h1>Now You: Lab 8</h1>

</section>
<section id="lab-8" class="slide level2">
<h2>Lab 8</h2>
<ul>
<li>The same recipe, twice: <strong>question, look, number and test, say it</strong></li>
<li>Neighborhoods: poverty and assaults</li>
<li>Correctional officers: time on the job and job satisfaction</li>
<li>Submit your Your Turn script to Canvas before you leave</li>
</ul>
<p><a href="../labs/lab-10-correlation.html">Lab 8 page</a></p>
</section></section>
<section>
<section id="midterm-review" class="title-slide slide level1 center" data-background-color="#73000A">
<h1>Midterm Review</h1>

</section>
<section id="the-midterm-next-week-session-9" class="slide level2">
<h2>The Midterm: Next Week, Session 9</h2>
<ul>
<li><strong>In class, monitored.</strong> You get an <code>.R</code> script and the data files; you answer in the script and submit it</li>
<li><strong>Allowed:</strong> your <em>printed</em> notes and homework. <strong>Not allowed:</strong> internet, AI tools, messaging</li>
<li>Code answers run in R; interpretation answers go in <code>#</code> comments</li>
<li>Everything on it is something we’ve already done. <strong>Nothing new</strong></li>
<li>Full list of skills: the <a href="../midterm.html">Midterm Study Guide</a></li>
</ul>
</section>
<section id="six-parts" class="slide level2 smaller">
<h2>Six Parts</h2>
<table class="caption-top">
<colgroup>
<col style="width: 8%">
<col style="width: 52%">
<col style="width: 12%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Part</th>
<th>Topic</th>
<th>Points</th>
<th>Where we did it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Data and levels of measurement</td>
<td>10</td>
<td>Sessions 1 and 2</td>
</tr>
<tr class="even">
<td>2</td>
<td>Descriptive statistics</td>
<td>20</td>
<td>Session 2</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Probability, sampling, and Bayes counting tables</td>
<td>20</td>
<td>Sessions 3 and 4</td>
</tr>
<tr class="even">
<td>4</td>
<td>Confidence intervals and <code>t.test()</code></td>
<td>20</td>
<td>Sessions 5 to 7</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Frequentist and Bayesian: p-values, <code>bayes_prop_test()</code></td>
<td>15</td>
<td>Sessions 6 and 7</td>
</tr>
<tr class="even">
<td>6</td>
<td>Correlation</td>
<td>15</td>
<td>Tonight</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>The next slides are one practice problem per part. <strong>Different data from the exam, same skills.</strong></p>
</div>
</section>
<section id="part-1-levels-of-measurement" class="slide level2">
<h2>Part 1: Levels of Measurement</h2>
<p>Crash data: nominal, ordinal, interval, or ratio?</p>
<ul>
<li><code>road_condition</code> (normal, wet, icy)</li>
<li><code>severity</code> (coded 1, 2, 3, from least to most severe)</li>
<li><code>driver_age</code></li>
<li><code>vehicle1_year</code></li>
</ul>
<div class="fragment">
<p><strong>Nominal</strong> (no order) · <strong>ordinal</strong> (ordered, uneven spacing, even when stored as 1, 2, 3) · <strong>ratio</strong> (true zero) · <strong>interval</strong> (equal steps, no true zero: year 0 is not “no year”)</p>
<p>On the exam: explain each level, with your own CJ example. <strong>Order, spacing, zero.</strong></p>
</div>
</section>
<section id="part-2-describe-a-small-vector" class="slide level2">
<h2>Part 2: Describe a Small Vector</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>days_held <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">20</span>)</span>
<span id="cb22-2"><a></a><span class="fu">mean</span>(days_held)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.375</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="fu">median</span>(days_held)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="fu">sd</span>(days_held)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.390562</code></pre>
</div>
</div>
<div class="fragment">
<ul>
<li>One long stay (20 days) pulls the <strong>mean</strong> up to 4.4, while the <strong>median</strong> stays at 2. Which one describes a <em>typical</em> stay? The median. The tail names the skew: this is <strong>right-skewed</strong></li>
<li>The SD, in words: <em>how far a typical value sits from the mean</em>. Here, about 6 days, and most of that comes from one person</li>
</ul>
</div>
</section>
<section id="part-3-the-counting-table" class="slide level2">
<h2>Part 3: The Counting Table</h2>
<p>A risk tool flags people as “likely to reoffend.” <strong>10%</strong> of people actually reoffend. The tool flags <strong>80%</strong> of those who do, and <strong>20%</strong> of those who don’t. Out of 1,000 people: of everyone flagged, what share actually reoffends?</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Flagged</th>
<th>Not flagged</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reoffends</td>
<td>80</td>
<td>20</td>
<td>100</td>
</tr>
<tr class="even">
<td>Does not</td>
<td>180</td>
<td>720</td>
<td>900</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>260</strong></td>
<td>740</td>
<td>1,000</td>
</tr>
</tbody>
</table>
<p>P(reoffends | flagged) = 80 / <strong>260</strong> = <strong>0.31</strong>. The “80%” is P(flagged | reoffends), the <em>other</em> conditional. <strong>Read the bar out loud: whatever follows it is the denominator.</strong></p>
</div>
</section>
<section id="part-4-a-two-group-t.test" class="slide level2">
<h2>Part 4: A Two-Group <code>t.test()</code></h2>
<p>Were intoxicated drivers younger than sober drivers, on average? (Intoxicated first, set by a <code>factor()</code> line.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="fu">t.test</span>(driver_age <span class="sc">~</span> intox, <span class="at">data =</span> crashes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

</section>
<section id="part-4-a-two-group-t.test-output" class="slide level2 output-location-slide"><h2>Part 4: A Two-Group <code>t.test()</code></h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  driver_age by intox
t = -0.72468, df = 1808.5, p-value = 0.4687
alternative hypothesis: true difference in means between group Intoxicated and group Sober is not equal to 0
95 percent confidence interval:
 -1.0104429  0.4652006
sample estimates:
mean in group Intoxicated       mean in group Sober 
                 38.33204                  38.60466 </code></pre>
</div>
</div></section><section id="part-4-reading-it" class="slide level2">
<h2>Part 4: Reading It</h2>
<ul>
<li>Averages: intoxicated drivers 38.3, sober drivers 38.6. The interval is <strong>Intoxicated minus Sober</strong>, in <strong>years</strong>, because age is in years: -1.0 to 0.5</li>
<li><strong>Where is zero?</strong> Inside the interval, so no detectable difference (p = 0.47)</li>
<li><strong>Detectable is not the same as large.</strong> The exam asks both: is there a difference, and is it big in real units?</li>
<li>A boxplot first (<code>ggplot(crashes, aes(intox, driver_age)) + geom_boxplot()</code>) shows you the answer before the test does</li>
</ul>
</section>
<section id="part-5-which-sentence-belongs-to-which-output" class="slide level2">
<h2>Part 5: Which Sentence Belongs to Which Output?</h2>
<p>Lab 7: suspicious-person stops vs traffic stops, searched or not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">bayes_prop_test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">3214</span>, <span class="dv">2023</span>), <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">3214</span> <span class="sc">+</span> <span class="dv">17271</span>, <span class="dv">2023</span> <span class="sc">+</span> <span class="dv">21191</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="fragment">
<ul>
<li><em>“If there were truly no difference, a gap this large would almost never happen.”</em> That’s the <strong>p-value</strong> (<code>prop.test()</code>)</li>
<li><em>“Given these data, there is more than a 99% probability that suspicious-person stops have the higher search rate.”</em> That’s <strong><code>bayes_prop_test()</code></strong></li>
<li>A p-value is <strong>never</strong> the probability that the null is true</li>
<li>On the exam: <code>source("bayes.R")</code> (the file is in the exam folder)</li>
</ul>
</div>
</section>
<section id="part-5-which-sentence-belongs-to-which-output-output" class="slide level2 output-location-slide"><h2>Part 5: Which Sentence Belongs to Which Output?</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
    Bayesian test of two proportions 

data, group 1:  3,214 of 20,485 (15.7%)
data, group 2:  2,023 of 23,214 (8.7%)
prior:          know-nothing (1 yes, 1 no), same for both groups

                         estimate      95% credible interval
group 1                  15.7%         15.2% to 16.2%
group 2                  8.7%          8.4% to 9.1%
difference (1 minus 2)   7.0 points    6.4 to 7.6 points

Probability group 1 is higher than group 2: more than 0.99 
Probability group 1 is lower than group 2:  less than 0.01 </code></pre>
</div>
</div></section><section id="part-6-correlation" class="slide level2">
<h2>Part 6: Correlation</h2>
<p>You did it tonight. On the exam, the same four steps:</p>
<ol type="1">
<li><strong>Look:</strong> a scatterplot</li>
<li><strong>Number and test:</strong> <code>cor.test(x, y)</code>. Report r, the confidence interval, and the p-value</li>
<li><strong>Where is zero?</strong> Inside the interval or outside?</li>
<li><strong>Say it:</strong> direction and strength in words, and what the correlation <strong>cannot</strong> tell you (cause; and if the rows are places, anything about individuals)</li>
</ol>
</section>
<section id="how-to-study-this-week" class="slide level2">
<h2>How to Study This Week</h2>
<ul>
<li>Work through the <a href="../midterm.html">Midterm Study Guide</a>: every skill on the exam is listed there</li>
<li>Re-run your own labs and homework from Sessions 2 to 8 until the code feels routine</li>
<li>Do the practice pages: Sessions <a href="../practice/practice-02.html">2</a>, <a href="../practice/practice-03.html">3</a>, <a href="../practice/practice-04.html">4</a>, <a href="../practice/practice-05.html">5</a>, <a href="../practice/practice-06.html">6</a>, and <a href="../practice/practice-10.html">8</a></li>
<li><strong>Print</strong> the notes you want to have. No internet during the exam</li>
<li>Charge your laptop, and make sure <code>library(tidyverse)</code> and <code>library(modeest)</code> load</li>
</ul>
</section>
<section id="homework-and-next-week" class="slide level2">
<h2>Homework and Next Week</h2>
<ul>
<li><strong>Homework 8:</strong> correlation on the Chicago areas, <strong>plus Project Checkpoint 1</strong>: describe your project’s outcome and two or three predictors (<a href="../weeks/week-10.html">Session 8 page</a>). Due Sunday</li>
<li><strong>Session 9:</strong> the midterm</li>
<li><strong>Checkpoint 2</strong> is due the Sunday after the midterm: correlations in <em>your</em> data, plus installing <code>brms</code> for Session 10</li>
<li><strong>Read before Session 10:</strong> Stanton Ch. 8 (multiple regression)</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>CRJU 705 · Session 8</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>