<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Scott M. Mourtgos">
  <title>CRJU 705 – Hypothesis Testing: Frequentist and Bayesian</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-1057dcdd0c631574b29197041191720a.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Hypothesis Testing: Frequentist and Bayesian</h1>
  <p class="subtitle">CRJU 705 · Session 6 · Fall 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Scott M. Mourtgos 
</div>
</div>
</div>

</section>
<section id="this-week" class="slide level2">
<h2>This Week</h2>
<p><strong>Topic:</strong> hypothesis testing — <em>twice</em>. One question, both great traditions.</p>
<ul>
<li>The Null Hypothesis Significance Test: its logic, and its fine print</li>
<li>p-values: what they are — and what they are not</li>
<li>Bayes’ theorem — back from Session 3, now pointed at hypotheses instead of diagnoses</li>
<li>The Bayesian answer: a posterior and a <strong>credible interval</strong>, from one line of R</li>
</ul>
<p><strong>Learning goals:</strong> run <code>prop.test()</code> <em>and</em> <code>bayes_prop_test()</code> on the same question; state correctly what each output lets you claim.</p>
</section>
<section id="how-today-works" class="slide level2">
<h2>How Today Works</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>The lecture</strong> — concepts</p>
<p>Stanton Ch. 5 → hypothesis testing, both ways: the p-value and the posterior</p>
</div><div class="column" style="width:50%;">
<p><strong>The in-class exercise</strong> — code</p>
<p>Lab 6: you run both tests yourself, step by step</p>
</div></div>
<p>Everything I run today is written up in the <a href="../demos/demo-06-hypothesis-testing.html">demo walkthrough</a>, so nothing on screen is something you have to capture in real time.</p>
</section>
<section id="where-weve-been" class="slide level2">
<h2>Where We’ve Been</h2>
<ul>
<li class="fragment"><strong>Session 3:</strong> Bayes’ theorem — beliefs update by evidence; ignore the base rate and “90% accurate” becomes a 15% answer</li>
<li class="fragment"><strong>Session 4:</strong> sampling distributions — sample statistics fluctuate in predictable ways</li>
<li class="fragment"><strong>Session 5:</strong> confidence intervals — an honest range around an estimate, and one sentence we were <em>not</em> allowed to say about it</li>
<li class="fragment"><strong>Today:</strong> the formal machinery for “is there a difference?” — then a second tradition answering the question you <em>meant</em> to ask</li>
</ul>
</section>
<section>
<section id="act-i-testing-the-frequentist-way" class="title-slide slide level1 center" data-background-color="#73000A">
<h1>Act I · Testing, the Frequentist Way</h1>

</section>
<section id="tonights-question" class="slide level2">
<h2>Tonight’s Question</h2>
<p>Among <strong>violent crimes</strong> in our Chicago sample: are the <em>domestic</em> ones more likely to end in an arrest?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>violent <span class="ot">&lt;-</span> crimes <span class="sc">|&gt;</span> <span class="fu">filter</span>(crime_category <span class="sc">==</span> <span class="st">"Violent"</span>)</span>
<span id="cb1-2"><a></a></span>
<span id="cb1-3"><a></a>violent <span class="sc">|&gt;</span> <span class="fu">count</span>(domestic, arrest)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  domestic arrest     n
  &lt;lgl&gt;    &lt;lgl&gt;  &lt;int&gt;
1 FALSE    FALSE   4685
2 FALSE    TRUE     714
3 TRUE     FALSE   3009
4 TRUE     TRUE     740</code></pre>
</div>
</div>
</section>
<section id="reading-the-table" class="slide level2">
<h2>Reading the Table</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Arrests</th>
<th>Out of</th>
<th>Arrest rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Domestic</strong></td>
<td>740</td>
<td>740 + 3,009 = 3,749</td>
<td><strong>19.7%</strong></td>
</tr>
<tr class="even">
<td><strong>Not domestic</strong></td>
<td>714</td>
<td>714 + 4,685 = 5,399</td>
<td><strong>13.2%</strong></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>A gap of about <strong>6.5 percentage points</strong>. All night the difference reads one way: <strong>Domestic minus Not domestic</strong>.</p>
</div>
<div class="fragment">
<p>But this is a <em>sample</em> of Chicago’s 2025 incidents. Session 4 taught us that sample numbers bounce around. Could a gap like this be nothing but bounce?</p>
</div>
</section>
<section id="lets-pretend-we-sampled-repeatedly" class="slide level2">
<h2>Let’s Pretend We Sampled Repeatedly</h2>
<p>Session 4’s move, applied to both groups at once: draw 10,000 repeated samples of each group and compute the arrest rate every time.</p>

<img data-src="week-06-hypothesis-testing_files/figure-revealjs/rep-rates-1.png" width="960" class="r-stretch"><p>The two piles do not even touch.</p>
</section>
<section id="the-difference-and-its-95-interval" class="slide level2">
<h2>The Difference and Its 95% Interval</h2>
<p>Subtract, pair by pair, and the <em>difference</em> gets its own pile:</p>

<img data-src="week-06-hypothesis-testing_files/figure-revealjs/rep-diff-1.png" width="960" class="r-stretch"><p>The middle 95% runs from about <strong>5 to 8.1 points</strong>. Zero is nowhere near it.</p>
</section>
<section id="what-if-there-were-no-real-difference" class="slide level2">
<h2>What If There Were No Real Difference?</h2>
<p>Build the <strong>boring world</strong> on purpose: give both groups the <em>same</em> arrest rate (the overall 15.9%), and run the same machinery.</p>

<img data-src="week-06-hypothesis-testing_files/figure-revealjs/rep-null-1.png" width="960" class="r-stretch"><p>Chance alone makes gaps of a point or two. It made a gap as big as ours in <strong>0 of 10,000</strong> tries. That count is the whole idea of a <strong>p-value</strong>.</p>
</section>
<section id="the-null-hypothesis-significance-test" class="slide level2 smaller">
<h2>The Null Hypothesis Significance Test</h2>
<ol type="1">
<li class="fragment"><strong>State the null</strong>, <span class="math inline">\(H_0\)</span>: the two arrest rates are the same (difference = 0). The boring world.</li>
<li class="fragment"><strong>State the alternative</strong>, <span class="math inline">\(H_1\)</span>: <em>some</em> difference. Note how little we commit to.</li>
<li class="fragment"><strong>Compute a test statistic</strong>: the observed gap, measured against how much gaps bounce by chance.</li>
<li class="fragment"><strong>Ask:</strong> how often would a gap this large appear by luck in the boring world? The <strong>p-value</strong>.</li>
<li class="fragment"><strong>Verdict:</strong> <span class="math inline">\(p &lt; \alpha\)</span> (usually .05) → “reject <span class="math inline">\(H_0\)</span>.” Otherwise → “fail to reject.”</li>
<li class="fragment">Note: the machine only weighs evidence <strong>against the null</strong> — <span class="math inline">\(H_1\)</span> never gets scored.</li>
</ol>
</section>
<section id="watch-the-p-value-do-its-job" class="slide level2">
<h2>Watch the p-Value Do Its Job</h2>
<video src="../media/week-06/NHST.mp4" controls="" preload="metadata" style="max-height:430px;">
</video>
<p>As the true difference grows, the overlap shrinks and <em>p</em> falls. Black = null · green = one alternative · orange = overlap · blue dashes = the α = .05 cutoffs.</p>
</section>
<section id="what-a-p-value-is-and-is-not" class="slide level2">
<h2>What a p-Value Is — and Is Not</h2>
<p><strong>It is:</strong> the probability of data <em>this extreme or more</em>, <strong>if</strong> the null is true and the model is right.</p>
<div class="fragment">
<p><strong>It is not:</strong></p>
<ul>
<li class="fragment"><del>the probability the null hypothesis is true</del> — that’s <span class="math inline">\(P(H_0 \mid \text{data})\)</span>, which frequentism never computes</li>
<li class="fragment"><del>the probability the result “is due to chance”</del> — same confusion, folksier outfit</li>
<li class="fragment"><del>1 − the probability the alternative is true</del></li>
<li class="fragment"><del>a measure of how <em>big</em> or <em>important</em> the effect is</del> — with enough data, microscopic effects earn microscopic p-values (hold that thought)</li>
</ul>
</div>
</section>
<section id="prop.test-on-the-real-question" class="slide level2">
<h2><code>prop.test()</code> on the Real Question</h2>
<p>Lab 5’s function, now with <strong>two groups</strong>: how many, out of how many, for each. Domestic first.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">740</span>, <span class="dv">714</span>), <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">3749</span>, <span class="dv">5399</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(740, 714) out of c(3749, 5399)
X-squared = 69.744, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: two.sided
95 percent confidence interval:
 0.04929331 0.08098520
sample estimates:
   prop 1    prop 2 
0.1973860 0.1322467 </code></pre>
</div>
</div>
</section>
<section id="reading-the-verdict" class="slide level2">
<h2>Reading the Verdict</h2>
<ul>
<li><strong><code>prop 1</code> and <code>prop 2</code></strong> at the bottom: 19.7% and 13.2%. Domestic is first because we typed it first</li>
<li><strong><code>95 percent confidence interval</code></strong>: about 4.9 to 8.1 points, Domestic minus Not domestic. Last week’s skill</li>
<li><strong><code>p-value &lt; 2.2e-16</code></strong>: R’s way of writing a decimal point followed by fifteen zeros. In the boring world, a gap like ours essentially never happens</li>
</ul>
<div class="fragment">
<p><span class="math inline">\(p &lt; .05\)</span> — <strong>“statistically significant.”</strong> Reject the null.</p>
</div>
</section>
<section id="the-same-line-lives-in-t.test" class="slide level2 smaller">
<h2>The Same Line Lives in <code>t.test()</code></h2>
<p>Last week’s homework, comparing two <em>means</em>. The p-value sat right above the interval the whole time:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">t.test</span>(injuries <span class="sc">~</span> intox, <span class="at">data =</span> crashes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  injuries by intox
t = 12.489, df = 1732.6, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Intoxicated and group Sober is not equal to 0
95 percent confidence interval:
 0.3259893 0.4474533
sample estimates:
mean in group Intoxicated       mean in group Sober 
                1.1300971                 0.7433758 </code></pre>
</div>
</div>
<p>Same reading: if both kinds of crash truly injured the same number of people, a gap this big would essentially never appear.</p>
</section></section>
<section>
<section id="the-fine-print-some-strong-assumptions" class="title-slide slide level1 center" data-background-color="#1B2A4A">
<h1>The Fine Print: Some Strong Assumptions</h1>

</section>
<section id="assumption-1-the-null-stands-alone" class="slide level2">
<h2>Assumption 1 · The Null Stands Alone</h2>

<img data-src="week-06-hypothesis-testing_files/figure-revealjs/sketch-null-1.png" width="960" class="r-stretch"><p>We computed how surprising the data are <em>under the null</em> — and never once said what the alternative world looks like.</p>
</section>
<section id="but-the-alternative-could-be-anywhere" class="slide level2">
<h2>…But the Alternative Could Be Anywhere</h2>

<img data-src="week-06-hypothesis-testing_files/figure-revealjs/sketch-alts-1.png" width="960" class="r-stretch"><p>“Reject the null” tells you where you <em>aren’t</em>. It never tells you where you <em>are</em>.</p>
</section>
<section id="assumption-2-the-shape-itself" class="slide level2">
<h2>Assumption 2 · The Shape Itself</h2>

<img data-src="week-06-hypothesis-testing_files/figure-revealjs/sketch-dist-null-1.png" width="960" class="r-stretch"><p>The p-value came from <em>this specific curve</em> — which assumes large-enough samples, independent observations, and a model that fits the data.</p>
</section>
<section id="and-many-shapes-fit-the-same-data" class="slide level2">
<h2>…And Many Shapes Fit the Same Data</h2>

<img data-src="week-06-hypothesis-testing_files/figure-revealjs/sketch-dist-many-1.png" width="960" class="r-stretch"><p>How often do researchers <em>test</em> those assumptions before trusting the p-value? Less often than you’d hope.</p>
</section></section>
<section>
<section id="act-ii-bayes-recapped" class="title-slide slide level1 center" data-background-color="#73000A">
<h1>Act II · Bayes, Recapped</h1>

</section>
<section id="bayes-theorem-recap-from-session-3" class="slide level2">
<h2>Bayes’ Theorem — Recap from Session 3</h2>
<p><span class="math display">\[
P(H \mid \text{data}) = P(\text{data} \mid H) \times P(H) \,/\, P(\text{data})
\qquad \small{\text{posterior} = \text{likelihood} \times \text{prior} / \text{evidence}}
\]</span></p>
<ul>
<li class="fragment">Session 3’s move: conditioning is <em>shrink the world, re-proportion</em> — Bayes’ theorem reverses the direction. Ianfluenza: prior 1% + “90% accurate” → posterior ≈ <strong>15%</strong></li>
<li class="fragment"><strong>New today:</strong> look where the p-value lives — entirely in the <strong>likelihood</strong>, <span class="math inline">\(P(\text{data} \mid H_0)\)</span>. It never becomes <span class="math inline">\(P(H_0 \mid \text{data})\)</span></li>
<li class="fragment">Bayesian testing finishes the flip — <span class="math inline">\(P(H \mid \text{data})\)</span>, the question your chief, judge, or city council actually asked — at the price of a stated prior</li>
</ul>
</section>
<section id="the-two-traditions-side-by-side" class="slide level2 smaller">
<h2>The Two Traditions, Side by Side</h2>
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 50%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Frequentist</th>
<th>Bayesian</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Asks</strong></td>
<td>How surprising are these data if <span class="math inline">\(H_0\)</span> is true?</td>
<td>How probable is each hypothesis, given the data?</td>
</tr>
<tr class="even">
<td><strong>Probability attaches to</strong></td>
<td>Data, over imagined repeated samples</td>
<td>Hypotheses and parameters directly</td>
</tr>
<tr class="odd">
<td><strong>Prior knowledge</strong></td>
<td>None used</td>
<td>Explicit, stated up front</td>
</tr>
<tr class="even">
<td><strong>Output</strong></td>
<td>p-value, confidence interval</td>
<td>Posterior distribution, credible interval</td>
</tr>
<tr class="odd">
<td><strong>“95%” means</strong></td>
<td>The <em>procedure</em> captures the truth in 95% of replications</td>
<td>95% probability the parameter lies in <em>this</em> interval</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="act-iii-the-recidivism-trial-both-ways" class="title-slide slide level1 center" data-background-color="#1B2A4A">
<h1>Act III · The Recidivism Trial, Both Ways</h1>

</section>
<section id="the-setup" class="slide level2">
<h2>The Setup</h2>
<ul>
<li><strong>Context:</strong> typical recidivism runs about <strong>60%</strong> — that’s what we believed going in</li>
<li><strong>Design:</strong> randomized trial of a reentry program — <strong>100 treated, 100 control</strong></li>
<li><strong>Outcomes:</strong> treatment <strong>40/100</strong> reoffend · control <strong>50/100</strong> reoffend</li>
<li><strong>Question:</strong> did the program reduce recidivism?</li>
</ul>
<div class="fragment">
<p>Ten percentage points, exactly the kind of effect a city would fund. Both traditions, go.</p>
</div>
</section>
<section id="the-frequentist-answer" class="slide level2">
<h2>The Frequentist Answer</h2>
<p>Treatment first, so the difference reads <strong>Treatment minus Control</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">50</span>), <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(40, 50) out of c(100, 100)
X-squared = 1.6364, df = 1, p-value = 0.2008
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.24719748  0.04719748
sample estimates:
prop 1 prop 2 
   0.4    0.5 </code></pre>
</div>
</div>
</section>
<section id="the-frequentist-answer-read-aloud" class="slide level2">
<h2>The Frequentist Answer, Read Aloud</h2>
<ul>
<li class="fragment"><span class="math inline">\(p = 0.20\)</span> — <strong>not statistically significant</strong></li>
<li class="fragment">The interval, about -25 to +5 points, has zero inside it</li>
<li class="fragment">Honest reading: <em>a 10-point gap like this could plausibly occur even if the program did nothing</em></li>
<li class="fragment">The grant report writes itself — “no significant effect” — and the program probably dies there</li>
</ul>
</section>
<section id="what-we-knew-before-the-trial" class="slide level2">
<h2>What We Knew Before the Trial</h2>
<p>A Bayesian has to say, out loud, what they believed <strong>before</strong> seeing the data. That is the <strong>prior</strong>.</p>
<ul>
<li class="fragment">We said it already: recidivism typically runs about <strong>60%</strong></li>
<li class="fragment">How firmly do we believe that? Let’s say: about as firmly as if we had already watched <strong>10 people</strong> — <strong>6 reoffended, 4 did not</strong></li>
<li class="fragment">In R, that whole belief is two numbers: <code>prior = c(6, 4)</code></li>
<li class="fragment">Then the trial’s 200 real people get added to our 10 imaginary ones. That adding-up is the <strong>posterior</strong>: what we believe <em>after</em> the data</li>
</ul>
</section>
<section id="the-bayesian-answer" class="slide level2">
<h2>The Bayesian Answer</h2>
<p>Same two numbers per group as <code>prop.test()</code>, plus the prior:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">bayes_prop_test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">50</span>), <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>), <span class="at">prior =</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bayesian test of two proportions 

data, group 1:  40 of 100 (40.0%)
data, group 2:  50 of 100 (50.0%)
prior:          6 yes, 4 no (about 60%, worth 10 cases), same for both groups

                         estimate      95% credible interval
group 1                  41.8%         32.8% to 51.1%
group 2                  50.9%         41.6% to 60.2%
difference (1 minus 2)   -9.1 points   -22.0 to 4.0 points

Probability group 1 is higher than group 2: 0.09 
Probability group 1 is lower than group 2:  0.91 </code></pre>
</div>
</div>
</section>
<section id="reading-it" class="slide level2">
<h2>Reading It</h2>
<ul>
<li class="fragment"><strong><code>estimate</code></strong>: our best single guess for each group’s true rate, after the data</li>
<li class="fragment"><strong><code>95% credible interval</code></strong> for the difference: about -22 to +4 points, Treatment minus Control</li>
<li class="fragment"><strong><code>Probability group 1 is lower than group 2</code>: 0.91</strong> — given the prior and the data, about a <strong>91% probability the program reduces recidivism</strong></li>
</ul>
<div class="fragment">
<p>And the sentence Session 5 forbade is now <strong>legal</strong>: <em>“There is a 95% probability the true difference lies between -22 and +4 points.”</em> That is exactly what a <strong>credible interval</strong> means.</p>
</div>
</section>
<section id="the-posteriors-seen" class="slide level2">
<h2>The Posteriors, Seen</h2>

<img data-src="week-06-hypothesis-testing_files/figure-revealjs/recid-plot-1.png" width="960" class="r-stretch"></section>
<section id="same-data-different-questions" class="slide level2">
<h2>Same Data, Different Questions</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Frequentist</th>
<th>Bayesian</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Verdict</td>
<td><span class="math inline">\(p = 0.20\)</span>: cannot reject “no effect”</td>
<td>Probability the program works ≈ 0.91</td>
</tr>
<tr class="even">
<td>Plain English</td>
<td>“This gap could plausibly be luck”</td>
<td>“About 9-to-1 odds the program works”</td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment">Both statements are <strong>true of the same data</strong>. Neither is a trick</li>
<li class="fragment">A policymaker deciding whether to fund the program next year: which sentence actually helps?</li>
<li class="fragment">Your homework asks you to sit with exactly this discomfort</li>
</ul>
</section>
<section id="does-the-prior-matter-here" class="slide level2">
<h2>Does the Prior Matter Here?</h2>
<p>Leave <code>prior =</code> out and the function starts from “I know nothing”:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">bayes_prop_test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">50</span>), <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li class="fragment">Probability the program works: <strong>0.92</strong> instead of 0.91. It barely moved</li>
<li class="fragment">Why? 200 real people outweigh 10 imaginary ones. <strong>Data overwhelm a modest prior</strong></li>
<li class="fragment">A prior matters most when data are scarce — which is exactly when you most need to say it out loud</li>
</ul>
</section></section>
<section>
<section id="act-iv-back-to-chicago-both-ways" class="title-slide slide level1 center" data-background-color="#73000A">
<h1>Act IV · Back to Chicago, Both Ways</h1>

</section>
<section id="the-bayesian-answer-to-tonights-question" class="slide level2 smaller">
<h2>The Bayesian Answer to Tonight’s Question</h2>
<p>We have no strong belief going in, so no <code>prior =</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">bayes_prop_test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">740</span>, <span class="dv">714</span>), <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">3749</span>, <span class="dv">5399</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bayesian test of two proportions 

data, group 1:  740 of 3,749 (19.7%)
data, group 2:  714 of 5,399 (13.2%)
prior:          know-nothing (1 yes, 1 no), same for both groups

                         estimate      95% credible interval
group 1                  19.8%         18.5% to 21.0%
group 2                  13.2%         12.3% to 14.2%
difference (1 minus 2)   6.5 points    5.0 to 8.1 points

Probability group 1 is higher than group 2: more than 0.99 
Probability group 1 is lower than group 2:  less than 0.01 </code></pre>
</div>
</div>
</section>
<section id="big-sample-small-sample" class="slide level2 smaller">
<h2>Big Sample, Small Sample</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Chicago arrests (9,148 cases)</th>
<th>Reentry trial (200 people)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>prop.test()</code></td>
<td>95% CI: 4.9 to 8.1 points · <span class="math inline">\(p &lt; .001\)</span></td>
<td>95% CI: -25 to +5 points · <span class="math inline">\(p = 0.20\)</span></td>
</tr>
<tr class="even">
<td><code>bayes_prop_test()</code></td>
<td>95% credible: 5 to 8.1 points</td>
<td>95% credible: -22 to +4 points · P(works) ≈ 0.91</td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment">With thousands of cases the two traditions hand you <strong>nearly the same range</strong>. The data drown out everything else</li>
<li class="fragment">With 100 per group, both ranges still include zero — but one tradition stops at “not significant,” and the other tells you <em>how probable</em> the effect is</li>
<li class="fragment">Neither is wrong. They answer <strong>different questions</strong></li>
</ul>
</section></section>
<section>
<section id="act-v-sample-size-changes-everything" class="title-slide slide level1 center" data-background-color="#73000A">
<h1>Act V · Sample Size Changes Everything</h1>

</section>
<section id="the-p-value-and-sample-size" class="slide level2">
<h2>The p-Value and Sample Size</h2>
<p>Fix a <em>trivial</em> true effect (Δ = 0.1) and just keep collecting data:</p>

<img data-src="../media/week-06/p_samplesize.gif" class="r-stretch"><p>The effect never grows — only <em>n</em> does — and <em>p</em> still dives below .05. <strong>Given enough data, everything is “significant.”</strong></p>
</section>
<section id="bayes-and-sample-size" class="slide level2">
<h2>Bayes and Sample Size</h2>
<p>Same trivial effect, Bayesian glasses — watch the posterior for the difference as <em>n</em> grows:</p>

<img data-src="../media/week-06/bayes_samplesize.gif" class="r-stretch"><p>More data doesn’t flip a verdict — it <strong>sharpens the estimate</strong>, which visibly converges on “about 0.1, i.e., almost nothing.” The tininess stays in view.</p>
</section>
<section id="so-always-ask-how-big" class="slide level2">
<h2>So Always Ask: How Big?</h2>
<ul>
<li class="fragment">“Significant” only means <em>detectable</em>. With enough cases, a gap of a single percentage point would earn a tiny p-value too</li>
<li class="fragment">So after either test, say the size <strong>in real units</strong>: arrest rates about <strong>6.5 points</strong> apart (19.7% vs 13.2%)</li>
<li class="fragment">Then ask the question no test can answer for you: is a gap that size big enough to <em>matter</em>?</li>
</ul>
</section>
<section id="what-we-learned-today" class="slide level2">
<h2>What We Learned Today</h2>
<ul>
<li class="fragment"><strong>NHST</strong>: standardized and everywhere — but it only asks <em>how surprising are the data under the null?</em>, never scores the alternative, and rewards sheer n</li>
<li class="fragment"><strong>p-values</strong> are not the probability any hypothesis is true, and are silent about <em>size</em></li>
<li class="fragment"><strong>Bayes</strong> answers <span class="math inline">\(P(H \mid \text{data})\)</span> at the price of a stated prior — tonight, in one line of R</li>
<li class="fragment">The same trial gave <span class="math inline">\(p = 0.20\)</span> <em>and</em> a 91% probability the program works. Both true; different questions</li>
<li class="fragment">Whatever tradition you use: <strong>say how big the difference is, in units a human cares about</strong></li>
</ul>
</section>
<section id="todays-lab-homework" class="slide level2">
<h2>Today’s Lab &amp; Homework</h2>
<ul>
<li><strong>Lab 6:</strong> one question about the correctional officers, answered twice. You run both tests, step by step, and submit your script (<a href="../labs/lab-06-testing.html">lab page</a>)</li>
<li><strong>Homework 6:</strong> Bayesian vs.&nbsp;frequentist reasoning, plus both tests on the Alaska crash data, and four R4DS exercises from <strong>Ch. 17, Dates and times</strong> (posted on the <a href="../weeks/week-06.html">Session 6 page</a>)</li>
<li><strong>Next session — the applied data workshop:</strong> the full messy-data pipeline, start to finish. <strong>Your final-project dataset selection is due at Session 7</strong> — come with a candidate dataset and be ready to defend it</li>
</ul>
</section></section>
<section>
<section id="appendix-how-bayes-became-computable-optional" class="title-slide slide level1 center" data-background-color="#1B2A4A">
<h1>Appendix · How Bayes Became Computable (optional)</h1>

</section>
<section id="the-ugly-denominator" class="slide level2">
<h2>The Ugly Denominator</h2>
<p><em>Not on any exam — this is the machinery behind the Bayesian models we start fitting in Session 8, for the curious.</em></p>
<p><span class="math display">\[
P(H \mid \text{data}) = \frac{P(\text{data} \mid H)\,P(H)}{\color{#73000A}{P(\text{data})}}
\]</span></p>
<p>That innocent-looking denominator is the probability of the data under <em>every possible hypothesis, weighted by its prior</em>:</p>
<p><span class="math display">\[
\color{#73000A}{P(\text{data}) = \int P(\text{data} \mid \theta)\, P(\theta)\, d\theta}
\]</span></p>
<div class="fragment">
<p>For realistic models this integral is <strong>intractable</strong> — for most of the 20th century, Bayes was philosophically beautiful and practically unusable.</p>
</div>
</section>
<section id="enter-mcmc" class="slide level2">
<h2>Enter MCMC</h2>
<p>How Markov chain Monte Carlo “measures the curve” without solving the integral:</p>
<ul>
<li class="fragment">We don’t know the whole posterior curve — but we <em>do</em> know its <strong>formula up to a constant</strong> (likelihood × prior)</li>
<li class="fragment">A sampler evaluates that formula at its <strong>current spot</strong> and at a <strong>proposed spot</strong></li>
<li class="fragment">Compare the two values: if the new spot is higher → <strong>accept</strong>; if lower → accept <em>with that probability</em></li>
<li class="fragment">The impossible constant appears in both numerator and denominator — it <strong>cancels in the ratio</strong>. We never need to know it</li>
</ul>
</section>
<section id="mcmc-watched-live" class="slide level2">
<h2>MCMC, Watched Live</h2>
<p>A Metropolis sampler exploring a distribution (left) while its samples pile up into that very shape (right):</p>

<img data-src="../media/week-06/mcmc_faceted.gif" class="r-stretch"></section>
<section id="we-end-up-with-the-probability-distribution" class="slide level2">
<h2>We End Up With the Probability Distribution</h2>
<ul>
<li class="fragment">The pile of accepted samples <strong>is</strong> the posterior — to any precision you like, just run longer</li>
<li class="fragment">Think back to Session 4: we approximated <em>sampling</em> distributions by drawing samples and stacking them. MCMC plays exactly the same trick on the <em>posterior</em></li>
<li class="fragment">This is why modern Bayes is possible at all — and it is what <code>brms</code> will do for us starting in Session 8. (Tonight’s <code>bayes_prop_test()</code> did not need it: for a simple proportion, the posterior has an exact formula.)</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>CRJU 705 · Session 6</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>