{
  "hash": "7bbe48b2ead0d84adae658ac61cd191e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Logic of Inference: Confidence Intervals\"\nsubtitle: \"CRJU 705 · Session 5 · Fall 2026\"\nauthor: \"Scott M. Mourtgos\"\nformat:\n  revealjs:\n    slide-number: true\n    preview-links: auto\n    chalkboard: true\n    footer: \"CRJU 705 · Session 5\"\n    theme: [default, custom-slides.scss]\n    fig-align: center\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n## This Week\n\n**Topic:** The logic of inference, using confidence intervals\n\n- What statistical *inference* actually is (and isn't)\n- Point estimates and why they're not enough\n- Confidence intervals: building them, reading them, and — hardest of all — *saying what they mean out loud without lying*\n\n**Learning goals:** explain in your own words what a 95% confidence interval does and does **not** mean; compute CIs for a proportion and a difference in means from real data.\n\n**R4DS thread:** you read Ch. 7 (Data import) & Ch. 8 (Getting help) — today's lab puts both to work.\n\n## Where We've Been\n\n::: incremental\n- **Session 3:** probability — the rules randomness follows\n- **Session 4:** sampling distributions — take many samples, and the sample statistics themselves form a distribution with predictable behavior\n- **Today:** we cash that in. If we know how sample statistics *behave*, we can attach an honest statement of **uncertainty** to a single sample's estimate.\n:::\n\n# The Logic of Inference {background-color=\"#73000A\"}\n\n## What Does \"Inference\" Mean?\n\n**Inference:** a reasoning process that begins with some information and leads to some conclusion.\n\n**Inductive inference:** reasons from *specific cases* to the *more general* — a cat jumps from a tree and lands on its feet; you infer something about cats generally.\n\n**Statistical inference:** dealing systematically with situations where we have *uncertain or incomplete* information. Conclusions drawn inductively from samples are **never fixed or firm**.\n\n. . .\n\n::: {.callout-important appearance=\"simple\"}\nYou **cannot PROVE** anything from samples or by using statistical inference.\n:::\n\n## If We Can't Prove Anything, What Are We Doing?\n\nWe collect data and analyze it with inferential statistics **to build up a weight of evidence that influences our certainty about one conclusion or another**.\n\n. . .\n\n**Let's look at the classic example:**\n\n- 1854 — cholera breaks out in Soho, London\n- The debate: bad air (\"miasma\") or contaminated water?\n- John Snow couldn't test *every household in London* — that's the whole population\n- So he mapped the **sample of evidence** he could get: deaths, and where people got their water\n\n## Sampled Evidence: Deaths and Pumps\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code  code-line-numbers=\"1-2|4-8|10-16\"}\ndeaths <- as_tibble(Snow.deaths) |> mutate(did = row_number())\npumps  <- as_tibble(Snow.pumps)  |> mutate(pid = row_number())\n\n# Every death-pump distance, then each death's NEAREST pump\npairs <- crossing(did = deaths$did, pid = pumps$pid) |>\n  left_join(deaths |> select(did, dx = x, dy = y), by = \"did\") |>\n  left_join(pumps  |> select(pid, px = x, py = y), by = \"pid\") |>\n  mutate(dist = sqrt((dx - px)^2 + (dy - py)^2))\n\nnearest <- pairs |>\n  slice_min(dist, n = 1, by = did)\n\nby_pump <- nearest |>\n  count(pid, name = \"deaths_nearest\") |>\n  arrange(desc(deaths_nearest))\nby_pump\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n     pid deaths_nearest\n   <int>          <int>\n 1     7            359\n 2    10             64\n 3     6             61\n 4     9             27\n 5     4             24\n 6     8             16\n 7     3             12\n 8     5              6\n 9    13              4\n10    11              2\n11    12              2\n12     2              1\n```\n\n\n:::\n:::\n\n\n## Sampled Evidence: The Map\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05-confidence-intervals_files/figure-revealjs/snow-map-1.png){width=960}\n:::\n:::\n\n\n## Sampled Evidence: Broad Street Accumulates Deaths Fastest\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05-confidence-intervals_files/figure-revealjs/snow-cumulative-1.png){width=960}\n:::\n:::\n\n\n## Why This Is Statistical Inference\n\n- Why wasn't Snow just *describing* the map?\n- What **bigger claim** was he making about the whole city — and about *cholera itself*?\n\n**That jump — from the data you have to the world you don't — is what we mean by inference.**\n\n. . .\n\n**Review from previous weeks — why do we sample?**\n\nWe almost never have access to the totality of the population data. At its *best*, a sample is **representative** of a population.\n\n# Point Estimates and Their Discontents {background-color=\"#1B2A4A\"}\n\n## A Rare Luxury: We Know the Truth\n\nOur Chicago file holds ~30,000 incidents from 2025. Today, *pretend the file is the whole population* — then we can check our inferences against the truth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrimes |> summarize(pop_arrest_rate = mean(arrest), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  pop_arrest_rate     n\n            <dbl> <int>\n1           0.161 30000\n```\n\n\n:::\n:::\n\n\nThe \"true\" citywide arrest proportion is **16.1%**. Lock that in — in real research you never get to see this number.\n\n## Now Act Like a Researcher: Draw One Sample\n\nA researcher can rarely afford all 30,000 case files. Suppose we pull a random sample of **250** incidents:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_250 <- crimes |> slice_sample(n = 250)\n\nsample_250 |> summarize(sample_arrest_rate = mean(arrest))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  sample_arrest_rate\n               <dbl>\n1              0.148\n```\n\n\n:::\n:::\n\n\n. . .\n\nThis is a **point estimate** — the sample's best single guess at the population value.\n\n**14.8% vs the true 16.1%.** Close-ish. But how good is this estimate? How *certain* are we?\n\n## Caution! Samples Fluctuate\n\nDraw a fresh sample of 250 and the estimate moves. Do it 1,000 times:\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nmany_estimates <- map_dbl(1:1000, \\(i) {\n  crimes |> slice_sample(n = 250) |> summarize(p = mean(arrest)) |> pull(p)\n})\n\nggplot(tibble(p = many_estimates), aes(p)) +\n  geom_histogram(bins = 30, fill = crju_colors[\"blue\"], color = \"white\") +\n  geom_vline(xintercept = mean(crimes$arrest),\n             color = crju_colors[\"garnet\"], linewidth = 1.2) +\n  labs(title = \"1,000 sample estimates of the arrest rate (n = 250 each)\",\n       subtitle = \"Garnet line = the true population value\",\n       x = \"Sample arrest proportion\", y = \"Number of samples\")\n```\n\n::: {.cell-output-display}\n![](week-05-confidence-intervals_files/figure-revealjs/many-samples-1.png){width=960}\n:::\n:::\n\n\n## What the Fluctuation Tells Us\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(many_estimates, c(0.025, 0.975))   # what is this telling us?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% \n0.120 0.208 \n```\n\n\n:::\n:::\n\n\n::: incremental\n- 95% of sample estimates landed between about **12% and 21%** — that's the *sampling distribution* from Session 4, live\n- Any *single* sample's estimate could easily be a couple points off the truth\n- So reporting \"14.8%\" alone is **overconfident** — we owe our reader a range that reflects the fluctuation\n- Problem: this required 1,000 samples and a known population. A real researcher has **one sample**. Now what?\n:::\n\n# The Confidence Interval {background-color=\"#73000A\"}\n\n## Our First Inferential Tool\n\nThe **confidence interval** turns *one* sample into an honest range, using what Session 4 taught us about how sample statistics behave:\n\n$$\\text{estimate} \\; \\pm \\; \\underbrace{1.96 \\times SE}_{\\text{margin of error}}$$\n\n- **SE** (standard error) = the standard deviation of the sampling distribution, *estimated from the one sample you have*\n- **1.96** comes from the normal distribution: ±1.96 SDs covers the middle 95%\n\nBigger samples → smaller SE → narrower interval.\n\n## R Does This For Us: `prop.test()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(sum(sample_250$arrest), n = 250)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  sum(sample_250$arrest) out of 250, null probability 0.5\nX-squared = 122.5, df = 1, p-value < 0.00000000000000022\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.1075899 0.1995409\nsample estimates:\n    p \n0.148 \n```\n\n\n:::\n:::\n\n\n. . .\n\nOur one sample of 250 says: point estimate **14.8%**, 95% CI **10.8% to 20.0%**. The true value (16.1%) is inside — this time. But *\"95% confident\"* of what, exactly?\n\n## The Classic Picture: 100 Samples, 100 Intervals\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code  code-line-numbers=\"1-7|9-10|12-18\"}\nci_100 <- map(1:100, \\(i) {\n  s  <- crimes |> slice_sample(n = 250)\n  ci <- prop.test(sum(s$arrest), n = 250)$conf.int\n  tibble(sample = i, estimate = mean(s$arrest), lo = ci[1], hi = ci[2])\n}) |>\n  list_rbind() |>\n  mutate(captured = lo <= mean(crimes$arrest) & mean(crimes$arrest) <= hi)\n\nsum(ci_100$captured)   # how many of the 100 intervals caught the truth?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97\n```\n\n\n:::\n\n```{.r .cell-code  code-line-numbers=\"1-7|9-10|12-18\"}\nggplot(ci_100, aes(sample, estimate, color = captured)) +\n  geom_hline(yintercept = mean(crimes$arrest), color = \"grey30\", linewidth = 1) +\n  geom_pointrange(aes(ymin = lo, ymax = hi), linewidth = 0.7, size = 0.25) +\n  scale_color_manual(values = c(\"TRUE\" = \"grey65\", \"FALSE\" = \"#73000A\")) +\n  labs(title = paste0(\"100 samples, 100 confidence intervals — \",\n                      sum(ci_100$captured), \" capture the truth\"),\n       subtitle = \"Horizontal line = true population arrest rate; garnet = intervals that missed\",\n       x = \"Sample number\", y = \"Arrest proportion\", color = \"Captured?\")\n```\n\n::: {.cell-output-display}\n![](week-05-confidence-intervals_files/figure-revealjs/ci-sim-1.png){width=960}\n:::\n:::\n\n\n## What Just Happened\n\n::: incremental\n- Each of the 100 samples produced a *different* interval — the interval is a **random quantity**, the population value is **fixed**\n- **97 of our 100** intervals captured the true arrest rate; 3 missed (the garnet ones)\n- In the long run, the 95% procedure captures the truth in **~95% of replications** — that long-run capture rate is *the entire meaning* of \"95% confident\"\n- The researchers who drew the garnet samples did nothing wrong — and their data give **no warning** that theirs are the unlucky intervals\n:::\n\n## In Practice\n\nIf we reran our whole study many times — drawing a new sample each time and constructing a new confidence interval each time — **in 95% of those replications the interval would contain the true population value.**\n\n::: {.callout-important appearance=\"simple\"}\n**IMPORTANT:**\n\n1. Our 95% CI does **not** necessarily contain the true population value\n2. Our 95% CI is **not** a statement about the probability that *this particular* interval is correct\n3. It is a **long-run prediction** based on numerous replications\n:::\n\n. . .\n\n**WTF?!?** — yes, everyone reacts this way. Point at the 100-intervals plot until it clicks.\n\n## Saying It Out Loud\n\n✅ **Defensible:**\n\n> \"We estimate the citywide arrest rate at 14.8% (95% CI: 10.8% to 20.0%). Values in this range are consistent with our data.\"\n\n> \"The method we used captures the true value 95% of the time.\"\n\n❌ **Not defensible:**\n\n> \"There is a 95% probability the true arrest rate is between 10.8% and 20.0%.\" *(The truth is fixed — it's either in there or it isn't.)*\n\n> \"95% of arrest rates fall in this interval.\" *(The CI is about the population parameter, not individual observations.)*\n\n## Sample Size Buys Precision\n\nSame procedure, three sample sizes, one draw each:\n\n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\nmap(c(100, 250, 1000, 4000), \\(n) {\n  s  <- crimes |> slice_sample(n = n)\n  ci <- prop.test(sum(s$arrest), n = n)$conf.int\n  tibble(n = n, estimate = mean(s$arrest),\n         lo = ci[1], hi = ci[2], width = ci[2] - ci[1])\n}) |>\n  list_rbind()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n      n estimate    lo    hi  width\n  <dbl>    <dbl> <dbl> <dbl>  <dbl>\n1   100    0.22  0.146 0.316 0.170 \n2   250    0.192 0.146 0.247 0.101 \n3  1000    0.154 0.132 0.178 0.0457\n4  4000    0.163 0.152 0.175 0.0231\n```\n\n\n:::\n:::\n\n\n. . .\n\nQuadrupling *n* roughly **halves** the width — precision grows with $\\sqrt{n}$, so it gets expensive fast.\n\n# Comparing Two Groups {background-color=\"#1B2A4A\"}\n\n## A Real Question: Do Violent Crimes Happen Later in the Day?\n\nStreet lore says violence is a nighttime phenomenon. Property crime, the daytime hustle. Our data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvp <- crimes |> filter(crime_category %in% c(\"Violent\", \"Property\"))\n\nvp |> summarize(mean_hour = mean(hour), sd_hour = sd(hour),\n                n = n(), .by = crime_category)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  crime_category mean_hour sd_hour     n\n  <chr>              <dbl>   <dbl> <int>\n1 Violent             12.8    6.87  9148\n2 Property            12.5    6.63 10371\n```\n\n\n:::\n:::\n\n\n. . .\n\nTwo **point estimates**: violent crimes average hour 12.8, property 12.5. Is that ~15-minute gap real, or sample fluctuation?\n\n## Let's Look at It Visually\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vp, aes(crime_category, hour, fill = crime_category)) +\n  geom_boxplot(show.legend = FALSE) +\n  scale_fill_manual(values = unname(crju_colors[c(\"blue\", \"garnet\")])) +\n  labs(x = NULL, y = \"Hour of day (0–23)\")\n```\n\n::: {.cell-output-display}\n![](week-05-confidence-intervals_files/figure-revealjs/two-group-box-1.png){width=960}\n:::\n:::\n\n\nThe boxes nearly coincide — the eye can't settle this one. We need inference.\n\n## Resample the Difference\n\nSame trick as before — resample each group, compute the difference in means, repeat:\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nviolent_hours  <- vp$hour[vp$crime_category == \"Violent\"]\nproperty_hours <- vp$hour[vp$crime_category == \"Property\"]\n\nmean_diffs <- replicate(1000, {\n  mean(sample(violent_hours,  length(violent_hours),  replace = TRUE)) -\n  mean(sample(property_hours, length(property_hours), replace = TRUE))\n})\n\nquantile(mean_diffs, c(0.025, 0.975))   # what is this telling us?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      2.5%      97.5% \n0.05568685 0.43652029 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(tibble(mean_diffs), aes(mean_diffs)) +\n  geom_histogram(bins = 30, fill = crju_colors[\"navy\"], color = \"white\") +\n  geom_vline(xintercept = 0, color = crju_colors[\"garnet\"], linewidth = 1.2) +\n  labs(title = \"1,000 resampled differences in mean hour (Violent − Property)\",\n       x = \"Difference in mean hour\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](week-05-confidence-intervals_files/figure-revealjs/mean-diffs-1.png){width=960}\n:::\n:::\n\n\n## The Two-Sample t-Test Gives the CI Directly\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(hour ~ crime_category, data = vp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  hour by crime_category\nt = -2.6061, df = 19021, p-value = 0.009164\nalternative hypothesis: true difference in means between group Property and group Violent is not equal to 0\n95 percent confidence interval:\n -0.44272107 -0.06263688\nsample estimates:\nmean in group Property  mean in group Violent \n              12.54334               12.79602 \n```\n\n\n:::\n:::\n\n\nWatch the direction: R orders groups alphabetically, so this tests **Property − Violent** — the mirror image of our resampled Violent − Property differences. Same finding, flipped sign.\n\n## Reading That Output Honestly\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(hour ~ crime_category, data = vp)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.44272107 -0.06263688\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n::: incremental\n- The 95% CI for the difference (Property − Violent) runs from **−0.44 to −0.06 hours** — it excludes zero, so the data are consistent with violent crimes genuinely averaging later\n- But look at the *magnitude*: the difference is somewhere between about **4 and 27 minutes**. Detectable ≠ dramatic.\n- With ~19,500 incidents, we can detect tiny differences. The CI hands you both facts at once: *direction* (probably real) and *size* (small). **Never report the first without the second.**\n- This is your vaccination against next week's topic — a \"significant\" result can be substantively trivial\n:::\n\n## Your Turn (5 minutes, with a neighbor)\n\nUsing `crimes`, compute a 95% CI for the proportion of incidents flagged as **domestic**:\n\n```r\ncrimes |> summarize(mean(domestic))          # point estimate\nprop.test(sum(crimes$domestic), nrow(crimes))\n```\n\n1. Write one **defensible** sentence reporting your interval.\n2. Trade sentences with your neighbor and audit each other: does the sentence claim a probability about *this* interval? If so, fix it.\n\n## Today's Lab & Homework\n\n- **Lab 5:** importing real data — `read_csv()`, `read_excel()`, parsing dates, and what to do when R yells at you ([lab page](../labs/lab-05-import.qmd))\n- **Homework 5:** confidence intervals on Alaska crash data (posted on the [Session 5 page](../weeks/week-05.qmd))\n- **Read before Session 6:** Stanton Ch. 5 · R4DS Ch. 19 (Joins) & skim Ch. 18 (Missing values)\n",
    "supporting": [
      "week-05-confidence-intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}