{
  "hash": "fefa44589e0c0b9f38559d1fbaefb95d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo Walkthrough · Session 7\"\nsubtitle: \"Four real criminal justice questions, one recipe: count, test, say it\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this page is.** The Session 7 lecture, written down step by step. Every chunk below is self-contained: copy any of them into your own R session and it runs as-is. Use this page to catch up after a missed class, or to re-run the examples at your own pace.\n:::\n\n## What you'll build\n\nFour answers to four real questions, each with the same recipe:\n\n1. **Question.** Name the two groups and the outcome. A yes/no outcome means `prop.test()` and `bayes_prop_test()`; a number means `t.test()`.\n2. **Count or describe.**\n3. **Test.**\n4. **Say it.** The honest sentence, how big in real units, and one thing the test cannot tell you.\n\nThe questions: did financial aid at release lower re-arrest? Were employed arrestees released more often? How much lower is income in Chicago's high-violence areas? Was body camera footage reported more often in fatal police shootings after 2020?\n\n## Setup\n\nThe tidyverse, the course's Bayesian function, and four datasets. Two of them are new to you and live on the course site; one is our Chicago anchor data; one comes straight from the *Washington Post*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nsource(\"https://smourtgos.github.io/crju705/R/bayes.R\")   # gives you bayes_prop_test()\nset.seed(705)\n\nrossi   <- read_csv(\"https://smourtgos.github.io/crju705/data/rossi.csv\",\n                    show_col_types = FALSE)\narrests <- read_csv(\"https://smourtgos.github.io/crju705/data/toronto-arrests.csv\",\n                    show_col_types = FALSE)\nareas   <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-areas.csv\",\n                    show_col_types = FALSE)\nshootings <- read_csv(\"https://raw.githubusercontent.com/washingtonpost/data-police-shootings/master/v2/fatal-police-shootings-data.csv\",\n                      show_col_types = FALSE)\n```\n:::\n\n\nMore about each dataset, and four more like them, is on the [Final-Project Data Options](../project-data.qmd) page.\n\n## 1 · Reentry: does money at release keep people out of jail?\n\n432 men released from Maryland state prisons in the 1970s were followed for one year. Half were **randomly assigned** to receive financial aid (`fin`). The outcome is `arrest`: 1 if arrested again within the year. One row is one man.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrossi |> count(fin, arrest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  fin   arrest     n\n  <chr>  <dbl> <int>\n1 no         0   150\n2 no         1    66\n3 yes        0   168\n4 yes        1    48\n```\n\n\n:::\n:::\n\n\nAid: 48 re-arrested out of 48 + 168 = **216** (22.2%). No aid: 66 out of 66 + 150 = **216** (30.6%). Aid goes first, so every difference reads **Aid minus No aid**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(48, 66), n = c(216, 216))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(48, 66) out of c(216, 216)\nX-squared = 3.4439, df = 1, p-value = 0.06349\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.170713151  0.004046484\nsample estimates:\n   prop 1    prop 2 \n0.2222222 0.3055556 \n```\n\n\n:::\n:::\n\n\nThe interval runs from about 17 points lower to 0.4 points higher, and **p = 0.063**. Zero is just inside, so: fail to reject the null. A funder who reads only that line cuts the program.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(48, 66), n = c(216, 216))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  48 of 216 (22.2%)\ndata, group 2:  66 of 216 (30.6%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  22.5%         17.2% to 28.2%\ngroup 2                  30.7%         24.8% to 37.0%\ndifference (1 minus 2)   -8.2 points   -16.5 to 0.0 points\n\nProbability group 1 is higher than group 2: 0.03 \nProbability group 1 is lower than group 2:  0.97 \n```\n\n\n:::\n:::\n\n\n**Say it.** Given these data, there is about a **97% probability** that men who got aid were re-arrested at a lower rate. About 22 of every 100 men with aid were re-arrested, against about 31 of every 100 without: roughly 8 fewer re-arrests per 100 people released. What this cannot tell you: whether the effect lasts past a year, or would hold today. \"Not significant\" is not \"no effect.\"\n\n**Why we can say \"caused.\"** The aid was assigned at random, so the groups should look alike before release. Check with a number, prior convictions, putting aid first with `factor()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrossi <- rossi |> mutate(fin = factor(fin, levels = c(\"yes\", \"no\")))\nt.test(prio ~ fin, data = rossi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  prio by fin\nt = -0.016594, df = 429.91, p-value = 0.9868\nalternative hypothesis: true difference in means between group yes and group no is not equal to 0\n95 percent confidence interval:\n -0.5529994  0.5437402\nsample estimates:\nmean in group yes  mean in group no \n         2.981481          2.986111 \n```\n\n\n:::\n:::\n\n\n2.98 prior convictions vs 2.99, p = 0.99. The groups started out the same, so the gap afterward is about the aid. This is the rare test where you *hope* for a big p-value.\n\n## 2 · Pretrial release: does a job get you released?\n\n5,226 Toronto arrests for possessing small amounts of marijuana, 1997 to 2002. `released` is whether the person was released with a summons instead of held for a bail hearing. The group is `employed`. One row is one arrest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrests |> count(employed, released)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  employed released     n\n  <chr>    <chr>    <int>\n1 No       No         349\n2 No       Yes        766\n3 Yes      No         543\n4 Yes      Yes       3568\n```\n\n\n:::\n:::\n\n\nEmployed: 3,568 released out of 3,568 + 543 = **4,111** (86.8%). Not employed: 766 out of 766 + 349 = **1,115** (68.7%).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(3568, 766), n = c(4111, 1115))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(3568, 766) out of c(4111, 1115)\nX-squared = 201.54, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.1512300 0.2106097\nsample estimates:\n   prop 1    prop 2 \n0.8679153 0.6869955 \n```\n\n\n:::\n\n```{.r .cell-code}\nbayes_prop_test(x = c(3568, 766), n = c(4111, 1115))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  3,568 of 4,111 (86.8%)\ndata, group 2:  766 of 1,115 (68.7%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  86.8%         85.7% to 87.8%\ngroup 2                  68.7%         65.9% to 71.4%\ndifference (1 minus 2)   18.1 points   15.2 to 21.0 points\n\nProbability group 1 is higher than group 2: more than 0.99 \nProbability group 1 is lower than group 2:  less than 0.01 \n```\n\n\n:::\n:::\n\n\nAbout 15 to 21 points more often for the employed, by either test. But the two groups differ in other ways. `checks` counts how many of six police databases (prior arrests, convictions, parole, and so on) had the person's name:\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrests |> summarize(avg_checks = mean(checks), people = n(), .by = employed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  employed avg_checks people\n  <chr>         <dbl>  <int>\n1 Yes            1.44   4111\n2 No             2.35   1115\n```\n\n\n:::\n:::\n\n\nPeople without a job had more of a record, and a record is a reason to hold someone. So compare like with like: keep only people with **no record at all**, and ask again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrests |> filter(checks == 0) |> count(employed, released)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  employed released     n\n  <chr>    <chr>    <int>\n1 No       No          35\n2 No       Yes        166\n3 Yes      No         124\n4 Yes      Yes       1526\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(x = c(1526, 166), n = c(1650, 201))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(1526, 166) out of c(1650, 201)\nX-squared = 21.112, df = 1, p-value = 4.333e-06\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.04224058 0.15571509\nsample estimates:\n   prop 1    prop 2 \n0.9248485 0.8258706 \n```\n\n\n:::\n:::\n\n\n**Say it.** Among people with clean records, the employed were released about 10 points more often (92.5% vs 82.6%; interval about 4 to 16 points). The gap shrank from 18 points to 10 when we compared like with like, but it did not disappear. What this cannot tell you: whether some other difference (age, citizenship, where the arrest happened) explains the rest. Only random assignment rules everything out, and nobody randomizes jobs.\n\n## 3 · Neighborhoods: violence and income\n\nChicago's 77 community areas. `high_violence` marks the 38 areas with the highest violent-crime rates. The outcome is `median_income`, a number in dollars, so the test is `t.test()`. One row is one **area**, not one person. First, name the groups and put High violence first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas <- areas |>\n  mutate(violence = factor(if_else(high_violence, \"High violence\", \"Other areas\"),\n                           levels = c(\"High violence\", \"Other areas\")))\n\nareas |>\n  summarize(avg_income = mean(median_income), areas = n(), .by = violence) |>\n  arrange(violence)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  violence      avg_income areas\n  <fct>              <dbl> <int>\n1 High violence     54355.    38\n2 Other areas       90088.    39\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(areas, aes(x = violence, y = median_income)) +\n  geom_boxplot(fill = \"goldenrod\", width = 0.5) +\n  labs(x = NULL, y = \"Median household income (dollars)\",\n       title = \"Chicago community areas, 2025\")\n```\n\n::: {.cell-output-display}\n![](demo-07-workshop_files/figure-html/chi-plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(median_income ~ violence, data = areas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  median_income by violence\nt = -6.3561, df = 74.959, p-value = 1.458e-08\nalternative hypothesis: true difference in means between group High violence and group Other areas is not equal to 0\n95 percent confidence interval:\n -46932.44 -24533.58\nsample estimates:\nmean in group High violence   mean in group Other areas \n                   54354.63                    90087.64 \n```\n\n\n:::\n:::\n\n\n**Say it.** High-violence areas minus other areas: about **$25,000 to $47,000 lower** median household income ($54,355 vs $90,088 on average), p = 0.00000001. The unit is dollars because the column is dollars. What this cannot tell you: which way it runs (does poverty breed violence, or does violence drive income out?), and anything about individual people. Each row is an area.\n\n## 4 · Use of force: body cameras over time\n\nThe *Washington Post*'s database of every person shot and killed by on-duty police in the U.S., 2015 to 2024. `body_camera` is TRUE when news or police reports said a camera recorded the incident. One row is one person killed. Group: before and after 2020.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshootings <- shootings |>\n  mutate(period = if_else(year(date) >= 2020, \"2020 to 2024\", \"2015 to 2019\"))\n\nshootings |> count(period, body_camera)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  period       body_camera     n\n  <chr>        <lgl>       <int>\n1 2015 to 2019 FALSE        4329\n2 2015 to 2019 TRUE          594\n3 2020 to 2024 FALSE        4302\n4 2020 to 2024 TRUE         1205\n```\n\n\n:::\n:::\n\n\n2020 to 2024: 1,205 of 1,205 + 4,302 = **5,507** (21.9%). 2015 to 2019: 594 of 594 + 4,329 = **4,923** (12.1%).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(1205, 594), n = c(5507, 4923))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(1205, 594) out of c(5507, 4923)\nX-squared = 174.76, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.08374831 0.11256026\nsample estimates:\n   prop 1    prop 2 \n0.2188124 0.1206581 \n```\n\n\n:::\n\n```{.r .cell-code}\nbayes_prop_test(x = c(1205, 594), n = c(5507, 4923))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  1,205 of 5,507 (21.9%)\ndata, group 2:  594 of 4,923 (12.1%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  21.9%         20.8% to 23.0%\ngroup 2                  12.1%         11.2% to 13.0%\ndifference (1 minus 2)   9.8 points    8.4 to 11.2 points\n\nProbability group 1 is higher than group 2: more than 0.99 \nProbability group 1 is lower than group 2:  less than 0.01 \n```\n\n\n:::\n:::\n\n\n**Say it.** About 12 in 100 fatal shootings had known camera footage before 2020, and about 22 in 100 after (8 to 11 points higher, by either test). Close to doubling, and still fewer than 1 in 4. What this cannot tell you: whether cameras changed anything about the shootings, or how many cameras existed but went unreported. With 10,430 cases, the p-value was never in doubt. The size is the whole story.\n\n## Four questions, one recipe\n\n| | Test | Answer | The lesson |\n|---|---|---|---|\n| Reentry | `prop.test()` + Bayes | 22% vs 31%; p = 0.063; 97% probably lower | \"Not significant\" is not \"no effect.\" Randomization lets us say \"caused\" |\n| Pretrial | `prop.test()`, then again after `filter()` | 18 points; 10 among clean records | Groups differ in other ways. Compare like with like |\n| Neighborhoods | `t.test()` | $25k to $47k lower | Say the size in real units. Areas are not people |\n| Use of force | `prop.test()` + Bayes | 12% to 22% | With a huge n, the p-value adds nothing; the size is the story |\n\n## Try a variation\n\n1. **Rossi:** were men released on **parole** (`paro`) re-arrested less often? Count, then both tests. Is parole randomly assigned the way aid was? What does that change about the sentence you can write?\n2. **Toronto:** were **citizens** (`citizen`) released more often than non-citizens? Then ask again among people with `checks == 0`. Does the gap shrink the way the employment gap did?\n3. **Chicago areas:** run `t.test(pct_vacant ~ violence, data = areas)`. How much higher is the share of vacant housing in high-violence areas, in percentage points?\n4. **Shootings:** was a body camera reported more often when the person was in a mental health crisis (`was_mental_illness_related`)? Count, then both tests, and say the size in plain words.\n",
    "supporting": [
      "demo-07-workshop_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}