{
  "hash": "7ef6b7f190b050250b9c0f93afb31e28",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo Walkthrough · Session 5\"\nsubtitle: \"Confidence intervals — turning one sample into an honest range\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this page is.** The Session 5 lecture demos, written down step by step. Every chunk below is self-contained — copy any of them into your own R session and they run as-is. Use this page to catch up after a missed class, or to re-run what happened on screen at your own pace.\n:::\n\n## What you'll build\n\n1. John Snow's 1854 cholera inference, recomputed from his original data — the classic example of reasoning from a sample to the world\n2. A demonstration that point estimates fluctuate: 1,000 samples from a population whose truth we secretly know\n3. A 95% confidence interval from `prop.test()`, and **the 100-intervals plot** — the picture that shows what \"95% confident\" actually means\n4. Sentences you can and cannot say when reporting an interval\n5. How sample size buys precision, and a CI for a two-group difference with `t.test()` — including what it looks like when an interval does, and does not, cross zero\n\n## Setup\n\nThree packages today: the tidyverse; **HistData**, which ships John Snow's original cholera data (`Snow.deaths` and `Snow.pumps`); and **patchwork**, which puts two plots side by side:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(HistData)    # install.packages(\"HistData\")   — once, if you don't have it\nlibrary(patchwork)   # install.packages(\"patchwork\")  — once, if you don't have it\nset.seed(705)\n\ncrimes <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-crimes-2025.csv\",\n                   show_col_types = FALSE)\n```\n:::\n\n\n## 1 · Inference, in 1854\n\nCholera breaks out in Soho, London. The debate: bad air (\"miasma\") or contaminated water? John Snow couldn't test every household in London — that's the whole population. So he mapped the **sample of evidence** he could get: deaths, and where people drew their water.\n\nWe can rerun his reasoning. For each of the 578 recorded deaths, find the *nearest* pump. Two verbs arrive ahead of schedule here — `crossing()` builds every death–pump pair, and `left_join()` looks up each point's coordinates. Joins get their full treatment in next week's lab; today, read them as \"pair up, then look up\" and focus on the logic:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths <- as_tibble(Snow.deaths)\npumps  <- as_tibble(Snow.pumps)\n\npairs <- crossing(case = deaths$case, pump = pumps$pump) |>\n  left_join(deaths |> select(case, dx = x, dy = y), by = \"case\") |>\n  left_join(pumps  |> select(pump, label, px = x, py = y), by = \"pump\") |>\n  mutate(dist = sqrt((dx - px)^2 + (dy - py)^2))\n\nnearest <- pairs |>\n  slice_min(dist, n = 1, by = case)\n\nnearest |>\n  count(label, name = \"deaths_nearest\") |>\n  arrange(desc(deaths_nearest))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   label          deaths_nearest\n   <chr>                   <int>\n 1 Broad St                  359\n 2 So Soho                    64\n 3 Crown Chapel               61\n 4 Briddle St                 27\n 5 Oxford St #2               24\n 6 Warwick                    16\n 7 Oxford St #1               12\n 8 Gt Marlborough              6\n 9 Vigo St                     4\n10 Coventry St                 2\n11 Dean St                     2\n12 Castle St E                 1\n```\n\n\n:::\n:::\n\n\nOne pump — **Broad St** — is the nearest pump for 359 of the 578 deaths. Seen on the map:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbroad <- pumps |> filter(label == \"Broad St\")\n\nggplot() +\n  geom_point(data = deaths, aes(x, y), color = \"firebrick\", alpha = 0.5, size = 1.5) +\n  geom_point(data = pumps, aes(x, y), color = \"navy\", size = 3, shape = 17) +\n  # the Broad St pump gets a gold triangle instead of a label, so nothing covers the deaths\n  geom_point(data = broad, aes(x, y), fill = \"gold\", color = \"navy\", size = 5, shape = 24) +\n  coord_equal() +\n  labs(title = \"Cholera deaths cluster around a single pump\",\n       subtitle = \"Red dots = deaths · navy triangles = water pumps · gold = the Broad St pump\",\n       x = NULL, y = NULL)\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/snow-map-1.png){width=672}\n:::\n:::\n\n\nSnow wasn't just *describing* this map — he was making a bigger claim about the whole city, and about cholera itself. **That jump — from the data you have to the world you don't — is what we mean by inference.** And the fine print from lecture: you cannot *PROVE* anything from samples. We collect data and analyze it to build up a **weight of evidence** that shifts our certainty toward one conclusion or another.\n\n## 2 · A rare luxury: we know the truth\n\nOur Chicago file holds ~30,000 incidents from 2025. Today, *pretend the file is the whole population* — then we can check every inference against the truth:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrimes |> summarize(pop_arrest_rate = mean(arrest), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  pop_arrest_rate     n\n            <dbl> <int>\n1           0.161 30000\n```\n\n\n:::\n:::\n\n\nThe \"true\" citywide arrest proportion is **16.1%**. Lock that in — in real research you never get to see this number.\n\nNow act like a researcher who can only afford to pull 250 case files:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_250 <- crimes |> slice_sample(n = 250)\n\nsample_250 |> summarize(sample_arrest_rate = mean(arrest))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  sample_arrest_rate\n               <dbl>\n1              0.148\n```\n\n\n:::\n:::\n\n\nThis is a **point estimate** — the sample's best single guess at the population value. About 14.8% versus the true 16.1%. Close-ish. But how good is this estimate? How *certain* are we?\n\n## 3 · Caution! Samples fluctuate\n\nDraw a fresh sample of 250 and the estimate moves. Do it 1,000 times:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmany_estimates <- map_dbl(1:1000, \\(i) {\n  crimes |> slice_sample(n = 250) |> summarize(p = mean(arrest)) |> pull(p)\n})\n\nggplot(tibble(p = many_estimates), aes(p)) +\n  geom_histogram(bins = 30, fill = \"steelblue\", color = \"white\") +\n  geom_vline(xintercept = mean(crimes$arrest), color = \"firebrick\", linewidth = 1.2) +\n  labs(title = \"1,000 sample estimates of the arrest rate (n = 250 each)\",\n       subtitle = \"Red line = the true population value\",\n       x = \"Sample arrest proportion\", y = \"Number of samples\")\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/many-samples-1.png){width=672}\n:::\n:::\n\n\nThat's Session 4's sampling distribution, live. Where did the middle 95% of estimates land?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(many_estimates, c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% \n0.120 0.208 \n```\n\n\n:::\n:::\n\n\nRoughly **12% to 21%** — any *single* sample's estimate could easily be a couple points off the truth. So reporting \"14.8%\" alone is **overconfident**; we owe our reader a range that reflects the fluctuation. Problem: this exercise required 1,000 samples and a known population. A real researcher has **one sample**. Now what?\n\n## 4 · The confidence interval\n\nThe confidence interval turns *one* sample into an honest range, using what Session 4 taught us about how sample statistics behave:\n\n$$\\text{estimate} \\; \\pm \\; \\underbrace{1.96 \\times SE}_{\\text{margin of error}}$$\n\nThe **SE** (standard error) is the standard deviation of the sampling distribution, *estimated from the one sample you have*; **1.96** comes from the normal distribution — ±1.96 SDs covers the middle 95%. R does the whole thing for us:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(sum(sample_250$arrest), n = 250)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  sum(sample_250$arrest) out of 250, null probability 0.5\nX-squared = 122.5, df = 1, p-value < 2.2e-16\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.1075899 0.1995409\nsample estimates:\n    p \n0.148 \n```\n\n\n:::\n:::\n\n\nOur one sample of 250 says: point estimate **14.8%**, 95% CI **10.8% to 20.0%**. The true value (16.1%) is inside — *this time*. But \"95% confident\" of what, exactly?\n\n## 5 · The classic picture: 100 samples, 100 intervals\n\nDraw 100 samples; build a 95% CI from each. (`map()` runs the procedure 100 times and `list_rbind()` stacks the 100 one-row results into one tibble — Session 3's `replicate()`, tibble-flavored; see the [simulation verbs reference](../resources.qmd#simulation-verbs).)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci_100 <- map(1:100, \\(i) {\n  s  <- crimes |> slice_sample(n = 250)\n  ci <- prop.test(sum(s$arrest), n = 250)$conf.int\n  tibble(sample = i, estimate = mean(s$arrest), lo = ci[1], hi = ci[2])\n}) |>\n  list_rbind() |>\n  mutate(captured = lo <= mean(crimes$arrest) & mean(crimes$arrest) <= hi)\n\nsum(ci_100$captured)   # how many of the 100 intervals caught the truth?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ci_100, aes(sample, estimate, color = captured)) +\n  geom_hline(yintercept = mean(crimes$arrest), color = \"grey30\", linewidth = 1) +\n  geom_pointrange(aes(ymin = lo, ymax = hi), linewidth = 0.7, size = 0.25) +\n  scale_color_manual(values = c(\"TRUE\" = \"grey65\", \"FALSE\" = \"firebrick\")) +\n  labs(title = paste0(\"100 samples, 100 confidence intervals — \",\n                      sum(ci_100$captured), \" capture the truth\"),\n       subtitle = \"Horizontal line = true population arrest rate; red = intervals that missed\",\n       x = \"Sample number\", y = \"Arrest proportion\", color = \"Captured?\")\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/ci-sim-plot-1.png){width=672}\n:::\n:::\n\n\nIn plain language: each vertical bar is one research team's interval, the truth never moves, and about 95 of 100 intervals catch it. Each sample produced a *different* interval — the interval is a **random quantity**; the population value is **fixed**. In our run, 97 of 100 captured the truth. The teams who drew the red samples did nothing wrong — and their data give **no warning** that theirs are the unlucky intervals.\n\nThat long-run capture rate is *the entire meaning* of \"95% confident\": if we reran the whole study many times, in 95% of those replications the interval would contain the true value. Three things follow:\n\n1. Our 95% CI does **not** necessarily contain the true population value\n2. Our 95% CI is **not** a statement about the probability that *this particular* interval is correct\n3. It is a **long-run prediction** based on numerous replications\n\n(Everyone reacts to this with some version of \"WTF?!?\" — so run it again, slower.)\n\n### Run it again: 100 new researchers\n\nNew samples, new intervals. This time look at them first *without* the truth line, the way each of the 100 researchers would:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1854)   # a local seed, so this figure is the same every time it renders\nci_100b <- map(1:100, \\(i) {\n  s  <- crimes |> slice_sample(n = 250)\n  ci <- prop.test(sum(s$arrest), n = 250)$conf.int\n  tibble(sample = i, estimate = mean(s$arrest), lo = ci[1], hi = ci[2])\n}) |>\n  list_rbind() |>\n  mutate(captured = lo <= mean(crimes$arrest) & mean(crimes$arrest) <= hi)\n\ny_lims <- range(c(ci_100b$lo, ci_100b$hi))\n\nggplot(ci_100b, aes(sample, estimate)) +\n  geom_pointrange(aes(ymin = lo, ymax = hi), color = \"grey40\", linewidth = 0.7, size = 0.25) +\n  coord_cartesian(ylim = y_lims) +\n  labs(title = \"100 new researchers, 100 new intervals: what each of them sees\",\n       subtitle = \"No truth line yet. From inside any one study, every interval looks equally trustworthy\",\n       x = \"Researcher\", y = \"Arrest proportion\")\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/ci-sim-again-1.png){width=672}\n:::\n:::\n\n\nNow drop the truth in:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ci_100b, aes(sample, estimate, color = captured)) +\n  geom_hline(yintercept = mean(crimes$arrest), color = \"grey30\", linewidth = 1) +\n  geom_pointrange(aes(ymin = lo, ymax = hi), linewidth = 0.7, size = 0.25) +\n  scale_color_manual(values = c(\"TRUE\" = \"grey65\", \"FALSE\" = \"firebrick\")) +\n  coord_cartesian(ylim = y_lims) +\n  labs(title = paste0(sum(ci_100b$captured),\n                      \" of 100 caught it this time; the intervals moved, the truth did not\"),\n       subtitle = \"Horizontal line = true population arrest rate; red = intervals that missed\",\n       x = \"Researcher\", y = \"Arrest proportion\", color = \"Captured?\")\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/ci-sim-again-truth-1.png){width=672}\n:::\n:::\n\n\nThe intervals moved; the truth did not; again about 95 of 100 caught it. Finally, pick two of those researchers — the first whose interval caught the truth and the first whose interval missed — and look at what each of them had in front of them (`patchwork`'s `+` puts the two plots side by side):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ni_hit  <- which(ci_100b$captured)[1]\ni_miss <- which(!ci_100b$captured)[1]\ntwo <- ci_100b |>\n  filter(sample %in% c(i_hit, i_miss)) |>\n  mutate(who = paste0(\"Researcher \", sample))\n\nleft <- ggplot(two, aes(who, estimate)) +\n  geom_pointrange(aes(ymin = lo, ymax = hi), color = \"grey40\", linewidth = 1, size = 0.6) +\n  coord_cartesian(ylim = y_lims) +\n  labs(title = \"What the researchers see\", x = NULL, y = \"Arrest proportion\")\n\nright <- ggplot(two, aes(who, estimate, color = captured)) +\n  geom_hline(yintercept = mean(crimes$arrest), color = \"grey30\", linewidth = 1) +\n  geom_pointrange(aes(ymin = lo, ymax = hi), linewidth = 1, size = 0.6, show.legend = FALSE) +\n  scale_color_manual(values = c(\"TRUE\" = \"grey65\", \"FALSE\" = \"firebrick\")) +\n  coord_cartesian(ylim = y_lims) +\n  labs(title = \"What only we can see\", x = NULL, y = NULL)\n\nleft + right\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/you-are-one-1.png){width=672}\n:::\n:::\n\n\n**You only ever get one stick, and nothing in your data tells you its color.** That is why the 95% belongs to the procedure, not to your interval.\n\n## 6 · Saying it out loud\n\nDefensible sentences:\n\n> \"We estimate the citywide arrest rate at 14.8% (95% CI: 10.8% to 20.0%). Values in this range are consistent with our data.\"\n\n> \"The method we used captures the true value 95% of the time.\"\n\nNot defensible:\n\n> \"There is a 95% probability the true arrest rate is between 10.8% and 20.0%.\" — the truth is fixed; it's either in there or it isn't.\n\n> \"95% of arrest rates fall in this interval.\" — the CI is about the population parameter, not individual observations.\n\nThe forbidden first sentence is forbidden only under **frequentist rules**, where probability attaches to the *procedure*, never to the parameter. Attaching probability to a claim itself is exactly what Session 3's Bayes' theorem does — and next session we compute an interval you *can* say that sentence about: the **credible interval**. If the forbidden sentence felt like the natural reading all along, your intuitions were Bayesian. You're in good company.\n\n## 7 · Sample size buys precision\n\nSame procedure, four sample sizes, one draw each:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwidth_tbl <- map(c(100, 250, 1000, 4000), \\(n) {\n  s  <- crimes |> slice_sample(n = n)\n  ci <- prop.test(sum(s$arrest), n = n)$conf.int\n  tibble(n = n, estimate = mean(s$arrest),\n         lo = ci[1], hi = ci[2], width = ci[2] - ci[1])\n}) |>\n  list_rbind()\n\nwidth_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n      n estimate     lo    hi  width\n  <dbl>    <dbl>  <dbl> <dbl>  <dbl>\n1   100    0.12  0.0663 0.204 0.138 \n2   250    0.184 0.139  0.239 0.0998\n3  1000    0.165 0.143  0.190 0.0470\n4  4000    0.167 0.155  0.179 0.0234\n```\n\n\n:::\n:::\n\n\nQuadrupling *n* roughly **halves** the width — precision grows with $\\sqrt{n}$, so it gets expensive fast. The same table as a picture:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(width_tbl, aes(factor(n), estimate)) +\n  geom_hline(yintercept = mean(crimes$arrest), color = \"grey30\", linewidth = 1) +\n  geom_pointrange(aes(ymin = lo, ymax = hi), color = \"navy\", linewidth = 1, size = 0.6) +\n  geom_text(aes(y = hi, label = sprintf(\"width %.3f\", width)), vjust = -0.7, size = 3.5) +\n  scale_y_continuous(expand = expansion(mult = c(0.05, 0.2))) +\n  labs(title = \"Same procedure, four sample sizes: the interval tightens as n grows\",\n       subtitle = \"Horizontal line = the true arrest rate\",\n       x = \"Sample size\", y = \"Arrest proportion\")\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/width-plot-1.png){width=672}\n:::\n:::\n\n\n## 8 · Comparing two groups: do violent crimes happen later in the day?\n\nStreet lore says violence is a nighttime phenomenon; property crime, the daytime hustle. Our data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvp <- crimes |>\n  filter(crime_category %in% c(\"Violent\", \"Property\")) |>\n  mutate(crime_category = factor(crime_category, levels = c(\"Violent\", \"Property\")))\n\nvp |> summarize(mean_hour = mean(hour), sd_hour = sd(hour), n = n(), .by = crime_category)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  crime_category mean_hour sd_hour     n\n  <fct>              <dbl>   <dbl> <int>\n1 Violent             12.8    6.87  9148\n2 Property            12.5    6.63 10371\n```\n\n\n:::\n:::\n\n\nOne line we did not need before: `factor(levels = ...)` tells R which group comes **first**, so every subtraction below reads **Violent minus Property**. (R's default is alphabetical, which would have put Property first and flipped every sign.) Two point estimates: violent crimes average about **12:48 pm** (12.80 hours after midnight), property crimes about **12:33 pm** (12.54). Is that 15-minute gap real, or sample fluctuation?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vp, aes(crime_category, hour, fill = crime_category)) +\n  geom_boxplot(show.legend = FALSE) +\n  scale_fill_manual(values = c(\"firebrick\", \"steelblue\")) +\n  scale_y_continuous(breaks = c(0, 6, 12, 18, 24),\n                     labels = c(\"midnight\", \"6 am\", \"noon\", \"6 pm\", \"midnight\")) +\n  labs(x = NULL, y = \"Time of day\")\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/two-group-box-1.png){width=672}\n:::\n:::\n\n\nThe boxes nearly coincide — the eye can't settle this one. So resample: pull a bootstrap sample from each group (`sample()` with `replace = TRUE` draws a full-size resample), take each group's mean, and difference them, 1,000 times:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)\nviolent_hours  <- vp$hour[vp$crime_category == \"Violent\"]\nproperty_hours <- vp$hour[vp$crime_category == \"Property\"]\n\nboot_violent  <- replicate(1000, mean(sample(violent_hours,  replace = TRUE)))\nboot_property <- replicate(1000, mean(sample(property_hours, replace = TRUE)))\nmean_diffs    <- boot_violent - boot_property\n\nquantile(mean_diffs, c(0.025, 0.975)) * 60   # in minutes: Violent minus Property\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     2.5%     97.5% \n 3.709722 26.345208 \n```\n\n\n:::\n:::\n\n\nThe middle 95% of resampled differences (Violent minus Property) runs from about **4 to 26 minutes** — all above zero. Here is what that looks like, and what \"the interval does not cross zero\" means. Two small helpers first: `clock()` turns hours-after-midnight into a clock time, and `two_panel()` draws the same pair of pictures for any two groups, so both examples below are built the same way:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclock <- function(h) {\n  m  <- round(h * 60)\n  hh <- (m %/% 60) %% 24\n  mm <- m %% 60\n  sprintf(\"%d:%02d %s\", ifelse(hh %% 12 == 0, 12, hh %% 12), mm, ifelse(hh < 12, \"am\", \"pm\"))\n}\n\ntwo_panel <- function(boot_a, boot_b, name_a, name_b) {\n  groups <- tibble(group = factor(rep(c(name_a, name_b), each = length(boot_a)),\n                                  levels = c(name_a, name_b)),\n                   mean_hour = c(boot_a, boot_b))\n  diffs <- tibble(diff_min = (boot_a - boot_b) * 60)\n  q <- quantile(diffs$diff_min, c(0.025, 0.975))\n\n  left <- ggplot(groups, aes(mean_hour, fill = group)) +\n    geom_density(alpha = 0.6, color = NA) +\n    scale_fill_manual(values = c(\"firebrick\", \"steelblue\")) +\n    scale_x_continuous(labels = clock) +\n    labs(title = \"1,000 resampled means per group\", x = \"Mean time of day\", y = NULL, fill = NULL) +\n    theme(legend.position = \"top\")\n\n  right <- ggplot(diffs, aes(diff_min, fill = between(diff_min, q[1], q[2]))) +\n    geom_histogram(bins = 40, color = \"white\") +\n    geom_vline(xintercept = 0, color = \"firebrick\", linewidth = 1.2) +\n    expand_limits(x = 0) +\n    scale_fill_manual(values = c(\"TRUE\" = \"navy\", \"FALSE\" = \"grey75\"), guide = \"none\") +\n    labs(title = paste0(name_a, \" minus \", name_b),\n         subtitle = paste0(\"Middle 95%: \", round(q[1]), \" to \", round(q[2]), \" minutes\"),\n         x = \"Minutes\", y = NULL)\n  left + right\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_panel(boot_violent, boot_property, \"Violent\", \"Property\")\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/cross-zero-no-1.png){width=672}\n:::\n:::\n\n\nLeft: the two bootstrap distributions of the group means barely overlap. Right: the distribution of their difference, in minutes, with the middle 95% shaded. The zero line sits outside the shading: every plausible value of the difference is on the \"later\" side, and \"no difference\" is not on the list. That is what \"the interval does not cross zero\" looks like.\n\nThe two-sample t-test gives the same interval directly, no loop required:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(hour ~ crime_category, data = vp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  hour by crime_category\nt = 2.6061, df = 19021, p-value = 0.009164\nalternative hypothesis: true difference in means between group Violent and group Property is not equal to 0\n95 percent confidence interval:\n 0.06263688 0.44272107\nsample estimates:\n mean in group Violent mean in group Property \n              12.79602               12.54334 \n```\n\n\n:::\n:::\n\n\nTwo lines matter: `95 percent confidence interval`, and the two `mean in group` lines that tell you which minus which. Violent is listed first because we told R so.\n\nReading it honestly: the 95% CI for the difference (Violent minus Property) runs from **0.06 to 0.44 hours**, about **4 to 27 minutes** later — it excludes zero, so the data are consistent with violent crimes genuinely averaging later. But look at the *magnitude*: somewhere between about 4 and 27 minutes. Detectable ≠ dramatic. With ~19,500 incidents we can detect tiny differences; the CI hands you both facts at once — *direction* (probably real) and *size* (small). **Never report the first without the second.** This is your vaccination against next session's topic: a \"significant\" result can be substantively trivial.\n\n## 9 · And when it does cross zero\n\nSame city, a question the data cannot settle: within violent crimes, do the ones that end in an arrest happen at a different time of day? Same recipe, new groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)\nviolent <- crimes |>\n  filter(crime_category == \"Violent\") |>\n  mutate(arrest = factor(if_else(arrest, \"Arrest\", \"No arrest\"), levels = c(\"Arrest\", \"No arrest\")))\n\narrest_hours   <- violent$hour[violent$arrest == \"Arrest\"]\nnoarrest_hours <- violent$hour[violent$arrest == \"No arrest\"]\nboot_arrest    <- replicate(1000, mean(sample(arrest_hours,   replace = TRUE)))\nboot_noarrest  <- replicate(1000, mean(sample(noarrest_hours, replace = TRUE)))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_panel(boot_arrest, boot_noarrest, \"Arrest\", \"No arrest\")\n```\n\n::: {.cell-output-display}\n![](demo-05-confidence-intervals_files/figure-html/cross-zero-yes-1.png){width=672}\n:::\n:::\n\n\nNow the two bells overlap heavily, and the shaded middle 95% of the difference straddles zero. Zero is one of the plausible answers, so this sample cannot even tell you the direction. R agrees:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(hour ~ arrest, data = violent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  hour by arrest\nt = -1.2287, df = 1941.3, p-value = 0.2193\nalternative hypothesis: true difference in means between group Arrest and group No arrest is not equal to 0\n95 percent confidence interval:\n -0.6653724  0.1527959\nsample estimates:\n   mean in group Arrest mean in group No arrest \n               12.58047                12.83676 \n```\n\n\n:::\n:::\n\n\nThe interval runs from about **40 minutes earlier to 9 minutes later**, zero inside. Next session this contrast gets a name: the violent-versus-property difference is *statistically significant*, the arrest-versus-no-arrest difference is not — and you have now seen what the name is pointing at.\n\n## Try a variation\n\n1. Compute a 95% CI for the proportion of incidents flagged as **domestic**: run `crimes |> count(domestic)`, then type the TRUE count and 30,000 into `prop.test()`. Then write one *defensible* sentence reporting it — and audit yourself: did you claim a probability about *this* interval?\n2. Add `conf.level = 0.80` to a `prop.test()` call. Does the interval get wider or narrower — and what did you trade to get it?\n3. In the 100-intervals simulation, change `n = 250` to `n = 1000` in both places. What changes: the capture rate, or the widths?\n4. Remove the Broad Street pump before the `slice_min()` step (`filter(pump != 7)` on the pairs). Which pump inherits the deaths — and why should that make you *more* confident in Snow's inference, not less?\n",
    "supporting": [
      "demo-05-confidence-intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}