{
  "hash": "f995e3f070f92a529f909877e15c233b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo Walkthrough · Session 8\"\nsubtitle: \"ANOVA — comparing three or more means, in both traditions\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this page is.** The Session 8 lecture demos, written down step by step. Every chunk below is self-contained — copy any of them into your own R session and they run as-is. Use this page to catch up after a missed class, or to re-run what happened on screen at your own pace.\n:::\n\n## What you'll build\n\n1. A demonstration of why \"just run a pile of t-tests\" backfires — the false-alarm rate, computed\n2. ANOVA's two kinds of variance, built by hand on three classrooms before any function does it for you\n3. A null world *by construction* — three random groups from the same 70 cities — and the F distribution it produces\n4. `aov()` and Tukey's HSD, with the ANOVA table reconciled against your hand computations\n5. The Bayesian twin: `brm()` + `emmeans()` + `pairs()`, read through HPD intervals\n6. The same workflow on 30,000 real Chicago incidents — where \"significant\" and \"dramatic\" part ways\n\n## Setup\n\nEverything below needs the tidyverse, two new packages (`brms` and `emmeans` — install once with `install.packages(c(\"brms\", \"emmeans\"))`), and the course's anchor dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)\nlibrary(emmeans)\nset.seed(705)\n\ncrimes <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-crimes-2025.csv\",\n                   show_col_types = FALSE)\n```\n:::\n\n\n## 1 · Why not just run a pile of t-tests?\n\nThree groups means 3 pairwise comparisons. Six groups means 15. Each test carries its own 5% false-alarm risk, and the risks pile up:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(groups = c(2, 3, 4, 6, 10)) |>\n  mutate(\n    pairwise_tests = choose(groups, 2),\n    p_false_alarm  = round(1 - 0.95^pairwise_tests, 2)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  groups pairwise_tests p_false_alarm\n   <dbl>          <dbl>         <dbl>\n1      2              1          0.05\n2      3              3          0.14\n3      4              6          0.26\n4      6             15          0.54\n5     10             45          0.9 \n```\n\n\n:::\n:::\n\n\nBy six groups you have a coin-flip's chance of at least one bogus \"significant\" difference; by ten it's near-certain. ANOVA's answer: ask **one omnibus question** — *are all the group means plausibly equal?* — at a single 5% risk. (When we go pairwise afterward, Tukey will restore the family-wise rate. Hold that thought.)\n\n## 2 · Two kinds of variance, built by hand\n\nThe name is strange — **AN**alysis **O**f **VA**riance for a question about *means* — but the trick is the whole method. Start with three imaginary classrooms:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclassrooms <- tibble(\n  score     = c(75, 80, 78, 74, 77,    # Class 1\n                88, 90, 92, 85, 87,    # Class 2\n                70, 65, 68, 72, 66),   # Class 3\n  classroom = factor(rep(c(\"Class 1\", \"Class 2\", \"Class 3\"), each = 5))\n)\n\nclass_stats <- classrooms |>\n  summarize(class_mean = mean(score), class_var = var(score), .by = classroom)\nclass_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  classroom class_mean class_var\n  <fct>          <dbl>     <dbl>\n1 Class 1         76.8       5.7\n2 Class 2         88.4       7.3\n3 Class 3         68.2       8.2\n```\n\n\n:::\n:::\n\n\nTwo different kinds of \"spread\" are hiding in that table. **Within-group variance** is how much scores bounce around *inside* each classroom; **between-group variance** is how much the classroom *averages* differ from each other:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(class_stats$class_var)   # WITHIN: average spread inside a class\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.066667\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(class_stats$class_mean)   # BETWEEN: spread of the class means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102.76\n```\n\n\n:::\n:::\n\n\nBetween (102.8) dwarfs within (7.1) — the class averages are far more spread out than the chance bouncing inside classes would suggest. Signal-to-noise ratio ≈ 14.5. These classes look genuinely different.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(classrooms, aes(classroom, score)) +\n  geom_boxplot(alpha = 0.2, width = 0.3) +\n  geom_jitter(width = 0.08, size = 3, alpha = 0.6, color = \"navy\") +\n  geom_point(data = class_stats, aes(y = class_mean),\n             shape = 23, size = 5, fill = \"firebrick\", color = \"white\") +\n  labs(title = \"Within vs. between group variance\",\n       subtitle = \"Within = spread inside each box · Between = spread OF the diamonds (class means)\",\n       x = NULL, y = \"Test score\")\n```\n\n::: {.cell-output-display}\n![](demo-08-anova_files/figure-html/classrooms-plot-1.png){width=672}\n:::\n:::\n\n\n## 3 · A null world by construction: Stanton's rain example\n\nNow flip the situation: three groups where **nothing differs** — by construction. Base R's `precip` holds annual precipitation for 70 U.S. cities. Draw three random groups of 20 from the *same* 70 cities:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"precip\")\nset.seed(705)   # so you draw the same \"random\" groups the lecture did\ngroup1 <- sample(precip, 20)\ngroup2 <- sample(precip, 20)\ngroup3 <- sample(precip, 20)\n\nc(mean(group1), mean(group2), mean(group3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 34.100 31.835 31.255\n```\n\n\n:::\n:::\n\n\nThe means differ a little — but any differences here are **pure sampling luck**. The null hypothesis is *true by construction*. Now the same two variances:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(c(var(group1), var(group2), var(group3)))    # WITHIN\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 132.6697\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(c(mean(group1), mean(group2), mean(group3)))  # BETWEEN\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.260108\n```\n\n\n:::\n:::\n\n\nWithin ≈ 133, between ≈ 2.3 — the classrooms' pattern, completely flipped. Why so lopsided? City-to-city rainfall varies a lot (Phoenix vs. Mobile), so within is big; but each group's *mean* averages 20 cities, and Session 4 taught you means fluctuate far less than raw values ($SE = \\sigma/\\sqrt{n}$). With no real group differences, between-group variance is nothing but the tiny sampling noise of three means. That's the diagnostic: **between ≫ within → something real separates the groups; between ≪ within → nothing but noise.** All we need is a ruler for \"how much bigger is big enough.\"\n\n### The ruler: F, and what it does in a null world\n\n$$F \\;=\\; \\frac{\\text{between-group variance}}{\\text{within-group variance}} \\;=\\; \\frac{\\text{signal}}{\\text{noise}}$$\n\nWhen the null is true, F bounces around low values by luck of the draw. Don't take that on faith — draw 10,000 F values from a null world and look:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)   # inline seed: keeps this particular histogram (and its cutoff) stable\nf_null <- tibble(f = rf(10000, df1 = 2, df2 = 57))   # our design: 3 groups, N = 60\ncutoff <- quantile(f_null$f, 0.95)\n\nggplot(f_null, aes(f)) +\n  geom_histogram(bins = 60, fill = \"steelblue\", color = \"white\") +\n  geom_vline(xintercept = cutoff, color = \"firebrick\", linewidth = 1.1) +\n  labs(title = \"10,000 F values from a null world — F(2, 57)\",\n       subtitle = \"Red line = 95th percentile: F values beyond it are rare when nothing differs\",\n       x = \"F value\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](demo-08-anova_files/figure-html/f-dist-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncutoff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     95% \n3.083248 \n```\n\n\n:::\n:::\n\n\nThe 95% cutoff for this design lands near ≈ 3.1 (theory says `qf(0.95, 2, 57)` ≈ 3.16 — simulation is how we watch the theory). An F far beyond it means our data are *unlikely under the null* — the same logic as every test we've run.\n\n## 4 · Running the ANOVA with `aov()`\n\n`aov()` wants long format — one row per observation, one column saying which group it belongs to:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrain <- tibble(\n  rainfall = c(group1, group2, group3),\n  group    = factor(rep(c(\"Group 1\", \"Group 2\", \"Group 3\"), each = 20))\n)\n\nrain_model <- aov(rainfall ~ group, data = rain)\nsummary(rain_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\ngroup        2     90    45.2   0.341  0.713\nResiduals   57   7562   132.7               \n```\n\n\n:::\n:::\n\n\n**F = 0.34, p = 0.71.** That F sits squarely in the fat part of the histogram above — nowhere near the cutoff. No evidence the groups differ. *Correct answer* — they're the same population by construction.\n\n### The table is our two variances, dressed up\n\nReconcile the ANOVA table against the numbers you computed by hand:\n\n- **Mean Sq Residuals = 132.7** — exactly the within-group variance from Section 3.\n- **Mean Sq group = 45.2 = 20 × 2.26** — the between-group variance, *scaled by the group size*. Why × 20? A 2-inch gap between means built on 20 cities each is far stronger evidence than the same gap built on 2 — `aov()` bakes the sample size into the signal.\n- **F = 45.2 / 132.7 = 0.34.** So when your hand-computed ratio and `aov()`'s F disagree, this scaling is why — same logic, different units.\n\n### Now make a difference artificially\n\nShift Group 3 down 15 inches — now there *is* a real difference, and we know exactly where it lives:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrain_shifted <- rain |>\n  mutate(rainfall = if_else(group == \"Group 3\", rainfall - 15, rainfall))\n\nshifted_model <- aov(rainfall ~ group, data = rain_shifted)\nsummary(shifted_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \ngroup        2   3775  1887.7   14.23 9.72e-06 ***\nResiduals   57   7562   132.7                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe within-group noise didn't move (132.7 — shifting a whole group doesn't change the spread *inside* it). The between-group signal exploded. **F = 14.2, p ≈ 0.00001** — deep in the tail.\n\n### A significant F only says \"*something* differs\" — Tukey says what\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(shifted_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = rainfall ~ group, data = rain_shifted)\n\n$group\n                   diff      lwr       upr     p adj\nGroup 2-Group 1  -2.265 -11.0301  6.500103 0.8087836\nGroup 3-Group 1 -17.845 -26.6101 -9.079897 0.0000246\nGroup 3-Group 2 -15.580 -24.3451 -6.814897 0.0002129\n```\n\n\n:::\n:::\n\n\nGroup 3 differs from both others — intervals exclude 0, adjusted p-values tiny, exactly where we put the difference. Group 1 vs. Group 2: interval spans 0, p = 0.81 — no evidence, *as designed*. And these p-values are already adjusted for making all three comparisons — Tukey is the fix for the t-test pile-up problem from Section 1.\n\n## 5 · The Bayesian twin: `brm()` + `emmeans()`\n\n::: {.callout-warning appearance=\"simple\"}\n`brms` compiles models with your computer's C++ toolchain. Expect the *first* model of each R session to pause ~a minute at \"Compiling Stan program...\" — that's normal, not a crash.\n:::\n\nIdentical formula, Bayesian machinery:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_rain <- brm(rainfall ~ group, data = rain,\n                  chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\nTwo independent MCMC chains, 2,000 draws each → a full **posterior distribution** for every group mean. `emmeans()` turns the fitted model into group summaries — one row per group, with the posterior median and a 95% **HPD interval**, the range holding the most credible values for that group's mean:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrain_post <- emmeans(bayes_rain, ~ group)\nrain_post\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n group   emmean lower.HPD upper.HPD\n Group 1   34.2      28.8      38.9\n Group 2   32.0      27.1      37.1\n Group 3   31.4      26.5      36.5\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n:::\n\n\nWhat we really care about are *differences*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(rain_post)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate lower.HPD upper.HPD\n Group 1 - Group 2    2.233     -5.05      9.20\n Group 1 - Group 3    2.733     -4.34      9.93\n Group 2 - Group 3    0.506     -7.00      7.57\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pairs(rain_post)) +\n  geom_vline(xintercept = 0, linetype = 2, color = \"firebrick\")\n```\n\n::: {.cell-output-display}\n![](demo-08-anova_files/figure-html/plot-pairs-rain-1.png){width=672}\n:::\n:::\n\n\nEvery 95% HPD interval for a pairwise difference **crosses 0**: zero — \"no difference\" — remains a credible value for every contrast. Same verdict as F = 0.34, p = 0.71. Two traditions, one conclusion. When a difference is *real*, its interval abandons 0 — you'll see that on the Chicago data below.\n\n**The prior we just used.** We didn't state a prior, so `brms` fell back on its **defaults**: essentially flat on the group coefficients — every difference equally believable before the data — and weakly informative on the intercept and spread. Flat priors mean \"the data do the talking,\" which is fine at this *n*, but *say so*: \"we used brms default priors\" belongs in any writeup that reports a posterior. And notice the pattern across the course — `ttestBF()` in Session 6, `brm()` today, the `correlation` package in Session 10 are **different interfaces to the same move**: prior + likelihood → posterior. The interface changes; the reasoning never does. Session 10 shows what happens when you deliberately *change* the prior — and when it matters.\n\n## 6 · Real data: does the clock differ by crime category?\n\nIn Session 5 we found violent crimes average slightly *later* in the day than property crimes — two groups. Chicago's data sort every incident into **three** categories, and ANOVA takes all three in one shot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrimes |> summarize(mean_hour = mean(hour), sd_hour = sd(hour),\n                    n = n(), .by = crime_category)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  crime_category mean_hour sd_hour     n\n  <chr>              <dbl>   <dbl> <int>\n1 Violent             12.8    6.87  9148\n2 Other               12.1    6.95 10481\n3 Property            12.5    6.63 10371\n```\n\n\n:::\n:::\n\n\nViolent runs latest (12.8), Other earliest (12.1). Gaps of fractions of an hour, with SDs near 7 — real structure, or noise? And remember: n = 30,000, and big samples detect *tiny* things.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchicago_model <- aov(hour ~ crime_category, data = crimes)\nsummary(chicago_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Df  Sum Sq Mean Sq F value   Pr(>F)    \ncrime_category     2    2351  1175.3    25.3 1.05e-11 ***\nResiduals      29997 1393374    46.5                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**F(2, 29997) = 25.3, p ≈ 10⁻¹¹.** *Something* differs, emphatically — but that's all the omnibus F will ever tell us. Which pairs, and by how much?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(chicago_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = hour ~ crime_category, data = crimes)\n\n$crime_category\n                      diff        lwr       upr     p adj\nProperty-Other   0.4285629 0.20732516 0.6498006 0.0000168\nViolent-Other    0.6812419 0.45269164 0.9097921 0.0000000\nViolent-Property 0.2526790 0.02356458 0.4817934 0.0263613\n```\n\n\n:::\n:::\n\n\nAll three intervals exclude 0 — every category differs from every other. Now look at the **sizes**: 0.25 to 0.68 hours. That's **15 to 41 minutes**, on a 24-hour clock, against SDs near 7 hours. The Bayesian version is the exact three lines from Section 5 with `hour ~ crime_category` swapped in — nothing new to learn — and it agrees: every HPD interval for a pairwise difference excludes zero (the lecture runs it in full; only the compile-and-sample wait argues against re-fitting it here).\n\n**Detectable ≠ dramatic.** Both traditions agree the mean incident hour genuinely differs across categories — and the biggest gap is 41 minutes. Detecting a difference is not the same as its *mattering*. Report **direction** *and* **size**, every time: \"Mean incident hour differed across crime categories, F(2, 29997) = 25.3, p < .001; violent crimes averaged ≈ 15 minutes later than property crimes, 95% CI [0.02, 0.48] hours.\" \"Significant\" without magnitude is malpractice — Session 6's lesson, now with three groups.\n\n## Try a variation\n\n1. In the shift demo, change `- 15` to `- 5` inches. Does F still clear the cutoff? Which Tukey comparisons survive, and which lose significance?\n2. Add `groups = 15` to the alpha-inflation table. How many pairwise tests would that demand, and what's the false-alarm probability?\n3. Delete the `set.seed(705)` line in the rain-groups chunk and re-run the draw plus `aov()` a few times. How much do F and p bounce around when the null is true? *(You're watching the left half of the F histogram, one draw at a time.)*\n4. Filter `crimes` to the four most common `primary_type` values (`count()` will find them) and run `aov(hour ~ primary_type)` plus Tukey. With six pairwise comparisons, which specific crime types actually differ on the clock?\n",
    "supporting": [
      "demo-08-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}