{
  "hash": "dee703906b6b095faf34712f8bee7684",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Practice Problems · Session 8\"\nsubtitle: \"ANOVA: two variances, the F-ratio, Tukey, and posterior differences\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Ungraded self-checks.** Work each problem in your own R session *before* clicking the solution. These use different data and numbers than the homework on purpose — if you can do these cold, Homework 8 (and the midterm's ANOVA questions) will feel routine.\n:::\n\n\n\nEvery problem here runs on typed-in or built-in data, so the only setup you need is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)      # Problem 5 only — expect the usual compile pause\nlibrary(emmeans)\n```\n:::\n\n\n## Problem 1 · The pile of t-tests, quantified\n\nYour department compares mean response times across **five patrol sectors**. A colleague proposes \"keeping it simple\": a separate t-test on every pair of sectors, each at the usual 5% false-alarm risk.\n\n(a) How many pairwise tests is that? (`choose()` counts them.)\n(b) If all five sectors truly have the **same** mean, what is the probability that at least one test comes up \"significant\" anyway?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchoose(5, 2)          # pairwise tests among 5 groups\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - 0.95^choose(5, 2) # P(at least one false alarm across all of them)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4012631\n```\n\n\n:::\n:::\n\n\nTen tests, and roughly a **40% chance** of at least one bogus \"significant\" difference when nothing differs at all. That's why ANOVA asks *one* omnibus question — are all five means plausibly equal? — at a single 5% risk, and saves the pairwise digging for an adjusted follow-up (Problem 4).\n:::\n\n## Problem 2 · Two variances, by hand\n\nDispatch pulls five response times (minutes) from each of three sectors — small on purpose, so you can see every number:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsectors <- tibble(\n  minutes = c(7, 9, 8, 10, 8,       # Adams\n              12, 14, 13, 15, 13,   # Baker\n              8, 10, 9, 7, 9),      # Charlie\n  sector  = factor(rep(c(\"Adams\", \"Baker\", \"Charlie\"), each = 5))\n)\n```\n:::\n\n\nCompute each sector's mean and variance, then the **within-group variance** (average of the three variances), the **between-group variance** (variance of the three means), and their ratio. What is the ratio telling you, in signal-and-noise terms?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsector_stats <- sectors |>\n  summarize(sector_mean = mean(minutes), sector_var = var(minutes), .by = sector)\nsector_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  sector  sector_mean sector_var\n  <fct>         <dbl>      <dbl>\n1 Adams           8.4        1.3\n2 Baker          13.4        1.3\n3 Charlie         8.6        1.3\n```\n\n\n:::\n\n```{.r .cell-code}\nwithin_var  <- mean(sector_stats$sector_var)   # noise: spread inside sectors\nbetween_var <- var(sector_stats$sector_mean)   # signal: spread OF the means\n\nwithin_var\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.3\n```\n\n\n:::\n\n```{.r .cell-code}\nbetween_var\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.013333\n```\n\n\n:::\n\n```{.r .cell-code}\nbetween_var / within_var\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.164103\n```\n\n\n:::\n:::\n\n\nThe sector means (8.4, 13.4, 8.6) are about **6 times** more spread out than the chance bouncing inside sectors would produce — between dwarfs within, which is the signature of a real group difference. Between-group variance is the signal, within-group variance is the noise, and the ratio is your first, unscaled look at F.\n:::\n\n## Problem 3 · `aov()` and reading the F table\n\nRun `aov(minutes ~ sector, ...)` on the same data and look at `summary()`. Then connect it to Problem 2: which table entry **is** your within-group variance? Why is `Mean Sq` for sector *not* 8.01? And what do F and p say?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsector_model <- aov(minutes ~ sector, data = sectors)\nsummary(sector_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nsector       2  80.13   40.07   30.82 1.87e-05 ***\nResiduals   12  15.60    1.30                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n- **Mean Sq Residuals = 1.30** — the within-group variance from Problem 2, exactly.\n- **Mean Sq sector = 40.07 = 5 × 8.01** — the between-group variance scaled by the **group size**. A 5-minute gap between means built on 5 calls each is stronger evidence than the same gap built on 2, so `aov()` bakes the sample size into the signal.\n- **F(2, 12) = 30.8** — which is 5 × our hand ratio of 6.16 — with **p ≈ 0.00002**: an F this large essentially never happens when the three sectors truly share a mean.\n\nThe F table is Problem 2's two variances dressed up: same logic, with the group size folded into the signal.\n:::\n\n## Problem 4 · Real(ish) data: `warpbreaks` and Tukey\n\nR ships `warpbreaks`: 54 industrial loom runs, recording how many times the yarn **broke** during each run under low, medium, or high `tension` (L/M/H, 18 runs each). Quality-control question: does mean breakage differ by tension setting?\n\nCompute the group means, run the ANOVA, then `TukeyHSD()`. Which pairs differ? **One pair shows no reliable difference** — name it and report the interval that told you so.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"warpbreaks\")\n\nwarpbreaks |>\n  summarize(mean_breaks = mean(breaks), sd_breaks = sd(breaks), n = n(),\n            .by = tension)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  tension mean_breaks sd_breaks  n\n1       L    36.38889 16.446487 18\n2       M    26.38889  9.121009 18\n3       H    21.66667  8.352527 18\n```\n\n\n:::\n\n```{.r .cell-code}\nwarp_model <- aov(breaks ~ tension, data = warpbreaks)\nsummary(warp_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \ntension      2   2034  1017.1   7.206 0.00175 **\nResiduals   51   7199   141.1                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nTukeyHSD(warp_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = breaks ~ tension, data = warpbreaks)\n\n$tension\n          diff       lwr        upr     p adj\nM-L -10.000000 -19.55982 -0.4401756 0.0384598\nH-L -14.722222 -24.28205 -5.1623978 0.0014315\nH-M  -4.722222 -14.28205  4.8376022 0.4630831\n```\n\n\n:::\n:::\n\n\n**F(2, 51) = 7.2, p ≈ .002** — the omnibus F says *something* differs. Tukey says *what*: M − L (−10.0, interval [−19.6, −0.4], p ≈ .04) and H − L (−14.7, interval [−24.3, −5.2], p ≈ .001) both exclude 0 — low tension breaks more yarn than either alternative. But **H − M spans 0** ([−14.3, 4.8], p ≈ .46): no evidence medium and high differ. A significant omnibus F never means *every* pair differs — Tukey names the pairs while holding the family-wise false-alarm rate at 5%.\n:::\n\n## Problem 5 · The Bayesian version: `brm()` + `emmeans()` + `pairs()`\n\nFit the Bayesian twin of Problem 4's model (expect the *Compiling Stan program...* pause — that's normal, not a crash), then get the posterior pairwise differences. Which 95% HPD intervals **cross zero**, and does the Bayesian verdict match Tukey's?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwarp_bayes <- brm(breaks ~ tension, data = warpbreaks,\n                  chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwarp_post <- emmeans(warp_bayes, ~ tension)\nwarp_post\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n tension emmean lower.HPD upper.HPD\n L         36.6      30.2      41.8\n M         26.4      20.1      31.8\n H         21.6      16.3      27.2\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\npairs(warp_post)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast estimate lower.HPD upper.HPD\n L - M       10.05      1.56      18.0\n L - H       14.79      5.91      22.5\n M - H        4.65     -2.66      12.9\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pairs(warp_post)) +\n  geom_vline(xintercept = 0, linetype = 2, color = \"firebrick\")\n```\n\n::: {.cell-output-display}\n![](practice-08_files/figure-html/p5-plot-1.png){width=672}\n:::\n:::\n\n\nL − M (≈ +10, HPD roughly [2, 18]) and L − H (≈ +14.7, roughly [7, 23]) **exclude 0** — credible differences. M − H (≈ +4.7, roughly [−3, 13]) **crosses 0** — zero remains a credible value, so no credible difference. Same verdict as Tukey, pair for pair. One nuance worth noticing: these Bayesian intervals are *per-comparison*, while Tukey deliberately widens its intervals to hold the *family-wise* rate — with only 3 contrasts the two land in the same place, but on borderline pairs they can disagree — worth watching for whenever you run both. When an HPD interval crosses zero, \"no difference\" is still on the table; when it doesn't, the difference is credible.\n:::\n\n## Problem 6 · Audit the memo\n\nA crime-analyst memo about the `warpbreaks`-style analysis contains these four sentences. **Two are wrong.** Find them, say why, and fix them.\n\n> (a) \"The omnibus test was significant, F(2, 51) = 7.2, p = .002, so all three tension settings differ from one another.\"\n>\n> (b) \"To be thorough, we also ran all three pairwise t-tests without adjustment and report those p-values instead of Tukey's.\"\n>\n> (c) \"Tukey's HSD keeps the family-wise false-alarm rate at 5% across all three comparisons.\"\n>\n> (d) \"Low tension averaged about 15 more breaks per run than high tension, 95% CI [5.2, 24.3].\"\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Unadjusted pairwise p-values vs. Tukey's family-wise-adjusted ones:\npairwise.t.test(warpbreaks$breaks, warpbreaks$tension, p.adjust.method = \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with pooled SD \n\ndata:  warpbreaks$breaks and warpbreaks$tension \n\n  L      M     \nM 0.0147 -     \nH 0.0005 0.2386\n\nP value adjustment method: none \n```\n\n\n:::\n\n```{.r .cell-code}\nTukeyHSD(aov(breaks ~ tension, data = warpbreaks))$tension[, \"p adj\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        M-L         H-L         H-M \n0.038459768 0.001431503 0.463083097 \n```\n\n\n:::\n:::\n\n\n**(a) is wrong.** A significant omnibus F licenses only \"at least one mean differs\" — and Tukey showed H vs. M does *not* differ. Fix: \"...so not all three tension means are equal; pairwise comparisons follow.\"\n\n**(b) is wrong.** Reporting *unadjusted* pairwise p-values quietly triples the false-alarm exposure — Problem 1's pile-of-t-tests problem in miniature. Compare the two outputs above: every unadjusted p is smaller than its Tukey counterpart (e.g., M vs. L: .015 unadjusted vs. .038 adjusted) precisely because the unadjusted version ignores the other tests being run. Fix: report the Tukey-adjusted results.\n\n**(c) and (d) are fine** — (d) is just Tukey's H − L row with the sign flipped, magnitude and interval intact. The concept to keep: per-comparison p-values and family-wise p-values answer different questions, and after a significant F, the family-wise one is the honest one.\n:::\n",
    "supporting": [
      "practice-08_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}