{
  "hash": "84e7192033306140a059da89759d93ef",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Applied Workshop: Real Questions, Real Tests\"\nsubtitle: \"CRJU 705 · Session 7 · Fall 2026\"\nauthor: \"Scott M. Mourtgos\"\nformat:\n  revealjs:\n    slide-number: true\n    preview-links: auto\n    chalkboard: true\n    footer: \"CRJU 705 · Session 7\"\n    theme: [default, custom-slides.scss]\n    fig-align: center\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n## This Week\n\n**Topic:** no new statistics. Tonight we *use* what you already have.\n\n- Four real questions from four corners of criminal justice: reentry, pretrial release, neighborhoods, police use of force\n- Every one answered with tools from Sessions 5 and 6: `count()`, `prop.test()`, `bayes_prop_test()`, `t.test()`\n- Then: **what data is out there**, so you can choose your final-project dataset this week\n\n**Learning goal:** given a two-group question on a dataset you have never seen, pick the test, run it, and say what it means (and what it does not).\n\n## How Today Works\n\n:::: columns\n::: {.column width=\"33%\"}\n**Lecture**\n\nFour worked examples, one recipe, and a picture of each\n:::\n\n::: {.column width=\"33%\"}\n**Lab 7**\n\nTwo more, and you write the code\n:::\n\n::: {.column width=\"33%\"}\n**What's out there**\n\nA menu of real datasets to explore this week\n:::\n::::\n\nEverything I run tonight is written up in the [demo walkthrough](../demos/demo-07-workshop.qmd), animations included.\n\n## The Recipe\n\nEvery question tonight, the same four steps:\n\n1. **Question.** Name the two groups and the outcome\n2. **Count or describe.** `count()` for yes/no; group averages for a number\n3. **Test.** Frequentist always; Bayesian too when the outcome is yes/no\n4. **Say it.** The honest sentence · how big, in real units · one thing this test **cannot** tell you\n\n## Which Test?\n\n| The outcome is... | Example | Test |\n|---|---|---|\n| **yes/no** | arrested again? searched? released? | `prop.test()` and `bayes_prop_test()` |\n| **a number** | age, income, number of prior arrests | `t.test(outcome ~ group, data = )` |\n\n. . .\n\nThat table covers every question in tonight's lecture and lab, and a surprising share of what gets published in criminal justice journals.\n\n# Example 1 · Reentry: Does Money at Release Keep People Out of Jail? {background-color=\"#73000A\"}\n\n## The Study\n\n- **432 men** released from Maryland state prisons in the 1970s, followed for one year\n- Half were **randomly assigned** to receive financial aid after release; half were not\n- Outcome: **arrested again** within the year (1 = yes)\n- One row = one released man\n\n. . .\n\n**Question:** did the aid group get re-arrested less often? Two groups, yes/no outcome: `prop.test()` and `bayes_prop_test()`.\n\n## Count\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrossi |> count(fin, arrest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  fin   arrest     n\n  <chr>  <dbl> <int>\n1 no         0   150\n2 no         1    66\n3 yes        0   168\n4 yes        1    48\n```\n\n\n:::\n:::\n\n\n- **Aid** (`fin = yes`): 48 re-arrested out of 48 + 168 = **216** (22.2%)\n- **No aid:** 66 out of 66 + 150 = **216** (30.6%)\n\nAid first all the way through, so every difference reads **Aid minus No aid**.\n\n## Test: `prop.test()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(48, 66), n = c(216, 216))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(48, 66) out of c(216, 216)\nX-squared = 3.4439, df = 1, p-value = 0.06349\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.170713151  0.004046484\nsample estimates:\n   prop 1    prop 2 \n0.2222222 0.3055556 \n```\n\n\n:::\n:::\n\n\n## Reading It\n\n- Interval: about **17 points lower to 0.4 points higher**. Zero is (just) inside\n- **p = 0.063**. Above 0.05: fail to reject the null\n\n. . .\n\nWhat is that 0.063 actually measuring? Let's *watch* it.\n\n## What Would Luck Alone Do?\n\nPretend aid did **nothing**: everyone has the same 26% chance of re-arrest. Run the study again and again. How often does luck alone hand us a gap as big as ours?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-83e69079de00aeb06b01\" style=\"width:950px;height:470px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-83e69079de00aeb06b01\">{\"x\":{\"visdat\":{\"c32f6719d03b\":[\"function () \",\"plotlyVisDat\"],\"c32f4fb6065e\":[\"function () \",\"data\"],\"c32f375c2e34\":[\"function () \",\"data\"]},\"cur_data\":\"c32f375c2e34\",\"attrs\":{\"c32f4fb6065e\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"type\":\"bar\",\"frame\":{},\"color\":{},\"colors\":[\"#73000A\",\"#BDBDBD\"],\"hoverinfo\":\"none\",\"inherit\":true},\"c32f375c2e34\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"text\":{},\"type\":\"scatter\",\"mode\":\"text\",\"frame\":{},\"textfont\":{\"size\":18,\"color\":\"#73000A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"inherit\":true}},\"layout\":{\"width\":950,\"height\":470,\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"barmode\":\"overlay\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Gap in re-arrest rate, aid minus no aid (points)\",\"range\":[-20.5,20.5]},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Share of pretend studies (%)\",\"range\":[0,8]},\"shapes\":[{\"type\":\"line\",\"x0\":-8.3000000000000007,\"x1\":-8.3000000000000007,\"y0\":0,\"y1\":8,\"line\":{\"color\":\"#1B2A4A\",\"width\":3}},{\"type\":\"line\",\"x0\":8.3000000000000007,\"x1\":8.3000000000000007,\"y0\":0,\"y1\":8,\"line\":{\"color\":\"#1B2A4A\",\"width\":3,\"dash\":\"dash\"}}],\"annotations\":[{\"x\":-8.5999999999999996,\"y\":7.7999999999999998,\"text\":\"Our study: -8.3\",\"showarrow\":false,\"xanchor\":\"right\",\"font\":{\"size\":15,\"color\":\"#1B2A4A\"}}],\"legend\":{\"orientation\":\"h\",\"y\":1.0800000000000001},\"hovermode\":\"closest\",\"showlegend\":true,\"sliders\":[{\"currentvalue\":{\"prefix\":\"\",\"xanchor\":\"right\",\"font\":{\"size\":16,\"color\":\"rgba(204,204,204,1)\"}},\"steps\":[{\"method\":\"animate\",\"args\":[[\"20 pretend studies\"],{\"transition\":{\"duration\":700,\"easing\":\"linear\"},\"frame\":{\"duration\":1500,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"20 pretend studies\",\"value\":\"20 pretend studies\"},{\"method\":\"animate\",\"args\":[[\"100 pretend studies\"],{\"transition\":{\"duration\":700,\"easing\":\"linear\"},\"frame\":{\"duration\":1500,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"100 pretend studies\",\"value\":\"100 pretend studies\"},{\"method\":\"animate\",\"args\":[[\"500 pretend studies\"],{\"transition\":{\"duration\":700,\"easing\":\"linear\"},\"frame\":{\"duration\":1500,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"500 pretend studies\",\"value\":\"500 pretend studies\"},{\"method\":\"animate\",\"args\":[[\"2,000 pretend studies\"],{\"transition\":{\"duration\":700,\"easing\":\"linear\"},\"frame\":{\"duration\":1500,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2,000 pretend studies\",\"value\":\"2,000 pretend studies\"},{\"method\":\"animate\",\"args\":[[\"10,000 pretend studies\"],{\"transition\":{\"duration\":700,\"easing\":\"linear\"},\"frame\":{\"duration\":1500,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"10,000 pretend studies\",\"value\":\"10,000 pretend studies\"}],\"visible\":true,\"pad\":{\"t\":40}}],\"updatemenus\":[{\"type\":\"buttons\",\"direction\":\"right\",\"showactive\":false,\"y\":0,\"x\":0,\"yanchor\":\"top\",\"xanchor\":\"right\",\"pad\":{\"t\":60,\"r\":5},\"buttons\":[{\"label\":\"Play\",\"method\":\"animate\",\"args\":[null,{\"fromcurrent\":true,\"mode\":\"immediate\",\"transition\":{\"duration\":700,\"easing\":\"linear\"},\"frame\":{\"duration\":1500,\"redraw\":false}}]}]}]},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displayModeBar\":false},\"data\":[{\"x\":[-20.833333333333332,-20.37037037037037,-19.907407407407408,-19.444444444444443,-18.981481481481481,-18.518518518518519,-18.055555555555557,-17.592592592592592,-17.12962962962963,-16.666666666666668,-16.203703703703702,-15.74074074074074,-15.277777777777779,-14.814814814814815,-14.351851851851851,-13.888888888888889,-13.425925925925926,-12.962962962962964,-12.5,-12.037037037037036,-11.574074074074074,-11.111111111111111,-10.648148148148149,-10.185185185185185,-9.7222222222222214,-9.2592592592592595,-8.7962962962962958,-8.3333333333333339,8.3333333333333339,8.7962962962962958,9.2592592592592595,9.7222222222222214,10.185185185185185,10.648148148148149,11.111111111111111,11.574074074074074,12.037037037037036,12.5,12.962962962962964,13.425925925925926,13.888888888888889,14.351851851851851,14.814814814814815,15.277777777777779,15.74074074074074,16.203703703703702,16.666666666666668,17.12962962962963,17.592592592592592,18.055555555555557,18.518518518518519,18.981481481481481,19.444444444444443,19.907407407407408,20.37037037037037,20.833333333333332],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"type\":\"bar\",\"frame\":\"20 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"At least as big as ours\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-7.8703703703703702,-7.4074074074074074,-6.9444444444444446,-6.4814814814814818,-6.0185185185185182,-5.5555555555555554,-5.0925925925925926,-4.6296296296296298,-4.166666666666667,-3.7037037037037037,-3.2407407407407409,-2.7777777777777777,-2.3148148148148149,-1.8518518518518519,-1.3888888888888888,-0.92592592592592593,-0.46296296296296297,0,0.46296296296296297,0.92592592592592593,1.3888888888888888,1.8518518518518519,2.3148148148148149,2.7777777777777777,3.2407407407407409,3.7037037037037037,4.166666666666667,4.6296296296296298,5.0925925925925926,5.5555555555555554,6.0185185185185182,6.4814814814814818,6.9444444444444446,7.4074074074074074,7.8703703703703702],\"y\":[0,0,10,0,0,5,5,0,0,5,0,0,5,0,10,5,0,5,0,0,0,10,10,0,0,5,0,10,0,0,0,0,5,0,0],\"type\":\"bar\",\"frame\":\"20 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"Smaller than ours\",\"marker\":{\"color\":\"rgba(189,189,189,1)\",\"line\":{\"color\":\"rgba(189,189,189,1)\"}},\"textfont\":{\"color\":\"rgba(189,189,189,1)\"},\"error_y\":{\"color\":\"rgba(189,189,189,1)\"},\"error_x\":{\"color\":\"rgba(189,189,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[13.5],\"y\":[7.2000000000000002],\"text\":\"10.0% had a gap<br>at least as big as ours\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"20 pretend studies\",\"textfont\":{\"size\":18,\"color\":\"#73000A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"frames\":[{\"name\":\"20 pretend studies\",\"data\":[{\"x\":[-20.833333333333332,-20.37037037037037,-19.907407407407408,-19.444444444444443,-18.981481481481481,-18.518518518518519,-18.055555555555557,-17.592592592592592,-17.12962962962963,-16.666666666666668,-16.203703703703702,-15.74074074074074,-15.277777777777779,-14.814814814814815,-14.351851851851851,-13.888888888888889,-13.425925925925926,-12.962962962962964,-12.5,-12.037037037037036,-11.574074074074074,-11.111111111111111,-10.648148148148149,-10.185185185185185,-9.7222222222222214,-9.2592592592592595,-8.7962962962962958,-8.3333333333333339,8.3333333333333339,8.7962962962962958,9.2592592592592595,9.7222222222222214,10.185185185185185,10.648148148148149,11.111111111111111,11.574074074074074,12.037037037037036,12.5,12.962962962962964,13.425925925925926,13.888888888888889,14.351851851851851,14.814814814814815,15.277777777777779,15.74074074074074,16.203703703703702,16.666666666666668,17.12962962962963,17.592592592592592,18.055555555555557,18.518518518518519,18.981481481481481,19.444444444444443,19.907407407407408,20.37037037037037,20.833333333333332],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"type\":\"bar\",\"frame\":\"20 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"At least as big as ours\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-7.8703703703703702,-7.4074074074074074,-6.9444444444444446,-6.4814814814814818,-6.0185185185185182,-5.5555555555555554,-5.0925925925925926,-4.6296296296296298,-4.166666666666667,-3.7037037037037037,-3.2407407407407409,-2.7777777777777777,-2.3148148148148149,-1.8518518518518519,-1.3888888888888888,-0.92592592592592593,-0.46296296296296297,0,0.46296296296296297,0.92592592592592593,1.3888888888888888,1.8518518518518519,2.3148148148148149,2.7777777777777777,3.2407407407407409,3.7037037037037037,4.166666666666667,4.6296296296296298,5.0925925925925926,5.5555555555555554,6.0185185185185182,6.4814814814814818,6.9444444444444446,7.4074074074074074,7.8703703703703702],\"y\":[0,0,10,0,0,5,5,0,0,5,0,0,5,0,10,5,0,5,0,0,0,10,10,0,0,5,0,10,0,0,0,0,5,0,0],\"type\":\"bar\",\"frame\":\"20 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"Smaller than ours\",\"marker\":{\"color\":\"rgba(189,189,189,1)\",\"line\":{\"color\":\"rgba(189,189,189,1)\"}},\"textfont\":{\"color\":\"rgba(189,189,189,1)\"},\"error_y\":{\"color\":\"rgba(189,189,189,1)\"},\"error_x\":{\"color\":\"rgba(189,189,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[13.5],\"y\":[7.2000000000000002],\"text\":\"10.0% had a gap<br>at least as big as ours\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"20 pretend studies\",\"textfont\":{\"size\":18,\"color\":\"#73000A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]},{\"name\":\"100 pretend studies\",\"data\":[{\"x\":[-20.833333333333332,-20.37037037037037,-19.907407407407408,-19.444444444444443,-18.981481481481481,-18.518518518518519,-18.055555555555557,-17.592592592592592,-17.12962962962963,-16.666666666666668,-16.203703703703702,-15.74074074074074,-15.277777777777779,-14.814814814814815,-14.351851851851851,-13.888888888888889,-13.425925925925926,-12.962962962962964,-12.5,-12.037037037037036,-11.574074074074074,-11.111111111111111,-10.648148148148149,-10.185185185185185,-9.7222222222222214,-9.2592592592592595,-8.7962962962962958,-8.3333333333333339,8.3333333333333339,8.7962962962962958,9.2592592592592595,9.7222222222222214,10.185185185185185,10.648148148148149,11.111111111111111,11.574074074074074,12.037037037037036,12.5,12.962962962962964,13.425925925925926,13.888888888888889,14.351851851851851,14.814814814814815,15.277777777777779,15.74074074074074,16.203703703703702,16.666666666666668,17.12962962962963,17.592592592592592,18.055555555555557,18.518518518518519,18.981481481481481,19.444444444444443,19.907407407407408,20.37037037037037,20.833333333333332],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,3,0,1,0,1,1,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"type\":\"bar\",\"frame\":\"100 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"At least as big as ours\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-7.8703703703703702,-7.4074074074074074,-6.9444444444444446,-6.4814814814814818,-6.0185185185185182,-5.5555555555555554,-5.0925925925925926,-4.6296296296296298,-4.166666666666667,-3.7037037037037037,-3.2407407407407409,-2.7777777777777777,-2.3148148148148149,-1.8518518518518519,-1.3888888888888888,-0.92592592592592593,-0.46296296296296297,0,0.46296296296296297,0.92592592592592593,1.3888888888888888,1.8518518518518519,2.3148148148148149,2.7777777777777777,3.2407407407407409,3.7037037037037037,4.166666666666667,4.6296296296296298,5.0925925925925926,5.5555555555555554,6.0185185185185182,6.4814814814814818,6.9444444444444446,7.4074074074074074,7.8703703703703702],\"y\":[0,4,2,3,1,2,3,1,2,7,2,6,2,2,4,4,3,3,4,1,5,5,3,2,4,1,0,3,2,0,1,2,2,2,0],\"type\":\"bar\",\"frame\":\"100 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"Smaller than ours\",\"marker\":{\"color\":\"rgba(189,189,189,1)\",\"line\":{\"color\":\"rgba(189,189,189,1)\"}},\"textfont\":{\"color\":\"rgba(189,189,189,1)\"},\"error_y\":{\"color\":\"rgba(189,189,189,1)\"},\"error_x\":{\"color\":\"rgba(189,189,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[13.5],\"y\":[7.2000000000000002],\"text\":\"12.0% had a gap<br>at least as big as ours\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"100 pretend studies\",\"textfont\":{\"size\":18,\"color\":\"#73000A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]},{\"name\":\"500 pretend studies\",\"data\":[{\"x\":[-20.833333333333332,-20.37037037037037,-19.907407407407408,-19.444444444444443,-18.981481481481481,-18.518518518518519,-18.055555555555557,-17.592592592592592,-17.12962962962963,-16.666666666666668,-16.203703703703702,-15.74074074074074,-15.277777777777779,-14.814814814814815,-14.351851851851851,-13.888888888888889,-13.425925925925926,-12.962962962962964,-12.5,-12.037037037037036,-11.574074074074074,-11.111111111111111,-10.648148148148149,-10.185185185185185,-9.7222222222222214,-9.2592592592592595,-8.7962962962962958,-8.3333333333333339,8.3333333333333339,8.7962962962962958,9.2592592592592595,9.7222222222222214,10.185185185185185,10.648148148148149,11.111111111111111,11.574074074074074,12.037037037037036,12.5,12.962962962962964,13.425925925925926,13.888888888888889,14.351851851851851,14.814814814814815,15.277777777777779,15.74074074074074,16.203703703703702,16.666666666666668,17.12962962962963,17.592592592592592,18.055555555555557,18.518518518518519,18.981481481481481,19.444444444444443,19.907407407407408,20.37037037037037,20.833333333333332],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.20000000000000001,0.20000000000000001,0.20000000000000001,0,0,0,0.40000000000000002,0.20000000000000001,1,0,0.40000000000000002,0.80000000000000004,0.59999999999999998,0.59999999999999998,0.80000000000000004,0.40000000000000002,0.40000000000000002,0.40000000000000002,0.20000000000000001,0,0,0,0.20000000000000001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"type\":\"bar\",\"frame\":\"500 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"At least as big as ours\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-7.8703703703703702,-7.4074074074074074,-6.9444444444444446,-6.4814814814814818,-6.0185185185185182,-5.5555555555555554,-5.0925925925925926,-4.6296296296296298,-4.166666666666667,-3.7037037037037037,-3.2407407407407409,-2.7777777777777777,-2.3148148148148149,-1.8518518518518519,-1.3888888888888888,-0.92592592592592593,-0.46296296296296297,0,0.46296296296296297,0.92592592592592593,1.3888888888888888,1.8518518518518519,2.3148148148148149,2.7777777777777777,3.2407407407407409,3.7037037037037037,4.166666666666667,4.6296296296296298,5.0925925925925926,5.5555555555555554,6.0185185185185182,6.4814814814814818,6.9444444444444446,7.4074074074074074,7.8703703703703702],\"y\":[1,1.2,1.6000000000000001,1.3999999999999999,1.8,2.2000000000000002,2.3999999999999999,1.3999999999999999,3.2000000000000002,3.7999999999999998,3.6000000000000001,3.7999999999999998,3.3999999999999999,4.4000000000000004,3.7999999999999998,3.2000000000000002,5,4.2000000000000002,5.7999999999999998,4.4000000000000004,4.5999999999999996,3.3999999999999999,2.2000000000000002,2.2000000000000002,4.2000000000000002,2.6000000000000001,1.3999999999999999,2,1.8,1.8,1.2,1.2,1.2,1.2,0.40000000000000002],\"type\":\"bar\",\"frame\":\"500 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"Smaller than ours\",\"marker\":{\"color\":\"rgba(189,189,189,1)\",\"line\":{\"color\":\"rgba(189,189,189,1)\"}},\"textfont\":{\"color\":\"rgba(189,189,189,1)\"},\"error_y\":{\"color\":\"rgba(189,189,189,1)\"},\"error_x\":{\"color\":\"rgba(189,189,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[13.5],\"y\":[7.2000000000000002],\"text\":\"7.0% had a gap<br>at least as big as ours\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"500 pretend studies\",\"textfont\":{\"size\":18,\"color\":\"#73000A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]},{\"name\":\"2,000 pretend studies\",\"data\":[{\"x\":[-20.833333333333332,-20.37037037037037,-19.907407407407408,-19.444444444444443,-18.981481481481481,-18.518518518518519,-18.055555555555557,-17.592592592592592,-17.12962962962963,-16.666666666666668,-16.203703703703702,-15.74074074074074,-15.277777777777779,-14.814814814814815,-14.351851851851851,-13.888888888888889,-13.425925925925926,-12.962962962962964,-12.5,-12.037037037037036,-11.574074074074074,-11.111111111111111,-10.648148148148149,-10.185185185185185,-9.7222222222222214,-9.2592592592592595,-8.7962962962962958,-8.3333333333333339,8.3333333333333339,8.7962962962962958,9.2592592592592595,9.7222222222222214,10.185185185185185,10.648148148148149,11.111111111111111,11.574074074074074,12.037037037037036,12.5,12.962962962962964,13.425925925925926,13.888888888888889,14.351851851851851,14.814814814814815,15.277777777777779,15.74074074074074,16.203703703703702,16.666666666666668,17.12962962962963,17.592592592592592,18.055555555555557,18.518518518518519,18.981481481481481,19.444444444444443,19.907407407407408,20.37037037037037,20.833333333333332],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.10000000000000001,0.050000000000000003,0.10000000000000001,0,0.050000000000000003,0,0.10000000000000001,0.14999999999999999,0.5,0.25,0.34999999999999998,0.69999999999999996,0.40000000000000002,0.65000000000000002,0.55000000000000004,0.25,0.34999999999999998,0.20000000000000001,0.29999999999999999,0.14999999999999999,0.050000000000000003,0,0.10000000000000001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"type\":\"bar\",\"frame\":\"2,000 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"At least as big as ours\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-7.8703703703703702,-7.4074074074074074,-6.9444444444444446,-6.4814814814814818,-6.0185185185185182,-5.5555555555555554,-5.0925925925925926,-4.6296296296296298,-4.166666666666667,-3.7037037037037037,-3.2407407407407409,-2.7777777777777777,-2.3148148148148149,-1.8518518518518519,-1.3888888888888888,-0.92592592592592593,-0.46296296296296297,0,0.46296296296296297,0.92592592592592593,1.3888888888888888,1.8518518518518519,2.3148148148148149,2.7777777777777777,3.2407407407407409,3.7037037037037037,4.166666666666667,4.6296296296296298,5.0925925925925926,5.5555555555555554,6.0185185185185182,6.4814814814814818,6.9444444444444446,7.4074074074074074,7.8703703703703702],\"y\":[0.84999999999999998,1.45,1.25,1.6499999999999999,1.25,1.75,2.5,1.8500000000000001,3,3.25,3.8999999999999999,3,3.7000000000000002,4.7000000000000002,4.2000000000000002,4.7000000000000002,4.9000000000000004,4.1500000000000004,4.0499999999999998,5.0499999999999998,3.6000000000000001,3.6000000000000001,3.0499999999999998,3.2000000000000002,3.1499999999999999,2.75,2.4500000000000002,2.75,1.8500000000000001,2.1499999999999999,0.94999999999999996,1.3500000000000001,0.80000000000000004,1.1000000000000001,0.75],\"type\":\"bar\",\"frame\":\"2,000 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"Smaller than ours\",\"marker\":{\"color\":\"rgba(189,189,189,1)\",\"line\":{\"color\":\"rgba(189,189,189,1)\"}},\"textfont\":{\"color\":\"rgba(189,189,189,1)\"},\"error_y\":{\"color\":\"rgba(189,189,189,1)\"},\"error_x\":{\"color\":\"rgba(189,189,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[13.5],\"y\":[7.2000000000000002],\"text\":\"5.3% had a gap<br>at least as big as ours\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2,000 pretend studies\",\"textfont\":{\"size\":18,\"color\":\"#73000A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]},{\"name\":\"10,000 pretend studies\",\"data\":[{\"x\":[-20.833333333333332,-20.37037037037037,-19.907407407407408,-19.444444444444443,-18.981481481481481,-18.518518518518519,-18.055555555555557,-17.592592592592592,-17.12962962962963,-16.666666666666668,-16.203703703703702,-15.74074074074074,-15.277777777777779,-14.814814814814815,-14.351851851851851,-13.888888888888889,-13.425925925925926,-12.962962962962964,-12.5,-12.037037037037036,-11.574074074074074,-11.111111111111111,-10.648148148148149,-10.185185185185185,-9.7222222222222214,-9.2592592592592595,-8.7962962962962958,-8.3333333333333339,8.3333333333333339,8.7962962962962958,9.2592592592592595,9.7222222222222214,10.185185185185185,10.648148148148149,11.111111111111111,11.574074074074074,12.037037037037036,12.5,12.962962962962964,13.425925925925926,13.888888888888889,14.351851851851851,14.814814814814815,15.277777777777779,15.74074074074074,16.203703703703702,16.666666666666668,17.12962962962963,17.592592592592592,18.055555555555557,18.518518518518519,18.981481481481481,19.444444444444443,19.907407407407408,20.37037037037037,20.833333333333332],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.01,0.050000000000000003,0.040000000000000001,0.02,0.02,0.080000000000000002,0.029999999999999999,0.22,0.23000000000000001,0.28999999999999998,0.29999999999999999,0.40999999999999998,0.54000000000000004,0.58999999999999997,0.68999999999999995,0.40000000000000002,0.33000000000000002,0.23999999999999999,0.20999999999999999,0.20999999999999999,0.17000000000000001,0.14000000000000001,0.029999999999999999,0.059999999999999998,0,0.02,0.02,0.01,0,0,0.01,0,0.02,0.01,0,0,0,0,0,0,0,0],\"type\":\"bar\",\"frame\":\"10,000 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"At least as big as ours\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-7.8703703703703702,-7.4074074074074074,-6.9444444444444446,-6.4814814814814818,-6.0185185185185182,-5.5555555555555554,-5.0925925925925926,-4.6296296296296298,-4.166666666666667,-3.7037037037037037,-3.2407407407407409,-2.7777777777777777,-2.3148148148148149,-1.8518518518518519,-1.3888888888888888,-0.92592592592592593,-0.46296296296296297,0,0.46296296296296297,0.92592592592592593,1.3888888888888888,1.8518518518518519,2.3148148148148149,2.7777777777777777,3.2407407407407409,3.7037037037037037,4.166666666666667,4.6296296296296298,5.0925925925925926,5.5555555555555554,6.0185185185185182,6.4814814814814818,6.9444444444444446,7.4074074074074074,7.8703703703703702],\"y\":[0.69999999999999996,0.92000000000000004,0.97999999999999998,1.4199999999999999,1.55,2.0099999999999998,1.97,2.3199999999999998,2.9399999999999999,3.1600000000000001,3.54,3.1899999999999999,3.79,4.2000000000000002,4.0800000000000001,4.5099999999999998,4.5999999999999996,4.0499999999999998,4.3899999999999997,4.4400000000000004,4.0499999999999998,3.7200000000000002,3.75,3.3199999999999998,3.3399999999999999,3,2.5800000000000001,2.4300000000000002,2.1800000000000002,1.8600000000000001,1.4199999999999999,1.3999999999999999,1.1699999999999999,0.80000000000000004,0.81999999999999995],\"type\":\"bar\",\"frame\":\"10,000 pretend studies\",\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"Smaller than ours\",\"marker\":{\"color\":\"rgba(189,189,189,1)\",\"line\":{\"color\":\"rgba(189,189,189,1)\"}},\"textfont\":{\"color\":\"rgba(189,189,189,1)\"},\"error_y\":{\"color\":\"rgba(189,189,189,1)\"},\"error_x\":{\"color\":\"rgba(189,189,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[13.5],\"y\":[7.2000000000000002],\"text\":\"5.4% had a gap<br>at least as big as ours\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"10,000 pretend studies\",\"textfont\":{\"size\":18,\"color\":\"#73000A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]}],\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## What the Picture Says\n\n- In a world where aid did nothing, about **5 studies in 100** still show a gap of 8.3 points or more, in one direction or the other. That is what p = 0.063 is measuring (`prop.test()` adds a small correction, so its number is a little bigger)\n- 5 in 100 is not *rare enough* to pass the 0.05 bar. So: fail to reject\n\n. . .\n\nA funder reading only the p-value writes \"no significant effect\" and cuts the program. Sound familiar? It is Session 6's recidivism trial, except this one is real. Now ask the other question.\n\n## Test: `bayes_prop_test()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(48, 66), n = c(216, 216))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  48 of 216 (22.2%)\ndata, group 2:  66 of 216 (30.6%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  22.5%         17.2% to 28.2%\ngroup 2                  30.7%         24.8% to 37.0%\ndifference (1 minus 2)   -8.2 points   -16.5 to 0.0 points\n\nProbability group 1 is higher than group 2: 0.03 \nProbability group 1 is lower than group 2:  0.97 \n```\n\n\n:::\n:::\n\n\n## Say It\n\n- **The sentence:** given these data, there is about a **97% probability** that men who got aid were re-arrested at a lower rate\n- **How big:** about **22 of every 100** men with aid were re-arrested, against about **31 of every 100** without: roughly 8 fewer re-arrests per 100 people released\n- **What this test cannot tell you:** whether the effect lasts past one year, or whether aid would work the same way today\n\n. . .\n\n**\"Not significant\" is not \"no effect.\"** Here the best estimate is an 8-point drop, and the data say it is very probably real.\n\n# Example 2 · Pretrial Release: Does a Job Get You Released? {background-color=\"#1B2A4A\"}\n\n## The Data\n\n- **5,226 arrests** by Toronto police for possessing small amounts of marijuana, 1997 to 2002\n- Outcome: **released** with a summons (instead of held for a bail hearing)\n- Group: was the person **employed**?\n- One row = one arrest\n\n## Count\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrests |> count(employed, released)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  employed released     n\n  <chr>    <chr>    <int>\n1 No       No         349\n2 No       Yes        766\n3 Yes      No         543\n4 Yes      Yes       3568\n```\n\n\n:::\n:::\n\n\n- **Employed:** 3,568 released out of 3,568 + 543 = **4,111** (86.8%)\n- **Not employed:** 766 out of 766 + 349 = **1,115** (68.7%)\n\n## Test: `prop.test()`\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nprop.test(x = c(3568, 766), n = c(4111, 1115))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(3568, 766) out of c(4111, 1115)\nX-squared = 201.54, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.1512300 0.2106097\nsample estimates:\n   prop 1    prop 2 \n0.8679153 0.6869955 \n```\n\n\n:::\n:::\n\n\n## Test: `bayes_prop_test()`\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(3568, 766), n = c(4111, 1115))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  3,568 of 4,111 (86.8%)\ndata, group 2:  766 of 1,115 (68.7%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  86.8%         85.7% to 87.8%\ngroup 2                  68.7%         65.9% to 71.4%\ndifference (1 minus 2)   18.1 points   15.2 to 21.0 points\n\nProbability group 1 is higher than group 2: more than 0.99 \nProbability group 1 is lower than group 2:  less than 0.01 \n```\n\n\n:::\n:::\n\n\n## Reading It\n\n- `prop.test()`: employed minus not employed, about **15 to 21 points**, p below 2.2e-16\n- `bayes_prop_test()`: **15.2 to 21.0 points**, and more than a 99% probability the employed rate is higher\n- With 5,000 cases, the two traditions land on the same range\n\n. . .\n\n**So a job gets you released?** Not so fast. What *else* is different about these two groups?\n\n## The Groups Differ in Other Ways\n\n`checks` counts how many police databases (prior arrests, convictions, parole, and so on) had the person's name in them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrests |> summarize(avg_checks = mean(checks), people = n(), .by = employed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  employed avg_checks people\n  <chr>         <dbl>  <int>\n1 Yes            1.44   4111\n2 No             2.35   1115\n```\n\n\n:::\n:::\n\n\nPeople without a job had **more of a record**, and a record is a reason to hold someone. The 18-point gap could be partly about records, not jobs.\n\n## Watch the Gap Shrink\n\nKeep narrowing to people with less and less of a record. Press Play.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-1d79ef83dbfb939825f7\" style=\"width:950px;height:470px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1d79ef83dbfb939825f7\">{\"x\":{\"visdat\":{\"c32f408d83b2\":[\"function () \",\"plotlyVisDat\"],\"c32fac13c3a\":[\"function () \",\"data\"],\"c32f1459095a\":[\"function () \",\"data\"]},\"cur_data\":\"c32f1459095a\",\"attrs\":{\"c32fac13c3a\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"type\":\"bar\",\"frame\":{},\"color\":{},\"colors\":[\"#73000A\",\"#6A8DBE\"],\"text\":{},\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"inherit\":true},\"c32f1459095a\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"text\":{},\"type\":\"scatter\",\"mode\":\"text\",\"frame\":{},\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"inherit\":true}},\"layout\":{\"width\":950,\"height\":470,\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"\",\"tickvals\":[1,2],\"ticktext\":[\"Employed\",\"Not employed\"],\"range\":[0.40000000000000002,2.6000000000000001],\"tickfont\":{\"size\":16}},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Released with a summons (%)\",\"range\":[0,110]},\"hovermode\":\"closest\",\"showlegend\":false,\"sliders\":[{\"currentvalue\":{\"prefix\":\"Who is included: \",\"xanchor\":\"right\",\"font\":{\"size\":16,\"color\":\"rgba(204,204,204,1)\"}},\"steps\":[{\"method\":\"animate\",\"args\":[[\"Everyone\"],{\"transition\":{\"duration\":800,\"easing\":\"linear\"},\"frame\":{\"duration\":1600,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"Everyone\",\"value\":\"Everyone\"},{\"method\":\"animate\",\"args\":[[\"In 3 or fewer databases\"],{\"transition\":{\"duration\":800,\"easing\":\"linear\"},\"frame\":{\"duration\":1600,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"In 3 or fewer databases\",\"value\":\"In 3 or fewer databases\"},{\"method\":\"animate\",\"args\":[[\"In 2 or fewer\"],{\"transition\":{\"duration\":800,\"easing\":\"linear\"},\"frame\":{\"duration\":1600,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"In 2 or fewer\",\"value\":\"In 2 or fewer\"},{\"method\":\"animate\",\"args\":[[\"In 1 or fewer\"],{\"transition\":{\"duration\":800,\"easing\":\"linear\"},\"frame\":{\"duration\":1600,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"In 1 or fewer\",\"value\":\"In 1 or fewer\"},{\"method\":\"animate\",\"args\":[[\"No record at all\"],{\"transition\":{\"duration\":800,\"easing\":\"linear\"},\"frame\":{\"duration\":1600,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"No record at all\",\"value\":\"No record at all\"}],\"visible\":true,\"pad\":{\"t\":40}}],\"updatemenus\":[{\"type\":\"buttons\",\"direction\":\"right\",\"showactive\":false,\"y\":0,\"x\":0,\"yanchor\":\"top\",\"xanchor\":\"right\",\"pad\":{\"t\":60,\"r\":5},\"buttons\":[{\"label\":\"Play\",\"method\":\"animate\",\"args\":[null,{\"fromcurrent\":true,\"mode\":\"immediate\",\"transition\":{\"duration\":800,\"easing\":\"linear\"},\"frame\":{\"duration\":1600,\"redraw\":false}}]}]}]},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displayModeBar\":false},\"data\":[{\"x\":[1],\"y\":[86.791534906348815],\"type\":\"bar\",\"frame\":\"Everyone\",\"text\":\"86.8%<br>(4,111 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Employed\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2],\"y\":[68.699551569506724],\"type\":\"bar\",\"frame\":\"Everyone\",\"text\":\"68.7%<br>(1,115 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Not employed\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5],\"y\":[104],\"text\":\"Gap: 18.1 points\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"Everyone\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"frames\":[{\"name\":\"Everyone\",\"data\":[{\"x\":[1],\"y\":[86.791534906348815],\"type\":\"bar\",\"frame\":\"Everyone\",\"text\":\"86.8%<br>(4,111 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Employed\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2],\"y\":[68.699551569506724],\"type\":\"bar\",\"frame\":\"Everyone\",\"text\":\"68.7%<br>(1,115 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Not employed\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5],\"y\":[104],\"text\":\"Gap: 18.1 points\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"Everyone\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]},{\"name\":\"In 3 or fewer databases\",\"data\":[{\"x\":[1],\"y\":[88.910344827586201],\"type\":\"bar\",\"frame\":\"In 3 or fewer databases\",\"text\":\"88.9%<br>(3,625 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Employed\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2],\"y\":[73.84428223844283],\"type\":\"bar\",\"frame\":\"In 3 or fewer databases\",\"text\":\"73.8%<br>(822 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Not employed\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5],\"y\":[104],\"text\":\"Gap: 15.1 points\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"In 3 or fewer databases\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]},{\"name\":\"In 2 or fewer\",\"data\":[{\"x\":[1],\"y\":[91.33064516129032],\"type\":\"bar\",\"frame\":\"In 2 or fewer\",\"text\":\"91.3%<br>(2,976 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Employed\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2],\"y\":[77.220077220077215],\"type\":\"bar\",\"frame\":\"In 2 or fewer\",\"text\":\"77.2%<br>(518 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Not employed\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5],\"y\":[104],\"text\":\"Gap: 14.1 points\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"In 2 or fewer\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]},{\"name\":\"In 1 or fewer\",\"data\":[{\"x\":[1],\"y\":[91.945739720220431],\"type\":\"bar\",\"frame\":\"In 1 or fewer\",\"text\":\"91.9%<br>(2,359 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Employed\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2],\"y\":[80.924855491329481],\"type\":\"bar\",\"frame\":\"In 1 or fewer\",\"text\":\"80.9%<br>(346 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Not employed\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5],\"y\":[104],\"text\":\"Gap: 11 points\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"In 1 or fewer\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]},{\"name\":\"No record at all\",\"data\":[{\"x\":[1],\"y\":[92.484848484848484],\"type\":\"bar\",\"frame\":\"No record at all\",\"text\":\"92.5%<br>(1,650 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Employed\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2],\"y\":[82.587064676616919],\"type\":\"bar\",\"frame\":\"No record at all\",\"text\":\"82.6%<br>(201 people)\",\"textposition\":\"inside\",\"insidetextfont\":{\"size\":16,\"color\":\"white\"},\"hoverinfo\":\"none\",\"showlegend\":false,\"name\":\"Not employed\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5],\"y\":[104],\"text\":\"Gap: 9.9 points\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"No record at all\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2]}],\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## Compare Like With Like\n\nNow do the last frame properly: keep only people with **no record at all** (`checks == 0`), and ask again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrests |> filter(checks == 0) |> count(employed, released)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  employed released     n\n  <chr>    <chr>    <int>\n1 No       No          35\n2 No       Yes        166\n3 Yes      No         124\n4 Yes      Yes       1526\n```\n\n\n:::\n:::\n\n\n- **Employed:** 1,526 of 1,650 released (92.5%)\n- **Not employed:** 166 of 201 (82.6%)\n\n## Test Again: `prop.test()`\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nprop.test(x = c(1526, 166), n = c(1650, 201))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(1526, 166) out of c(1650, 201)\nX-squared = 21.112, df = 1, p-value = 4.333e-06\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.04224058 0.15571509\nsample estimates:\n   prop 1    prop 2 \n0.9248485 0.8258706 \n```\n\n\n:::\n:::\n\n\n## Test Again: `bayes_prop_test()`\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(1526, 166), n = c(1650, 201))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  1,526 of 1,650 (92.5%)\ndata, group 2:  166 of 201 (82.6%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  92.4%         91.1% to 93.7%\ngroup 2                  82.3%         76.7% to 87.2%\ndifference (1 minus 2)   10.2 points   5.1 to 15.8 points\n\nProbability group 1 is higher than group 2: more than 0.99 \nProbability group 1 is lower than group 2:  less than 0.01 \n```\n\n\n:::\n:::\n\n\n## Say It\n\n- **Among people with clean records**, the employed were released about **10 points** more often: interval about 4 to 16 points (p = 0.000004), credible interval 5.1 to 15.8 points, and more than a 99% probability the employed rate is higher\n- The gap **shrank** from 18 points to 10 when we compared like with like, but it did **not disappear**\n- **What this cannot tell you:** whether some *other* difference (age, citizenship, where the arrest happened) explains the rest\n\n. . .\n\n`filter()` is the simplest honest move you have: **make the groups more alike, then ask again.**\n\n# Example 3 · Neighborhoods: Violence and Income {background-color=\"#73000A\"}\n\n## The Data\n\n- Chicago's **77 community areas** (our anchor data, 2025 crimes plus census numbers)\n- Group: the 38 areas with violent-crime rates above the city's median vs the other 39\n- Outcome: **median household income**, a number in dollars\n- One row = one **area**, not one person\n\n. . .\n\nThe outcome is a number, so: `t.test()`.\n\n## Describe\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas |>\n  summarize(avg_income = mean(median_income), areas = n(), .by = violence) |>\n  arrange(violence)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  violence      avg_income areas\n  <fct>              <dbl> <int>\n1 High violence     54355.    38\n2 Other areas       90088.    39\n```\n\n\n:::\n:::\n\n\n## See It\n\nEach dot is one community area. Press Play.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-24d2567802cb020e3839\" style=\"width:950px;height:470px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-24d2567802cb020e3839\">{\"x\":{\"visdat\":{\"c32f1f4aa94\":[\"function () \",\"plotlyVisDat\"],\"c32f65eadb8c\":[\"function () \",\"data\"],\"c32f1df3f89a\":[\"function () \",\"data\"],\"c32f7c4655d2\":[\"function () \",\"data\"],\"c32f6dac8dbb\":[\"function () \",\"data\"]},\"cur_data\":\"c32f6dac8dbb\",\"attrs\":{\"c32f65eadb8c\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":{},\"ids\":{},\"color\":{},\"colors\":[\"#73000A\",\"#6A8DBE\"],\"marker\":{\"size\":11,\"opacity\":0.80000000000000004},\"text\":{},\"hoverinfo\":\"text\",\"inherit\":true},\"c32f1df3f89a\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":{},\"ids\":{},\"marker\":{\"symbol\":\"line-ew-open\",\"size\":70,\"color\":\"#1B2A4A\",\"line\":{\"width\":4,\"color\":\"#1B2A4A\"}},\"showlegend\":false,\"hoverinfo\":\"none\",\"inherit\":true},\"c32f7c4655d2\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"text\":{},\"type\":\"scatter\",\"mode\":\"text\",\"frame\":{},\"textfont\":{\"size\":15,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"inherit\":true},\"c32f6dac8dbb\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"text\":{},\"type\":\"scatter\",\"mode\":\"text\",\"frame\":{},\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"inherit\":true}},\"layout\":{\"width\":950,\"height\":470,\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"\",\"range\":[0.40000000000000002,2.6000000000000001],\"tickvals\":[1,2],\"ticktext\":[\"High violence\",\"Other areas\"],\"tickfont\":{\"size\":16}},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Median household income\",\"tickprefix\":\"$\",\"range\":[0,190000]},\"legend\":{\"orientation\":\"h\",\"y\":1.0800000000000001},\"hovermode\":\"closest\",\"showlegend\":true,\"sliders\":[{\"currentvalue\":{\"prefix\":\"\",\"xanchor\":\"right\",\"font\":{\"size\":16,\"color\":\"rgba(204,204,204,1)\"}},\"steps\":[{\"method\":\"animate\",\"args\":[[\"All 77 areas\"],{\"transition\":{\"duration\":900,\"easing\":\"linear\"},\"frame\":{\"duration\":1800,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"All 77 areas\",\"value\":\"All 77 areas\"},{\"method\":\"animate\",\"args\":[[\"Split by violence\"],{\"transition\":{\"duration\":900,\"easing\":\"linear\"},\"frame\":{\"duration\":1800,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"Split by violence\",\"value\":\"Split by violence\"},{\"method\":\"animate\",\"args\":[[\"The two averages\"],{\"transition\":{\"duration\":900,\"easing\":\"linear\"},\"frame\":{\"duration\":1800,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"The two averages\",\"value\":\"The two averages\"}],\"visible\":true,\"pad\":{\"t\":40}}],\"updatemenus\":[{\"type\":\"buttons\",\"direction\":\"right\",\"showactive\":false,\"y\":0,\"x\":0,\"yanchor\":\"top\",\"xanchor\":\"right\",\"pad\":{\"t\":60,\"r\":5},\"buttons\":[{\"label\":\"Play\",\"method\":\"animate\",\"args\":[null,{\"fromcurrent\":true,\"mode\":\"immediate\",\"transition\":{\"duration\":900,\"easing\":\"linear\"},\"frame\":{\"duration\":1800,\"redraw\":false}}]}]}]},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displayModeBar\":false},\"data\":[{\"x\":[1.5852434957586228,1.6252607601787894,1.4437455120775848,1.5456569191720337,1.6157706860080361,1.4469500740058721,1.5509846333507449,1.3610301426518709,1.4874441291578113,1.3833345123846084,1.5546015878487378,1.5566770728863775,1.4852923806197942,1.6630183335766195,1.4558567123953252,1.3446314965188504,1.3737060988415033,1.5368057949654759,1.4148044825904071,1.6319889220688493,1.4253774526342751,1.3347541192453354,1.590352104306221,1.4916004111804069,1.3408737553004175,1.3830301252473145,1.454918769132346,1.6507958707865327,1.5688773033488541,1.5307861972600221,1.610421747174114,1.6570276147127152,1.4310303718317301,1.4371789184119552,1.381778475176543,1.501842933492735,1.4225114270579069,1.6555513394437731],\"y\":[70067,124208,56531,47533,38642,37170,111332,42221,80267,119471,45340,46865,27757,20240,50075,64746,35737,39802,44028,43564,57863,40515,46691,65978,48745,62475,39340,54430,17639,55497,53852,38273,31397,37962,47170,68129,70808,83116],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"All 77 areas\",\"ids\":[\"Uptown\",\"Near North Side\",\"Humboldt Park\",\"Austin\",\"West Garfield Park\",\"East Garfield Park\",\"Near West Side\",\"North Lawndale\",\"Lower West Side\",\"Loop\",\"Armour Square\",\"Douglas\",\"Oakland\",\"Fuller Park\",\"Grand Boulevard\",\"Kenwood\",\"Washington Park\",\"Woodlawn\",\"South Shore\",\"Chatham\",\"Avalon Park\",\"South Chicago\",\"Burnside\",\"Calumet Heights\",\"Roseland\",\"Pullman\",\"South Deering\",\"West Pullman\",\"Riverdale\",\"New City\",\"Chicago Lawn\",\"West Englewood\",\"Englewood\",\"Greater Grand Crossing\",\"Auburn Gresham\",\"Washington Heights\",\"Morgan Park\",\"Ohare\"],\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"size\":11,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"text\":[\"Uptown<br>$ 70,067\",\"Near North Side<br>$124,208\",\"Humboldt Park<br>$ 56,531\",\"Austin<br>$ 47,533\",\"West Garfield Park<br>$ 38,642\",\"East Garfield Park<br>$ 37,170\",\"Near West Side<br>$111,332\",\"North Lawndale<br>$ 42,221\",\"Lower West Side<br>$ 80,267\",\"Loop<br>$119,471\",\"Armour Square<br>$ 45,340\",\"Douglas<br>$ 46,865\",\"Oakland<br>$ 27,757\",\"Fuller Park<br>$ 20,240\",\"Grand Boulevard<br>$ 50,075\",\"Kenwood<br>$ 64,746\",\"Washington Park<br>$ 35,737\",\"Woodlawn<br>$ 39,802\",\"South Shore<br>$ 44,028\",\"Chatham<br>$ 43,564\",\"Avalon Park<br>$ 57,863\",\"South Chicago<br>$ 40,515\",\"Burnside<br>$ 46,691\",\"Calumet Heights<br>$ 65,978\",\"Roseland<br>$ 48,745\",\"Pullman<br>$ 62,475\",\"South Deering<br>$ 39,340\",\"West Pullman<br>$ 54,430\",\"Riverdale<br>$ 17,639\",\"New City<br>$ 55,497\",\"Chicago Lawn<br>$ 53,852\",\"West Englewood<br>$ 38,273\",\"Englewood<br>$ 31,397\",\"Greater Grand Crossing<br>$ 37,962\",\"Auburn Gresham<br>$ 47,170\",\"Washington Heights<br>$ 68,129\",\"Morgan Park<br>$ 70,808\",\"Ohare<br>$ 83,116\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"name\":\"High violence\",\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"line\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5602839561086148,1.5883749618753791,1.6554862488526851,1.6736057437956333,1.6112459718994796,1.6403066139947624,1.4213392326515168,1.3369657455850392,1.4624321477953344,1.6039004156179726,1.5194677747786045,1.5399841395579279,1.6664497165102512,1.5003168907575308,1.6070935722906143,1.6731413488090039,1.4831513819564135,1.5753663763962686,1.3894205709546805,1.6247364136297255,1.4270267256908118,1.4765514323394746,1.6397968856524676,1.4901344801019878,1.4191259116586297,1.6296191779151559,1.5314990463573486,1.4995609736815094,1.4909657582826912,1.5971987485885619,1.6633806337136776,1.6411678585689515,1.6161321791354566,1.369385524392128,1.617698880219832,1.6324320716969669,1.3482682557776571,1.526551957335323,1.3990662880986928],\"y\":[60916,70823,92490,145659,105499,137914,128066,110554,96870,131665,77173,86513,90361,91411,87411,72340,68284,70767,93916,107916,141208,54569,118170,69838,61942,65811,96218,67012,66071,79960,74610,75895,63702,78437,73123,82235,132097,115423,70549],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"All 77 areas\",\"ids\":[\"Rogers Park\",\"West Ridge\",\"Lincoln Square\",\"North Center\",\"Lake View\",\"Lincoln Park\",\"Edison Park\",\"Norwood Park\",\"Jefferson Park\",\"Forest Glen\",\"North Park\",\"Albany Park\",\"Portage Park\",\"Irving Park\",\"Dunning\",\"Montclare\",\"Belmont Cragin\",\"Hermosa\",\"Avondale\",\"Logan Square\",\"West Town\",\"South Lawndale\",\"Near South Side\",\"Hyde Park\",\"East Side\",\"Hegewisch\",\"Garfield Ridge\",\"Archer Heights\",\"Brighton Park\",\"Mckinley Park\",\"Bridgeport\",\"West Elsdon\",\"Gage Park\",\"Clearing\",\"West Lawn\",\"Ashburn\",\"Beverly\",\"Mount Greenwood\",\"Edgewater\"],\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"size\":11,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"text\":[\"Rogers Park<br>$ 60,916\",\"West Ridge<br>$ 70,823\",\"Lincoln Square<br>$ 92,490\",\"North Center<br>$145,659\",\"Lake View<br>$105,499\",\"Lincoln Park<br>$137,914\",\"Edison Park<br>$128,066\",\"Norwood Park<br>$110,554\",\"Jefferson Park<br>$ 96,870\",\"Forest Glen<br>$131,665\",\"North Park<br>$ 77,173\",\"Albany Park<br>$ 86,513\",\"Portage Park<br>$ 90,361\",\"Irving Park<br>$ 91,411\",\"Dunning<br>$ 87,411\",\"Montclare<br>$ 72,340\",\"Belmont Cragin<br>$ 68,284\",\"Hermosa<br>$ 70,767\",\"Avondale<br>$ 93,916\",\"Logan Square<br>$107,916\",\"West Town<br>$141,208\",\"South Lawndale<br>$ 54,569\",\"Near South Side<br>$118,170\",\"Hyde Park<br>$ 69,838\",\"East Side<br>$ 61,942\",\"Hegewisch<br>$ 65,811\",\"Garfield Ridge<br>$ 96,218\",\"Archer Heights<br>$ 67,012\",\"Brighton Park<br>$ 66,071\",\"Mckinley Park<br>$ 79,960\",\"Bridgeport<br>$ 74,610\",\"West Elsdon<br>$ 75,895\",\"Gage Park<br>$ 63,702\",\"Clearing<br>$ 78,437\",\"West Lawn<br>$ 73,123\",\"Ashburn<br>$ 82,235\",\"Beverly<br>$132,097\",\"Mount Greenwood<br>$115,423\",\"Edgewater<br>$ 70,549\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"name\":\"Other areas\",\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"line\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-1,-1],\"y\":[90087.641025641031,54354.631578947374],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"All 77 areas\",\"ids\":[\"Other areas\",\"High violence\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":70,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-0.66999999999999993,-0.66999999999999993],\"y\":[90087.641025641031,54354.631578947374],\"text\":[\"Average<br>$90,088\",\"Average<br>$54,355\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"All 77 areas\",\"textfont\":{\"size\":15,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-1],\"y\":[175000],\"text\":\"Gap: about $35,700\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"All 77 areas\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"frames\":[{\"name\":\"All 77 areas\",\"data\":[{\"x\":[1.5852434957586228,1.6252607601787894,1.4437455120775848,1.5456569191720337,1.6157706860080361,1.4469500740058721,1.5509846333507449,1.3610301426518709,1.4874441291578113,1.3833345123846084,1.5546015878487378,1.5566770728863775,1.4852923806197942,1.6630183335766195,1.4558567123953252,1.3446314965188504,1.3737060988415033,1.5368057949654759,1.4148044825904071,1.6319889220688493,1.4253774526342751,1.3347541192453354,1.590352104306221,1.4916004111804069,1.3408737553004175,1.3830301252473145,1.454918769132346,1.6507958707865327,1.5688773033488541,1.5307861972600221,1.610421747174114,1.6570276147127152,1.4310303718317301,1.4371789184119552,1.381778475176543,1.501842933492735,1.4225114270579069,1.6555513394437731],\"y\":[70067,124208,56531,47533,38642,37170,111332,42221,80267,119471,45340,46865,27757,20240,50075,64746,35737,39802,44028,43564,57863,40515,46691,65978,48745,62475,39340,54430,17639,55497,53852,38273,31397,37962,47170,68129,70808,83116],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"All 77 areas\",\"ids\":[\"Uptown\",\"Near North Side\",\"Humboldt Park\",\"Austin\",\"West Garfield Park\",\"East Garfield Park\",\"Near West Side\",\"North Lawndale\",\"Lower West Side\",\"Loop\",\"Armour Square\",\"Douglas\",\"Oakland\",\"Fuller Park\",\"Grand Boulevard\",\"Kenwood\",\"Washington Park\",\"Woodlawn\",\"South Shore\",\"Chatham\",\"Avalon Park\",\"South Chicago\",\"Burnside\",\"Calumet Heights\",\"Roseland\",\"Pullman\",\"South Deering\",\"West Pullman\",\"Riverdale\",\"New City\",\"Chicago Lawn\",\"West Englewood\",\"Englewood\",\"Greater Grand Crossing\",\"Auburn Gresham\",\"Washington Heights\",\"Morgan Park\",\"Ohare\"],\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"size\":11,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"text\":[\"Uptown<br>$ 70,067\",\"Near North Side<br>$124,208\",\"Humboldt Park<br>$ 56,531\",\"Austin<br>$ 47,533\",\"West Garfield Park<br>$ 38,642\",\"East Garfield Park<br>$ 37,170\",\"Near West Side<br>$111,332\",\"North Lawndale<br>$ 42,221\",\"Lower West Side<br>$ 80,267\",\"Loop<br>$119,471\",\"Armour Square<br>$ 45,340\",\"Douglas<br>$ 46,865\",\"Oakland<br>$ 27,757\",\"Fuller Park<br>$ 20,240\",\"Grand Boulevard<br>$ 50,075\",\"Kenwood<br>$ 64,746\",\"Washington Park<br>$ 35,737\",\"Woodlawn<br>$ 39,802\",\"South Shore<br>$ 44,028\",\"Chatham<br>$ 43,564\",\"Avalon Park<br>$ 57,863\",\"South Chicago<br>$ 40,515\",\"Burnside<br>$ 46,691\",\"Calumet Heights<br>$ 65,978\",\"Roseland<br>$ 48,745\",\"Pullman<br>$ 62,475\",\"South Deering<br>$ 39,340\",\"West Pullman<br>$ 54,430\",\"Riverdale<br>$ 17,639\",\"New City<br>$ 55,497\",\"Chicago Lawn<br>$ 53,852\",\"West Englewood<br>$ 38,273\",\"Englewood<br>$ 31,397\",\"Greater Grand Crossing<br>$ 37,962\",\"Auburn Gresham<br>$ 47,170\",\"Washington Heights<br>$ 68,129\",\"Morgan Park<br>$ 70,808\",\"Ohare<br>$ 83,116\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"name\":\"High violence\",\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"line\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5602839561086148,1.5883749618753791,1.6554862488526851,1.6736057437956333,1.6112459718994796,1.6403066139947624,1.4213392326515168,1.3369657455850392,1.4624321477953344,1.6039004156179726,1.5194677747786045,1.5399841395579279,1.6664497165102512,1.5003168907575308,1.6070935722906143,1.6731413488090039,1.4831513819564135,1.5753663763962686,1.3894205709546805,1.6247364136297255,1.4270267256908118,1.4765514323394746,1.6397968856524676,1.4901344801019878,1.4191259116586297,1.6296191779151559,1.5314990463573486,1.4995609736815094,1.4909657582826912,1.5971987485885619,1.6633806337136776,1.6411678585689515,1.6161321791354566,1.369385524392128,1.617698880219832,1.6324320716969669,1.3482682557776571,1.526551957335323,1.3990662880986928],\"y\":[60916,70823,92490,145659,105499,137914,128066,110554,96870,131665,77173,86513,90361,91411,87411,72340,68284,70767,93916,107916,141208,54569,118170,69838,61942,65811,96218,67012,66071,79960,74610,75895,63702,78437,73123,82235,132097,115423,70549],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"All 77 areas\",\"ids\":[\"Rogers Park\",\"West Ridge\",\"Lincoln Square\",\"North Center\",\"Lake View\",\"Lincoln Park\",\"Edison Park\",\"Norwood Park\",\"Jefferson Park\",\"Forest Glen\",\"North Park\",\"Albany Park\",\"Portage Park\",\"Irving Park\",\"Dunning\",\"Montclare\",\"Belmont Cragin\",\"Hermosa\",\"Avondale\",\"Logan Square\",\"West Town\",\"South Lawndale\",\"Near South Side\",\"Hyde Park\",\"East Side\",\"Hegewisch\",\"Garfield Ridge\",\"Archer Heights\",\"Brighton Park\",\"Mckinley Park\",\"Bridgeport\",\"West Elsdon\",\"Gage Park\",\"Clearing\",\"West Lawn\",\"Ashburn\",\"Beverly\",\"Mount Greenwood\",\"Edgewater\"],\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"size\":11,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"text\":[\"Rogers Park<br>$ 60,916\",\"West Ridge<br>$ 70,823\",\"Lincoln Square<br>$ 92,490\",\"North Center<br>$145,659\",\"Lake View<br>$105,499\",\"Lincoln Park<br>$137,914\",\"Edison Park<br>$128,066\",\"Norwood Park<br>$110,554\",\"Jefferson Park<br>$ 96,870\",\"Forest Glen<br>$131,665\",\"North Park<br>$ 77,173\",\"Albany Park<br>$ 86,513\",\"Portage Park<br>$ 90,361\",\"Irving Park<br>$ 91,411\",\"Dunning<br>$ 87,411\",\"Montclare<br>$ 72,340\",\"Belmont Cragin<br>$ 68,284\",\"Hermosa<br>$ 70,767\",\"Avondale<br>$ 93,916\",\"Logan Square<br>$107,916\",\"West Town<br>$141,208\",\"South Lawndale<br>$ 54,569\",\"Near South Side<br>$118,170\",\"Hyde Park<br>$ 69,838\",\"East Side<br>$ 61,942\",\"Hegewisch<br>$ 65,811\",\"Garfield Ridge<br>$ 96,218\",\"Archer Heights<br>$ 67,012\",\"Brighton Park<br>$ 66,071\",\"Mckinley Park<br>$ 79,960\",\"Bridgeport<br>$ 74,610\",\"West Elsdon<br>$ 75,895\",\"Gage Park<br>$ 63,702\",\"Clearing<br>$ 78,437\",\"West Lawn<br>$ 73,123\",\"Ashburn<br>$ 82,235\",\"Beverly<br>$132,097\",\"Mount Greenwood<br>$115,423\",\"Edgewater<br>$ 70,549\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"name\":\"Other areas\",\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"line\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-1,-1],\"y\":[90087.641025641031,54354.631578947374],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"All 77 areas\",\"ids\":[\"Other areas\",\"High violence\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":70,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-0.66999999999999993,-0.66999999999999993],\"y\":[90087.641025641031,54354.631578947374],\"text\":[\"Average<br>$90,088\",\"Average<br>$54,355\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"All 77 areas\",\"textfont\":{\"size\":15,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-1],\"y\":[175000],\"text\":\"Gap: about $35,700\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"All 77 areas\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3,4]},{\"name\":\"Split by violence\",\"data\":[{\"x\":[1.0852434957586228,1.1252607601787894,0.94374551207758484,1.0456569191720337,1.1157706860080361,0.94695007400587206,1.0509846333507449,0.86103014265187083,0.98744412915781143,0.88333451238460836,1.0546015878487378,1.0566770728863775,0.98529238061979418,1.1630183335766195,0.95585671239532533,0.84463149651885039,0.8737060988415033,1.0368057949654759,0.91480448259040714,1.1319889220688493,0.92537745263427496,0.83475411924533549,1.090352104306221,0.99160041118040676,0.84087375530041752,0.88303012524731461,0.95491876913234597,1.1507958707865327,1.0688773033488541,1.0307861972600221,1.110421747174114,1.1570276147127152,0.93103037183172999,0.93717891841195522,0.88177847517654295,1.001842933492735,0.92251142705790701,1.1555513394437731],\"y\":[70067,124208,56531,47533,38642,37170,111332,42221,80267,119471,45340,46865,27757,20240,50075,64746,35737,39802,44028,43564,57863,40515,46691,65978,48745,62475,39340,54430,17639,55497,53852,38273,31397,37962,47170,68129,70808,83116],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"Split by violence\",\"ids\":[\"Uptown\",\"Near North Side\",\"Humboldt Park\",\"Austin\",\"West Garfield Park\",\"East Garfield Park\",\"Near West Side\",\"North Lawndale\",\"Lower West Side\",\"Loop\",\"Armour Square\",\"Douglas\",\"Oakland\",\"Fuller Park\",\"Grand Boulevard\",\"Kenwood\",\"Washington Park\",\"Woodlawn\",\"South Shore\",\"Chatham\",\"Avalon Park\",\"South Chicago\",\"Burnside\",\"Calumet Heights\",\"Roseland\",\"Pullman\",\"South Deering\",\"West Pullman\",\"Riverdale\",\"New City\",\"Chicago Lawn\",\"West Englewood\",\"Englewood\",\"Greater Grand Crossing\",\"Auburn Gresham\",\"Washington Heights\",\"Morgan Park\",\"Ohare\"],\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"size\":11,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"text\":[\"Uptown<br>$ 70,067\",\"Near North Side<br>$124,208\",\"Humboldt Park<br>$ 56,531\",\"Austin<br>$ 47,533\",\"West Garfield Park<br>$ 38,642\",\"East Garfield Park<br>$ 37,170\",\"Near West Side<br>$111,332\",\"North Lawndale<br>$ 42,221\",\"Lower West Side<br>$ 80,267\",\"Loop<br>$119,471\",\"Armour Square<br>$ 45,340\",\"Douglas<br>$ 46,865\",\"Oakland<br>$ 27,757\",\"Fuller Park<br>$ 20,240\",\"Grand Boulevard<br>$ 50,075\",\"Kenwood<br>$ 64,746\",\"Washington Park<br>$ 35,737\",\"Woodlawn<br>$ 39,802\",\"South Shore<br>$ 44,028\",\"Chatham<br>$ 43,564\",\"Avalon Park<br>$ 57,863\",\"South Chicago<br>$ 40,515\",\"Burnside<br>$ 46,691\",\"Calumet Heights<br>$ 65,978\",\"Roseland<br>$ 48,745\",\"Pullman<br>$ 62,475\",\"South Deering<br>$ 39,340\",\"West Pullman<br>$ 54,430\",\"Riverdale<br>$ 17,639\",\"New City<br>$ 55,497\",\"Chicago Lawn<br>$ 53,852\",\"West Englewood<br>$ 38,273\",\"Englewood<br>$ 31,397\",\"Greater Grand Crossing<br>$ 37,962\",\"Auburn Gresham<br>$ 47,170\",\"Washington Heights<br>$ 68,129\",\"Morgan Park<br>$ 70,808\",\"Ohare<br>$ 83,116\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"name\":\"High violence\",\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"line\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2.0602839561086146,2.0883749618753793,2.1554862488526849,2.1736057437956333,2.1112459718994798,2.1403066139947624,1.9213392326515168,1.8369657455850392,1.9624321477953344,2.1039004156179728,2.0194677747786045,2.0399841395579279,2.1664497165102512,2.0003168907575311,2.1070935722906143,2.1731413488090037,1.9831513819564135,2.0753663763962686,1.8894205709546805,2.1247364136297255,1.9270267256908118,1.9765514323394746,2.1397968856524674,1.9901344801019878,1.9191259116586297,2.1296191779151559,2.0314990463573483,1.9995609736815094,1.9909657582826912,2.0971987485885619,2.1633806337136776,2.1411678585689513,2.1161321791354566,1.869385524392128,2.117698880219832,2.1324320716969667,1.8482682557776571,2.026551957335323,1.8990662880986928],\"y\":[60916,70823,92490,145659,105499,137914,128066,110554,96870,131665,77173,86513,90361,91411,87411,72340,68284,70767,93916,107916,141208,54569,118170,69838,61942,65811,96218,67012,66071,79960,74610,75895,63702,78437,73123,82235,132097,115423,70549],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"Split by violence\",\"ids\":[\"Rogers Park\",\"West Ridge\",\"Lincoln Square\",\"North Center\",\"Lake View\",\"Lincoln Park\",\"Edison Park\",\"Norwood Park\",\"Jefferson Park\",\"Forest Glen\",\"North Park\",\"Albany Park\",\"Portage Park\",\"Irving Park\",\"Dunning\",\"Montclare\",\"Belmont Cragin\",\"Hermosa\",\"Avondale\",\"Logan Square\",\"West Town\",\"South Lawndale\",\"Near South Side\",\"Hyde Park\",\"East Side\",\"Hegewisch\",\"Garfield Ridge\",\"Archer Heights\",\"Brighton Park\",\"Mckinley Park\",\"Bridgeport\",\"West Elsdon\",\"Gage Park\",\"Clearing\",\"West Lawn\",\"Ashburn\",\"Beverly\",\"Mount Greenwood\",\"Edgewater\"],\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"size\":11,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"text\":[\"Rogers Park<br>$ 60,916\",\"West Ridge<br>$ 70,823\",\"Lincoln Square<br>$ 92,490\",\"North Center<br>$145,659\",\"Lake View<br>$105,499\",\"Lincoln Park<br>$137,914\",\"Edison Park<br>$128,066\",\"Norwood Park<br>$110,554\",\"Jefferson Park<br>$ 96,870\",\"Forest Glen<br>$131,665\",\"North Park<br>$ 77,173\",\"Albany Park<br>$ 86,513\",\"Portage Park<br>$ 90,361\",\"Irving Park<br>$ 91,411\",\"Dunning<br>$ 87,411\",\"Montclare<br>$ 72,340\",\"Belmont Cragin<br>$ 68,284\",\"Hermosa<br>$ 70,767\",\"Avondale<br>$ 93,916\",\"Logan Square<br>$107,916\",\"West Town<br>$141,208\",\"South Lawndale<br>$ 54,569\",\"Near South Side<br>$118,170\",\"Hyde Park<br>$ 69,838\",\"East Side<br>$ 61,942\",\"Hegewisch<br>$ 65,811\",\"Garfield Ridge<br>$ 96,218\",\"Archer Heights<br>$ 67,012\",\"Brighton Park<br>$ 66,071\",\"Mckinley Park<br>$ 79,960\",\"Bridgeport<br>$ 74,610\",\"West Elsdon<br>$ 75,895\",\"Gage Park<br>$ 63,702\",\"Clearing<br>$ 78,437\",\"West Lawn<br>$ 73,123\",\"Ashburn<br>$ 82,235\",\"Beverly<br>$132,097\",\"Mount Greenwood<br>$115,423\",\"Edgewater<br>$ 70,549\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"name\":\"Other areas\",\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"line\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-1,-1],\"y\":[90087.641025641031,54354.631578947374],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"Split by violence\",\"ids\":[\"Other areas\",\"High violence\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":70,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-0.66999999999999993,-0.66999999999999993],\"y\":[90087.641025641031,54354.631578947374],\"text\":[\"Average<br>$90,088\",\"Average<br>$54,355\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"Split by violence\",\"textfont\":{\"size\":15,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[-1],\"y\":[175000],\"text\":\"Gap: about $35,700\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"Split by violence\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3,4]},{\"name\":\"The two averages\",\"data\":[{\"x\":[1.0852434957586228,1.1252607601787894,0.94374551207758484,1.0456569191720337,1.1157706860080361,0.94695007400587206,1.0509846333507449,0.86103014265187083,0.98744412915781143,0.88333451238460836,1.0546015878487378,1.0566770728863775,0.98529238061979418,1.1630183335766195,0.95585671239532533,0.84463149651885039,0.8737060988415033,1.0368057949654759,0.91480448259040714,1.1319889220688493,0.92537745263427496,0.83475411924533549,1.090352104306221,0.99160041118040676,0.84087375530041752,0.88303012524731461,0.95491876913234597,1.1507958707865327,1.0688773033488541,1.0307861972600221,1.110421747174114,1.1570276147127152,0.93103037183172999,0.93717891841195522,0.88177847517654295,1.001842933492735,0.92251142705790701,1.1555513394437731],\"y\":[70067,124208,56531,47533,38642,37170,111332,42221,80267,119471,45340,46865,27757,20240,50075,64746,35737,39802,44028,43564,57863,40515,46691,65978,48745,62475,39340,54430,17639,55497,53852,38273,31397,37962,47170,68129,70808,83116],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"The two averages\",\"ids\":[\"Uptown\",\"Near North Side\",\"Humboldt Park\",\"Austin\",\"West Garfield Park\",\"East Garfield Park\",\"Near West Side\",\"North Lawndale\",\"Lower West Side\",\"Loop\",\"Armour Square\",\"Douglas\",\"Oakland\",\"Fuller Park\",\"Grand Boulevard\",\"Kenwood\",\"Washington Park\",\"Woodlawn\",\"South Shore\",\"Chatham\",\"Avalon Park\",\"South Chicago\",\"Burnside\",\"Calumet Heights\",\"Roseland\",\"Pullman\",\"South Deering\",\"West Pullman\",\"Riverdale\",\"New City\",\"Chicago Lawn\",\"West Englewood\",\"Englewood\",\"Greater Grand Crossing\",\"Auburn Gresham\",\"Washington Heights\",\"Morgan Park\",\"Ohare\"],\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"size\":11,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"text\":[\"Uptown<br>$ 70,067\",\"Near North Side<br>$124,208\",\"Humboldt Park<br>$ 56,531\",\"Austin<br>$ 47,533\",\"West Garfield Park<br>$ 38,642\",\"East Garfield Park<br>$ 37,170\",\"Near West Side<br>$111,332\",\"North Lawndale<br>$ 42,221\",\"Lower West Side<br>$ 80,267\",\"Loop<br>$119,471\",\"Armour Square<br>$ 45,340\",\"Douglas<br>$ 46,865\",\"Oakland<br>$ 27,757\",\"Fuller Park<br>$ 20,240\",\"Grand Boulevard<br>$ 50,075\",\"Kenwood<br>$ 64,746\",\"Washington Park<br>$ 35,737\",\"Woodlawn<br>$ 39,802\",\"South Shore<br>$ 44,028\",\"Chatham<br>$ 43,564\",\"Avalon Park<br>$ 57,863\",\"South Chicago<br>$ 40,515\",\"Burnside<br>$ 46,691\",\"Calumet Heights<br>$ 65,978\",\"Roseland<br>$ 48,745\",\"Pullman<br>$ 62,475\",\"South Deering<br>$ 39,340\",\"West Pullman<br>$ 54,430\",\"Riverdale<br>$ 17,639\",\"New City<br>$ 55,497\",\"Chicago Lawn<br>$ 53,852\",\"West Englewood<br>$ 38,273\",\"Englewood<br>$ 31,397\",\"Greater Grand Crossing<br>$ 37,962\",\"Auburn Gresham<br>$ 47,170\",\"Washington Heights<br>$ 68,129\",\"Morgan Park<br>$ 70,808\",\"Ohare<br>$ 83,116\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"name\":\"High violence\",\"textfont\":{\"color\":\"rgba(115,0,10,1)\"},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"line\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2.0602839561086146,2.0883749618753793,2.1554862488526849,2.1736057437956333,2.1112459718994798,2.1403066139947624,1.9213392326515168,1.8369657455850392,1.9624321477953344,2.1039004156179728,2.0194677747786045,2.0399841395579279,2.1664497165102512,2.0003168907575311,2.1070935722906143,2.1731413488090037,1.9831513819564135,2.0753663763962686,1.8894205709546805,2.1247364136297255,1.9270267256908118,1.9765514323394746,2.1397968856524674,1.9901344801019878,1.9191259116586297,2.1296191779151559,2.0314990463573483,1.9995609736815094,1.9909657582826912,2.0971987485885619,2.1633806337136776,2.1411678585689513,2.1161321791354566,1.869385524392128,2.117698880219832,2.1324320716969667,1.8482682557776571,2.026551957335323,1.8990662880986928],\"y\":[60916,70823,92490,145659,105499,137914,128066,110554,96870,131665,77173,86513,90361,91411,87411,72340,68284,70767,93916,107916,141208,54569,118170,69838,61942,65811,96218,67012,66071,79960,74610,75895,63702,78437,73123,82235,132097,115423,70549],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"The two averages\",\"ids\":[\"Rogers Park\",\"West Ridge\",\"Lincoln Square\",\"North Center\",\"Lake View\",\"Lincoln Park\",\"Edison Park\",\"Norwood Park\",\"Jefferson Park\",\"Forest Glen\",\"North Park\",\"Albany Park\",\"Portage Park\",\"Irving Park\",\"Dunning\",\"Montclare\",\"Belmont Cragin\",\"Hermosa\",\"Avondale\",\"Logan Square\",\"West Town\",\"South Lawndale\",\"Near South Side\",\"Hyde Park\",\"East Side\",\"Hegewisch\",\"Garfield Ridge\",\"Archer Heights\",\"Brighton Park\",\"Mckinley Park\",\"Bridgeport\",\"West Elsdon\",\"Gage Park\",\"Clearing\",\"West Lawn\",\"Ashburn\",\"Beverly\",\"Mount Greenwood\",\"Edgewater\"],\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"size\":11,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"text\":[\"Rogers Park<br>$ 60,916\",\"West Ridge<br>$ 70,823\",\"Lincoln Square<br>$ 92,490\",\"North Center<br>$145,659\",\"Lake View<br>$105,499\",\"Lincoln Park<br>$137,914\",\"Edison Park<br>$128,066\",\"Norwood Park<br>$110,554\",\"Jefferson Park<br>$ 96,870\",\"Forest Glen<br>$131,665\",\"North Park<br>$ 77,173\",\"Albany Park<br>$ 86,513\",\"Portage Park<br>$ 90,361\",\"Irving Park<br>$ 91,411\",\"Dunning<br>$ 87,411\",\"Montclare<br>$ 72,340\",\"Belmont Cragin<br>$ 68,284\",\"Hermosa<br>$ 70,767\",\"Avondale<br>$ 93,916\",\"Logan Square<br>$107,916\",\"West Town<br>$141,208\",\"South Lawndale<br>$ 54,569\",\"Near South Side<br>$118,170\",\"Hyde Park<br>$ 69,838\",\"East Side<br>$ 61,942\",\"Hegewisch<br>$ 65,811\",\"Garfield Ridge<br>$ 96,218\",\"Archer Heights<br>$ 67,012\",\"Brighton Park<br>$ 66,071\",\"Mckinley Park<br>$ 79,960\",\"Bridgeport<br>$ 74,610\",\"West Elsdon<br>$ 75,895\",\"Gage Park<br>$ 63,702\",\"Clearing<br>$ 78,437\",\"West Lawn<br>$ 73,123\",\"Ashburn<br>$ 82,235\",\"Beverly<br>$132,097\",\"Mount Greenwood<br>$115,423\",\"Edgewater<br>$ 70,549\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"name\":\"Other areas\",\"textfont\":{\"color\":\"rgba(106,141,190,1)\"},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"line\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2,1],\"y\":[90087.641025641031,54354.631578947374],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"The two averages\",\"ids\":[\"Other areas\",\"High violence\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":70,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2.3300000000000001,1.3300000000000001],\"y\":[90087.641025641031,54354.631578947374],\"text\":[\"Average<br>$90,088\",\"Average<br>$54,355\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"The two averages\",\"textfont\":{\"size\":15,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[1.5],\"y\":[175000],\"text\":\"Gap: about $35,700\",\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"The two averages\",\"textfont\":{\"size\":20,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"marker\":{\"color\":\"rgba(148,103,189,1)\",\"line\":{\"color\":\"rgba(148,103,189,1)\"}},\"error_y\":{\"color\":\"rgba(148,103,189,1)\"},\"error_x\":{\"color\":\"rgba(148,103,189,1)\"},\"line\":{\"color\":\"rgba(148,103,189,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3,4]}],\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## Test\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nt.test(median_income ~ violence, data = areas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  median_income by violence\nt = -6.3561, df = 74.959, p-value = 1.458e-08\nalternative hypothesis: true difference in means between group High violence and group Other areas is not equal to 0\n95 percent confidence interval:\n -46932.44 -24533.58\nsample estimates:\nmean in group High violence   mean in group Other areas \n                   54354.63                    90087.64 \n```\n\n\n:::\n:::\n\n\n## Say It {.smaller}\n\n- High-violence areas minus other areas: about **$25,000 to $47,000 lower** median income (averages $54,355 vs $90,088), p = 0.00000001\n- **How big:** the typical household in a high-violence area earns roughly **$36,000 a year less**. The unit is dollars because the column is dollars\n- **What this cannot tell you:**\n  - which way it runs (does poverty breed violence, or does violence drive out income?) or what else explains both\n  - anything about individual *people*. Each row is an area. \"People with less income commit more violence\" is a claim about people, and these data are not about people\n\n# Example 4 · Use of Force: Body Cameras Over Time {background-color=\"#1B2A4A\"}\n\n## The Data\n\n- The *Washington Post*'s database of **every person shot and killed by on-duty police** in the U.S., 2015 to 2024: **10,430 people**\n- `body_camera` is TRUE when news or police reports said a body camera recorded the incident\n- One row = one person killed\n\n. . .\n\n**Question:** after 2020's wave of police reform, did body camera footage exist more often? Group: 2015 to 2019 vs 2020 to 2024. Yes/no outcome.\n\n## Count\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshootings |> count(period, body_camera)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  period       body_camera     n\n  <chr>        <lgl>       <int>\n1 2015 to 2019 FALSE        4329\n2 2015 to 2019 TRUE          594\n3 2020 to 2024 FALSE        4302\n4 2020 to 2024 TRUE         1205\n```\n\n\n:::\n:::\n\n\n- **2020 to 2024:** 1,205 of 1,205 + 4,302 = **5,507** (21.9%)\n- **2015 to 2019:** 594 of 594 + 4,329 = **4,923** (12.1%)\n\n## Year by Year\n\nThe share of fatal shootings with a body camera reported, one year at a time. Press Play.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-c5e778ffb43a74098bb7\" style=\"width:950px;height:470px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c5e778ffb43a74098bb7\">{\"x\":{\"visdat\":{\"c32f6c05298e\":[\"function () \",\"plotlyVisDat\"],\"c32f46eb6109\":[\"function () \",\"data\"],\"c32f72fba3f\":[\"function () \",\"data\"],\"c32f4e6c81c8\":[\"function () \",\"data\"]},\"cur_data\":\"c32f4e6c81c8\",\"attrs\":{\"c32f46eb6109\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"type\":\"bar\",\"frame\":{},\"color\":{},\"colors\":[\"#6A8DBE\",\"#73000A\"],\"text\":{},\"textposition\":\"outside\",\"textfont\":{\"size\":14},\"hoverinfo\":\"none\",\"inherit\":true},\"c32f72fba3f\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":{},\"ids\":{},\"marker\":{\"symbol\":\"line-ew-open\",\"size\":230,\"color\":\"#1B2A4A\",\"line\":{\"width\":4,\"color\":\"#1B2A4A\"}},\"showlegend\":false,\"hoverinfo\":\"none\",\"inherit\":true},\"c32f4e6c81c8\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"text\":{},\"type\":\"scatter\",\"mode\":\"text\",\"frame\":{},\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":\"none\",\"inherit\":true}},\"layout\":{\"width\":950,\"height\":470,\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"\",\"range\":[2014.4000000000001,2024.5999999999999],\"dtick\":1},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Body camera reported (%)\",\"range\":[0,38]},\"legend\":{\"orientation\":\"h\",\"y\":1.0800000000000001},\"hovermode\":\"closest\",\"showlegend\":true,\"sliders\":[{\"currentvalue\":{\"prefix\":\"\",\"xanchor\":\"right\",\"font\":{\"size\":16,\"color\":\"rgba(204,204,204,1)\"}},\"steps\":[{\"method\":\"animate\",\"args\":[[\"2015\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2015\",\"value\":\"2015\"},{\"method\":\"animate\",\"args\":[[\"2016\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2016\",\"value\":\"2016\"},{\"method\":\"animate\",\"args\":[[\"2017\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2017\",\"value\":\"2017\"},{\"method\":\"animate\",\"args\":[[\"2018\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2018\",\"value\":\"2018\"},{\"method\":\"animate\",\"args\":[[\"2019\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2019\",\"value\":\"2019\"},{\"method\":\"animate\",\"args\":[[\"2020\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2020\",\"value\":\"2020\"},{\"method\":\"animate\",\"args\":[[\"2021\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2021\",\"value\":\"2021\"},{\"method\":\"animate\",\"args\":[[\"2022\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2022\",\"value\":\"2022\"},{\"method\":\"animate\",\"args\":[[\"2023\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2023\",\"value\":\"2023\"},{\"method\":\"animate\",\"args\":[[\"2024\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"2024\",\"value\":\"2024\"},{\"method\":\"animate\",\"args\":[[\"The two periods\"],{\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false},\"mode\":\"immediate\"}],\"label\":\"The two periods\",\"value\":\"The two periods\"}],\"visible\":true,\"pad\":{\"t\":40}}],\"updatemenus\":[{\"type\":\"buttons\",\"direction\":\"right\",\"showactive\":false,\"y\":0,\"x\":0,\"yanchor\":\"top\",\"xanchor\":\"right\",\"pad\":{\"t\":60,\"r\":5},\"buttons\":[{\"label\":\"Play\",\"method\":\"animate\",\"args\":[null,{\"fromcurrent\":true,\"mode\":\"immediate\",\"transition\":{\"duration\":400,\"easing\":\"linear\"},\"frame\":{\"duration\":900,\"redraw\":false}}]}]}]},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displayModeBar\":false},\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,0,0,0,0],\"type\":\"bar\",\"frame\":\"2015\",\"text\":[\"8%\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[0,0,0,0,0],\"type\":\"bar\",\"frame\":\"2015\",\"text\":[\"\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2015\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2015\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"frames\":[{\"name\":\"2015\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,0,0,0,0],\"type\":\"bar\",\"frame\":\"2015\",\"text\":[\"8%\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[0,0,0,0,0],\"type\":\"bar\",\"frame\":\"2015\",\"text\":[\"\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2015\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2015\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2016\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,0,0,0],\"type\":\"bar\",\"frame\":\"2016\",\"text\":[\"8%\",\"15%\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[0,0,0,0,0],\"type\":\"bar\",\"frame\":\"2016\",\"text\":[\"\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2016\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2016\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2017\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,0,0],\"type\":\"bar\",\"frame\":\"2017\",\"text\":[\"8%\",\"15%\",\"11%\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[0,0,0,0,0],\"type\":\"bar\",\"frame\":\"2017\",\"text\":[\"\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2017\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2017\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2018\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,12.600806451612904,0],\"type\":\"bar\",\"frame\":\"2018\",\"text\":[\"8%\",\"15%\",\"11%\",\"13%\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[0,0,0,0,0],\"type\":\"bar\",\"frame\":\"2018\",\"text\":[\"\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2018\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2018\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2019\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,12.600806451612904,13.897280966767372],\"type\":\"bar\",\"frame\":\"2019\",\"text\":[\"8%\",\"15%\",\"11%\",\"13%\",\"14%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[0,0,0,0,0],\"type\":\"bar\",\"frame\":\"2019\",\"text\":[\"\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2019\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2019\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2020\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,12.600806451612904,13.897280966767372],\"type\":\"bar\",\"frame\":\"2020\",\"text\":[\"8%\",\"15%\",\"11%\",\"13%\",\"14%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[17.72771792360431,0,0,0,0],\"type\":\"bar\",\"frame\":\"2020\",\"text\":[\"18%\",\"\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2020\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2020\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2021\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,12.600806451612904,13.897280966767372],\"type\":\"bar\",\"frame\":\"2021\",\"text\":[\"8%\",\"15%\",\"11%\",\"13%\",\"14%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[17.72771792360431,21.428571428571427,0,0,0],\"type\":\"bar\",\"frame\":\"2021\",\"text\":[\"18%\",\"21%\",\"\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2021\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2021\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2022\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,12.600806451612904,13.897280966767372],\"type\":\"bar\",\"frame\":\"2022\",\"text\":[\"8%\",\"15%\",\"11%\",\"13%\",\"14%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[17.72771792360431,21.428571428571427,19.051959890610757,0,0],\"type\":\"bar\",\"frame\":\"2022\",\"text\":[\"18%\",\"21%\",\"19%\",\"\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2022\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2022\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2023\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,12.600806451612904,13.897280966767372],\"type\":\"bar\",\"frame\":\"2023\",\"text\":[\"8%\",\"15%\",\"11%\",\"13%\",\"14%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[17.72771792360431,21.428571428571427,19.051959890610757,30.326460481099655,0],\"type\":\"bar\",\"frame\":\"2023\",\"text\":[\"18%\",\"21%\",\"19%\",\"30%\",\"\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2023\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2023\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"2024\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,12.600806451612904,13.897280966767372],\"type\":\"bar\",\"frame\":\"2024\",\"text\":[\"8%\",\"15%\",\"11%\",\"13%\",\"14%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[17.72771792360431,21.428571428571427,19.051959890610757,30.326460481099655,20.170212765957444],\"type\":\"bar\",\"frame\":\"2024\",\"text\":[\"18%\",\"21%\",\"19%\",\"30%\",\"20%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"2024\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2010,2010],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"2024\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]},{\"name\":\"The two periods\",\"data\":[{\"x\":[2015,2016,2017,2018,2019],\"y\":[7.5376884422110546,15.119916579770596,11.280487804878049,12.600806451612904,13.897280966767372],\"type\":\"bar\",\"frame\":\"The two periods\",\"text\":[\"8%\",\"15%\",\"11%\",\"13%\",\"14%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(106,141,190,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2015 to 2019\",\"marker\":{\"color\":\"rgba(106,141,190,1)\",\"line\":{\"color\":\"rgba(106,141,190,1)\"}},\"error_y\":{\"color\":\"rgba(106,141,190,1)\"},\"error_x\":{\"color\":\"rgba(106,141,190,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2020,2021,2022,2023,2024],\"y\":[17.72771792360431,21.428571428571427,19.051959890610757,30.326460481099655,20.170212765957444],\"type\":\"bar\",\"frame\":\"The two periods\",\"text\":[\"18%\",\"21%\",\"19%\",\"30%\",\"20%\"],\"textposition\":[\"outside\",\"outside\",\"outside\",\"outside\",\"outside\"],\"textfont\":{\"color\":\"rgba(115,0,10,1)\",\"size\":14},\"hoverinfo\":[\"none\",\"none\",\"none\",\"none\",\"none\"],\"name\":\"2020 to 2024\",\"marker\":{\"color\":\"rgba(115,0,10,1)\",\"line\":{\"color\":\"rgba(115,0,10,1)\"}},\"error_y\":{\"color\":\"rgba(115,0,10,1)\"},\"error_x\":{\"color\":\"rgba(115,0,10,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2017,2022],\"y\":[12.065813528336381,21.881242055565643],\"type\":\"scatter\",\"mode\":\"markers\",\"frame\":\"The two periods\",\"ids\":[\"2015 to 2019\",\"2020 to 2024\"],\"marker\":{\"color\":\"#1B2A4A\",\"symbol\":\"line-ew-open\",\"size\":230,\"line\":{\"color\":\"#1B2A4A\",\"width\":4}},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"line\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true},{\"x\":[2017,2022],\"y\":[19.5,35],\"text\":[\"2015 to 2019: 12.1%\",\"2020 to 2024: 21.9%\"],\"type\":\"scatter\",\"mode\":\"text\",\"frame\":\"The two periods\",\"textfont\":{\"size\":17,\"color\":\"#1B2A4A\"},\"showlegend\":false,\"hoverinfo\":[\"none\",\"none\"],\"marker\":{\"color\":\"rgba(214,39,40,1)\",\"line\":{\"color\":\"rgba(214,39,40,1)\"}},\"error_y\":{\"color\":\"rgba(214,39,40,1)\"},\"error_x\":{\"color\":\"rgba(214,39,40,1)\"},\"line\":{\"color\":\"rgba(214,39,40,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"visible\":true}],\"traces\":[0,1,2,3]}],\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## What the Picture Says\n\n- The rise is real, but **not smooth**: 2023 hit 30%, and 2024 fell back to 20%\n- Comparing two five-year periods averages over those bumps. That is a choice, and an honest write-up says so\n\n. . .\n\nNow the two tests on the two periods.\n\n## Test: `prop.test()`\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nprop.test(x = c(1205, 594), n = c(5507, 4923))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(1205, 594) out of c(5507, 4923)\nX-squared = 174.76, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.08374831 0.11256026\nsample estimates:\n   prop 1    prop 2 \n0.2188124 0.1206581 \n```\n\n\n:::\n:::\n\n\n## Test: `bayes_prop_test()`\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(1205, 594), n = c(5507, 4923))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  1,205 of 5,507 (21.9%)\ndata, group 2:  594 of 4,923 (12.1%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  21.9%         20.8% to 23.0%\ngroup 2                  12.1%         11.2% to 13.0%\ndifference (1 minus 2)   9.8 points    8.4 to 11.2 points\n\nProbability group 1 is higher than group 2: more than 0.99 \nProbability group 1 is lower than group 2:  less than 0.01 \n```\n\n\n:::\n:::\n\n\n## Say It\n\n- `prop.test()`: about **8 to 11 points** higher after 2020, p below 2.2e-16. `bayes_prop_test()`: 8.4 to 11.2 points, more than a 99% probability the later rate is higher\n- **How big:** about **12 in 100** fatal shootings had known camera footage before 2020, and about **22 in 100** after. Close to doubling, yet still fewer than 1 in 4\n- **What this cannot tell you:** whether cameras changed anything about the shootings, or how many cameras *existed* but were never reported\n\n. . .\n\nWith 10,430 cases, the p-value was never in doubt. **The size is the whole story.**\n\n## Four Questions, One Recipe {.smaller}\n\n| | Question | Test | Answer | The lesson |\n|---|---|---|---|---|\n| **Reentry** | Does aid lower re-arrest? | `prop.test()` + Bayes | 22% vs 31%; p = 0.063; 97% probably lower | \"Not significant\" is not \"no effect\" |\n| **Pretrial** | Does a job get you released? | `prop.test()` + Bayes, then again after `filter()` | 18 points; 10 among clean records | Groups differ in other ways. Compare like with like |\n| **Neighborhoods** | Lower income where violence is high? | `t.test()` | $25k to $47k lower | Size in real units. Areas are not people |\n| **Use of force** | More body camera footage after 2020? | `prop.test()` + Bayes | 12% to 22% | Huge n: the p-value adds nothing; the size is the story |\n\n# Now You: Lab 7 {background-color=\"#73000A\"}\n\n## Lab 7\n\nTwo more real questions, same recipe, and this time you write the code ([lab page](../labs/lab-07-workshop.qmd)):\n\n- **With me:** a pretrial risk-assessment tool. Do people it labels High risk get re-arrested more often than people it labels Low risk?\n- **Your Turn:** Minneapolis police stops. Are people searched more often in suspicious-person stops than in traffic stops? Then a `t.test()` on the *Post* data\n\nSubmit your Your Turn script to Canvas before you leave.\n\n# What's Out There {background-color=\"#1B2A4A\"}\n\n## Your Final Project Needs a Dataset\n\nThe **[Final-Project Data Options](../project-data.qmd)** page lists real criminal justice datasets that load with **one line of R**:\n\n- Reentry, pretrial release, police stops, police shootings, risk assessment, public opinion about crime and police, state crime rates\n- Each one: what a row is, how many rows, the key variables, a starter question, and whether it has the numeric variables regression will need (Sessions 10 and 11)\n\n## What's Eligible\n\n- Everything on that page is eligible, **including the reentry, pretrial, police stops, shootings, and risk-assessment data from tonight**, as long as your question goes beyond what we did in class\n- **Not eligible:** our course datasets, which includes the **Chicago** data from Example 3, plus crash, officers, prisoners, and the rest\n\n## Two Ways to Load a Dataset\n\nOur course copy, the way you have loaded everything all semester:\n\n```r\narrests <- read_csv(\"https://smourtgos.github.io/crju705/data/toronto-arrests.csv\")\n```\n\nThe original, from an R package (install once, then load it each time):\n\n```r\ninstall.packages(\"carData\")   # once, in the console\nlibrary(carData)\ndata(Arrests)\n```\n\nSame data either way. Use whichever you like.\n\n## How to Size Up a Dataset in Five Minutes\n\n1. **What is one row?** A person? An arrest? A neighborhood? A year?\n2. **How many rows?** Hundreds is plenty; millions is a headache\n3. **What are the variables?** `glimpse()` tells you names and types\n4. **Anything strange?** 999s, negative ages, lots of `NA`: `summary()` finds them\n5. **Could it answer a question you care about?** Name the groups, or the variables\n\n## Homework 7 and Next Week\n\n- **Homework 7:** explore **two** datasets (from the menu, or one you found and cleared with me), then **choose one** for your final project. Due **Sunday by 11:59 pm** (posted on the [Session 7 page](../weeks/week-07.qmd))\n- No reading this week\n- **Session 8:** more worked examples like tonight's, and review for the midterm\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}