{
  "hash": "a4c0dece73c701e7593bfe41d915bc77",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Practice Problems · Session 12\"\nsubtitle: \"Logistic regression: odds, odds ratios, and predicted probabilities\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Ungraded self-checks.** Work each problem in your own R session *before* clicking the solution. Homework 12 is your own final-project model, so this bank is where you drill the logistic workflow on neutral data first — if you can do these cold, Checkpoint 4 (and the presentation questions afterward) will feel routine.\n:::\n\n\n\nProblems that use data need only this setup — the 20,000 Alaska crashes from Labs 5, 7, 8, and 12. In lab you modeled *whether the driver was intoxicated*; here the question flips: **does an intoxicated driver make a crash more likely to injure someone?** The outcome is a flag we build ourselves:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)   # only if you re-fit Problem 6's model yourself\n\ncrashes <- read_csv(\"https://smourtgos.github.io/crju705/data/crash-ak.csv\") |>\n  mutate(injury = as.integer(injuries > 0))   # 1 = someone was injured\n```\n:::\n\n\n## Problem 1 · Odds ↔ probability, three conversions\n\nNo data, just the ladder. (a) About **12%** of released defendants in a jurisdiction fail to appear: convert that probability to **odds**, and phrase it as \"1 to ___.\" (b) A program director says the odds a participant completes supervision are **4**: what *probability* is that? (c) A logistic model reports a baseline **log-odds of −1.99**: use `plogis()` to recover the probability — and notice where you've landed.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n0.12 / (1 - 0.12)   # (a) probability -> odds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1363636\n```\n\n\n:::\n\n```{.r .cell-code}\n4 / (4 + 1)         # (b) odds -> probability\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8\n```\n\n\n:::\n\n```{.r .cell-code}\nplogis(-1.99)       # (c) log-odds -> probability\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1202569\n```\n\n\n:::\n\n```{.r .cell-code}\nqlogis(0.12)        # and back up the ladder: probability -> log-odds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.99243\n```\n\n\n:::\n:::\n\n\n(a) Odds ≈ **0.136** — about 1 to 7.3: for every failure to appear, roughly seven appearances. (b) Odds of 4 (\"four to one\") is a probability of **0.80**. (c) `plogis(-1.99)` ≈ **0.12** — you've climbed back down to (a), because −1.99 is exactly `qlogis(0.12)`. Probability, odds, and log-odds are three readouts of one quantity; `plogis()` and `qlogis()` move you up and down the ladder, and the model does its arithmetic on the log-odds rung.\n:::\n\n## Problem 2 · Fit it: `glm(family = binomial)`\n\nFirst check the base rate of `injury` (you built the flag in Setup — always know the baseline you're modeling). Then fit `injury ~ intox_any + num_vehicles`. What do the two coefficients say *before* any transformation — and what scale are they on?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(crashes$injury)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.478\n```\n\n\n:::\n\n```{.r .cell-code}\ninjury_model <- glm(injury ~ intox_any + num_vehicles,\n                    data = crashes, family = binomial)\nsummary(injury_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = injury ~ intox_any + num_vehicles, family = binomial, \n    data = crashes)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -0.56478    0.06601  -8.556  < 2e-16 ***\nintox_any     0.64840    0.05465  11.865  < 2e-16 ***\nnum_vehicles  0.23736    0.03570   6.649 2.95e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 27687  on 19999  degrees of freedom\nResidual deviance: 27496  on 19997  degrees of freedom\nAIC: 27502\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nBaseline: about **48%** of crashes injure someone — this outcome is nowhere near rare, which will matter in Problem 5. Both coefficients are positive with tiny p-values: intoxication (+0.65) and each additional vehicle (+0.24) raise the **log-odds** of an injury crash. Sign and significance are readable right off this table; the *sizes* are not, because nobody thinks in log-odds — which is exactly why the next move is always `exp()`.\n:::\n\n## Problem 3 · Exponentiate: log-odds → odds ratios\n\nTurn the model into odds ratios with confidence intervals (`exp(cbind(OR = coef(...), confint(...)))`). Interpret each predictor in one sentence with the holding-constant clause — and state what the \"no effect\" value is for an odds ratio.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(OR = coef(injury_model), confint(injury_model)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   OR     2.5 %    97.5 %\n(Intercept)  0.568485 0.4994012 0.6468929\nintox_any    1.912470 1.7188884 2.1296050\nnum_vehicles 1.267901 1.1823033 1.3598917\n```\n\n\n:::\n:::\n\n\n- **Intoxication: OR ≈ 1.91** [1.72, 2.13] — a crash involving an intoxicated driver has about **91% higher odds** of injuring someone than a sober-driver crash, holding the number of vehicles constant.\n- **Vehicles: OR ≈ 1.27** [1.18, 1.36] — each additional vehicle multiplies the odds of injury by about 1.27. (In these data `num_vehicles` is only ever 1 or 2, so this is really the two-vehicle vs. single-vehicle contrast — check your predictor's actual values before narrating a \"per unit\" story.)\n- For odds ratios the no-effect value is **1**, not 0 — both intervals sit clearly above it.\n\n`exp()` converts every log-odds coefficient into a multiplier on the *odds*, and 1 is the number that means \"nothing happening.\"\n:::\n\n## Problem 4 · From effects to cases: predicted probabilities\n\nOdds ratios describe effects; a briefing needs *cases*. Use `predict(type = \"response\")` for two crash profiles — **(i)** sober driver, single vehicle; **(ii)** intoxicated driver, two vehicles — then reproduce profile (i) by hand with `plogis()` and the coefficients. How do the two probabilities compare with the 48% baseline?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofiles <- tibble(intox_any = c(0, 1), num_vehicles = c(1, 2))\n\nprofiles |>\n  mutate(p_injury = predict(injury_model, newdata = profiles, type = \"response\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  intox_any num_vehicles p_injury\n      <dbl>        <dbl>    <dbl>\n1         0            1    0.419\n2         1            2    0.636\n```\n\n\n:::\n\n```{.r .cell-code}\nb <- coef(injury_model)\nunname(plogis(b[1] + b[2] * 0 + b[3] * 1))   # profile (i), by hand\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4188691\n```\n\n\n:::\n:::\n\n\nA sober single-vehicle crash carries about a **42%** predicted probability of injury; an intoxicated two-vehicle crash about **64%** — one below the 48% baseline, one well above it. And the by-hand version demystifies the machinery: plug the profile into the log-odds equation, then `plogis()` climbs down the ladder to a probability. Report odds ratios for *effects* and predicted probabilities for *cases* — decision-makers think in probabilities, and `predict()` is how you hand them one.\n:::\n\n## Problem 5 · Audit the memo (the classic mistake)\n\nA draft memo about your model reads:\n\n> \"The odds ratio for intoxication is 1.91, so a crash with an intoxicated driver is **91% more likely to injure someone**. Since about 48% of crashes cause injury, that works out to roughly **0.48 × 1.91 ≈ 92% of intoxicated-driver crashes causing injury**.\"\n\nBoth bolded claims are wrong — and the second one should already smell wrong (what would an OR of 2.5 imply?). Name each error, then compute what the model *actually* says happens to a two-vehicle crash's injury probability when the driver is intoxicated, working through the odds.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_sober <- unname(plogis(b[1] + b[3] * 2))          # sober, two vehicles\np_intox <- unname(plogis(b[1] + b[2] + b[3] * 2))   # intoxicated, two vehicles\nc(p_sober = p_sober, p_intox = p_intox)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p_sober   p_intox \n0.4775014 0.6360684 \n```\n\n\n:::\n\n```{.r .cell-code}\nodds_sober <- p_sober / (1 - p_sober)\nodds_intox <- p_intox / (1 - p_intox)\nc(odds_sober = odds_sober, odds_intox = odds_intox, ratio = odds_intox / odds_sober)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nodds_sober odds_intox      ratio \n 0.9138807  1.7477694  1.9124700 \n```\n\n\n:::\n:::\n\n\n**Error 1:** \"91% more likely\" reads the odds ratio as a *probability* ratio. An OR of 1.91 multiplies the **odds** by 1.91 — nothing else. **Error 2:** multiplying the baseline probability by the OR (0.48 × 1.91) is arithmetic on the wrong scale; with an OR of 2.5 it would \"predict\" 120% of crashes causing injury, which is the tell that probabilities don't multiply this way.\n\nWhat actually happens: the sober two-vehicle probability of .48 converts to odds of ≈ 0.91; multiply *those* by 1.91 to get odds ≈ 1.75; convert back and the probability is ≈ **.64**. The real change is 48% → 64% — about 16 percentage points, a ~33% relative rise, nowhere near 91%. When the baseline probability is small, odds and probability move almost together; at a baseline near 50%, they part company badly — so multiply odds, never probabilities, and use `predict()` when you want the probability itself.\n:::\n\n## Problem 6 · Reading a `brms` bernoulli output\n\nA classmate fits the Bayesian twin of your Problem 2 model and sends you the summary below. **Without fitting anything**, answer: (a) what do `Family: bernoulli` and `Links: mu = logit` tell you about the scale of the `Estimate` column? (b) Exponentiate the `intox_any` estimate and both CI bounds — what odds ratio and 95% credible interval do you get, and does it agree with `glm()`'s? (c) Are there signs of sampling trouble? (d) Write the one Bayesian sentence about intoxication you're now licensed to say.\n\n```\n Family: bernoulli\n  Links: mu = logit\nFormula: injury ~ intox_any + num_vehicles\n   Data: crashes (Number of observations: 20000)\n  Draws: 2 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 2000\n\nRegression Coefficients:\n             Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept       -0.56      0.07    -0.70    -0.44 1.00     2056     1378\nintox_any        0.65      0.06     0.54     0.76 1.00     1795     1378\nnum_vehicles     0.24      0.04     0.17     0.31 1.00     2081     1415\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n*(Want to reproduce it? The code is below — but budget for the \"Compiling Stan program...\" pause plus a couple of minutes of sampling on 20,000 rows. The reading practice is the point; the refit is optional.)*\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninjury_bayes <- brm(injury ~ intox_any + num_vehicles, data = crashes,\n                    family = bernoulli(),\n                    chains = 2, iter = 2000, seed = 705, refresh = 0)\nsummary(injury_bayes)\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(c(estimate = 0.65, ci_low = 0.54, ci_high = 0.76))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nestimate   ci_low  ci_high \n1.915541 1.716007 2.138276 \n```\n\n\n:::\n:::\n\n\n(a) `bernoulli` is `brms`'s name for a 0/1 outcome and `logit` is the link — so the `Estimate` column is in **log-odds**, exactly like `glm()`'s coefficient table, and needs exponentiating before anyone speaks.\n\n(b) exp(0.65) ≈ **1.92**, with a 95% credible interval of roughly **[1.72, 2.14]** — landing almost exactly on `glm()`'s OR of 1.91 [1.72, 2.13], as expected with default priors and 20,000 crashes.\n\n(c) No trouble: **Rhat = 1.00** on every row and effective sample sizes in the 1,400–2,100 range mean the two chains agreed and mixed well.\n\n(d) \"Given the data and priors, there is a 95% probability that intoxication multiplies a crash's odds of injuring someone by between roughly 1.7 and 2.1, holding the number of vehicles constant.\" Same machinery as every `brm()` you've run — bernoulli is just `family = binomial` in Bayesian clothing, and the coefficients only become English after `exp()`.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}