{
  "hash": "e9117b4e27b30abe51f2fa145c36e9e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Practice Problems · Session 6\"\nsubtitle: \"Hypothesis testing, both ways: p-values, posteriors, and credible intervals\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Ungraded self-checks.** Work each problem in your own R session *before* clicking the solution. These use different questions and numbers than the homework on purpose — if you can run *and read* both traditions cold here, Homework 6 will feel routine.\n:::\n\n\n\nAll problems that use data need only:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nsource(\"https://smourtgos.github.io/crju705/R/bayes.R\")   # gives you bayes_prop_test()\ncrimes <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-crimes-2025.csv\")\n```\n:::\n\n\n## Problem 1 · What a p-value promises\n\nA study compares case-processing times in two courts and reports **p = 0.03**. Three readings:\n\n> (a) \"There is a 3% chance the courts truly process cases at the same speed.\"\n>\n> (b) \"If the courts truly processed cases at the same speed, a gap this large or larger would show up in about 3% of studies like this one.\"\n>\n> (c) \"There is a 97% chance the courts differ.\"\n\nPick the correct one. Then verify the machinery's actual promise by simulation: run 5,000 t-tests comparing two groups drawn from the *same* normal distribution (n = 40 each) and compute how often p < .05.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)\nnull_world_p <- replicate(5000, t.test(rnorm(40), rnorm(40))$p.value)\nmean(null_world_p < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0552\n```\n\n\n:::\n:::\n\n\n**(b)** — and only (b). A **p-value** is $P(\\text{data this extreme} \\mid H_0)$, a statement about *data under an assumed null*; (a) and (c) both flip it into $P(H \\mid \\text{data})$, which frequentism never computes (that flip is Bayes' job, and it costs a prior). The simulation shows the promise being kept: in a world where the null is *true*, about 5.5% of our 5,000 tests came up \"significant\" — right around the advertised 5% false-alarm rate, and no better.\n:::\n\n## Problem 2 · Which finding is bigger?\n\nTwo studies of body-worn cameras and citizen complaints. **Study A** (50,000 police stops): 20.8% of stops without a camera drew a complaint vs 20.0% with one, **p = 0.03**. **Study B** (40 stops): 70% vs 40%, **p = 0.11**. A headline writer says A \"found an effect\" and B \"found nothing.\" Check both with `prop.test()` (A: 5,200 of 25,000 vs 5,000 of 25,000; B: 14 of 20 vs 8 of 20), then say what the headline gets wrong.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(5200, 5000), n = c(25000, 25000))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(5200, 5000) out of c(25000, 25000)\nX-squared = 4.8775, df = 1, p-value = 0.02721\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.0008961201 0.0151038799\nsample estimates:\nprop 1 prop 2 \n 0.208  0.200 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(x = c(14, 8), n = c(20, 20))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(14, 8) out of c(20, 20)\nX-squared = 2.5253, df = 1, p-value = 0.112\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.0439946  0.6439946\nsample estimates:\nprop 1 prop 2 \n   0.7    0.4 \n```\n\n\n:::\n:::\n\n\nStudy A's gap is **0.8 of a percentage point** (interval about 0.1 to 1.5 points): real, probably, and tiny. Study B's gap is **30 points**, with an interval from about 4 points lower to 64 points higher: possibly huge, possibly nothing, because 40 stops cannot tell. The p-value measures how *detectable* a gap is, and detectability is mostly sample size. It never measures how *big* the gap is. \"Significant\" is not \"large,\" and \"not significant\" is not \"nothing.\"\n:::\n\n## Problem 3 · Both tests, one new question\n\nAre crimes on the **street** more likely to end in an arrest than crimes inside a **residence**? Filter `crimes` to `location_description %in% c(\"STREET\", \"RESIDENCE\")`, count arrests by location, and run **both** tests with STREET first: `prop.test()` and `bayes_prop_test()`.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrimes |>\n  filter(location_description %in% c(\"STREET\", \"RESIDENCE\")) |>\n  count(location_description, arrest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  location_description arrest     n\n  <chr>                <lgl>  <int>\n1 RESIDENCE            FALSE   3248\n2 RESIDENCE            TRUE     339\n3 STREET               FALSE   6533\n4 STREET               TRUE    1374\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(x = c(1374, 339), n = c(7907, 3587))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(1374, 339) out of c(7907, 3587)\nX-squared = 121.61, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.06635519 0.09216907\nsample estimates:\n    prop 1     prop 2 \n0.17377008 0.09450795 \n```\n\n\n:::\n\n```{.r .cell-code}\nbayes_prop_test(x = c(1374, 339), n = c(7907, 3587))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  1,374 of 7,907 (17.4%)\ndata, group 2:  339 of 3,587 (9.5%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  17.4%         16.6% to 18.2%\ngroup 2                  9.5%          8.5% to 10.5%\ndifference (1 minus 2)   7.9 points    6.6 to 9.2 points\n\nProbability group 1 is higher than group 2: more than 0.99 \nProbability group 1 is lower than group 2:  less than 0.01 \n```\n\n\n:::\n:::\n\n\nStreet: 1,374 arrests out of 1,374 + 6,533 = 7,907 (17.4%). Residence: 339 out of 339 + 3,248 = 3,587 (9.5%). STREET was typed first, so both outputs read STREET minus RESIDENCE. `prop.test()`: 95% confidence interval about **6.6 to 9.2 points**, `p-value < 2.2e-16`, reject the null. `bayes_prop_test()`: 95% credible interval about **6.6 to 9.2 points**. With more than 11,000 incidents the two traditions return the same range; the data drown out the know-nothing prior.\n:::\n\n## Problem 4 · How big, in real units\n\nBoth tests just endorsed the street-vs-residence difference. Before anyone acts on it, say **how big** it is in words a city council member would follow, with no p-value and no interval. Then say what the tests *cannot* tell the council.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\nAbout **17 of every 100** street incidents end in an arrest, against about **10 of every 100** incidents inside a residence: roughly 8 more arrests per 100 incidents. That is the size. Whether 8 per 100 is big enough to matter, and *why* the gap exists (different crime types happen on the street, officers are already nearby, witnesses are present), no test can say. Both tests tell you the gap is almost surely real. Neither tells you it is important, and neither tells you what causes it.\n:::\n\n## Problem 5 · The sentence you're licensed to say\n\nSession 5 forbade \"there's a 95% probability the truth is in this interval.\" Using Problem 3's two outputs, write (1) the honest sentence for the **confidence** interval and (2) the sentence the **credible** interval lets you say. The numbers are the same. What is different?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n(1) Confidence interval: *\"We estimate the street arrest rate is 7.9 points higher (95% CI: 6.6 to 9.2); the method that built this interval captures the truth 95% of the time.\"* The 95% belongs to the *procedure*.\n\n(2) Credible interval: *\"Given these data, there is a 95% probability that the true difference is between 6.6 and 9.2 points.\"* The 95% belongs to *this interval*. That is the sentence everyone wants to say about a confidence interval, and only the Bayesian output licenses it, at the price of a stated prior (here, \"know nothing\").\n:::\n\n## Problem 6 · The diversion-program trial\n\nA county pilots a **pretrial diversion program** to reduce failures to appear (FTA). Historically, about **25%** of defendants fail to appear, and the county trusts that figure about as much as having watched **12 defendants: 3 failed to appear, 9 showed up**. That is `prior = c(3, 9)`. The pilot randomizes 120 defendants: of **60 diversion clients, 12** fail to appear; of **60 controls, 19** do.\n\n1. Run the frequentist test, diversion first: `prop.test(x = c(12, 19), n = c(60, 60))`.\n2. Run `bayes_prop_test()` with the same numbers and the prior.\n3. Write one sentence for the county board.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(12, 19), n = c(60, 60))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(12, 19) out of c(60, 60)\nX-squared = 1.5658, df = 1, p-value = 0.2108\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.28856877  0.05523544\nsample estimates:\n   prop 1    prop 2 \n0.2000000 0.3166667 \n```\n\n\n:::\n\n```{.r .cell-code}\nbayes_prop_test(x = c(12, 19), n = c(60, 60), prior = c(3, 9))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  12 of 60 (20.0%)\ndata, group 2:  19 of 60 (31.7%)\nprior:          3 yes, 9 no (about 25%, worth 12 cases), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  20.8%         12.3% to 30.9%\ngroup 2                  30.6%         20.5% to 41.6%\ndifference (1 minus 2)   -9.7 points   -23.7 to 4.4 points\n\nProbability group 1 is higher than group 2: 0.09 \nProbability group 1 is lower than group 2:  0.91 \n```\n\n\n:::\n:::\n\n\nThe frequentist verdict: p ≈ 0.21 — an 11.7-point gap like this could plausibly arise if the program did nothing, so \"not significant,\" and the grant report probably ends there. The Bayesian output tells the board what it actually asked: given prior experience and the pilot data, there is about a **91% probability the diversion program lowers failure-to-appear** (credible interval for the difference about −24 to +4 points). One board-ready sentence: *\"The pilot is too small for a definitive verdict, but the evidence currently runs about 9-to-1 that diversion reduces failures to appear.\"* Both statements are true of the same data — they answer different questions, and only one of them helps a decision-maker.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}