{
  "hash": "e7a945f6f40629ceb6f3439fc715853b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo Walkthrough · Session 11\"\nsubtitle: \"Multiple linear regression — least squares, R², 'holding constant,' and the Bayesian version\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this page is.** The Session 11 lecture demos, written down step by step. Run the setup chunk once, then work top to bottom — every demo reproduces exactly what happened on screen. Use this page to catch up after a missed class, or to re-run the lecture at your own pace.\n:::\n\n## What you'll build\n\n1. A hand-rolled ruler for \"best line\" — `SSR()` — tested on three candidate lines, the proof that `lm()` beats every hand-picked guess, and the check that one-predictor R² is just Session 10's correlation, squared\n2. The best-fitting *plane* for two predictors (static slices here — the slides have the spinnable 3D version)\n3. The ice-cream/drownings lurker: a \"significant\" coefficient that evaporates when the third variable enters\n4. A real two-predictor model of violent crime across Chicago's 77 community areas — read honestly, then diagnosed (residual plot, VIF)\n5. The same model in `brms`: posterior distributions, and the reporting sentence each tradition licenses\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(bayesplot)\nlibrary(brms)\nlibrary(car)\nset.seed(705)\n\nareas <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-areas.csv\",\n                  show_col_types = FALSE)\n```\n:::\n\n\n::: {.callout-warning appearance=\"simple\"}\nTwo non-tidyverse packages today: `car` (for VIF — `install.packages(\"car\")` if you don't have it) and `brms` from ANOVA week (`bayesplot` came along free when you installed it). The usual `brms` reminder: the first `brm()` of a session pauses at `Compiling Stan program...` for a minute before sampling starts. It is not frozen. Compiling.\n:::\n\n## 1 · Least squares: build the ruler by hand\n\nTen students, hours studied and exam scores. Some line through this cloud is the \"best\" one — but best by what ruler? Start with three candidates. (Seed 1 is kept from the lecture so every number matches the slides.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nstudents <- tibble(\n  hours = 1:10,\n  score = 40 + 5 * hours + rnorm(10, 0, 5)\n)\n\ncandidates <- tibble(\n  a = c(20, 50, 37),\n  b = c(5, 3, 5.2),\n  line = c(\"a = 20, b = 5\", \"a = 50, b = 3\", \"a = 37, b = 5.2\")\n)\n\nggplot(students, aes(hours, score)) +\n  geom_abline(data = candidates, aes(intercept = a, slope = b, color = line),\n              linewidth = 1.1) +\n  geom_point(size = 4, color = \"navy\") +\n  scale_color_manual(values = c(\"firebrick\", \"seagreen\", \"steelblue\")) +\n  labs(x = \"Hours studied\", y = \"Exam score\", color = NULL,\n       title = \"Which line is best? We need a ruler, not a vibe.\")\n```\n\n::: {.cell-output-display}\n![](demo-11-regression_files/figure-html/candidate-lines-1.png){width=672}\n:::\n:::\n\n\nThe ruler: for any candidate line, measure every vertical miss, square it (so misses above and below don't cancel), and add them up. That total is the **sum of squared residuals**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSSR <- function(a, b) {\n  predicted <- a + b * students$hours\n  sum((students$score - predicted)^2)\n}\n\nSSR(20, 5)      # too low\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4405.871\n```\n\n\n:::\n\n```{.r .cell-code}\nSSR(50, 3)      # too flat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 584.9933\n```\n\n\n:::\n\n```{.r .cell-code}\nSSR(37, 5.2)    # roughly right\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 196.9529\n```\n\n\n:::\n:::\n\n\nSmaller total = better line. **Least squares** = find the line with the smallest total of all. No trial and error required — `lm()` solves for it directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_hours <- lm(score ~ hours, data = students)\ncoef(fit_hours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       hours \n   39.15588     5.27366 \n```\n\n\n:::\n\n```{.r .cell-code}\nSSR(coef(fit_hours)[1], coef(fit_hours)[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 130.9173\n```\n\n\n:::\n:::\n\n\nOur best hand-picked guess left about 197 in squared misses; `lm()` gets it down to about 131 — and **no other line does better**. Read the slope: each additional hour of studying predicts about 5.3 more points, in this sample. The vertical gap between each point and the winning line is that student's **residual** — the miss the model owns. (The slides animate the search: the line tilts until the SSR stops shrinking.) So how much did the winning line explain? That's **R²**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_hours)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9460216\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(students$hours, students$score)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9460216\n```\n\n\n:::\n:::\n\n\n**R² is the proportion of the outcome's variance the model accounts for** — here about 95% (it's simulated data; real life humbles us below). And notice the second line: with one predictor, R² is just Session 10's correlation, squared. With multiple predictors, R² keeps the same meaning — variance explained by the whole team — but no single correlation owns it anymore.\n\n## 2 · Two predictors: from line to plane\n\nWith one predictor the model is a line through a 2-D cloud. With two, it's a **plane** floating in a 3-D cloud — one slope along each predictor's axis, chosen by the same ruler: minimize the total squared vertical distance from every point to the surface. Simulate data where we *know* the truth — intercept 10, slopes 2 and 3 — and check that `lm()` finds it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)   # kept from the lecture — same cloud as the slides\nplane_data <- tibble(\n  x1 = runif(100, 0, 10),\n  x2 = runif(100, 0, 10),\n  y  = 10 + 2 * x1 + 3 * x2 + rnorm(100, 0, 2)\n)\n\nplane_fit <- lm(y ~ x1 + x2, data = plane_data)\ncoef(plane_fit) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)          x1          x2 \n       9.80        1.98        3.02 \n```\n\n\n:::\n:::\n\n\nClose to (10, 2, 3) — least squares recovered the plane. A flat page can't spin a 3-D plot, but slicing the plane says the same thing: hold `x2` fixed at a few values and plot predicted `y` against `x1`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslices <- expand_grid(x1 = seq(0, 10, length.out = 50), x2 = c(2, 5, 8))\nslices$predicted <- predict(plane_fit, newdata = slices)\n\nggplot(slices, aes(x1, predicted, color = factor(x2))) +\n  geom_line(linewidth = 1.2) +\n  scale_color_manual(values = c(\"steelblue\", \"navy\", \"firebrick\")) +\n  labs(title = \"The plane, sliced: the x1 slope is the same at every fixed x2\",\n       subtitle = \"Parallel lines are what 'holding x2 constant' looks like\",\n       x = \"x1\", y = \"Predicted y\", color = \"x2 held at\")\n```\n\n::: {.cell-output-display}\n![](demo-11-regression_files/figure-html/plane-slices-1.png){width=672}\n:::\n:::\n\n\nEvery slice climbs at slope ≈ 2 (the `x1` coefficient); jumping *between* slices is the `x2` coefficient's job. For the grab-and-spin 3-D version — points, plane, and residuals — open the [Session 11 slides](../slides/week-11-regression.qmd) (\"The Best-Fitting Plane, Live\").\n\n## 3 · The lurking third variable\n\nIce cream sales and drowning deaths are strongly correlated. Every summer. Reliably. Build the world where temperature secretly drives both:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)\nlurk <- tibble(\n  temperature    = runif(100, 60, 100),\n  icecream_sales = 20 + 5 * temperature + rnorm(100, 0, 30),\n  drownings      = -10 + 0.8 * temperature + rnorm(100, 0, 10)\n)\n\nggplot(lurk, aes(icecream_sales, drownings)) +\n  geom_point(color = \"navy\", size = 2.5) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"firebrick\") +\n  labs(title = \"r = 0.6 — ban ice cream?\",\n       x = \"Ice cream sales\", y = \"Drownings\")\n```\n\n::: {.cell-output-display}\n![](demo-11-regression_files/figure-html/lurker-data-1.png){width=672}\n:::\n:::\n\n\nModel 1 fits what the scatterplot suggests — ice cream \"predicts\" drownings:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlurk_m1 <- lm(drownings ~ icecream_sales, data = lurk)\nsummary(lurk_m1)$coefficients |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error t value Pr(>|t|)\n(Intercept)     -0.3876     7.5245 -0.0515    0.959\nicecream_sales   0.1315     0.0175  7.5165    0.000\n```\n\n\n:::\n:::\n\n\nThe coefficient is positive and the p-value has ten zeros in it. Statistically significant; the model says it's real. Do we believe it? No — but notice that *nothing in this output warns us*. The model can only see the variables we gave it. So give it the lurker:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlurk_m2 <- lm(drownings ~ icecream_sales + temperature, data = lurk)\nsummary(lurk_m2)$coefficients |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error t value Pr(>|t|)\n(Intercept)    -10.0979     6.5333 -1.5456   0.1255\nicecream_sales  -0.0339     0.0299 -1.1352   0.2591\ntemperature      0.9884     0.1553  6.3634   0.0000\n```\n\n\n:::\n:::\n\n\nHolding temperature constant, ice cream's coefficient collapses from 0.13 to about −0.03 and goes nonsignificant (p ≈ 0.26), while R² jumps from 0.37 to 0.55. Temperature was driving both variables the whole time. This is *holding constant* doing real work: comparing days with the **same temperature**, ice cream tells you nothing about drownings. An **added-variable plot** (from `car`) shows exactly that — the ice cream–drownings relationship after temperature's contribution is removed from both:\n\n\n::: {.cell}\n\n```{.r .cell-code}\navPlots(lurk_m2, terms = ~ icecream_sales,\n        main = \"Ice cream vs. drownings, with temperature partialed out\")\n```\n\n::: {.cell-output-display}\n![](demo-11-regression_files/figure-html/lurker-avplot-1.png){width=672}\n:::\n:::\n\n\nFlat. That flat line *is* the multiple-regression coefficient for ice cream. The moral: multiple regression holds constant **only the variables you measured and included**. Every observational model has potential lurkers you didn't measure — so coefficients are **adjusted associations, not causal effects**. Keep that loaded; the Chicago models below will tempt you to talk causally.\n\n## 4 · Real data: violence across Chicago's 77 areas\n\nYou plotted violent-crime rate against unemployment across the 77 community areas in Session 10 — a strong upward cloud, each dot an *area*, not a person (say it with me: ecological). Look at that scatter again first if it isn't fresh, then fit one predictor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_m1 <- lm(violent_rate ~ unemployment_rate, data = areas)\nsummary(chi_m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = violent_rate ~ unemployment_rate, data = areas)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-32.137  -6.340  -2.670   5.843  43.339 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        -2.7444     2.8629  -0.959    0.341    \nunemployment_rate   3.3007     0.2463  13.400   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.27 on 75 degrees of freedom\nMultiple R-squared:  0.7054,\tAdjusted R-squared:  0.7014 \nF-statistic: 179.5 on 1 and 75 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nEach additional percentage point of unemployment is associated with **3.3 more violent crimes per 1,000 residents**, and unemployment alone accounts for about 70% of the between-area variance. Strong — but is unemployment getting credit for other disadvantage it travels with? Add vacant housing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_m2 <- lm(violent_rate ~ unemployment_rate + pct_vacant, data = areas)\nsummary(chi_m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = violent_rate ~ unemployment_rate + pct_vacant, data = areas)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-27.6759  -5.8167  -0.9943   4.5144  26.7266 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        -9.2679     2.4616  -3.765 0.000332 ***\nunemployment_rate   2.1156     0.2620   8.075 9.35e-12 ***\npct_vacant          1.9352     0.2859   6.769 2.65e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.708 on 74 degrees of freedom\nMultiple R-squared:  0.818,\tAdjusted R-squared:  0.8131 \nF-statistic: 166.3 on 2 and 74 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nBoth predictors earn significant coefficients, and R² climbs from 0.70 to **0.82**. But watch unemployment's slope: **3.3 → 2.1**. Some of what looked like \"unemployment\" in the simple model was shared with vacancy. That shrinkage *is* \"holding constant\" — the lurker lesson, on real data. Reading the coefficients out loud:\n\n- **Intercept (−9.3):** predicted rate when both predictors are 0 — no Chicago area looks like that; it anchors the plane, nothing more\n- **`unemployment_rate` (2.12):** +1 point of unemployment ↔ about 2.1 more violent crimes per 1,000 residents, **vacancy held fixed**\n- **`pct_vacant` (1.94):** +1 point of vacancy ↔ about 1.9 more violent crimes per 1,000 residents, **unemployment held fixed**\n\nAnd what they are *not*: not causal effects (these are adjusted associations between *areas*, with every unmeasured lurker still at large); not people-level claims (an unemployed *person* is not \"2.1 crimes more dangerous\" — Session 10's ecological fallacy rides along with every coefficient today); and not the full story (the model holds constant *only what's in the model*).\n\n### Watch the units\n\nCoefficient *size* is meaningless until you check the predictor's units. Median income, in dollars:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(violent_rate ~ median_income, data = areas))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) median_income \n68.5585257487 -0.0005221118 \n```\n\n\n:::\n\n```{.r .cell-code}\nareas |>\n  mutate(income_10k = median_income / 10000) |>\n  lm(violent_rate ~ income_10k, data = _) |>\n  coef()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  income_10k \n  68.558526   -5.221118 \n```\n\n\n:::\n:::\n\n\nSame model, same fit. But −0.0005 \"looks like\" nothing; the honest reading is **about 5 *fewer* violent crimes per 1,000 residents per $10,000 of median income**. Rescale before you interpret.\n\n### Does a third predictor earn its keep?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_m3 <- lm(violent_rate ~ unemployment_rate + pct_vacant + pct_no_hs_diploma,\n             data = areas)\nsummary(chi_m3)$coefficients |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Estimate Std. Error t value Pr(>|t|)\n(Intercept)         -8.853      2.862  -3.093    0.003\nunemployment_rate    2.140      0.276   7.741    0.000\npct_vacant           1.923      0.291   6.613    0.000\npct_no_hs_diploma   -0.039      0.135  -0.290    0.773\n```\n\n\n:::\n:::\n\n\nCoefficient ≈ 0, p ≈ 0.77 — with unemployment and vacancy already in, the diploma share adds nothing detectable. And **adjusted R²** (R² with a per-predictor penalty) actually *falls*, 0.813 → 0.811 (compare `summary(chi_m2)$adj.r.squared` with `summary(chi_m3)$adj.r.squared`). More predictors ≠ more truth. Every variable argues its way in — theory first, fit second.\n\n### Diagnostics: the residual plot and VIF\n\nRegression assumes the misses are patternless. So look at the misses:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(fitted = fitted(chi_m2), residual = resid(chi_m2)) |>\n  ggplot(aes(fitted, residual)) +\n  geom_hline(yintercept = 0, linetype = 2) +\n  geom_point(color = \"navy\", size = 2.5, alpha = 0.8) +\n  labs(title = \"Residuals vs. fitted values — the all-purpose diagnostic\",\n       x = \"Fitted violent-crime rate\", y = \"Residual\")\n```\n\n::: {.cell-output-display}\n![](demo-11-regression_files/figure-html/residual-plot-1.png){width=672}\n:::\n:::\n\n\nRead it honestly. What we want: a patternless horizontal band around zero. What we have: centered on zero with no obvious curve (good — the straight-plane assumption isn't visibly wrong), but the **spread widens at higher fitted values** — the model misses by more in high-violence areas. That fanning (**heteroscedasticity**) is common with rate outcomes; it doesn't bias the coefficients, but it makes the standard errors less trustworthy at the extremes — worth a sentence when you report. A *curve* in this plot would be worse news: it would say the model's *shape* is wrong, not just its noise.\n\n**Multicollinearity** is the other standard check: if two predictors move in near-lockstep, the model can't tell whose coefficient the shared variance belongs to — estimates get wobbly and standard errors balloon. **VIF** measures how redundant each predictor is with the others (rules of thumb: > 5, pay attention; > 10, you have a problem):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(chi_m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nunemployment_rate        pct_vacant \n         1.807177          1.807177 \n```\n\n\n:::\n:::\n\n\nAbout 1.8: unemployment and vacancy are correlated (r ≈ 0.67), but each still carries plenty of its own information. If VIF *were* high: drop one predictor, combine them into an index, or accept wide intervals — you cannot p-value your way out.\n\n## 5 · The Bayesian version\n\nIdentical formula, Bayesian machinery — the same `brms` workflow you've run since ANOVA week. (This is the chunk with the compile pause. Go refill your coffee.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_bayes <- brm(violent_rate ~ unemployment_rate + pct_vacant,\n                 data = areas,\n                 chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixef(chi_bayes) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Estimate Est.Error   Q2.5 Q97.5\nIntercept            -9.25      2.42 -13.93 -4.68\nunemployment_rate     2.12      0.27   1.58  2.64\npct_vacant            1.92      0.29   1.36  2.48\n```\n\n\n:::\n:::\n\n\nPosterior means land almost exactly on the least-squares estimates — with `brms`'s default priors (flat on the slopes, weakly informative on the intercept and spread) and a decent *n*, they should. The Session 10 rule travels: defaults are fine, **but say which prior you used**. One sentence in your methods — \"brms default priors, 2 chains × 2,000 iterations, seed 705\" — covers it. Below the posterior plot: the sentence each tradition licenses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_areas(chi_bayes, pars = c(\"b_unemployment_rate\", \"b_pct_vacant\"),\n           prob = 0.95) +\n  labs(title = \"Posterior distributions: predictors of violent-crime rate\",\n       subtitle = \"Shaded = central 95% credible interval — both sit clear of zero\")\n```\n\n::: {.cell-output-display}\n![](demo-11-regression_files/figure-html/chicago-mcmc-areas-1.png){width=672}\n:::\n:::\n\n\n> **Frequentist:** \"Holding vacancy constant, each percentage point of unemployment was associated with about 2.1 more violent crimes per 1,000 residents (b = 2.12, 95% CI [1.59, 2.64], p < .001).\"\n>\n> **Bayesian:** \"Given the data and priors, there is a 95% probability the unemployment coefficient lies between ≈ 1.6 and ≈ 2.6 — zero is not a credible value.\"\n\nBoth are area-level, adjusted **associations** — neither sentence licenses \"unemployment causes violence.\"\n\n## Try a variation\n\n1. Beat the machine: using `SSR()`, hunt by hand for an (a, b) pair that gets below 131. (Spoiler: you can tie `lm()` to more decimal places, but never beat it.)\n2. In the lurker simulation, give ice cream a *real* effect — change the `drownings` line to `-10 + 0.8 * temperature + 0.05 * icecream_sales + rnorm(100, 0, 10)`. Does `lurk_m2` find it?\n3. In the third-predictor test, swap `pct_no_hs_diploma` for a predictor of your choice (`pct_renter`? `median_rent`?). Does anything earn its keep next to unemployment and vacancy — by its coefficient *and* by adjusted R²?\n4. Run `predict(chi_m2, newdata = tibble(unemployment_rate = 23, pct_vacant = 25))` — roughly Englewood — and then again with 10 and 10. Which prediction does the residual plot say to trust more, and why?\n",
    "supporting": [
      "demo-11-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}