{
  "hash": "ee3c740759f30df38610bc9fd9b4ad02",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Practice Problems · Session 10\"\nsubtitle: \"Correlation: covariance to r, what r can't see, and inference in both traditions\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Ungraded self-checks.** Work each problem in your own R session *before* clicking the solution. These use different data and variables than the homework on purpose — if you can do these cold, Homework 10 (and Checkpoint 2 on your own project) will feel routine.\n:::\n\n\n\nProblems that use data need only this setup — `cities` is the 100 simulated-but-realistic cities you pivoted in Lab 4; today we stay in one year and go cross-sectional. One row = one **city**, not one person. Keep that in mind: it decides what your sentences are allowed to claim (Problem 6 will test you on it).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(correlation)\n\ncities <- read_csv(\"https://smourtgos.github.io/crju705/data/cities-wide.csv\")\n```\n:::\n\n\n## Problem 1 · Covariance's units problem\n\nCompute the covariance of `vcr_2025` (violent crimes per 100,000 residents) with **`population_2020`**, and then with **`poverty_rate`**. One of these covariances is roughly 3,800 times the size of the other. Is that association 3,800 times stronger? Settle it: divide each covariance by the two standard deviations involved, then confirm with `cor()`.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov(cities$population_2020, cities$vcr_2025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3449575\n```\n\n\n:::\n\n```{.r .cell-code}\ncov(cities$poverty_rate,    cities$vcr_2025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 914.0015\n```\n\n\n:::\n\n```{.r .cell-code}\n# Divide out the units: cov / (sd_x * sd_y)\ncov(cities$population_2020, cities$vcr_2025) /\n  (sd(cities$population_2020) * sd(cities$vcr_2025))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04429418\n```\n\n\n:::\n\n```{.r .cell-code}\ncov(cities$poverty_rate, cities$vcr_2025) /\n  (sd(cities$poverty_rate) * sd(cities$vcr_2025))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6082377\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(cities$population_2020, cities$vcr_2025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04429418\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(cities$poverty_rate,    cities$vcr_2025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6082377\n```\n\n\n:::\n:::\n\n\nThe ~3.4-million covariance turns into **r = 0.04** — essentially nothing — while the \"little\" 914 becomes **r = 0.61**. The first number was huge only because population is measured in *hundreds of thousands of people*; covariance is glued to its units, so its size is uninterpretable across pairs. Dividing by both SDs cancels the units and puts every pair on the same −1 to +1 ruler.\n:::\n\n## Problem 2 · What r can't see\n\nA training study measures 80 recruits' pre-qualification **anxiety** (0–10 scale) and their **marksmanship score** (100-point course). Simulate it, compute r, and then plot it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)   # inline seed: keeps this particular draw stable\nrecruits <- tibble(\n  anxiety      = seq(0, 10, length.out = 80),\n  marksmanship = 88 - 2.1 * (anxiety - 5)^2 + rnorm(80, 0, 6)\n)\n```\n:::\n\n\nA colleague computes `cor()`, gets roughly −0.04, and writes: *\"anxiety and marksmanship are unrelated.\"* What did they miss, and what habit would have caught it?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(recruits$anxiety, recruits$marksmanship)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.04161482\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(recruits, aes(anxiety, marksmanship)) +\n  geom_point(alpha = 0.6, color = \"grey30\") +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"firebrick\") +\n  labs(x = \"Pre-qualification anxiety (0-10)\", y = \"Marksmanship score\")\n```\n\n::: {.cell-output-display}\n![](practice-10_files/figure-html/p2-1.png){width=672}\n:::\n:::\n\n\nr ≈ −0.04, and the plot shows anything but \"unrelated\": scores peak around mid-scale anxiety and collapse at both extremes — a strong inverted-U (the classic arousal-performance curve). Because the upslope and downslope cancel, the *linear* summary lands near zero. **r measures straight-line association only; r ≈ 0 means no linear relationship, not no relationship** — which is why you plot before you correlate, every time.\n:::\n\n## Problem 3 · One unit can manufacture a correlation\n\nTwenty patrol beats, each with an average 911 **response time** (minutes) and a resident **satisfaction** score (0–100). Then the analyst appends beat 21 — the beat covering the airport, a giant low-density parcel: response time 28.4 minutes, satisfaction 31.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)   # inline seed: keeps this particular draw stable\nbeats <- tibble(\n  response_min = rnorm(20, 10, 1.5),\n  satisfaction = rnorm(20, 70, 6)\n)\n\nbeats_all <- beats |>\n  add_row(response_min = 28.4, satisfaction = 31)\n```\n:::\n\n\nCompute **Pearson's r and Spearman's rho** for the 20 beats, and again with the airport included. What happens to each — and which coefficient is telling the more honest story about the *typical* beat?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(pearson_20  = cor(beats$response_min, beats$satisfaction),\n  spearman_20 = cor(beats$response_min, beats$satisfaction, method = \"spearman\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n pearson_20 spearman_20 \n 0.03864620 -0.01654135 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(pearson_21  = cor(beats_all$response_min, beats_all$satisfaction),\n  spearman_21 = cor(beats_all$response_min, beats_all$satisfaction, method = \"spearman\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n pearson_21 spearman_21 \n -0.8071187  -0.1506494 \n```\n\n\n:::\n:::\n\n\nTwenty beats show essentially nothing (r ≈ 0.04). Add **one** unrepresentative unit and Pearson leaps to ≈ **−0.81** — a \"very strong\" negative correlation manufactured entirely by a single point sitting far out in both variables. Spearman moves only from ≈ −0.02 to ≈ −0.15, because to a rank-based measure the airport is just \"rank 21,\" not \"a dozen standard deviations of leverage.\" Neither number substitutes for the scatterplot — but when one wild unit is in the data, Spearman describes the typical beats far more honestly, and a Pearson-Spearman gap this large is itself a red flag to go look.\n:::\n\n## Problem 4 · Inference: the matrix, then the star pair\n\n(a) Run `correlation()` on `vcr_2025`, `poverty_rate`, `unemployment_rate`, and `police_per_10k`. Which pairs survive the Holm adjustment — and why do these p-values need adjusting at all?\n\n(b) The star pair is poverty and violence. Run `cor.test()` on it and write the one-sentence lecture-style report: r, df, p, CI, direction, strength.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncities |>\n  select(vcr_2025, poverty_rate, unemployment_rate, police_per_10k) |>\n  correlation()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1        |        Parameter2 |     r |        95% CI | t(98) |         p\n---------------------------------------------------------------------------------\nvcr_2025          |      poverty_rate |  0.61 | [ 0.47, 0.72] |  7.59 | < .001***\nvcr_2025          | unemployment_rate |  0.08 | [-0.11, 0.28] |  0.84 | > .999   \nvcr_2025          |    police_per_10k | -0.09 | [-0.28, 0.11] | -0.90 | > .999   \npoverty_rate      | unemployment_rate |  0.05 | [-0.15, 0.24] |  0.48 | > .999   \npoverty_rate      |    police_per_10k |  0.05 | [-0.15, 0.24] |  0.46 | > .999   \nunemployment_rate |    police_per_10k |  0.16 | [-0.04, 0.34] |  1.58 | 0.591    \n\np-value adjustment method: Holm (1979)\nObservations: 100\n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(cities$poverty_rate, cities$vcr_2025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  cities$poverty_rate and cities$vcr_2025\nt = 7.5858, df = 98, p-value = 1.92e-11\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.4676946 0.7187836\nsample estimates:\n      cor \n0.6082377 \n```\n\n\n:::\n:::\n\n\n(a) Exactly **one** pair survives: poverty with violent crime (r = .61, adjusted p < .001). Every other CI crosses 0, with adjusted p-values from .59 to essentially 1. The adjustment exists because this table runs **six tests at once** — six chances at a 5% false alarm is Session 8's pile-of-t-tests problem wearing correlation clothes, and Holm restores the family-wise honesty.\n\n(b) \"Across these 100 cities, poverty was moderately associated with the violent-crime rate, r = .61, t(98) = 7.59, p < .001, 95% CI [.47, .72] — cities with higher poverty rates recorded more violent crime per 100,000 residents.\" (By the lecture's bands, .61 is a *moderate* correlation — and in messy social-science data, a moderate r is a major finding.) A correlation matrix is the map; `cor.test()` is the full readout you pull for the one relationship your analysis is actually about.\n:::\n\n## Problem 5 · Bayesian correlation: a strong pair and an honest null\n\nRun the Bayesian version (`bayesian = TRUE`) twice: once on `poverty_rate` + `vcr_2025`, once on `unemployment_rate` + `vcr_2025`. For each, read out **rho, the 95% credible interval, pd, % in ROPE, and the Bayes factor**. For the second pair, also compute 1/BF. What can you say about unemployment that a p-value never could?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)   # inline seed: the Bayesian version samples from the posterior\ncities |>\n  select(vcr_2025, poverty_rate) |>\n  correlation(bayesian = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1 |   Parameter2 |  rho |       95% CI |      pd | % in ROPE\n---------------------------------------------------------------------\nvcr_2025   | poverty_rate | 0.58 | [0.46, 0.70] | 100%*** |        0%\n\nParameter1 |         Prior |          BF\n----------------------------------------\nvcr_2025   | Beta (3 +- 3) | 4.25e+08***\n\nObservations: 100\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(705)\nbayes_unemp <- cities |>\n  select(vcr_2025, unemployment_rate) |>\n  correlation(bayesian = TRUE)\nbayes_unemp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1 |        Parameter2 |  rho |        95% CI |     pd | % in ROPE\n--------------------------------------------------------------------------\nvcr_2025   | unemployment_rate | 0.08 | [-0.11, 0.25] | 79.83% |    55.05%\n\nParameter1 |         Prior |     BF\n-----------------------------------\nvcr_2025   | Beta (3 +- 3) | 0.319°\n\nObservations: 100\n```\n\n\n:::\n\n```{.r .cell-code}\n1 / bayes_unemp$BF\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.129932\n```\n\n\n:::\n:::\n\n\n**Poverty:** rho ≈ .58 (a touch below the frequentist .61 — the mildly skeptical prior's pull), 95% CI ≈ [.46, .70], pd = 100%, 0% in ROPE, BF ≈ 4 × 10⁸ — evidence far past \"extreme\" on Session 6's scale.\n\n**Unemployment:** rho ≈ .08, CI ≈ [−.11, .25] straddling 0, pd ≈ 80% (a coin flip barely leaning positive), and **over half the posterior sits inside the ROPE** — the \"practically zero\" band. The BF ≈ 0.32 is *below 1*: taking 1/BF, the data are about **3 times more consistent with no correlation than with one**. That's the sentence a p-value can never earn — the frequentist p ≈ .40 only says \"failed to reject\"; the Bayes factor gives you *positive evidence for the null*, stated as such.\n:::\n\n## Problem 6 · The sentence audit\n\nYour Problems 4–5 results end up in a briefing. Five draft sentences below — **which are defensible, and what exactly is wrong with the rest?**\n\n> (a) \"Cities with higher poverty rates recorded higher violent-crime rates in 2025 (r = .61).\"\n>\n> (b) \"Poor residents commit most of the violent crime in these cities.\"\n>\n> (c) \"Poverty causes violent crime.\"\n>\n> (d) \"City-level poverty statistically accounts for about 37% of the city-to-city variance in violent-crime rates.\"\n>\n> (e) \"We found no reliable city-level association between unemployment and violent crime; if anything, the data modestly favor there being none.\"\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(cities$poverty_rate, cities$vcr_2025)^2   # the 37% in sentence (d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3699531\n```\n\n\n:::\n:::\n\n\n**Defensible: (a), (d), and (e).** (a) stays at the level of the rows — cities — and claims only association. (d) is r² = .61² ≈ .37, correctly framed as *variance accounted for*, still at the city level. (e) matches Problem 5's output, including the BF ≈ 0.32 nuance.\n\n**(b) fails** — the **ecological fallacy**. These rows are cities; every resident of a city shares one poverty rate and one crime rate, so the data contain nothing about *which residents* are involved in violence. **(c) fails** — a causal claim from a cross-sectional correlation; disinvestment, housing, policing patterns, and more lurk behind both variables. The audit habit: check every sentence for the *level* the data measure (areas vs. people) and the *strength* the design supports (association vs. cause).\n:::\n",
    "supporting": [
      "practice-10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}