{
  "hash": "fc8198dc3d77ad17f8ef06fe24329f64",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo Walkthrough · Session 6\"\nsubtitle: \"Hypothesis testing, twice — the p-value from prop.test(), the posterior from bayes_prop_test()\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this page is.** The Session 6 lecture demos, written down step by step. Every chunk below is self-contained — copy any of them into your own R session and they run as-is. Use this page to catch up after a missed class, or to re-run what happened on screen at your own pace.\n:::\n\n## What you'll build\n\n1. A real question in percent: among Chicago's violent crimes, are domestic ones more likely to end in an arrest?\n2. Repeated sampling of that gap — 10,000 draws — and the same machinery run in a world with *no* real difference\n3. The NHST verdict from `prop.test()`, and where the same p-value lives in last week's `t.test()`\n4. The recidivism trial, both ways: $p = 0.20$ from `prop.test()`, a 91% probability the program works from `bayes_prop_test()`\n5. Back to Chicago with both tools — and what sample size does to each\n\n## Setup\n\nThe tidyverse, the Chicago incidents, and one new line: `source()` loads the course's Bayesian function from the course site. There is nothing to install.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nsource(\"https://smourtgos.github.io/crju705/R/bayes.R\")   # gives you bayes_prop_test()\nset.seed(705)\n\ncrimes <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-crimes-2025.csv\",\n                   show_col_types = FALSE)\n\nviolent <- crimes |> filter(crime_category == \"Violent\")\n```\n:::\n\n\n## 1 · Tonight's question\n\nAmong violent crimes in our sample, are the *domestic* ones more likely to end in an arrest? Count first, exactly as in Lab 5:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nviolent |> count(domestic, arrest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  domestic arrest     n\n  <lgl>    <lgl>  <int>\n1 FALSE    FALSE   4685\n2 FALSE    TRUE     714\n3 TRUE     FALSE   3009\n4 TRUE     TRUE     740\n```\n\n\n:::\n:::\n\n\nRead four numbers off that table. Domestic: 740 arrests out of 740 + 3,009 = **3,749**, which is **19.7%**. Not domestic: 714 arrests out of 714 + 4,685 = **5,399**, which is **13.2%**. A gap of about **6.5 percentage points**. Everything below reads the difference one way: **Domestic minus Not domestic**.\n\nBut this is a *sample* of Chicago's 2025 incidents, and Session 4 taught us that sample numbers bounce around. Could a gap like this be nothing but bounce?\n\n## 2 · Pretend we sampled repeatedly\n\nSession 4's move, applied to both groups at once. Pull out each group's arrests (a column of TRUE and FALSE), then draw 10,000 repeated samples of each and compute the arrest rate every time:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndom_arrest <- violent$arrest[violent$domestic]\nnon_arrest <- violent$arrest[!violent$domestic]\n\nreps <- tibble(\n  Domestic       = replicate(10000, mean(sample(dom_arrest, replace = TRUE))),\n  `Not domestic` = replicate(10000, mean(sample(non_arrest, replace = TRUE)))\n)\n\nreps |>\n  pivot_longer(everything(), names_to = \"group\", values_to = \"rate\") |>\n  mutate(group = factor(group, levels = c(\"Domestic\", \"Not domestic\"))) |>\n  ggplot(aes(100 * rate, fill = group)) +\n  geom_histogram(bins = 60, alpha = 0.7, position = \"identity\", color = NA) +\n  scale_fill_manual(values = c(\"firebrick\", \"steelblue\")) +\n  labs(title = \"10,000 repeated samples per group\",\n       x = \"Arrest rate (%)\", y = \"Count\", fill = NULL)\n```\n\n::: {.cell-output-display}\n![](demo-06-hypothesis-testing_files/figure-html/rep-rates-1.png){width=672}\n:::\n:::\n\n\nThe two piles do not even touch. Subtract, pair by pair, and the *difference* gets its own pile:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrep_diff <- 100 * (reps$Domestic - reps$`Not domestic`)   # percentage points\nci_rep   <- quantile(rep_diff, c(0.025, 0.975))\nci_rep\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n4.952760 8.074351 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(tibble(rep_diff), aes(rep_diff)) +\n  geom_histogram(bins = 60, fill = \"navy\", color = \"white\") +\n  geom_vline(xintercept = 0, color = \"firebrick\", linewidth = 1.2) +\n  geom_vline(xintercept = ci_rep, color = \"goldenrod\", linetype = 2, linewidth = 1) +\n  labs(title = \"Repeated-sampling differences (Domestic minus Not domestic)\",\n       subtitle = \"Red line = zero (no difference); gold dashes = middle 95%\",\n       x = \"Difference in arrest rate, percentage points\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](demo-06-hypothesis-testing_files/figure-html/rep-diff-1.png){width=672}\n:::\n:::\n\n\nThe middle 95% of plausible differences runs from about **5 to 8 points**. Zero is nowhere near it.\n\n### What if there were no real difference?\n\nBuild the **boring world** on purpose. Give both groups the *same* arrest rate (the overall 15.9% among violent crimes) by drawing both groups from the full list of violent incidents, and run the same machinery:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_gap <- 100 * (mean(dom_arrest) - mean(non_arrest))\n\nnull_diff <- 100 * replicate(10000,\n  mean(sample(violent$arrest, 3749, replace = TRUE)) -\n  mean(sample(violent$arrest, 5399, replace = TRUE)))\n\nggplot(tibble(null_diff), aes(null_diff)) +\n  geom_histogram(bins = 60, fill = \"gray50\", color = \"white\") +\n  geom_vline(xintercept = obs_gap, color = \"firebrick\", linewidth = 1.4) +\n  labs(title = \"10,000 gaps from a world with NO real difference\",\n       subtitle = \"Red line = the gap we actually saw\",\n       x = \"Difference in arrest rate, percentage points\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](demo-06-hypothesis-testing_files/figure-html/rep-null-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsum(abs(null_diff) >= obs_gap)   # how many boring-world gaps were as big as ours?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nChance alone makes gaps of a point or two. It made a gap as big as ours in **none** of the 10,000 tries. That count, out of 10,000, is the whole idea of a **p-value**. Formalize it and you have invented the NHST.\n\n## 3 · The Null Hypothesis Significance Test, in five steps\n\n1. **State the null**, $H_0$: the two arrest rates are the same (difference = 0). The boring world.\n2. **State the alternative**, $H_1$: *some* difference — note how little we commit to.\n3. **Compute a test statistic**: the observed gap, measured against how much gaps bounce by chance.\n4. **Ask:** how often would a gap this large appear by luck in the boring world? That's the **p-value**.\n5. **Verdict:** $p < \\alpha$ (usually .05) → \"reject $H_0$.\" Otherwise → \"fail to reject.\"\n\nNotice the machine only weighs evidence **against the null** — $H_1$ never gets scored. And be precise about the p-value. It **is** the probability of data *this extreme or more, if the null is true and the model is right*. It is **not** the probability the null is true (that's $P(H_0 \\mid \\text{data})$, which frequentism never computes), **not** the probability the result \"is due to chance,\" and **not** a measure of how *big* the effect is — with enough data, microscopic effects earn microscopic p-values. Hold that thought.\n\n`prop.test()` is Lab 5's function, now with **two groups**: how many, out of how many, for each. Domestic first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(740, 714), n = c(3749, 5399))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(740, 714) out of c(3749, 5399)\nX-squared = 69.744, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.04929331 0.08098520\nsample estimates:\n   prop 1    prop 2 \n0.1973860 0.1322467 \n```\n\n\n:::\n:::\n\n\nReading the verdict, bottom up. `prop 1` and `prop 2` are the two rates, 19.7% and 13.2%; Domestic is first because we typed it first. The `95 percent confidence interval`, about **4.9 to 8.1 points**, is last week's skill. And `p-value < 2.2e-16` is R's way of writing a decimal point followed by fifteen zeros: in the boring world, a gap like ours essentially never happens. Under .05 — **\"statistically significant.\"** Reject the null.\n\nThe same line lives in `t.test()`. Last week's homework compared two *means*; you read the interval, and the p-value was sitting right above it the whole time:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrashes <- read_csv(\"https://smourtgos.github.io/crju705/data/crash-ak.csv\",\n                    show_col_types = FALSE) |>\n  mutate(intox = if_else(intox_any == 1, \"Intoxicated\", \"Sober\"))\n\nt.test(injuries ~ intox, data = crashes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  injuries by intox\nt = 12.489, df = 1732.6, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Intoxicated and group Sober is not equal to 0\n95 percent confidence interval:\n 0.3259893 0.4474533\nsample estimates:\nmean in group Intoxicated       mean in group Sober \n                1.1300971                 0.7433758 \n```\n\n\n:::\n:::\n\n\nOne caution: everything above was scored against *one* curve — the null — and that tidy curve itself assumes large-enough samples, independent observations, and a model that fits the data. NHST never asks what the alternative world looks like, and researchers rarely test the assumptions before trusting the p-value. (The lecture's sketch figures make this vivid — see the [Session 6 slides](../slides/week-06-hypothesis-testing.qmd).)\n\n## 4 · The recidivism trial, both ways\n\nTypical recidivism runs about **60%**. A randomized trial of a reentry program puts 100 people in treatment and 100 in control. Outcomes: treatment **40/100** reoffend, control **50/100**. Did the program reduce recidivism? Ten percentage points is exactly the kind of effect a city would fund.\n\n**The frequentist answer.** Treatment first, so the difference reads Treatment minus Control:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(40, 50), n = c(100, 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(40, 50) out of c(100, 100)\nX-squared = 1.6364, df = 1, p-value = 0.2008\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.24719748  0.04719748\nsample estimates:\nprop 1 prop 2 \n   0.4    0.5 \n```\n\n\n:::\n:::\n\n\n$p = 0.20$ — **not statistically significant**, and the interval (about −25 to +5 points) has zero inside it. Honest reading: *a 10-point gap like this could plausibly occur even if the program did nothing*. The grant report writes itself — \"no significant effect\" — and the program probably dies there.\n\n**The Bayesian answer.** A Bayesian has to say, out loud, what they believed *before* the data. That is the **prior**. We said it already: recidivism typically runs about 60%. How firmly? Say about as firmly as if we had already watched **10 people: 6 reoffended, 4 did not**. In R that whole belief is two numbers, `prior = c(6, 4)`. The function adds the trial's 200 real people to our 10 imaginary ones; that adding-up is the **posterior**, what we believe *after* the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(40, 50), n = c(100, 100), prior = c(6, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  40 of 100 (40.0%)\ndata, group 2:  50 of 100 (50.0%)\nprior:          6 yes, 4 no (about 60%, worth 10 cases), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  41.8%         32.8% to 51.1%\ngroup 2                  50.9%         41.6% to 60.2%\ndifference (1 minus 2)   -9.1 points   -22.0 to 4.0 points\n\nProbability group 1 is higher than group 2: 0.09 \nProbability group 1 is lower than group 2:  0.91 \n```\n\n\n:::\n:::\n\n\nReading it. `estimate` is the best single guess for each group's true rate after the data. The `95% credible interval` for the difference runs from about **−22 to +4 points**, Treatment minus Control. And the last line is the one a policymaker wants: given the prior and the data, there is about a **91% probability the program reduces recidivism**.\n\nNow say the sentence Session 5 forbade — **legally**: *\"There is a 95% probability the true difference lies between −22 and +4 points.\"* That is exactly what a **credible interval** means.\n\nThe function hands back the 100,000 plausible values it used, so you can look at them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- bayes_prop_test(x = c(40, 50), n = c(100, 100), prior = c(6, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  40 of 100 (40.0%)\ndata, group 2:  50 of 100 (50.0%)\nprior:          6 yes, 4 no (about 60%, worth 10 cases), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  41.8%         32.8% to 51.1%\ngroup 2                  50.9%         41.6% to 60.2%\ndifference (1 minus 2)   -9.1 points   -22.0 to 4.0 points\n\nProbability group 1 is higher than group 2: 0.09 \nProbability group 1 is lower than group 2:  0.91 \n```\n\n\n:::\n\n```{.r .cell-code}\nresult$draws |>\n  select(Treatment = group1, Control = group2) |>\n  pivot_longer(everything(), names_to = \"group\", values_to = \"rate\") |>\n  ggplot(aes(100 * rate, fill = group)) +\n  geom_density(alpha = 0.5, color = NA) +\n  scale_fill_manual(values = c(\"gray50\", \"firebrick\")) +\n  labs(title = \"What we now believe about each group's recidivism rate\",\n       x = \"Recidivism rate (%)\", y = \"Posterior density\", fill = NULL)\n```\n\n::: {.cell-output-display}\n![](demo-06-hypothesis-testing_files/figure-html/recid-plot-1.png){width=672}\n:::\n:::\n\n\n| | Frequentist | Bayesian |\n|---|---|---|\n| Verdict | $p = 0.20$: cannot reject \"no effect\" | Probability the program works ≈ 0.91 |\n| Plain English | \"This gap could plausibly be luck\" | \"About 9-to-1 odds the program works\" |\n\nBoth statements are **true of the same data**. Neither is a trick. A policymaker deciding whether to fund the program next year: which sentence actually helps?\n\n**Does the prior matter here?** Leave `prior =` out and the function starts from \"I know nothing\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(40, 50), n = c(100, 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  40 of 100 (40.0%)\ndata, group 2:  50 of 100 (50.0%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  40.2%         30.9% to 49.8%\ngroup 2                  50.0%         40.4% to 59.6%\ndifference (1 minus 2)   -9.8 points   -23.2 to 3.7 points\n\nProbability group 1 is higher than group 2: 0.08 \nProbability group 1 is lower than group 2:  0.92 \n```\n\n\n:::\n:::\n\n\n0.92 instead of 0.91. It barely moved, because 200 real people outweigh 10 imaginary ones: **data overwhelm a modest prior**. A prior matters most when data are scarce, which is exactly when you most need to say it out loud.\n\n## 5 · Back to Chicago, both ways\n\nWe have no strong belief going in about domestic arrest rates, so no `prior =`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(740, 714), n = c(3749, 5399))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  740 of 3,749 (19.7%)\ndata, group 2:  714 of 5,399 (13.2%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  19.8%         18.5% to 21.0%\ngroup 2                  13.2%         12.3% to 14.2%\ndifference (1 minus 2)   6.5 points    5.0 to 8.1 points\n\nProbability group 1 is higher than group 2: more than 0.99 \nProbability group 1 is lower than group 2:  less than 0.01 \n```\n\n\n:::\n:::\n\n\n| | Chicago arrests (9,148 cases) | Reentry trial (200 people) |\n|---|---|---|\n| `prop.test()` | 95% CI: 4.9 to 8.1 points · $p < .001$ | 95% CI: −25 to +5 points · $p = 0.20$ |\n| `bayes_prop_test()` | 95% credible: 5.0 to 8.1 points | 95% credible: −22 to +4 points · P(works) ≈ 0.91 |\n\nWith thousands of cases the two traditions hand you **nearly the same range**; the data drown out everything else. With 100 per group, both ranges still include zero — but one tradition stops at \"not significant,\" and the other tells you *how probable* the effect is. Neither is wrong. They answer **different questions**.\n\n## 6 · Sample size changes everything\n\nThe lecture closed with two animations you should watch in the [Session 6 slides](../slides/week-06-hypothesis-testing.qmd): fix a *trivial* true effect and just keep collecting data, and *p* still dives below .05 — **given enough data, everything is \"significant.\"** The same growing dataset through Bayesian glasses doesn't flip a verdict; it **sharpens the estimate**, which visibly converges on \"almost nothing.\" The tininess stays in view.\n\nSo after either test, say the size **in real units**: arrest rates about 6.5 points apart (19.7% vs 13.2%). Then ask the question no test can answer for you: is a gap that size big enough to *matter*?\n\n## Try a variation\n\n1. Ask tonight's question about **property** crimes instead: `crimes |> filter(crime_category == \"Property\") |> count(domestic, arrest)`, then type the four numbers into `prop.test()` and `bayes_prop_test()`. How small is the domestic group, and what does that do to both intervals?\n2. Give the recidivism trial a **skeptic's prior**: someone who has watched 100 people, 60 of whom reoffended, writes `prior = c(60, 40)`. How far does the 0.91 move now, and why more than before?\n3. Make the trial's evidence stronger — treatment 35/100 instead of 40/100 — and re-run both tests. Where does *p* land now, and where does the probability the program works?\n4. Rerun the repeated sampling with `replicate(100, …)` instead of 10,000. How stable are the interval endpoints across reruns? *(The pile of repeated samples is itself a sample.)*\n",
    "supporting": [
      "demo-06-hypothesis-testing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}