{
  "hash": "c47066387fae584164471dedbf736019",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Practice Problems · Session 2\"\nsubtitle: \"Central tendency, dispersion, and the shapes of distributions\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Ungraded self-checks.** Work each problem in your own R session *before* clicking the solution. These use different numbers and variables than the homework on purpose — if you can do these cold, Homework 2 (and the midterm's descriptives section) will feel routine.\n:::\n\n\n\nAll problems that use data need only:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(modeest)   # for mfv(); install.packages(\"modeest\") once if needed\nofficers <- read_csv(\"https://smourtgos.github.io/crju705/data/officers.csv\")\nnbhd     <- read_csv(\"https://smourtgos.github.io/crju705/data/neighborhoods.csv\")\n```\n:::\n\n\n## Problem 1 · Three kinds of typical\n\nResponse times (in minutes) for 10 priority calls one Friday night — nine routine, plus one call that sat in the queue through a shift change:\n\n```r\nresponse <- c(4, 5, 5, 6, 6, 6, 7, 8, 9, 42)\n```\n\nCompute the **mean**, **median**, and **mode**. Which of the three would you *not* want on the department's public dashboard, and why?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponse <- c(4, 5, 5, 6, 6, 6, 7, 8, 9, 42)\n\nmean(response)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.8\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(response)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n\n```{.r .cell-code}\nmfv(response)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\nThe one 42-minute call drags the mean to 9.8 minutes even though *no* routine call took longer than 9 — classic central-tendency behavior: the mean chases outliers, while the median (6) and mode (6) stay with the bulk of the data.\n:::\n\n## Problem 2 · Same mean, different story\n\nTwo detective units both average 30 open cases per detective — but look at the individual caseloads:\n\n```r\nunit_a <- c(18, 30, 42)\nunit_b <- c(29, 30, 31)\n```\n\nCompute for each unit: the **range** (with `range()` and `diff()`), the **deviations from the mean**, the **sum of squared deviations**, and the **population variance and SD** by hand. Then run `var()` and `sd()` — why don't the built-ins match your hand calculations?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunit_a <- c(18, 30, 42)\nunit_b <- c(29, 30, 31)\n\ndiff(range(unit_a)); diff(range(unit_b))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\nunit_a - mean(unit_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -12   0  12\n```\n\n\n:::\n\n```{.r .cell-code}\nunit_b - mean(unit_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1  0  1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sum of squares\nsum((unit_a - mean(unit_a))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 288\n```\n\n\n:::\n\n```{.r .cell-code}\nsum((unit_b - mean(unit_b))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\n# Population variance and SD (divide by n)\nsum((unit_a - mean(unit_a))^2) / 3; sqrt(sum((unit_a - mean(unit_a))^2) / 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 96\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.797959\n```\n\n\n:::\n\n```{.r .cell-code}\nsum((unit_b - mean(unit_b))^2) / 3; sqrt(sum((unit_b - mean(unit_b))^2) / 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6666667\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8164966\n```\n\n\n:::\n\n```{.r .cell-code}\n# R's built-ins\nvar(unit_a); sd(unit_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 144\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(unit_b); sd(unit_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\nIdentical centers, radically different **dispersion**: unit A's SD (~9.8 population / 12 sample) says workloads genuinely vary; unit B's (~1) says everyone carries the same load. The built-ins disagree with your hand math because R divides by n − 1, not n — Session 4 pays off that IOU.\n:::\n\n## Problem 3 · Audit the briefing note\n\nA draft briefing memo about Problem 1's data contains two sentences:\n\n> (a) \"The typical priority call waited about 10 minutes for an officer.\"\n>\n> (b) \"Half of priority calls had an officer on scene within 6 minutes.\"\n\nOne is defensible, one is misleading. Which is which — and rewrite the misleading one in a single honest sentence.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponse <- c(4, 5, 5, 6, 6, 6, 7, 8, 9, 42)\nc(mean = mean(response), median = median(response))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean median \n   9.8    6.0 \n```\n\n\n:::\n:::\n\n\nSentence (b) is defensible — it is exactly what the median (6) means. Sentence (a) launders the mean (9.8) into the word \"typical,\" but *nine of ten* calls beat 10 minutes; only the queued outlier pushes the average there. An honest rewrite: \"Half of priority calls had an officer within 6 minutes; one call held during a shift change took 42.\" With skewed data, \"typical\" belongs to the median — and outliers deserve their own sentence, not a hiding place inside the mean.\n:::\n\n## Problem 4 · Real data: how much do officers sleep?\n\nUsing `officers`, summarize `sleep_hours` — mean, median, SD, min, max — and make a histogram (`binwidth = 0.5`). Is the distribution roughly symmetric or skewed? How do you know from the *numbers alone*?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nofficers |>\n  summarize(mean_sleep = mean(sleep_hours), median_sleep = median(sleep_hours),\n            sd_sleep = sd(sleep_hours), min = min(sleep_hours), max = max(sleep_hours))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  mean_sleep median_sleep sd_sleep   min   max\n       <dbl>        <dbl>    <dbl> <dbl> <dbl>\n1       6.40          6.4     1.40   2.5    10\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(officers, aes(sleep_hours)) +\n  geom_histogram(binwidth = 0.5, fill = \"steelblue\", color = \"white\") +\n  labs(x = \"Sleep per night (hours)\", y = \"Officers\")\n```\n\n::: {.cell-output-display}\n![](practice-02_files/figure-html/p4-1.png){width=672}\n:::\n:::\n\n\nMean (6.40) and median (6.4) are essentially identical — the numeric signature of a roughly **symmetric distribution**, which the histogram confirms. (Compare Problem 1, where mean and median disagreed badly: that gap *is* the skew detector.)\n:::\n\n## Problem 5 · The empirical rule, checked against reality\n\nIf `sleep_hours` were perfectly normal, about **68%** of officers would fall within ±1 SD of the mean and about **95%** within ±2 SD. Compute the *actual* shares. (Hint: `mean(abs(x - m) <= s)` — the same mean-of-a-logical move as always.)\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- mean(officers$sleep_hours)\ns <- sd(officers$sleep_hours)\n\nmean(abs(officers$sleep_hours - m) <= s)       # within +/- 1 SD\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.695\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(abs(officers$sleep_hours - m) <= 2 * s)   # within +/- 2 SD\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.955\n```\n\n\n:::\n:::\n\n\nAbout 69.5% and 95.5% — within a couple points of the **empirical rule's** 68/95 benchmarks. That is what \"the SD tells you how typical or extreme a value is\" means in practice: for bell-shaped data, mean ± 2 SD brackets nearly everyone.\n:::\n\n## Problem 6 · A Poisson in the wild\n\nUsing `nbhd` (500 neighborhoods), make a bar chart of `assaults` (last year's count per neighborhood), then compute its **mean and variance**. Now simulate 500 draws from a Poisson with the same λ — `rpois(500, lambda = mean(nbhd$assaults))` — and compare the two count tables. Does the textbook distribution fit the real one?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(nbhd, aes(assaults)) +\n  geom_bar(fill = \"grey40\") +\n  labs(x = \"Assaults last year\", y = \"Neighborhoods\")\n```\n\n::: {.cell-output-display}\n![](practice-02_files/figure-html/p6-1.png){width=672}\n:::\n\n```{.r .cell-code}\nnbhd |> summarize(mean_assaults = mean(assaults), var_assaults = var(assaults))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  mean_assaults var_assaults\n          <dbl>        <dbl>\n1          1.07         1.69\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(705)\ntable(nbhd$assaults)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  0   1   2   3   4   5   6   7 \n219 134  87  32  17   4   5   2 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(rpois(500, lambda = mean(nbhd$assaults)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  0   1   2   3   4   5 \n148 192 102  45  11   2 \n```\n\n\n:::\n:::\n\n\nThe broad shape matches — right-skewed counts of a rare event, exactly the **Poisson's** territory. But look closer: the real data have *more zeros* (219 vs ~148) *and* a longer tail (counts up to 7 vs 5), and the variance (1.69) exceeds the mean (1.07), where a true Poisson would have them equal. Real CJ counts are usually messier than the textbook distribution — a mismatch called overdispersion that you'll meet again later in the course.\n:::\n",
    "supporting": [
      "practice-02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}