{
  "hash": "e1f29060f8df18c2ade89c85f9ea0e81",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo Walkthrough · Session 2\"\nsubtitle: \"Central tendency, dispersion, and distribution shapes — the hard way first, then the easy way\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this page is.** The Session 2 lecture demos, written down step by step. Every chunk below is self-contained — copy any of them into your own R session and they run as-is. Use this page to catch up after a missed class, or to re-run what happened on screen at your own pace.\n:::\n\n## What you'll build\n\n1. Mean, median, and mode — computed *by hand* first, so the built-ins never feel like magic\n2. The sentencing demo: one 30-year outlier, three very different answers to \"what's typical?\" — then the same lesson live in Chicago's 77 community areas\n3. The dispersion machinery, one step at a time: raw values → deviations → squared deviations → variance → SD\n4. The empirical rule (68–95–99.7), checked against real daily crime counts\n5. The Poisson distribution — and proof that real robbery counts actually follow it\n\n## Setup\n\nEverything below needs the tidyverse, plus **modeest** for the mode (`install.packages(\"modeest\")` once — then `library()` every session):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(modeest)\nset.seed(705)\ncrimes <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-crimes-2025.csv\",\n                   show_col_types = FALSE)\nareas  <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-areas.csv\",\n                   show_col_types = FALSE)\n```\n:::\n\n\n## 1 · Three ways to say \"typical\"\n\nSeven days of rainfall. The **mean** is just \"add them up, divide by how many\" — do it the hard way once so you know exactly what `mean()` does:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrainfall <- c(0, 0, 0, 2, 1, 1, 4)   # rain each day this week\n\n# The hard way:\nsum(rainfall) / length(rainfall)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.142857\n```\n\n\n:::\n\n```{.r .cell-code}\n# The easy way:\nmean(rainfall)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.142857\n```\n\n\n:::\n:::\n\n\nThe **median** is the middle value of the *sorted* data, and the **mode** is the most frequent value. Base R has no mode function (`mode()` does something else entirely!), so we use `mfv()` — \"most frequent value\" — from modeest:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(rainfall)   # seven values, so the 4th one is the middle\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0 0 0 1 1 2 4\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(rainfall)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmfv(rainfall)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nThree answers — mean ≈ 1.14, median 1, mode 0 — from the same seven numbers. When could they disagree by enough to matter? Glad you asked.\n\n## 2 · When \"the average\" misleads: sentencing\n\nTen people convicted of robbery, and one judge in a bad mood:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsentences <- c(2, 2, 3, 3, 3, 4, 4, 5, 5, 30)   # note the outlier!\n\nmean(sentences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.1\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(sentences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.5\n```\n\n\n:::\n\n```{.r .cell-code}\nmfv(sentences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n:::\n\n\nOne 30-year sentence drags the mean to **6.1 years** — yet *nobody* in the data actually received a sentence near 6 years. The median (3.5) and mode (3) describe the group far better:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsent_stats <- tibble(\n  measure = c(\"Mean\", \"Median\", \"Mode\"),\n  value = c(mean(sentences), median(sentences), mfv(sentences))\n)\n\nggplot(tibble(sentences), aes(sentences)) +\n  geom_histogram(binwidth = 1, fill = \"grey85\", color = \"black\") +\n  geom_vline(data = sent_stats, aes(xintercept = value, color = measure),\n             linewidth = 1.2, linetype = \"dashed\") +\n  labs(title = \"Sentence Lengths (in Years)\",\n       x = \"Years in Prison\", y = \"Number of People\", color = NULL)\n```\n\n::: {.cell-output-display}\n![](demo-02-descriptives_files/figure-html/sentences-plot-1.png){width=672}\n:::\n:::\n\n\nWorth sitting with: which of the three would be most honest in a press release about sentencing policy — and which would an advocate quote?\n\n### The same thing in live data\n\nCrime rates per 1,000 residents across Chicago's 77 community areas, 2025:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas |>\n  summarize(\n    mean_rate   = mean(crime_rate),\n    median_rate = median(crime_rate),\n    max_rate    = max(crime_rate)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_rate median_rate max_rate\n      <dbl>       <dbl>    <dbl>\n1      96.9          82     292.\n```\n\n\n:::\n:::\n\n\nMean about 97, median 82 — the mean sits well above the median, the signature of a **right-skewed** distribution. Who's dragging it up?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas |> slice_max(crime_rate, n = 3) |> select(community, crime_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  community          crime_rate\n  <chr>                   <dbl>\n1 Fuller Park              292.\n2 West Garfield Park       220.\n3 Englewood                214.\n```\n\n\n:::\n:::\n\n\nFuller Park tops the list at roughly 292 crimes per 1,000 residents — partly because only about 2,300 people live there, so even a modest crime count divided by a tiny population produces a huge *rate*. Same lesson as the 30-year sentence, in live data. (Want to see it? Reuse the sentencing-histogram pattern on `areas$crime_rate` — the mean line lands visibly right of the median.)\n\n## 3 · Dispersion: the machinery, step by step\n\nTwo three-candidate elections, identical mean support, completely different situations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvotes1 <- c(200, 300, 400)   # wide spread\nvotes2 <- c(299, 300, 301)   # tight cluster\n\nmean(votes1); mean(votes2)       # identical means...\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 300\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 300\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(votes1)); diff(range(votes2))   # ...very different ranges\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 200\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n**Step 1 — deviations from the mean.** The range only uses two values; the real machinery asks about every value. How far is each one from 300?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvotes1 - mean(votes1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -100    0  100\n```\n\n\n:::\n\n```{.r .cell-code}\nvotes2 - mean(votes2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1  0  1\n```\n\n\n:::\n:::\n\n\nWhy not just average these? Because they *always* cancel:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(votes1 - mean(votes1))   # the sum of deviations is always zero\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n**Step 2 — square them.** Squaring makes every deviation positive (and makes big misses count extra):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum((votes1 - mean(votes1))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20000\n```\n\n\n:::\n\n```{.r .cell-code}\nsum((votes2 - mean(votes2))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n20,000 versus 2 — *now* the two elections look as different as they are.\n\n**Step 3 — average, then un-square.** The mean squared deviation is the **variance**; its square root is the **standard deviation**, which puts you back in vote units:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum((votes1 - mean(votes1))^2) / length(votes1)          # variance (population formula)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6666.667\n```\n\n\n:::\n\n```{.r .cell-code}\nsqrt(sum((votes1 - mean(votes1))^2) / length(votes1))    # SD — back to vote units\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 81.64966\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(votes1); sd(votes1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10000\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(votes2); sd(votes2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\nR's built-ins give slightly different answers *on purpose*: `var()` and `sd()` divide by **n − 1**, not n (10,000 vs. our hand-computed 6,666.7). *Why* is Session 4's simulation payoff — for now, file the IOU.\n\n### Seeing the machinery\n\nThe same three steps, drawn. First build one tidy table holding both scenarios plus their deviations and squared deviations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvotes_df <- tibble(\n  scenario = rep(c(\"Wide Spread\", \"Tight Cluster\"), each = 3),\n  candidate = factor(rep(1:3, times = 2)),\n  votes = c(votes1, votes2)\n) |>\n  mutate(dev = votes - mean(votes), sq_dev = dev^2, .by = scenario)\nvotes_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  scenario      candidate votes   dev sq_dev\n  <chr>         <fct>     <dbl> <dbl>  <dbl>\n1 Wide Spread   1           200  -100  10000\n2 Wide Spread   2           300     0      0\n3 Wide Spread   3           400   100  10000\n4 Tight Cluster 1           299    -1      1\n5 Tight Cluster 2           300     0      0\n6 Tight Cluster 3           301     1      1\n```\n\n\n:::\n:::\n\n\nRaw values — same dashed mean line, very different stories:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(votes_df, aes(candidate, votes)) +\n  geom_col(fill = \"steelblue\") +\n  geom_hline(yintercept = 300, color = \"firebrick\", linetype = \"dashed\", linewidth = 1) +\n  facet_wrap(~scenario) +\n  labs(title = \"Same mean (dashed line) — very different stories\",\n       x = \"Candidate\", y = \"Votes\")\n```\n\n::: {.cell-output-display}\n![](demo-02-descriptives_files/figure-html/machinery-raw-1.png){width=672}\n:::\n:::\n\n\nDeviations — notice the Tight Cluster bars are barely visible at this scale:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(votes_df, aes(candidate, dev)) +\n  geom_col(fill = \"steelblue\") +\n  geom_hline(yintercept = 0, color = \"grey40\") +\n  facet_wrap(~scenario) +\n  labs(title = \"How far is each value from the mean?\",\n       x = \"Candidate\", y = \"Deviation from mean\")\n```\n\n::: {.cell-output-display}\n![](demo-02-descriptives_files/figure-html/machinery-dev-1.png){width=672}\n:::\n:::\n\n\nSquared deviations — all positive, and the big misses dominate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(votes_df, aes(candidate, sq_dev)) +\n  geom_col(fill = \"steelblue\") +\n  facet_wrap(~scenario) +\n  labs(title = \"Squaring: all positive, and big misses dominate\",\n       x = \"Candidate\", y = \"Squared deviation\")\n```\n\n::: {.cell-output-display}\n![](demo-02-descriptives_files/figure-html/machinery-sq-1.png){width=672}\n:::\n:::\n\n\nAverage those bars and you have the variance; take the square root and you're back in the original units — the SD. In words: **\"on average, how far is each value from the mean?\"**\n\n## 4 · Distributions: the normal and the empirical rule\n\nA **distribution** is the shape of the data — how many observations fall at each value. The most famous shape is the normal, defined by just two numbers (mean and SD). Simulate one and look:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsims <- tibble(x = rnorm(n = 1000, mean = 100, sd = 10))\nggplot(sims, aes(x)) + geom_histogram(bins = 30, fill = \"grey80\", color = \"white\")\n```\n\n::: {.cell-output-display}\n![](demo-02-descriptives_files/figure-html/normal-hist-1.png){width=672}\n:::\n:::\n\n\nFor normal data, the SD comes with a promise — the **empirical rule**: about 68% of values within ±1 SD of the mean, 95% within ±2, 99.7% within ±3. The exact theoretical values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npct_within <- function(k) 100 * (pnorm(k) - pnorm(-k))\ntibble(k = 1:3, pct_within = round(pct_within(1:3), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n      k pct_within\n  <int>      <dbl>\n1     1       68.3\n2     2       95.4\n3     3       99.7\n```\n\n\n:::\n:::\n\n\n### The empirical rule, on real data\n\nDoes the promise hold outside a textbook? Count total crimes per day in the real Chicago data (365 days), then check what share of days land within 1, 2, and 3 SDs of the mean:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_crimes <- crimes |> count(date)\n\nm <- mean(daily_crimes$n)\ns <- sd(daily_crimes$n)\nc(mean = m, sd = s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    mean       sd \n82.19178 12.36160 \n```\n\n\n:::\n\n```{.r .cell-code}\ndaily_crimes |>\n  summarize(\n    within_1_sd = mean(n > m - 1*s & n < m + 1*s),\n    within_2_sd = mean(n > m - 2*s & n < m + 2*s),\n    within_3_sd = mean(n > m - 3*s & n < m + 3*s)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  within_1_sd within_2_sd within_3_sd\n        <dbl>       <dbl>       <dbl>\n1       0.682       0.956       0.992\n```\n\n\n:::\n:::\n\n\nAbout 68% / 96% / 99% — on a variable nobody simulated, the rule practically nails it. Daily *totals* of many small events pile up into a roughly bell-shaped heap (a preview of Session 4's central limit theorem), and once a variable is roughly normal, its mean and SD tell you almost everything: about 82 crimes on a typical day, and only about one day in twenty lands outside the 57–107 band. (Histogram `daily_crimes$n` yourself and you'll see the bell.)\n\n## 5 · The Poisson — and proof it's not hypothetical\n\nCounts of *rare* events (crimes per day, 911 calls per hour) follow a different, often skewed shape: the **Poisson**, with one parameter, λ = the expected number of events. Simulate a rare event (λ = 1):\n\n\n::: {.cell}\n\n```{.r .cell-code}\npois_sims <- tibble(x = rpois(n = 1000, lambda = 1))\nggplot(pois_sims, aes(x)) + geom_bar(fill = \"navy\")\n```\n\n::: {.cell-output-display}\n![](demo-02-descriptives_files/figure-html/poisson-hist-1.png){width=672}\n:::\n:::\n\n\nZero and one dominate, with a right tail — nothing like a bell. Now the real thing — robberies per day in our Chicago sample:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_robberies <- crimes |>\n  filter(primary_type == \"ROBBERY\") |>\n  count(date)\n\nggplot(daily_robberies, aes(n)) +\n  geom_bar(fill = \"firebrick\") +\n  labs(x = \"Robberies per day\", y = \"Number of days\",\n       title = \"Real crime counts look Poisson\")\n```\n\n::: {.cell-output-display}\n![](demo-02-descriptives_files/figure-html/chicago-poisson-1.png){width=672}\n:::\n:::\n\n\nMost days see one or two robberies, a handful see six or more — that skewed staircase is the Poisson shape, live in real data. (One honest footnote: `count(date)` only lists days with *at least one* robbery, so the zero-robbery days are missing from this plot — see the last variation prompt.)\n\nRecognizing shape is the point: bell-shaped variables and count variables call for different tools, and matching tool to shape is a theme for the whole semester.\n\n## Try a variation\n\n1. In the rainfall data, change one day to `10` inches. Which of the three \"typical\" measures move, and which barely budge? *(This is why we say the median is robust.)*\n2. In the votes demo, change `400` to `1000` and re-run the sum-of-squares chunk. Squaring emphasizes big misses — by how much did that one change inflate the total?\n3. Run the `summarize()` pattern on `areas$violent_rate`: mean, SD, min, max. The SD comes out roughly three-quarters the size of the mean — what does that say about how *unequally* violence is distributed across Chicago's communities?\n4. The robbery plot is missing its zero days: 2025 has 365 days, but `nrow(daily_robberies)` is smaller. How many zero-robbery days went missing, and where would that bar sit? Then swap in `primary_type == \"THEFT\"` — with a much higher λ, does the shape still look skewed?\n",
    "supporting": [
      "demo-02-descriptives_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}