{
  "hash": "4141ff822b1722ed3ad82240ad87ac12",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 7 · Real Questions, Real Tests\"\nsubtitle: \"CRJU 705 · Session 7\"\n---\n\n**Goal:** by the end of this lab you can take a real criminal justice dataset you have never seen, ask it a two-group question, and answer it with the same four steps every time. No new functions tonight. Everything here is something you already ran in Labs 5 and 6, pointed at data researchers actually use.\n\n**How labs work:** run the Setup chunk as-is, follow the Walkthrough along with me, then complete the **Your Turn** tasks in your own script. That script is what you submit to Canvas before you leave.\n\n## The recipe\n\nEvery question tonight, in lecture and here, runs the same four steps:\n\n1. **Question.** Name the two groups and the outcome. If the outcome is yes/no, the test is `prop.test()` (and `bayes_prop_test()`). If the outcome is a number, the test is `t.test()`.\n2. **Count or describe.** `count()` for a yes/no outcome; the group averages for a number.\n3. **Test.** Type the numbers in, or give `t.test()` the formula.\n4. **Say it.** The honest sentence, how big in real units, and one thing this test cannot tell you.\n\n## Setup\n\nOpen RStudio, start a new R script, and run:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nsource(\"https://smourtgos.github.io/crju705/R/bayes.R\")\n\n# Walkthrough: pretrial defendants scored by a risk-assessment tool\ncompas <- read_csv(\"https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv\",\n                   show_col_types = FALSE) |>\n  mutate(reoffended = factor(if_else(two_year_recid == 1, \"Reoffended\", \"Did not\"),\n                             levels = c(\"Reoffended\", \"Did not\")))\n\n# Your Turn: police stops in Minneapolis, 2017\nstops <- read_csv(\"https://smourtgos.github.io/crju705/data/mpls-stops.csv\",\n                  show_col_types = FALSE)\n\n# Your Turn: people killed in police shootings, 2015 to 2024\nshootings <- read_csv(\"https://raw.githubusercontent.com/washingtonpost/data-police-shootings/master/v2/fatal-police-shootings-data.csv\",\n                      show_col_types = FALSE) |>\n  mutate(crisis = factor(if_else(was_mental_illness_related, \"Crisis\", \"No crisis\"),\n                         levels = c(\"Crisis\", \"No crisis\")))\n```\n:::\n\n\nThree datasets, three `read_csv()` lines, the same line you have used all semester. Two of them come straight from the people who built them (ProPublica and the *Washington Post*), and one is a copy on our course site. Each `mutate()` line does what you did in Homework 5: it turns a 1/0 or TRUE/FALSE column into two labeled groups, with the group we care about first.\n\nWhen the first file loads, R prints a message that starts `New names:`. That file has two columns called `decile_score` and two called `priors_count`, and R renamed the second copy of each so it can tell them apart. Nothing is broken, and there is nothing to fix. Real data does this.\n\n## Walkthrough\n\n### The data\n\nIn 2013 and 2014, Broward County, Florida, used a commercial tool called **COMPAS** to score people arrested and awaiting trial. Each person got a label: Low, Medium, or High risk. ProPublica then checked who was arrested again within two years. One row is one defendant. `two_year_recid` is 1 if that person was arrested again within two years.\n\n### Question\n\n**Do people the tool labels High risk reoffend more often than people it labels Low risk?** Two groups (High, Low). A yes/no outcome (reoffended or not). So: `prop.test()`, then `bayes_prop_test()`.\n\n### Count\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompas |> count(score_text, two_year_recid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  score_text two_year_recid     n\n  <chr>               <dbl> <int>\n1 High                    0   402\n2 High                    1  1001\n3 Low                     0  2681\n4 Low                     1  1216\n5 Medium                  0   880\n6 Medium                  1  1034\n```\n\n\n:::\n:::\n\n\nFour numbers, two per group, High first:\n\n- **High:** 1,001 reoffended, out of 1,001 + 402 = **1,403**\n- **Low:** 1,216 reoffended, out of 1,216 + 2,681 = **3,897**\n\nWe are comparing only High and Low tonight, so the Medium rows sit out. Say so out loud whenever you leave a group aside.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1001 / 1403\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7134711\n```\n\n\n:::\n\n```{.r .cell-code}\n1216 / 3897\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3120349\n```\n\n\n:::\n:::\n\n\nAbout **71%** of people labeled High were arrested again, against about **31%** of people labeled Low.\n\n### Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(1001, 1216), n = c(1403, 3897))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(1001, 1216) out of c(1403, 3897)\nX-squared = 681.57, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.3731784 0.4296940\nsample estimates:\n   prop 1    prop 2 \n0.7134711 0.3120349 \n```\n\n\n:::\n:::\n\n\nHigh minus Low: the interval runs from about **37 to 43 points**, and the p-value is below 2.2e-16. Reject the null.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_prop_test(x = c(1001, 1216), n = c(1403, 3897))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBayesian test of two proportions \n\ndata, group 1:  1,001 of 1,403 (71.3%)\ndata, group 2:  1,216 of 3,897 (31.2%)\nprior:          know-nothing (1 yes, 1 no), same for both groups\n\n                         estimate      95% credible interval\ngroup 1                  71.3%         68.9% to 73.7%\ngroup 2                  31.2%         29.8% to 32.7%\ndifference (1 minus 2)   40.1 points   37.3 to 42.9 points\n\nProbability group 1 is higher than group 2: more than 0.99 \nProbability group 1 is lower than group 2:  less than 0.01 \n```\n\n\n:::\n:::\n\n\nCredible interval about **37 to 43 points**, and more than a 99% probability that the High group's rate is the higher one. With 5,300 people, the two traditions land on the same range.\n\n### Say it\n\n- **The sentence:** given these data, there is a 95% probability that the true gap in two-year re-arrest between people labeled High and Low is between about 37 and 43 percentage points.\n- **How big, in real units:** about 71 of every 100 people labeled High were arrested again within two years, compared with about 31 of every 100 labeled Low.\n- **What this test cannot tell you:** whether the tool is *good enough* to decide who stays in jail. Almost 3 in 10 people labeled High were *not* arrested again, and \"arrested again\" is not the same as \"committed a crime.\" A p-value cannot answer whether that error rate is acceptable. That is a question about values, not statistics.\n\n### Same data, a number instead of yes/no\n\nWere the people who reoffended younger? The outcome is now **age**, a number, so the test is `t.test()`. The `reoffended` column was set up in Setup with Reoffended first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(age ~ reoffended, data = compas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  age by reoffended\nt = -16.7, df = 7192.1, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Reoffended and group Did not is not equal to 0\n95 percent confidence interval:\n -5.081144 -4.013598\nsample estimates:\nmean in group Reoffended    mean in group Did not \n                32.31990                 36.86727 \n```\n\n\n:::\n:::\n\n\nReoffended minus Did not: about **4 to 5 years younger** (32.3 vs 36.9 on average), p below 2.2e-16.\n\nIn plain words: people who were arrested again were, on average, about four and a half years younger. That is one of the oldest findings in criminology (offending peaks young), showing up again in a dataset built for something else.\n\n## Your Turn\n\nYour question: **in Minneapolis, are people searched more often in stops for a suspicious person than in traffic stops?** `problem` is the reason for the stop (`suspicious` or `traffic`) and `personSearch` is whether the person was searched (`YES` or `NO`). Suspicious goes first all the way through. Work in your own script and comment each answer.\n\n**1.** Count. Run `stops |> count(problem, personSearch)`. In a comment, write the four numbers you need: how many people were searched in suspicious-person stops, out of how many, and the same for traffic stops. Some rows say `NA`: no search was recorded either way. Leave them out of both totals. Then compute the two rates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n**2.** The frequentist test. Put your four numbers into `prop.test(x = c(__, __), n = c(__, __))`, suspicious first. In a comment, report the confidence interval for the difference in percentage points and the p-value. Reject or fail to reject?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n**3.** The Bayesian test. Same four numbers into `bayes_prop_test()`. In a comment, report the credible interval for the difference and the probability that suspicious-person stops have the higher search rate. Then write the one sentence this output lets you say that Task 2's output does not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n**4.** Say it. In a comment, state the size of the difference in plain words a city council member would understand (no p-values, no intervals). Then name one thing this comparison cannot tell you.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# a comment-only task\n```\n:::\n\n\n**5.** A t-test on a different dataset. Among people killed in police shootings, were those in a mental health crisis older or younger than everyone else? Run `t.test(age ~ crisis, data = shootings)`. In a comment: the two average ages, the confidence interval for the difference in years, the p-value, and one sentence in plain words.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n**6.** *(Stretch)* Suppose a report from another city found about 1 person in 10 searched across all stops, and you trust it about as much as having seen 50 stops: `prior = c(5, 45)`. Rerun Task 3 with it. In a comment: how much did anything move, and why?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\nWhen you are done, submit your script to Canvas. The in-class exercise is graded on completing it.\n",
    "supporting": [
      "lab-07-workshop_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}