{
  "hash": "a60b31d84282e34a87f12b13f28c5fd5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Practice Problems · Session 5\"\nsubtitle: \"Confidence intervals: building them, reading them, saying them honestly\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Ungraded self-checks.** Work each problem in your own R session *before* clicking the solution. These use different numbers and variables than the homework on purpose — if you can do these cold, Homework 5 (and the midterm's inference questions) will feel routine.\n:::\n\n\n\nAll problems that use data need only:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nprisoners <- read_csv(\"https://smourtgos.github.io/crju705/data/prisoners.csv\")\ncrimes    <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-crimes-2025.csv\")\n```\n:::\n\n\n## Problem 1 · The margin of error, by hand\n\nUsing `prisoners` (300 records), build a 95% CI for the mean of `months_served` with nothing but Session 4 parts: the sample mean, the standard error (`sd / sqrt(n)`), and ±1.96. Then check yourself against `t.test(prisoners$months_served)$conf.int`.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm  <- mean(prisoners$months_served)\nse <- sd(prisoners$months_served) / sqrt(nrow(prisoners))\n\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36.45667\n```\n\n\n:::\n\n```{.r .cell-code}\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.456781\n```\n\n\n:::\n\n```{.r .cell-code}\nc(lo = m - 1.96 * se, hi = m + 1.96 * se)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      lo       hi \n33.60138 39.31196 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(prisoners$months_served)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 33.58982 39.32351\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nBy hand: 33.6 to 39.3 months. `t.test()` agrees to a decimal (it uses the t-distribution's 1.97 instead of the normal's 1.96 — with n = 300 that's a rounding error). The whole machine is just **estimate ± 1.96 × SE**: last week's standard error, cashed in.\n:::\n\n## Problem 2 · A proportion with `prop.test()`\n\nWhat share of these 300 prison records are **drug offenses**? Get the point estimate and a 95% CI with `prop.test()`. One warning: the output prints a p-value testing whether the proportion equals 0.5 — that's not a question anyone asked. Read past it to the interval.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprisoners |> summarize(prop_drug = mean(offense_type == \"Drug\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  prop_drug\n      <dbl>\n1     0.297\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(sum(prisoners$offense_type == \"Drug\"), n = nrow(prisoners))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  sum(prisoners$offense_type == \"Drug\") out of nrow(prisoners), null probability 0.5\nX-squared = 48.803, df = 1, p-value = 2.83e-12\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.2462485 0.3523909\nsample estimates:\n        p \n0.2966667 \n```\n\n\n:::\n:::\n\n\nPoint estimate 29.7%, 95% CI **24.6% to 35.2%**. With only 300 records, the **confidence interval** spans about ±5 points — honest uncertainty that the lone number \"29.7%\" hides.\n:::\n\n## Problem 3 · Which sentence survives?\n\nFour draft sentences about Problem 2's interval. Exactly **one** is defensible — which, and what's wrong with each of the others?\n\n> (a) \"There is a 95% probability that the true proportion of drug offenses is between 24.6% and 35.2%.\"\n>\n> (b) \"We estimate that 29.7% of admissions are drug offenses (95% CI: 24.6% to 35.2%); the procedure that built this interval captures the true share 95% of the time.\"\n>\n> (c) \"If we drew many new samples of 300, 95% of their sample proportions would land between 24.6% and 35.2%.\"\n>\n> (d) \"We are 95% sure our sample's proportion is correct.\"\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(prop.test(sum(prisoners$offense_type == \"Drug\"),\n                n = nrow(prisoners))$conf.int, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.246 0.352\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n**(b) survives.** (a) attaches a probability to *this particular* interval — under frequentist rules the truth is fixed, so it's either in there or it isn't; the 95% belongs to the procedure. (c) confuses the interval with the sampling distribution: future samples produce *new* intervals around *their own* estimates, not values inside this one. (d) is doubly wrong — the sample proportion is known exactly (29.7%); the uncertainty is entirely about the *population*. **Confidence-interval interpretation** in one line: the 95% describes the long-run capture rate of the method, never the odds on one interval.\n:::\n\n## Problem 4 · Buy precision with n\n\nUsing `crimes`, estimate the proportion of incidents classified as **Violent** (`crime_category == \"Violent\"`) from a random sample of **300**, then from a sample of **1,200** — `slice_sample()`, then `prop.test()` for each. Before you run it: quadrupling n should do what to the CI's width? Verify.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)\nmap(c(300, 1200), \\(n) {\n  s  <- crimes |> slice_sample(n = n)\n  ci <- prop.test(sum(s$crime_category == \"Violent\"), n = n)$conf.int\n  tibble(n = n, estimate = mean(s$crime_category == \"Violent\"),\n         lo = ci[1], hi = ci[2], width = ci[2] - ci[1])\n}) |>\n  list_rbind()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n      n estimate    lo    hi  width\n  <dbl>    <dbl> <dbl> <dbl>  <dbl>\n1   300    0.3   0.249 0.356 0.106 \n2  1200    0.299 0.274 0.326 0.0526\n```\n\n\n:::\n:::\n\n\nThis run: width ≈ 0.106 at n = 300 vs ≈ 0.053 at n = 1,200 — quadrupling the sample cut the width almost exactly in half, because **CI width shrinks with √n**. Precision is bought on a square-root discount: four times the data for twice the precision.\n:::\n\n## Problem 5 · Two groups, one honest sentence\n\nDo **drug** and **property** offenders differ in time served? Filter `prisoners` to those two offense types, compare the group means of `months_served`, then run `t.test(months_served ~ offense_type, ...)`. Careful on two fronts: which direction is R subtracting, and does the CI include zero? Finish with a one-sentence report a warden could read.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndp <- prisoners |> filter(offense_type %in% c(\"Drug\", \"Property\"))\n\ndp |> summarize(mean_months = mean(months_served), sd_months = sd(months_served),\n                n = n(), .by = offense_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  offense_type mean_months sd_months     n\n  <chr>              <dbl>     <dbl> <int>\n1 Property            37.1      26.6    74\n2 Drug                33.1      24.5    89\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(months_served ~ offense_type, data = dp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  months_served by offense_type\nt = -0.98293, df = 150.35, p-value = 0.3272\nalternative hypothesis: true difference in means between group Drug and group Property is not equal to 0\n95 percent confidence interval:\n -11.953437   4.011439\nsample estimates:\n    mean in group Drug mean in group Property \n              33.12360               37.09459 \n```\n\n\n:::\n:::\n\n\nR orders groups alphabetically, so this is **Drug − Property**: the point estimate says drug offenders served about 4 fewer months, but the 95% CI runs from **−12.0 to +4.0 months — zero sits comfortably inside**. The honest sentence: \"Drug offenders in our sample averaged about four fewer months served than property offenders, but with 163 records the data are consistent with anything from 12 fewer months to 4 more — including no difference at all.\" A **two-group CI** that crosses zero doesn't prove the groups are equal; it says this sample can't settle the direction. (Compare the homework's crash data, where the interval excluded zero — learn to say both outcomes out loud.)\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}