{
  "hash": "d88dce14da4a2e82ffe2fd9f97403cf3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic Regression: Yes/No Outcomes\"\nsubtitle: \"CRJU 705 · Session 11 · Fall 2026\"\nauthor: \"Scott M. Mourtgos\"\nformat:\n  revealjs:\n    slide-number: true\n    preview-links: auto\n    chalkboard: true\n    footer: \"CRJU 705 · Session 11\"\n    theme: [default, custom-slides.scss]\n    fig-align: center\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n## This Week\n\n**Topic:** logistic regression: modeling outcomes that are *yes or no*\n\n- Why `lm()` breaks when the outcome is 0/1\n- Odds, log-odds, and the **odds ratio**: the currency of logistic regression\n- `glm(family = binomial)`, predicted probabilities, and the Bayesian version with `brms`\n\n**Learning goals:** fit a logistic regression in both traditions; translate coefficients into odds ratios *and* predicted probabilities; say the results in plain language without confusing odds with probability.\n\n**Also today:** the course pays off a promise it made in Session 1.\n\n## Where We've Been\n\n::: incremental\n- **Session 8:** correlation: how two continuous variables move together\n- **Session 10:** multiple regression: a *plane* through a 3D cloud of points, minimizing squared error, each coefficient's effect holding the others constant (and lurking variables like the ice-cream/drowning lurker handled by putting them *in* the model)\n- Every model so far predicted a **number**: a crime rate, an incident hour, an exam score\n- **Today:** what happens when the outcome only has two values: arrest or no arrest, reoffend or desist, hit again or not?\n:::\n\n# The Problem: Yes/No Outcomes {background-color=\"#73000A\"}\n\n## Criminal Justice Runs on Binary Outcomes\n\n- Was an **arrest** made?\n- Does the defendant **fail to appear**?\n- Is the parolee **re-arrested** within three years?\n- Did the crash involve an **intoxicated driver**?\n- Is this neighborhood a **high-violence** area?\n\n. . .\n\nLinear regression predicts *continuous* outcomes (crime rates, response times). **Logistic regression predicts binary outcomes**: its currency is **probability (0 to 1)**, expressed along the way as odds and log-odds.\n\n## Session 1 Made You a Promise\n\nRemember the opening case study? **40 bank robberies, five zones**, one question: *where will they hit next?*\n\n::: incremental\n- We built `future_hit` = 1 if the same zone was hit again within 10 days, 0 otherwise\n- We fit a model, showed you a coefficient table nobody could read yet, and sent the patrol cars to the **West Zone**: where the robber was caught\n- That slide said: *\"Don't worry about the machinery today: logistic regression is Session 11.\"*\n:::\n\n. . .\n\n**Today is Session 11.** Let's reopen the machinery.\n\n\n\n## The Machinery, Reopened\n\nThe exact model from Session 1: one function, one `family` argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrobbery_model <- glm(\n  future_hit ~ 0 + scale(day_of_year) + prior_robberies_in_zone + zone,\n  data = robberies, family = binomial\n)\n```\n:::\n\n\n- `glm()` = *generalized* linear model: regression's family business\n- `family = binomial` is the switch that makes it **logistic**: predict a 0/1 outcome\n- Everything else looks exactly like the `lm()` formulas from Session 10\n\n::: aside\nTwo formula details you can safely skim: `0 +` drops the global intercept so each zone gets its own baseline, and `scale()` puts day-of-year on a standard scale. Read the *table*, not the formula: today is about the `family` switch.\n:::\n\n## The Table You Couldn't Read in August\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                    | estimate| std.error| statistic| p.value| odds_ratio|\n|:-----------------------|--------:|---------:|---------:|-------:|----------:|\n|scale(day_of_year)      |    0.034|     1.055|     0.032|   0.975|      1.034|\n|prior_robberies_in_zone |   -0.033|     0.194|    -0.171|   0.864|      0.967|\n|zoneNorth               |  -17.528|  3956.181|    -0.004|   0.996|      0.000|\n|zoneSouth               |  -17.563|  2284.020|    -0.008|   0.994|      0.000|\n|zoneEast                |   -1.309|     1.328|    -0.986|   0.324|      0.270|\n|zoneWest                |    1.114|     2.053|     0.543|   0.587|      3.047|\n|zoneDowntown            |   -0.979|     1.149|    -0.852|   0.394|      0.376|\n\n\n:::\n:::\n\n\n## Reading It With Today's Eyes\n\n::: incremental\n- The `estimate` column is in **log-odds**: that's why it looked like gibberish in August; by the end of today it won't\n- `exp(estimate)` turns each one into an **odds ratio**: West's is by far the largest, which is why West had the highest predicted probability of a repeat hit. *That's* why the cars went west.\n- Those -17.5s with standard errors in the thousands? North and South never saw a repeat hit within 10 days: with **zero events**, the model can't estimate their log-odds. 39 robberies is small data, and the output says so honestly.\n:::\n\n## Logistic vs. Linear: The Road and the Hill\n\nLinear regression is a **straight road**: it keeps going forever in both directions. Logistic regression is a **curved hill** that flattens at 0 and 1, because probabilities can't go below 0 or above 1.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-12-logistic_files/figure-revealjs/road-hill-1.png){width=960}\n:::\n:::\n\n\n## Watch Linear Regression Fail\n\nPredicting *graduated the academy (yes/no)* from study hours:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-12-logistic_files/figure-revealjs/linear-fails-1.png){width=960}\n:::\n:::\n\n\n## What Went Wrong\n\n::: incremental\n- The linear model happily predicts values like **1.2** and **-0.3**: probabilities that cannot exist\n- Inside the middle of the data the two lines nearly agree; the damage is at the edges: exactly where predictions get used (\"what about a recruit who studies *a lot*?\")\n- The fix is the **logit transformation**: instead of modeling the probability directly, model something built from it that a straight line *can* live on\n- (The full derivation is Ph.D.-stats material: what you need is the ladder on the next slides)\n:::\n\n# Odds and Log-Odds {background-color=\"#1B2A4A\"}\n\n## The Model You Already Know\n\n$$Y = b_0 + b_1 X_1 + b_2 X_2 + \\varepsilon$$\n\n- $Y$: outcome (dependent variable)\n- $b_0$: intercept (value of $Y$ when all X's are zero)\n- $b_1, b_2$: slope coefficients (effect of each X, **holding the others constant**)\n- $\\varepsilon$: error term (what's left unexplained)\n\n. . .\n\nThe right-hand side is an unbounded straight line. Probability is trapped in [0, 1]. Something has to give.\n\n## Step 1: Probability to Odds\n\nSuppose 3 out of 4 parolees complete supervision: $p = 0.75$.\n\n$$\\text{odds} = \\frac{p}{1-p} = \\frac{0.75}{0.25} = 3 \\quad \\text{(\"three to one\")}$$\n\n| Probability | Odds | Log-odds |\n|:---:|:---:|:---:|\n| 0.25 | 0.33 | -1.10 |\n| 0.50 | 1.00 | 0.00 |\n| 0.75 | 3.00 | +1.10 |\n\n**Step 2, odds to log-odds:** odds run 0 to ∞; *log*-odds run -∞ to +∞. That's a scale a straight line can live on.\n\n## The Logistic Model\n\nJust treat logit($p$), the log-odds, as your Y. Then...\n\n$$\\text{logit}(p) = \\ln\\!\\left(\\frac{p}{1-p}\\right) = b_0 + b_1 X_1 + b_2 X_2$$\n\n- Same intercept, same slopes, same \"holding the others constant\"\n- The line now predicts **log-odds**, which convert back to a probability that politely stays between 0 and 1: the curved hill\n\n. . .\n\n::: {.callout-important appearance=\"simple\"}\n**But the coefficients are log-odds!!!** Nobody thinks in log-odds. So what do we do with them?\n:::\n\n## What Do We Do With Log-Odds?\n\n<br>\n\n::: {.r-fit-text}\n**EXPONENTIATE!**\n:::\n\n<br>\n\n`exp(coefficient)` = the **odds ratio**: *multiply the odds of the outcome by this much for each one-unit increase in X, holding the other predictors constant.*\n\n## The Odds-Ratio Rosetta Stone: Odds Shrink {.smaller}\n\n| Log-odds coefficient (β) | Odds ratio (e^β^) | Effect on odds | Intuitive interpretation |\n|:---:|:---:|:---:|:---|\n| -2.0 | 0.14 | ↓ 86% | Odds are 86% lower than baseline |\n| -1.0 | 0.37 | ↓ 63% | Odds are 63% lower than baseline |\n| -0.5 | 0.61 | ↓ 39% | Odds are 39% lower than baseline |\n| 0.0 | 1.00 | No change | Odds unchanged |\n\nNegative log-odds → ratio **below 1** → odds shrink. Zero → ratio of exactly 1 → nothing happens.\n\n## The Odds-Ratio Rosetta Stone: Odds Grow {.smaller}\n\n| Log-odds coefficient (β) | Odds ratio (e^β^) | Effect on odds | Intuitive interpretation |\n|:---:|:---:|:---:|:---|\n| 0.0 | 1.00 | No change | Odds unchanged |\n| 0.3 | 1.35 | ↑ 35% | Odds are 35% higher than baseline |\n| 0.7 | 2.01 | ↑ 101% | Odds are about twice as high |\n| 1.0 | 2.72 | ↑ 172% | Odds are 2.7× higher |\n| 2.0 | 7.39 | ↑ 639% | Odds are over seven times higher |\n\nPositive log-odds → ratio **above 1** → odds grow.\n\n# Fitting It: glm() {background-color=\"#73000A\"}\n\n## Two Traditions, Same Curve\n\n| Approach | What it estimates | Interpretation |\n|:---|:---|:---|\n| **Frequentist** | Point estimates and confidence intervals | \"If we repeated this 100 times, 95% of the intervals would contain the true β.\" |\n| **Bayesian** | Posterior distributions for each β | \"Given our data and priors, there's a 95% probability β lies in this range.\" |\n\nExactly the split you know from Sessions 6 and 10: nothing new, just a new model underneath it.\n\n## The Frequentist Version\n\nToy data first: 32 cars from a 1974 *Motor Trend* issue, predicting **manual transmission (1) vs. automatic (0)** from horsepower and weight. Small enough to check every number; real CJ data in a few minutes.\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\ndata(mtcars)\ncars_df <- mtcars |>\n  rownames_to_column(\"car\") |>\n  mutate(am = as.factor(am))   # 0 = automatic, 1 = manual\n\nmodel_freq <- glm(am ~ hp + wt, data = cars_df, family = binomial)\nsummary(model_freq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = am ~ hp + wt, family = binomial, data = cars_df)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept) 18.86630    7.44356   2.535  0.01126 * \nhp           0.03626    0.01773   2.044  0.04091 * \nwt          -8.08348    3.06868  -2.634  0.00843 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 43.230  on 31  degrees of freedom\nResidual deviance: 10.059  on 29  degrees of freedom\nAIC: 16.059\n\nNumber of Fisher Scoring iterations: 8\n```\n\n\n:::\n:::\n\n\n## Reading the Output: Exponentiate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(model_freq))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         (Intercept)                   hp                   wt \n156145483.5063250661         1.0369208455         0.0003085967 \n```\n\n\n:::\n:::\n\n\n::: incremental\n- `hp`: log-odds 0.036 → **odds ratio 1.037**; each additional horsepower multiplies the odds of a manual transmission by about 1.04 (+3.7%), *holding weight constant*\n- `wt`: log-odds -8.08 → **odds ratio 0.0003**; each additional 1,000 lbs cuts the odds by ~99.97%, *holding horsepower constant*\n- Wildly different sizes partly because the **units** differ: one horsepower is a nudge; a thousand pounds is a different car\n:::\n\n## From Effects to Cases: predict()\n\nOdds ratios describe *effects*. For an actual *case*, ask for the probability directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_cars <- cars_df |>\n  filter(car %in% c(\"Honda Civic\", \"Cadillac Fleetwood\")) |>\n  select(car, hp, wt)\n\ntwo_cars |>\n  mutate(p_manual = predict(model_freq, newdata = two_cars, type = \"response\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 car  hp    wt         p_manual\n1 Cadillac Fleetwood 205 5.250 0.00000009787752\n2        Honda Civic  52 1.615 0.99954591741880\n```\n\n\n:::\n:::\n\n\n. . .\n\n`type = \"response\"` returns probabilities: the light Civic is a near-certain manual (99.95%); the 5,250-lb Fleetwood, near-certain automatic. **Report both:** odds ratios for effects, predicted probabilities for cases.\n\n# Seeing It: The Curved Surface {background-color=\"#1B2A4A\"}\n\n## Session 10's Plane, Bent\n\n::: incremental\n- Last session: two predictors + linear regression = a **flat plane** floating through the 3D cloud\n- Same two predictors + logistic regression = a **curved sheet**: a plateau near probability 1, a floor near 0, and an S-shaped cliff between them\n- The surface *is* the model: its height at any (hp, wt) combination is the predicted probability of a manual transmission there\n- Let's build it from nothing but `predict()`\n:::\n\n## Building the Surface\n\nAsk the model for a prediction at every combination of horsepower and weight: a 40 × 40 grid, 1,600 predictions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhp_seq <- seq(min(cars_df$hp), max(cars_df$hp), length.out = 40)\nwt_seq <- seq(min(cars_df$wt), max(cars_df$wt), length.out = 40)\ngrid   <- expand.grid(hp = hp_seq, wt = wt_seq)\n\ngrid$prob <- predict(model_freq, newdata = grid, type = \"response\")\n\n# Reshape the 1,600 predictions into a grid; t() puts rows on the\n# wt (y) axis and columns on the hp (x) axis, which is what plotly expects\nz_matrix <- t(matrix(grid$prob, nrow = length(hp_seq), ncol = length(wt_seq)))\n```\n:::\n\n\nThe observed cars sit at height 0 (automatic) or 1 (manual); the surface passes between them.\n\n## The 3D Logistic Surface\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\ndata_points <- cars_df |>\n  mutate(prob = as.numeric(as.character(am)))   # 0 = auto, 1 = manual\n\nplot_ly(width = 950, height = 520) |>\n  add_markers(data = data_points,\n              x = ~hp, y = ~wt, z = ~prob,\n              color = ~am, colors = c(\"steelblue\", \"firebrick\"),\n              symbol = I(\"circle\"), size = I(50),\n              name = \"Observed Data\") |>\n  add_surface(x = hp_seq, y = wt_seq, z = z_matrix,\n              colorscale = list(c(0, 'lightblue'), c(1, 'firebrick')),\n              opacity = 0.6,\n              name = \"Predicted Probability Surface\") |>\n  layout(\n    title = \"Logistic Regression: Curved Probability Surface\",\n    scene = list(\n      xaxis = list(title = \"Horsepower (hp)\"),\n      yaxis = list(title = \"Weight (1000 lbs)\"),\n      zaxis = list(title = \"Probability (Manual Transmission)\")\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-185b6a3cbd0da17bc15e\" style=\"width:950px;height:520px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-185b6a3cbd0da17bc15e\">{\"x\":{\"visdat\":{\"c76b3b36ce2f\":[\"function () \",\"plotlyVisDat\"],\"c76bb1a8e08\":[\"function () \",\"data\"]},\"cur_data\":\"c76bb1a8e08\",\"attrs\":{\"c76bb1a8e08\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"z\":{},\"type\":\"scatter3d\",\"mode\":\"markers\",\"color\":{},\"colors\":[\"steelblue\",\"firebrick\"],\"symbol\":[\"circle\"],\"size\":[50],\"name\":\"Observed Data\",\"inherit\":true},\"c76bb1a8e08.1\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"z\":[[0.99980085770222293,0.99984691700557438,0.99988232458020954,0.99990954324448533,0.99993046659096252,0.99994655046443726,0.99995891410672744,0.99996841795199254,0.99997572345435182,0.99998133909262321,0.99998565574292131,0.99998897387455343,0.99999152445829864,0.9999934850401353,0.99999499209793485,0.9999961505404682,0.99999704100948383,0.99999772549289101,0.99999825163962452,0.99999865607646676,0.99999896695765944,0.99999920592476121,0.99999938961315982,0.99999953081010384,0.9999996393448598,0.99999972277295823,0.99999978690216051,0.99999983619675681,0.99999987408834257,0.99999990321470422,0.99999992560344608,0.99999994281313953,0.99999995604182146,0.99999996621039455,0.99999997402673468,0.99999998003496926,0.99999998465335616,0.9999999882034003,0.99999999093223468,0.99999999302982467],[0.99955217687469111,0.99965573336353608,0.99973534935800912,0.99979655689841063,0.99984361077219752,0.99987978297539282,0.99990758946586655,0.9999289647043289,0.99994539596240339,0.99995802664632216,0.99996773576920339,0.99997519906894095,0.999980936005468,0.99998534589671917,0.99998873570155811,0.99999134137944434,0.99999334431122155,0.99999488392264024,0.99999606738850022,0.99999697709243107,0.99999767636130643,0.99999821387330523,0.99999862704637266,0.9999989446429034,0.99999918877193128,0.99999937642818304,0.99999952067512321,0.9999996315543398,0.99999971678457,0.99999978229902842,0.9999998326584385,0.99999987136852131,0.99999990112404236,0.99999992399640392,0.99999994157784444,0.99999995509227957,0.99999996548050418,0.99999997346568537,0.99999997960370401,0.99999998432185289],[0.99899326620807183,0.99922596744799708,0.9994049130564493,0.99954250785897636,0.99964829946465583,0.99972963417687954,0.99979216323101028,0.99984023314335013,0.99987718648263413,0.99990559349149943,0.99992743038005438,0.99994421652468823,0.9999571200174836,0.99996703885152394,0.99997466335683227,0.99998052421155026,0.99998502935771794,0.99998849238389764,0.9999911543459673,0.9999932005424591,0.99999477341067189,0.99999598244037835,0.9999969117947124,0.99999762616843402,0.99999817529119739,0.99999859738920027,0.99999892184612649,0.99999917124858306,0.99999936295839742,0.9999995103212167,0.99999962359553662,0.99999971066682647,0.99999977759646408,0.99999982904368889,0.99999986858994916,0.99999989898821984,0.99999992235464807,0.9999999403158657,0.99999995412222653,0.99999996473484754],[0.99773837913595964,0.99826063591663794,0.99866245407569576,0.99897154208551331,0.99920926076788352,0.99939206637957734,0.99953263017571925,0.99964070510006608,0.99972379560942093,0.99978767469574037,0.99983678257780195,0.99987453391688008,0.99990355441025669,0.99992586291765573,0.99994301161277543,0.99995619380622514,0.99996632688070708,0.9999741160733826,0.99998010352280942,0.99998470598135492,0.99998824381044715,0.99999096327244652,0.99999305366818581,0.99999466051155639,0.9999958956573044,0.99999684508650455,0.99999757489134899,0.99999813587567943,0.99999856709140422,0.99999889855691682,0.99999915334671319,0.99999934919765088,0.99999949974365543,0.99999961546481519,0.99999970441693353,0.99999977279231944,0.99999982535085696,0.99999986575135691,0.99999989680626156,0.99999992067742849],[0.99492722642667175,0.99609609869794546,0.99699645162595596,0.99768963866230886,0.99822313061969148,0.99863360118314548,0.99894934967514737,0.99919219378313451,0.99937894254228377,0.99952253932591506,0.9996329468085251,0.99971783099330669,0.99978308924509807,0.9998332575010741,0.99987182406750386,0.99990147129134443,0.99992426160152781,0.99994178067652151,0.99995524758962018,0.99996559953163344,0.99997355696866463,0.9999796737471236,0.99998437561994491,0.99998798986768145,0.99999076807161602,0.99999290362132132,0.99999454517372977,0.99999580699964208,0.99999677693733979,0.99999752250663154,0.99999809560874875,0.99999853613914647,0.99999887476463734,0.99999913505814497,0.99999933513965844,0.99999948893760815,0.99999960715846203,0.99999969803203637,0.99999976788440048,0.99999982157825607],[0.98866157179742087,0.99126150046444383,0.99326931792700557,0.99481821709211471,0.99601210669690998,0.99693177095015351,0.99763985026137336,0.99818481807971704,0.99860412675993426,0.99892667890401177,0.9991747587359594,0.99936553557249685,0.99951223071374351,0.999625021054242,0.9997117376088297,0.99977840478742819,0.99982965630472176,0.99986905569775497,0.99989934318387885,0.99992262570061663,0.9999405231539048,0.99995428093561023,0.99996485647216249,0.99997298578735394,0.99997923468822136,0.99998403812261327,0.9999877304396233,0.99999056865432512,0.99999275033333646,0.99999442734451471,0.99999571642689911,0.99999670731609247,0.9999974689903558,0.99999805447201418,0.99999850451828998,0.9999988504584213,0.99999911637452565,0.99999932077799936,0.99999947789813926,0.99999959867268318],[0.97485248127697821,0.98055659459008493,0.9849867919898988,0.98841948637721633,0.9910744246615345,0.99312492781900086,0.99470687770757693,0.99592631500766138,0.99686570177076073,0.9975889915108026,0.99814568098616141,0.99857401745537833,0.99890351948341038,0.99915694770208752,0.99935183936979044,0.99950169964449398,0.99961692422527648,0.99970551267766861,0.99977361918597296,0.99982597734560319,0.99986622754419496,0.99989716911645188,0.99992095446808649,0.99993923847076915,0.99995329340280692,0.9999640973629812,0.99997240226861184,0.99997878614559221,0.99998369333522652,0.99998746540779071,0.99999036492949711,0.99999259373422145,0.99999430697009584,0.99999562389770846,0.99999663619096435,0.9999974143180792,0.99999801244668729,0.99999847221439242,0.99999882562716713,0.99999909728732161],[0.94515819009870816,0.95730273990250525,0.96685223592639191,0.97432321688927725,0.98014493606524244,0.98466746357080703,0.98817229405566465,0.99088338073049753,0.99297746207890603,0.99459315900997902,0.99583868538981468,0.99679821447128958,0.99753703951319261,0.99810570166005663,0.99854325963367108,0.99887986090433489,0.99913875258722051,0.99933784770264023,0.9994909413224452,0.99960865263190291,0.9996991533616274,0.99976873025790092,0.99982221894513212,0.99986333831612317,0.99989494809668955,0.99991924714097935,0.99993792604056198,0.99995228454029095,0.99996332185744907,0.99997180614596648,0.99997832791439534,0.99998334110032228,0.99998719465114227,0.99999015680408865,0.99999243375245483,0.99999418399549533,0.99999552936980962,0.99999656352947053,0.99999735846483129,0.99999796951357367],[0.88455311209594867,0.90882381007164303,0.92840500783225333,0.94403984307986422,0.95642062852636223,0.96616044004588519,0.97378311296487607,0.97972474206492655,0.98434145106462478,0.98791988976735712,0.99068828609521364,0.99282685614248223,0.99447701071819594,0.99574917880441194,0.99672927881183337,0.99748397088622709,0.99806486204630074,0.99851183936786547,0.99885569243278882,0.99912016512340918,0.9993235542056208,0.99947995084870167,0.99960020250494108,0.99969265676134833,0.99976373577331612,0.9998183793885137,0.99986038669498856,0.99989267911079915,0.99991750293986703,0.99993658526406659,0.99995125388740669,0.99996252960143994,0.99997119714719118,0.9999778597853658,0.99998298125703711,0.99998691804602247,0.9999899441830461,0.99999227031496996,0.9999940583645478,0.999995432800029],[0.77305535217184052,0.81588757400483813,0.85218163899788468,0.88235272574103307,0.90703740017471779,0.92697142275072397,0.94290006822347949,0.9555211397609501,0.9654547222008274,0.97323196023034264,0.97929584331511965,0.98400861920021965,0.98766216640033622,0.99048905653005714,0.99267304413128821,0.99435838151304146,0.99565775539785351,0.99665886391630532,0.99742976175262232,0.99802314370578282,0.99847974243373383,0.99883100310501638,0.99910117686535405,0.99930895237654482,0.99946872321898272,0.99959156999405063,0.99968601991499695,0.99975863345424409,0.99981445692396553,0.99985737133378927,0.99989036112310792,0.9999157210684958,0.99993521552912956,0.99995020097355125,0.99996172023318053,0.99997057499418052,0.99997738154471916,0.99998261364103336,0.99998663546610489,0.99998972696926325],[0.60229025730997376,0.66331506666915419,0.71933956402074417,0.76928413794101524,0.81265562775690314,0.84946925901339421,0.88011608460085922,0.90521963947387607,0.92551143534241398,0.94173851155736532,0.95460396654007185,0.96473482393683607,0.97266954591216137,0.97885806751393756,0.98366883016802154,0.98739901476121961,0.99028560612993877,0.9925159588277197,0.99423721901690409,0.99556437448553414,0.99658693825943223,0.99737438772987341,0.99798052780734758,0.99844695430350028,0.99880578172263013,0.99908177918662944,0.99929403557354013,0.99945725332136515,0.99958275116598894,0.99967923979691919,0.99975342097359843,0.99981044976192013,0.99985429085645983,0.9998879930755904,0.99991390071342368,0.99993381621038058,0.99994912531796076,0.99996089338308514,0.99996993940282286,0.9999768929740539],[0.40236743465371172,0.46691716521809201,0.53259384354756756,0.59716009050126073,0.65852577877633256,0.71500480819293966,0.76546926836414464,0.80938020237485664,0.84671606080367479,0.87784280866019393,0.90337012148358564,0.92402465214247198,0.94055481558935272,0.95366879784054204,0.96400048291545859,0.97209565370155171,0.97841123929171347,0.98332194358101743,0.98713032353995467,0.99007784727993775,0.99235553164965218,0.9941134697730305,0.99546899453517679,0.99651346965349796,0.99731782391979795,0.9979369951195991,0.99841346013944521,0.99878001684763873,0.99906196327582675,0.99927879701206657,0.99944553593397811,0.99957374200283222,0.99967231331626993,0.99974809595412295,0.99980635607421164,0.99985114385724472,0.99988557388738764,0.99991204104364928,0.99993238666894813,0.9999480264294901],[0.23036738606613849,0.28026400611400737,0.33624635967077854,0.39723928224128441,0.46160175688474731,0.52727028291493239,0.59200857550071317,0.65370393094077905,0.71063003468716834,0.76161086727071481,0.8060611776308465,0.84392175895217358,0.87553252235857826,0.90148844014877849,0.92251067757360761,0.93934861937421343,0.95271531869493342,0.9632514328953321,0.97151006372003712,0.97795518017120719,0.98296781643553488,0.98685597927420621,0.9898656906245219,0.99219169262468765,0.99398707922445262,0.99537157314986258,0.99643842523483483,0.99726004489787279,0.99789252600253786,0.99837924478737783,0.99875369679737103,0.99904172013261849,0.99926322976186854,0.99943356572264841,0.99956453840015846,0.99966523731561174,0.99974265596731293,0.99980217399324467,0.99984792890005847,0.99988310245431344],[0.11744350609536325,0.14757107558422339,0.18381752087333744,0.22660019008400761,0.27597343618490522,0.33149348465201278,0.39213360351969478,0.45629506482356341,0.52194051382012818,0.58683676232166559,0.64885030219237294,0.70621569955306718,0.75770908143822491,0.80269845025094344,0.84108607850865102,0.87318485498546772,0.89957419011397355,0.92096911410314786,0.93811955858616614,0.95174321020779318,0.96248740371522623,0.97091255248582831,0.97748970852798123,0.98260630307183505,0.98657586631338812,0.9896490450363592,0.99202437036399904,0.99385799169255373,0.99527206705075055,0.99636177145005544,0.99720102470236227,0.99784710039903013,0.99834429276997638,0.99872680963929439,0.99902104056373831,0.99924732674386485,0.9994213372384968,0.99955513616519176,0.99965800856948428,0.99973709853231241],[0.055856468825819627,0.071464527445916415,0.091013541151885521,0.1152464330859042,0.14490292816895817,0.18063289375945893,0.22287675894875664,0.27172375269618232,0.32677471722211926,0.38705140915776948,0.45099827624524969,0.51660574440429741,0.58164571857287029,0.64396569647118018,0.70176228535429264,0.75376408099819758,0.79929193444443114,0.83820875549677432,0.870799441085367,0.89762696700242051,0.91939956240824883,0.93686726559714806,0.95075214957548293,0.96170812127907634,0.97030289288109384,0.97701463955098244,0.98223725513453608,0.98628986678234642,0.9894278175847202,0.991853492035775,0.99372615035527079,0.99517043205948397,0.99628347404202533,0.99714073682323134,0.99780069782610592,0.99830858827999025,0.99869934318572628,0.99899991517887832,0.99923108072697098,0.99940884491548221],[0.025627683562487631,0.033084863508801986,0.042617037328384358,0.054740073827631699,0.070059324896618314,0.089260899399666069,0.11308519528037063,0.14227497026548724,0.17749144179272935,0.21919716986940224,0.26751533050283516,0.32209075739741394,0.38199368987471655,0.44571256942010767,0.51126718736177246,0.5764365286304669,0.63905094224650261,0.69727030123904543,0.74977605982434559,0.79584156242927251,0.83528953742737133,0.86837592087280158,0.89564636770535977,0.91780162154944755,0.9355913695610526,0.94974181010979764,0.96091330754312165,0.96968085412018834,0.97652978520337264,0.98186052153288783,0.9859978605447024,0.98920191350347386,0.99167898333825699,0.99359149722492868,0.99506662308027882,0.99620349803556774,0.99707915419084325,0.99775329736608176,0.99827211517330483,0.99867128498843594],[0.011558049423769331,0.01498418592228002,0.01940598801775718,0.025099405170732374,0.032407978673184214,0.041753554648745431,0.05364472424993369,0.068679709056840815,0.087538757855338725,0.11095940457772042,0.13968688723803527,0.17439299569870753,0.21556147846212753,0.26334851855742386,0.31744227912855233,0.37696141574896141,0.44043911264415031,0.50592605884008746,0.5712102927794398,0.63410689209705018,0.69274028297760104,0.74574523590162278,0.79234728495275419,0.83232818381678364,0.86591394065696814,0.89363199068147303,0.91617488915273504,0.93429149650411691,0.9487118612655232,0.96010268050525915,0.9690462017189122,0.97603495418365105,0.98147594840092189,0.98569972516586657,0.98897123615867966,0.99150076847237323,0.99345397312570283,0.99496059408168958,0.99612180772289993,0.99701624916443521],[0.0051716661977388376,0.0067175617725238725,0.0087214997085660762,0.011316428231022829,0.014672004443021629,0.019003459741611439,0.024581741760933251,0.031744487604291632,0.040906819835042726,0.052570073676925164,0.067325293902287683,0.085846710299015042,0.10886866957959243,0.1371383559919489,0.17133737143462185,0.21196971921663749,0.25922364013304122,0.31282993011551991,0.37195553556286426,0.4351790632241887,0.50058357733330616,0.5659681263258739,0.62913442225236227,0.68817279296597356,0.74167185167496141,0.78880907180627458,0.82932446670972226,0.86341315327586554,0.89158343626658931,0.9145189616003313,0.9329672694216613,0.94766196867209818,0.95927595419673772,0.96839869746488461,0.975529951887116,0.98108337905750154,0.98539533587573358,0.98873568701577741,0.99131877011396186,0.99331351767070586],[0.0023058376846617819,0.0029976715491506476,0.0038962697065599372,0.0050628686056199239,0.0065764577887765163,0.0085386643819565615,0.011079801513318223,0.014366232112998053,0.01860912244878208,0.024074491264828166,0.031094143719278967,0.040076538101582078,0.051515779386407681,0.065995696082826516,0.084184351079519368,0.10681259594361023,0.13462904544501336,0.16832437072376175,0.20842190597421642,0.25514099307287613,0.30825433166006555,0.36697697618400504,0.42993356648373382,0.49524096257079842,0.5607111586814636,0.62413443209565689,0.6835684201948764,0.73755617437644383,0.78522691233320685,0.8262781712059829,0.86087321853968168,0.88950030699369542,0.91283343423032981,0.93161830838136972,0.94659179416954442,0.95843283867631146,0.96773809938910693,0.97501458036771504,0.98068265396629661,0.98508456553107071],[0.0010264416269535057,0.0013349244807438448,0.0017359564891367089,0.0022571924282214031,0.0029344739026328482,0.0038142000686274794,0.0049563484116803194,0.0064382985161140268,0.008359629645504036,0.010848068375353747,0.014066741265518859,0.018222815973874682,0.02357745500139288,0.030456704224832841,0.039262418638777816,0.050481502395799169,0.064690535040988789,0.082551275334307936,0.1047907867263498,0.13215861699043122,0.16535378158830683,0.20491803241629872,0.25110085006522598,0.303716078555055,0.36202664198371315,0.42470375479147437,0.48989943440362521,0.55544053242178681,0.61910784362842097,0.67892778018322308,0.73339849632969834,0.78160081592875297,0.82318909599035495,0.85829380368318708,0.88738220792328393,0.91111790154538608,0.93024423063331185,0.94550099584883884,0.95757304002697963,0.96706416173880294],[0.00045659471792566732,0.00059391977290597223,0.00077251467862490591,0.0010047600516114837,0.0013067353309626716,0.001699313291563622,0.0022095711468260409,0.0028726047655751462,0.0037338526364247642,0.0048520584192952897,0.0063030232999991796,0.0081843178381459936,0.010621129862962661,0.01377340661527717,0.017844383015438395,0.023090437639231354,0.029831930090303181,0.038464174610476701,0.049466907503501134,0.06340943312348879,0.080947079200151636,0.1028028427159452,0.12972672495114804,0.16242537887983854,0.20145807256242607,0.24710345894275448,0.2992157390101296,0.35710541429334919,0.41949074661403063,0.48456021169068741,0.55015740231994414,0.61405560089714317,0.67425151487546608,0.7291991352303091,0.77793081253066554,0.82005705386500927,0.85567458382685102,0.88522874698405507,0.90937195743060162,0.92884465072690114],[0.00020304392347201368,0.00026413139956173686,0.00034359124177972978,0.00044694466060878253,0.00058136906032413358,0.00075619275413174722,0.00098353600631382156,0.0012791406795047684,0.0016634422829877448,0.002162952380857599,0.0028120363708932852,0.0036551915401619927,0.0047499523901603094,0.0061705727020129825,0.0080126528300313339,0.010398888929818084,0.013486105220672638,0.017473669095929109,0.022613247158517771,0.029219586019537953,0.037681523148665449,0.048471663325782878,0.062152015685961327,0.079371360014742376,0.10084836275435616,0.12733301702522895,0.15953892480681212,0.19804198127645514,0.24314904300479276,0.29475385461298337,0.35221415089876756,0.41429564559459636,0.47922451118679471,0.54486293435724165,0.60897866938269063,0.66954029250214864,0.72495843440104146,0.7742169530996964,0.81688187228360842,0.85301524244636484],[9.0279249225858125e-05,0.00011744450768842346,0.0001527826133707231,0.00019875155664028106,0.00025854797193820746,0.00033632869147595012,0.00043749846646095849,0.0005690834183763781,0.00074021542874694627,0.00096275985499540498,0.001252128020491792,0.0016283272447675601,0.0021173151164682285,0.002752741525176267,0.0035781816458733844,0.0046499850256585965,0.0060408884768593952,0.0078445599946556834,0.010181250404536303,0.013204716446438117,0.017110522521740498,0.022145694812537774,0.028619440421508574,0.036914185345690485,0.047495442329361676,0.060917911191111895,0.077823716509390128,0.098926944049320911,0.12497713472203052,0.15669416945830958,0.1946696947799221,0.23923780136146464,0.2903309403255106,0.34735368557328467,0.40911953965901054,0.47389354643481801,0.53955830471266997,0.60387803535294504,0.66479480740310171,0.72067676302071504],[4.0138272570014032e-05,5.2216769992765196e-05,6.7929708560614824e-05,8.837052705982525e-05,0.00011496151214264428,0.00014955261622570028,0.00019454991317277071,0.00025308254153966225,0.00032921960045740933,0.00042825183248577041,0.00055705725509527944,0.00072457543775095363,0.0009424221637488857,0.0012256851097876907,0.0015939522966597294,0.0020726387764862025,0.002694693597113679,0.0035027885407935846,0.004552111948556592,0.0059139135497461044,0.0076799661814050237,0.0099681209581803307,0.012929121926583437,0.016754794343330319,0.021687595088882156,0.028031265379807168,0.036161886244114476,0.046537920859843991,0.05970675130047768,0.076303748992983755,0.097038182476044274,0.12265871378894172,0.15389085132343167,0.1913411311715007,0.2353699092984157,0.28594748451402185,0.34252482764938463,0.40396350015071786,0.46856852666405435,0.53424469873301272],[1.7845031612044358e-05,2.3215153590455764e-05,3.0201262568725284e-05,3.9289610537742937e-05,5.1112739765553822e-05,6.6493478437089658e-05,8.6502156416024792e-05,0.00011253100583741426,0.00014639089487341632,0.00019043707628126186,0.00024773261592462193,0.0003222607282103271,0.00041920054635518071,0.00054528509621822486,0.00070926566912990041,0.00092251369661646462,0.0011997999595762549,0.0015603018898525628,0.0020289032115004741,0.0026378665061445399,0.0034289785190046969,0.0044562896850220274,0.005789591994137794,0.0075187996885057199,0.0097594090721674753,0.012659205527665638,0.016406338315465806,0.021238765670336762,0.027454836621093187,0.035424354824327382,0.045598779166190442,0.058518170959989978,0.074811059527388021,0.095181672868675529,0.12037738462848592,0.15112869780571619,0.18805619095150133,0.2315455186609009,0.28160394901262642,0.33772836162926617],[7.9336052544319482e-06,1.0321103255416221e-05,1.3427072869873735e-05,1.7467717634222267e-05,2.2724296746259426e-05,2.9562697116236599e-05,3.8458891468600196e-05,5.003205111531795e-05,6.5087612387580839e-05,8.4673284385328987e-05,0.00011015187942453174,0.00014329600651604444,0.00018641116964421734,0.0002424957552468672,0.00031544890256057626,0.00041034048450557805,0.0005337615827209095,0.00069427916038438189,0.00090302541146798111,0.0011744608330486229,0.0015273608001389371,0.0019860886911204105,0.0025822347113242218,0.0033567185673499767,0.0043624756469611515,0.0056678690098781754,0.0073609902363794477,0.0095550250065828176,0.012394853312396703,0.016065010857612246,0.020799027395514671,0.026889933482566075,0.034701323990029447,0.044677701421366844,0.057351808479533424,0.073345252094461535,0.093357009301654637,0.1181327727056133,0.14840742573200569,0.18481475755040636],[3.5271299711249535e-06,4.5885722485561954e-06,5.9694393818876384e-06,7.7658560867789313e-06,1.0102873033645498e-05,1.3143170644611385e-05,1.7098381417756301e-05,2.2243818256055005e-05,2.8937632888607398e-05,3.764573602969645e-05,4.897421059971169e-05,6.3711468552402769e-05,8.2883076080420879e-05,0.00010782304699127844,0.00014026653882733204,0.00018247035655375314,0.0002373695711477771,0.00030878101823617353,0.00040166761027357872,0.0005224814684020527,0.00067960909540416554,0.00088394845596346042,0.0011496562391987515,0.001495114121226128,0.0019441758954079258,0.0025277732004056809,0.0032859763516101749,0.0042706281146706656,0.0055486909016773606,0.007206468941401316,0.0093548807689011072,0.012135953503598439,0.015730671014487586,0.020368204219274082,0.026336338878537861,0.033992530551701011,0.043774375739340399,0.056207305606695734,0.071905932754877569,0.091563785361017822],[1.568091048940743e-06,2.0399881408577688e-06,2.6538962942634743e-06,3.4525515606833403e-06,4.4915505703816218e-06,5.8432205468391386e-06,7.6016538020920279e-06,9.8892570432741689e-06,1.2865271174925479e-05,1.673685429006444e-05,2.1773498696416603e-05,2.8325784445037265e-05,3.6849772906425086e-05,4.793873520574386e-05,6.2364418636542222e-05,8.1130714255245231e-05,0.00010554344556576292,0.00013730110930977528,0.00017861283908053815,0.00023235172567187478,0.00030225403545982058,0.00039317797207064732,0.00051143961751827299,0.00066524880140742362,0.00086527416359847816,0.0011253749277245386,0.0014635472581797824,0.0019031459064784758,0.0024744574791310948,0.0032167202029380068,0.0041807062197996847,0.0054320050579600597,0.0070551682900580831,0.0091588900831174724,0.011882396448511768,0.015403180416802376,0.019946123172960288,0.025793839266172583,0.033297715208161861,0.042888494188569826],[6.9714098498712296e-07,9.0693695088107239e-07,1.1798683460813574e-06,1.5349349239686278e-06,1.9968541209663739e-06,2.5977816804265149e-06,3.3795500471955621e-06,4.3965803287193421e-06,5.719670488903609e-06,7.4409234063210549e-06,9.6801577235038052e-06,1.2593247543328973e-05,1.6382971144545413e-05,2.1313123282655461e-05,2.7726872378787981e-05,3.607063863302509e-05,4.6925152129434161e-05,6.1045847623141417e-05,7.9415398932502427e-05,0.00010331203463269723,0.00013439836466533914,0.00017483685725625398,0.00022743993020516695,0.00029586497857094971,0.00038486770159588658,0.00050063100246817613,0.00065119174594333203,0.00084699404983080572,0.0011016058840328186,0.0014326459209998141,0.0018629802002683177,0.0024222635607308108,0.0031489191045473634,0.0040926699286183308,0.0053177599300719041,0.0069070221135057921,0.0089669683592899802,0.011634074583470721,0.015082403242206945,0.019532614324514627],[3.099343741390402e-07,4.0320534162002749e-07,5.2454505376910218e-07,6.8240044211942946e-07,8.8776042770248182e-07,1.1549208934280983e-06,1.5024798596729129e-06,1.9546321358059731e-06,2.542853564300758e-06,3.3080920887418232e-06,4.3036181481584417e-06,5.5987327799681534e-06,7.2835914910162586e-06,9.4754795762280049e-06,1.2326975515641202e-05,1.6036570365196422e-05,2.0862481770769404e-05,2.714062318965301e-05,3.5307977426718833e-05,4.5932998560110799e-05,5.9755153493014942e-05,7.7736347038975914e-05,0.00010112779565936151,0.00013155698017939963,0.00017114068827321917,0.00022263194443571503,0.00028961093467656205,0.00037673301208604969,0.0004900507015245017,0.00063743153395654515,0.0008290998082864712,0.0010783383243458387,0.0014023961183252495,0.0018236606384643863,0.0023711679556252386,0.0030825426786522717,0.0040064800255873688,0.0052059050118381999,0.0067619655625214539,0.0087790326634918318],[1.3779034324879879e-07,1.7925667475270803e-07,2.3320179255521118e-07,3.033810330528864e-07,3.9467985328885246e-07,5.1345392539774219e-07,6.6797157718141479e-07,8.6898937782752119e-07,1.1305009358062567e-06,1.4707110327106739e-06,1.9133029011982157e-06,2.4890868584867454e-06,3.2381450483749132e-06,4.212621570398569e-06,5.480352184998481e-06,7.1295861998062296e-06,9.2751291224259169e-06,1.206633348426389e-05,1.5697493752828356e-05,2.0421368361467254e-05,2.6566769159125557e-05,3.4561441025356056e-05,4.4961821469272127e-05,5.8491746950096413e-05,7.6092792048569556e-05,9.8989731631574982e-05,0.00012877565911767971,0.00016752264570086804,0.00021792557533606378,0.00028348905233037278,0.00036877019660216405,0.00047969389661352995,0.00062396190491253219,0.00081158330704396073,0.0010555616909076414,0.001372784151266127,0.001785169460594481,0.0023211476613270443,0.0030175611736524871,0.003922098097226095],[6.1258700104010276e-08,7.9693764267628361e-08,1.0367663723073151e-07,1.3487686431522509e-07,1.7546641984744847e-07,2.2827090675866565e-07,2.9696625764457272e-07,3.8633463023619218e-07,5.0259731085096365e-07,6.5384779998136862e-07,8.5061522783985183e-07,1.1065973197570345e-06,1.4396139331643763e-06,1.8728475407087423e-06,2.4364570060296267e-06,3.1696769792146279e-06,4.1235490348595548e-06,5.3644746368142773e-06,6.9788371955842617e-06,9.0790148594760753e-06,1.1811202412654445e-05,1.5365586452837152e-05,1.9989581606219611e-05,2.6005048228200946e-05,3.3830688528484972e-05,4.4011177403900166e-05,5.7255051152672816e-05,7.4483983632863459e-05,9.6896866599435606e-05,0.00012605313213586735,0.00016398107871868663,0.0002133186761670056,0.00027749654023958854,0.00036097562635189492,0.00046955587114063481,0.00061077672998236931,0.00079443658499475352,0.0010332656472880749,0.0013437966073595051,0.0017474892762742887],[2.7234333629194236e-08,3.5430176983336586e-08,4.6092460166853653e-08,5.9963428306194625e-08,7.8008696133965106e-08,1.0148446830626063e-07,1.3202498881608165e-07,1.7175630717286886e-07,2.2344428100677278e-07,2.906871180443445e-07,3.7816586088614604e-07,4.9197025150981874e-07,6.4002265967177637e-07,8.3262958560068574e-07,1.0831991276514746e-06,1.4091743579147797e-06,1.833247577025967e-06,2.3849399692036965e-06,3.1026566098576196e-06,4.0363598597008268e-06,5.2510472113977595e-06,6.8312756283877694e-06,8.8870472193729207e-06,1.1561465780973007e-05,1.5040696884502516e-05,1.9566924315294516e-05,2.5455203877760583e-05,3.3115386241779429e-05,4.3080632284138323e-05,5.6044501450291054e-05,7.2909187319040734e-05,9.4848245232634245e-05,0.0001233881567016649,0.00016051437136527976,0.00020880914550226113,0.00027163066599878344,0.00035334574904695762,0.00045963200786109553,0.00059787000928580999,0.00077765184827876502],[1.210781346894778e-08,1.5751513581333986e-08,2.0491741177480431e-08,2.6658482927218179e-08,3.4681030982516523e-08,4.5117867749270954e-08,5.8695544110939027e-08,7.6359257568367163e-08,9.9338651233513582e-08,1.2923341419102075e-07,1.6812464217936831e-07,2.187197107966271e-07,2.8454074633234347e-07,3.7016981425566032e-07,4.8156789360145064e-07,6.2648984180304012e-07,8.1502423641592681e-07,1.0602956727041965e-06,1.3793784041542342e-06,1.794484923522264e-06,2.3345122185342689e-06,3.0370533300957575e-06,3.9510142232426889e-06,5.1400181037247943e-06,6.6868341039578568e-06,8.6991385278273343e-06,1.1317009532879504e-05,1.4722676671782122e-05,1.9153203467738546e-05,2.4916985011485809e-05,3.24152075247556e-05,4.2169761205245425e-05,5.4859545126222846e-05,7.136768415503755e-05,9.2842932385151837e-05,0.00012077951652902457,0.00015712094180324885,0.00020439492627366166,0.00026588875485031906,0.00034587708729489047],[5.3828798517037239e-09,7.0027924926202783e-09,9.1101982622315905e-09,1.1851802322001508e-08,1.5418458975392426e-08,2.0058457816106031e-08,2.6094808180300295e-08,3.3947725142803987e-08,4.4163882397030435e-08,5.7454468426897515e-08,7.4744695209052857e-08,9.7238205935765858e-08,1.2650086542137826e-07,1.645697661473405e-07,2.1409503823788125e-07,2.785243352286867e-07,3.6234283825042765e-07,4.7138548598217395e-07,6.1324316543943942e-07,7.9779113928417982e-07,1.0378764940923453e-06,1.3502124630367526e-06,1.7565418759933179e-06,2.2851507220512437e-06,2.9728371769360679e-06,3.8674731457795864e-06,5.0313366041060407e-06,6.5454466529621518e-06,8.5152029642301553e-06,1.1077722023453181e-05,1.441138057556578e-05,1.8748230123256609e-05,2.4390145841240663e-05,3.1729832641699262e-05,4.12781482437241e-05,5.3699641145356379e-05,6.9858770381743798e-05,9.0880012669115849e-05,0.00011822602102426984,0.00015379924159950376],[2.3931154426818226e-09,3.1132946178911829e-09,4.0502030127003037e-09,5.2690626660232156e-09,6.854723400589824e-09,8.9175695668154487e-09,1.1601204349512245e-08,1.5092446573255084e-08,1.9634335924512576e-08,2.5543051936511862e-08,3.3229924535244384e-08,4.323006838839177e-08,5.6239634407197797e-08,7.3164271623534724e-08,9.518217305930753e-08,1.2382609444783062e-07,1.6109005542959177e-07,2.0956815106718099e-07,2.7263513681131978e-07,3.5468135799687148e-07,4.6141837796750586e-07,6.0027658033612751e-07,7.809224232242645e-07,1.0159313521779376e-06,1.3216632134626715e-06,1.719401104572424e-06,2.2368329347703021e-06,2.9099788209167204e-06,3.7856984717785932e-06,4.9249530750291824e-06,6.4070487008694995e-06,8.33515652246357e-06,1.0843493968214935e-05,1.4106666427364026e-05,1.835181933595726e-05,2.3874445774881325e-05,3.1058948615747626e-05,4.0405386267550074e-05,5.2564259907415956e-05,6.8381757112131393e-05],[1.0639289135683537e-09,1.3841054646507911e-09,1.8006352799138532e-09,2.3425147098035964e-09,3.0474662059347856e-09,3.9645643357018642e-09,5.1576520641875087e-09,6.7097851247146466e-09,8.7290138688145128e-09,1.135590509374107e-08,1.4773327472513714e-08,1.9219181789918435e-08,2.5002962187562314e-08,3.2527301312716932e-08,4.231599921463884e-08,5.5050487190536786e-08,7.1617264971805033e-08,9.3169613535268712e-08,1.2120787960036241e-07,1.5768392070975294e-07,2.0513698168341035e-07,2.6687046126092377e-07,3.4718187420937197e-07,4.5166201720802956e-07,5.8758416417578532e-07,7.6441038368027758e-07,9.9445022383111225e-07,1.2937176159945444e-06,1.683045645815551e-06,2.1895367883962424e-06,2.8484495527120098e-06,3.705652852453831e-06,4.8208189284901633e-06,6.2715770384607666e-06,8.158916972539948e-06,1.0614218393226167e-05,1.3808395064396557e-05,1.7963790069918665e-05,2.3369649306431765e-05,3.0402249086049859e-05],[4.7300047131138417e-10,6.1534424799599137e-10,8.0052466433222923e-10,1.0414328894038683e-09,1.3548395338426971e-09,1.7625621208685766e-09,2.292983893618982e-09,2.9830296891696561e-09,3.8807364279281541e-09,5.0485971606846945e-09,6.5679114661037114e-09,8.5444450475828201e-09,1.1115792517076593e-08,1.4460955919195299e-08,1.8812805795460306e-08,2.447429225369567e-08,3.1839534560193839e-08,4.1421257385276513e-08,5.3886483647755697e-08,7.0102968676640682e-08,9.1199608150708923e-08,1.1864502504027583e-07,1.5434980627637863e-07,2.0079950620333805e-07,2.6122767563237722e-07,3.3984096159201086e-07,4.4211194761017162e-07,5.7516011986369258e-07,7.4824747900267139e-07,9.7342329785226569e-07,1.2663629069016828e-06,1.6474588949537613e-06,2.143240681244021e-06,2.788221270020547e-06,3.6272997287093082e-06,4.7188866038037678e-06,6.1389697929630711e-06,7.9864038230516185e-06,1.0389790586241799e-05,1.3516430266052615e-05],[2.1028608484469939e-10,2.7356914126165419e-10,3.5589646887232026e-10,4.6299921098009601e-10,6.0233322921275685e-10,7.8359813665913895e-10,1.0194125277542884e-09,1.3261924104353606e-09,1.7252939918332026e-09,2.2445003714966829e-09,2.9199556369571238e-09,3.7986810019456991e-09,4.9418481459412928e-09,6.4290376255949348e-09,8.363778803434742e-09,1.0880756950863515e-08,1.4155189241191984e-08,1.8415022333589719e-08,2.3956800671025688e-08,3.1166310148168061e-08,4.0545434237349911e-08,5.2747092133774486e-08,6.8620691100889439e-08,8.9271257128785177e-08,1.1613636021401849e-07,1.5108618931240773e-07,1.9655374353725229e-07,2.5570420265221589e-07,3.326552672741465e-07,4.327638073009901e-07,5.6299877288005362e-07,7.3242632700381437e-07,9.5284097049108066e-07,1.2395865923307537e-06,1.6126245983096148e-06,2.0979234683731645e-06,2.7292664647309667e-06,3.5506033144427542e-06,4.6191095458835728e-06,6.0091663997949021e-06],[9.3488780994783339e-11,1.2162310004548723e-10,1.5822410247679624e-10,2.05839734351031e-10,2.6778471531105382e-10,3.4837128982393772e-10,4.5320942022280206e-10,5.8959731921655766e-10,7.6702950843825403e-10,9.9785777107226523e-10,1.298151010184116e-09,1.6888138710177915e-09,2.1970419991448461e-09,2.8582152409483807e-09,3.718360579881461e-09,4.8373562635716061e-09,6.2931001741583418e-09,8.1869326191413473e-09,1.0650691045312186e-08,1.3855887783095481e-08,1.802564972129699e-08,2.3450251081246628e-08,3.0507320589175597e-08,3.9688129748788331e-08,5.1631792244764955e-08,6.7169755231565689e-08,8.7383679717781011e-08,1.1368073931853556e-07,1.4789157919962173e-07,1.923977544841053e-07,2.5029751954147387e-07,3.2562150927900778e-07,4.2361332663591445e-07,5.5109456868820484e-07,7.1693970158624864e-07,9.3269384106014631e-07,1.2133764425994022e-06,1.5785268458736172e-06,2.0535644519302586e-06,2.6715582103584781e-06]],\"type\":\"surface\",\"x\":[52,59.256410256410255,66.512820512820511,73.769230769230774,81.025641025641022,88.282051282051285,95.538461538461547,102.7948717948718,110.05128205128204,117.30769230769231,124.56410256410257,131.82051282051282,139.07692307692309,146.33333333333331,153.58974358974359,160.84615384615384,168.10256410256409,175.35897435897436,182.61538461538461,189.87179487179486,197.12820512820514,204.38461538461539,211.64102564102564,218.89743589743588,226.15384615384616,233.41025641025641,240.66666666666666,247.92307692307693,255.17948717948718,262.43589743589746,269.69230769230768,276.94871794871796,284.20512820512818,291.46153846153845,298.71794871794873,305.97435897435901,313.23076923076923,320.4871794871795,327.74358974358972,335],\"y\":[1.5129999999999999,1.6132820512820512,1.7135641025641024,1.8138461538461539,1.9141282051282051,2.0144102564102564,2.1146923076923079,2.2149743589743589,2.3152564102564104,2.4155384615384614,2.5158205128205129,2.6161025641025644,2.7163846153846154,2.8166666666666664,2.9169487179487179,3.0172307692307694,3.1175128205128209,3.2177948717948719,3.3180769230769229,3.4183589743589744,3.5186410256410259,3.6189230769230769,3.7192051282051284,3.8194871794871799,3.9197692307692309,4.0200512820512824,4.120333333333333,4.2206153846153853,4.3208974358974359,4.4211794871794874,4.5214615384615389,4.6217435897435895,4.7220256410256418,4.8223076923076924,4.9225897435897439,5.0228717948717954,5.1231538461538459,5.2234358974358983,5.3237179487179489,5.4240000000000004],\"colorscale\":[[\"0\",\"lightblue\"],[\"1\",\"firebrick\"]],\"opacity\":0.59999999999999998,\"name\":\"Predicted Probability Surface\",\"inherit\":true}},\"layout\":{\"width\":950,\"height\":520,\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Logistic Regression: Curved Probability Surface\",\"scene\":{\"xaxis\":{\"title\":\"Horsepower (hp)\"},\"yaxis\":{\"title\":\"Weight (1000 lbs)\"},\"zaxis\":{\"title\":\"Probability (Manual Transmission)\"}},\"hovermode\":\"closest\",\"showlegend\":true,\"legend\":{\"yanchor\":\"top\",\"y\":0.5}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[110,175,105,245,62,95,123,123,180,180,180,205,215,230,97,150,150,245,175],\"y\":[3.2149999999999999,3.4399999999999999,3.46,3.5699999999999998,3.1899999999999999,3.1499999999999999,3.4399999999999999,3.4399999999999999,4.0700000000000003,3.73,3.7799999999999998,5.25,5.4240000000000004,5.3449999999999998,2.4649999999999999,3.52,3.4350000000000001,3.8399999999999999,3.8450000000000002],\"z\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"type\":\"scatter3d\",\"mode\":\"markers\",\"name\":\"Observed Data\",\"marker\":{\"color\":\"rgba(70,130,180,1)\",\"size\":[50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50],\"sizemode\":\"area\",\"symbol\":\"circle\",\"line\":{\"color\":\"rgba(70,130,180,1)\"}},\"textfont\":{\"color\":\"rgba(70,130,180,1)\",\"size\":50},\"error_y\":{\"color\":\"rgba(70,130,180,1)\",\"width\":50},\"error_x\":{\"color\":\"rgba(70,130,180,1)\",\"width\":50},\"line\":{\"color\":\"rgba(70,130,180,1)\",\"width\":50},\"frame\":null},{\"x\":[110,110,93,66,52,65,66,91,113,264,175,335,109],\"y\":[2.6200000000000001,2.875,2.3199999999999998,2.2000000000000002,1.615,1.835,1.9350000000000001,2.1400000000000001,1.5129999999999999,3.1699999999999999,2.77,3.5699999999999998,2.7799999999999998],\"z\":[1,1,1,1,1,1,1,1,1,1,1,1,1],\"type\":\"scatter3d\",\"mode\":\"markers\",\"name\":\"Observed Data\",\"marker\":{\"color\":\"rgba(178,34,34,1)\",\"size\":[50,50,50,50,50,50,50,50,50,50,50,50,50],\"sizemode\":\"area\",\"symbol\":\"circle\",\"line\":{\"color\":\"rgba(178,34,34,1)\"}},\"textfont\":{\"color\":\"rgba(178,34,34,1)\",\"size\":50},\"error_y\":{\"color\":\"rgba(178,34,34,1)\",\"width\":50},\"error_x\":{\"color\":\"rgba(178,34,34,1)\",\"width\":50},\"line\":{\"color\":\"rgba(178,34,34,1)\",\"width\":50},\"frame\":null},{\"colorbar\":{\"title\":\"am\",\"ticklen\":2,\"len\":0.5,\"lenmode\":\"fraction\",\"y\":1,\"yanchor\":\"top\"},\"colorscale\":[[\"0\",\"lightblue\"],[\"1\",\"firebrick\"]],\"showscale\":true,\"z\":[[0.99980085770222293,0.99984691700557438,0.99988232458020954,0.99990954324448533,0.99993046659096252,0.99994655046443726,0.99995891410672744,0.99996841795199254,0.99997572345435182,0.99998133909262321,0.99998565574292131,0.99998897387455343,0.99999152445829864,0.9999934850401353,0.99999499209793485,0.9999961505404682,0.99999704100948383,0.99999772549289101,0.99999825163962452,0.99999865607646676,0.99999896695765944,0.99999920592476121,0.99999938961315982,0.99999953081010384,0.9999996393448598,0.99999972277295823,0.99999978690216051,0.99999983619675681,0.99999987408834257,0.99999990321470422,0.99999992560344608,0.99999994281313953,0.99999995604182146,0.99999996621039455,0.99999997402673468,0.99999998003496926,0.99999998465335616,0.9999999882034003,0.99999999093223468,0.99999999302982467],[0.99955217687469111,0.99965573336353608,0.99973534935800912,0.99979655689841063,0.99984361077219752,0.99987978297539282,0.99990758946586655,0.9999289647043289,0.99994539596240339,0.99995802664632216,0.99996773576920339,0.99997519906894095,0.999980936005468,0.99998534589671917,0.99998873570155811,0.99999134137944434,0.99999334431122155,0.99999488392264024,0.99999606738850022,0.99999697709243107,0.99999767636130643,0.99999821387330523,0.99999862704637266,0.9999989446429034,0.99999918877193128,0.99999937642818304,0.99999952067512321,0.9999996315543398,0.99999971678457,0.99999978229902842,0.9999998326584385,0.99999987136852131,0.99999990112404236,0.99999992399640392,0.99999994157784444,0.99999995509227957,0.99999996548050418,0.99999997346568537,0.99999997960370401,0.99999998432185289],[0.99899326620807183,0.99922596744799708,0.9994049130564493,0.99954250785897636,0.99964829946465583,0.99972963417687954,0.99979216323101028,0.99984023314335013,0.99987718648263413,0.99990559349149943,0.99992743038005438,0.99994421652468823,0.9999571200174836,0.99996703885152394,0.99997466335683227,0.99998052421155026,0.99998502935771794,0.99998849238389764,0.9999911543459673,0.9999932005424591,0.99999477341067189,0.99999598244037835,0.9999969117947124,0.99999762616843402,0.99999817529119739,0.99999859738920027,0.99999892184612649,0.99999917124858306,0.99999936295839742,0.9999995103212167,0.99999962359553662,0.99999971066682647,0.99999977759646408,0.99999982904368889,0.99999986858994916,0.99999989898821984,0.99999992235464807,0.9999999403158657,0.99999995412222653,0.99999996473484754],[0.99773837913595964,0.99826063591663794,0.99866245407569576,0.99897154208551331,0.99920926076788352,0.99939206637957734,0.99953263017571925,0.99964070510006608,0.99972379560942093,0.99978767469574037,0.99983678257780195,0.99987453391688008,0.99990355441025669,0.99992586291765573,0.99994301161277543,0.99995619380622514,0.99996632688070708,0.9999741160733826,0.99998010352280942,0.99998470598135492,0.99998824381044715,0.99999096327244652,0.99999305366818581,0.99999466051155639,0.9999958956573044,0.99999684508650455,0.99999757489134899,0.99999813587567943,0.99999856709140422,0.99999889855691682,0.99999915334671319,0.99999934919765088,0.99999949974365543,0.99999961546481519,0.99999970441693353,0.99999977279231944,0.99999982535085696,0.99999986575135691,0.99999989680626156,0.99999992067742849],[0.99492722642667175,0.99609609869794546,0.99699645162595596,0.99768963866230886,0.99822313061969148,0.99863360118314548,0.99894934967514737,0.99919219378313451,0.99937894254228377,0.99952253932591506,0.9996329468085251,0.99971783099330669,0.99978308924509807,0.9998332575010741,0.99987182406750386,0.99990147129134443,0.99992426160152781,0.99994178067652151,0.99995524758962018,0.99996559953163344,0.99997355696866463,0.9999796737471236,0.99998437561994491,0.99998798986768145,0.99999076807161602,0.99999290362132132,0.99999454517372977,0.99999580699964208,0.99999677693733979,0.99999752250663154,0.99999809560874875,0.99999853613914647,0.99999887476463734,0.99999913505814497,0.99999933513965844,0.99999948893760815,0.99999960715846203,0.99999969803203637,0.99999976788440048,0.99999982157825607],[0.98866157179742087,0.99126150046444383,0.99326931792700557,0.99481821709211471,0.99601210669690998,0.99693177095015351,0.99763985026137336,0.99818481807971704,0.99860412675993426,0.99892667890401177,0.9991747587359594,0.99936553557249685,0.99951223071374351,0.999625021054242,0.9997117376088297,0.99977840478742819,0.99982965630472176,0.99986905569775497,0.99989934318387885,0.99992262570061663,0.9999405231539048,0.99995428093561023,0.99996485647216249,0.99997298578735394,0.99997923468822136,0.99998403812261327,0.9999877304396233,0.99999056865432512,0.99999275033333646,0.99999442734451471,0.99999571642689911,0.99999670731609247,0.9999974689903558,0.99999805447201418,0.99999850451828998,0.9999988504584213,0.99999911637452565,0.99999932077799936,0.99999947789813926,0.99999959867268318],[0.97485248127697821,0.98055659459008493,0.9849867919898988,0.98841948637721633,0.9910744246615345,0.99312492781900086,0.99470687770757693,0.99592631500766138,0.99686570177076073,0.9975889915108026,0.99814568098616141,0.99857401745537833,0.99890351948341038,0.99915694770208752,0.99935183936979044,0.99950169964449398,0.99961692422527648,0.99970551267766861,0.99977361918597296,0.99982597734560319,0.99986622754419496,0.99989716911645188,0.99992095446808649,0.99993923847076915,0.99995329340280692,0.9999640973629812,0.99997240226861184,0.99997878614559221,0.99998369333522652,0.99998746540779071,0.99999036492949711,0.99999259373422145,0.99999430697009584,0.99999562389770846,0.99999663619096435,0.9999974143180792,0.99999801244668729,0.99999847221439242,0.99999882562716713,0.99999909728732161],[0.94515819009870816,0.95730273990250525,0.96685223592639191,0.97432321688927725,0.98014493606524244,0.98466746357080703,0.98817229405566465,0.99088338073049753,0.99297746207890603,0.99459315900997902,0.99583868538981468,0.99679821447128958,0.99753703951319261,0.99810570166005663,0.99854325963367108,0.99887986090433489,0.99913875258722051,0.99933784770264023,0.9994909413224452,0.99960865263190291,0.9996991533616274,0.99976873025790092,0.99982221894513212,0.99986333831612317,0.99989494809668955,0.99991924714097935,0.99993792604056198,0.99995228454029095,0.99996332185744907,0.99997180614596648,0.99997832791439534,0.99998334110032228,0.99998719465114227,0.99999015680408865,0.99999243375245483,0.99999418399549533,0.99999552936980962,0.99999656352947053,0.99999735846483129,0.99999796951357367],[0.88455311209594867,0.90882381007164303,0.92840500783225333,0.94403984307986422,0.95642062852636223,0.96616044004588519,0.97378311296487607,0.97972474206492655,0.98434145106462478,0.98791988976735712,0.99068828609521364,0.99282685614248223,0.99447701071819594,0.99574917880441194,0.99672927881183337,0.99748397088622709,0.99806486204630074,0.99851183936786547,0.99885569243278882,0.99912016512340918,0.9993235542056208,0.99947995084870167,0.99960020250494108,0.99969265676134833,0.99976373577331612,0.9998183793885137,0.99986038669498856,0.99989267911079915,0.99991750293986703,0.99993658526406659,0.99995125388740669,0.99996252960143994,0.99997119714719118,0.9999778597853658,0.99998298125703711,0.99998691804602247,0.9999899441830461,0.99999227031496996,0.9999940583645478,0.999995432800029],[0.77305535217184052,0.81588757400483813,0.85218163899788468,0.88235272574103307,0.90703740017471779,0.92697142275072397,0.94290006822347949,0.9555211397609501,0.9654547222008274,0.97323196023034264,0.97929584331511965,0.98400861920021965,0.98766216640033622,0.99048905653005714,0.99267304413128821,0.99435838151304146,0.99565775539785351,0.99665886391630532,0.99742976175262232,0.99802314370578282,0.99847974243373383,0.99883100310501638,0.99910117686535405,0.99930895237654482,0.99946872321898272,0.99959156999405063,0.99968601991499695,0.99975863345424409,0.99981445692396553,0.99985737133378927,0.99989036112310792,0.9999157210684958,0.99993521552912956,0.99995020097355125,0.99996172023318053,0.99997057499418052,0.99997738154471916,0.99998261364103336,0.99998663546610489,0.99998972696926325],[0.60229025730997376,0.66331506666915419,0.71933956402074417,0.76928413794101524,0.81265562775690314,0.84946925901339421,0.88011608460085922,0.90521963947387607,0.92551143534241398,0.94173851155736532,0.95460396654007185,0.96473482393683607,0.97266954591216137,0.97885806751393756,0.98366883016802154,0.98739901476121961,0.99028560612993877,0.9925159588277197,0.99423721901690409,0.99556437448553414,0.99658693825943223,0.99737438772987341,0.99798052780734758,0.99844695430350028,0.99880578172263013,0.99908177918662944,0.99929403557354013,0.99945725332136515,0.99958275116598894,0.99967923979691919,0.99975342097359843,0.99981044976192013,0.99985429085645983,0.9998879930755904,0.99991390071342368,0.99993381621038058,0.99994912531796076,0.99996089338308514,0.99996993940282286,0.9999768929740539],[0.40236743465371172,0.46691716521809201,0.53259384354756756,0.59716009050126073,0.65852577877633256,0.71500480819293966,0.76546926836414464,0.80938020237485664,0.84671606080367479,0.87784280866019393,0.90337012148358564,0.92402465214247198,0.94055481558935272,0.95366879784054204,0.96400048291545859,0.97209565370155171,0.97841123929171347,0.98332194358101743,0.98713032353995467,0.99007784727993775,0.99235553164965218,0.9941134697730305,0.99546899453517679,0.99651346965349796,0.99731782391979795,0.9979369951195991,0.99841346013944521,0.99878001684763873,0.99906196327582675,0.99927879701206657,0.99944553593397811,0.99957374200283222,0.99967231331626993,0.99974809595412295,0.99980635607421164,0.99985114385724472,0.99988557388738764,0.99991204104364928,0.99993238666894813,0.9999480264294901],[0.23036738606613849,0.28026400611400737,0.33624635967077854,0.39723928224128441,0.46160175688474731,0.52727028291493239,0.59200857550071317,0.65370393094077905,0.71063003468716834,0.76161086727071481,0.8060611776308465,0.84392175895217358,0.87553252235857826,0.90148844014877849,0.92251067757360761,0.93934861937421343,0.95271531869493342,0.9632514328953321,0.97151006372003712,0.97795518017120719,0.98296781643553488,0.98685597927420621,0.9898656906245219,0.99219169262468765,0.99398707922445262,0.99537157314986258,0.99643842523483483,0.99726004489787279,0.99789252600253786,0.99837924478737783,0.99875369679737103,0.99904172013261849,0.99926322976186854,0.99943356572264841,0.99956453840015846,0.99966523731561174,0.99974265596731293,0.99980217399324467,0.99984792890005847,0.99988310245431344],[0.11744350609536325,0.14757107558422339,0.18381752087333744,0.22660019008400761,0.27597343618490522,0.33149348465201278,0.39213360351969478,0.45629506482356341,0.52194051382012818,0.58683676232166559,0.64885030219237294,0.70621569955306718,0.75770908143822491,0.80269845025094344,0.84108607850865102,0.87318485498546772,0.89957419011397355,0.92096911410314786,0.93811955858616614,0.95174321020779318,0.96248740371522623,0.97091255248582831,0.97748970852798123,0.98260630307183505,0.98657586631338812,0.9896490450363592,0.99202437036399904,0.99385799169255373,0.99527206705075055,0.99636177145005544,0.99720102470236227,0.99784710039903013,0.99834429276997638,0.99872680963929439,0.99902104056373831,0.99924732674386485,0.9994213372384968,0.99955513616519176,0.99965800856948428,0.99973709853231241],[0.055856468825819627,0.071464527445916415,0.091013541151885521,0.1152464330859042,0.14490292816895817,0.18063289375945893,0.22287675894875664,0.27172375269618232,0.32677471722211926,0.38705140915776948,0.45099827624524969,0.51660574440429741,0.58164571857287029,0.64396569647118018,0.70176228535429264,0.75376408099819758,0.79929193444443114,0.83820875549677432,0.870799441085367,0.89762696700242051,0.91939956240824883,0.93686726559714806,0.95075214957548293,0.96170812127907634,0.97030289288109384,0.97701463955098244,0.98223725513453608,0.98628986678234642,0.9894278175847202,0.991853492035775,0.99372615035527079,0.99517043205948397,0.99628347404202533,0.99714073682323134,0.99780069782610592,0.99830858827999025,0.99869934318572628,0.99899991517887832,0.99923108072697098,0.99940884491548221],[0.025627683562487631,0.033084863508801986,0.042617037328384358,0.054740073827631699,0.070059324896618314,0.089260899399666069,0.11308519528037063,0.14227497026548724,0.17749144179272935,0.21919716986940224,0.26751533050283516,0.32209075739741394,0.38199368987471655,0.44571256942010767,0.51126718736177246,0.5764365286304669,0.63905094224650261,0.69727030123904543,0.74977605982434559,0.79584156242927251,0.83528953742737133,0.86837592087280158,0.89564636770535977,0.91780162154944755,0.9355913695610526,0.94974181010979764,0.96091330754312165,0.96968085412018834,0.97652978520337264,0.98186052153288783,0.9859978605447024,0.98920191350347386,0.99167898333825699,0.99359149722492868,0.99506662308027882,0.99620349803556774,0.99707915419084325,0.99775329736608176,0.99827211517330483,0.99867128498843594],[0.011558049423769331,0.01498418592228002,0.01940598801775718,0.025099405170732374,0.032407978673184214,0.041753554648745431,0.05364472424993369,0.068679709056840815,0.087538757855338725,0.11095940457772042,0.13968688723803527,0.17439299569870753,0.21556147846212753,0.26334851855742386,0.31744227912855233,0.37696141574896141,0.44043911264415031,0.50592605884008746,0.5712102927794398,0.63410689209705018,0.69274028297760104,0.74574523590162278,0.79234728495275419,0.83232818381678364,0.86591394065696814,0.89363199068147303,0.91617488915273504,0.93429149650411691,0.9487118612655232,0.96010268050525915,0.9690462017189122,0.97603495418365105,0.98147594840092189,0.98569972516586657,0.98897123615867966,0.99150076847237323,0.99345397312570283,0.99496059408168958,0.99612180772289993,0.99701624916443521],[0.0051716661977388376,0.0067175617725238725,0.0087214997085660762,0.011316428231022829,0.014672004443021629,0.019003459741611439,0.024581741760933251,0.031744487604291632,0.040906819835042726,0.052570073676925164,0.067325293902287683,0.085846710299015042,0.10886866957959243,0.1371383559919489,0.17133737143462185,0.21196971921663749,0.25922364013304122,0.31282993011551991,0.37195553556286426,0.4351790632241887,0.50058357733330616,0.5659681263258739,0.62913442225236227,0.68817279296597356,0.74167185167496141,0.78880907180627458,0.82932446670972226,0.86341315327586554,0.89158343626658931,0.9145189616003313,0.9329672694216613,0.94766196867209818,0.95927595419673772,0.96839869746488461,0.975529951887116,0.98108337905750154,0.98539533587573358,0.98873568701577741,0.99131877011396186,0.99331351767070586],[0.0023058376846617819,0.0029976715491506476,0.0038962697065599372,0.0050628686056199239,0.0065764577887765163,0.0085386643819565615,0.011079801513318223,0.014366232112998053,0.01860912244878208,0.024074491264828166,0.031094143719278967,0.040076538101582078,0.051515779386407681,0.065995696082826516,0.084184351079519368,0.10681259594361023,0.13462904544501336,0.16832437072376175,0.20842190597421642,0.25514099307287613,0.30825433166006555,0.36697697618400504,0.42993356648373382,0.49524096257079842,0.5607111586814636,0.62413443209565689,0.6835684201948764,0.73755617437644383,0.78522691233320685,0.8262781712059829,0.86087321853968168,0.88950030699369542,0.91283343423032981,0.93161830838136972,0.94659179416954442,0.95843283867631146,0.96773809938910693,0.97501458036771504,0.98068265396629661,0.98508456553107071],[0.0010264416269535057,0.0013349244807438448,0.0017359564891367089,0.0022571924282214031,0.0029344739026328482,0.0038142000686274794,0.0049563484116803194,0.0064382985161140268,0.008359629645504036,0.010848068375353747,0.014066741265518859,0.018222815973874682,0.02357745500139288,0.030456704224832841,0.039262418638777816,0.050481502395799169,0.064690535040988789,0.082551275334307936,0.1047907867263498,0.13215861699043122,0.16535378158830683,0.20491803241629872,0.25110085006522598,0.303716078555055,0.36202664198371315,0.42470375479147437,0.48989943440362521,0.55544053242178681,0.61910784362842097,0.67892778018322308,0.73339849632969834,0.78160081592875297,0.82318909599035495,0.85829380368318708,0.88738220792328393,0.91111790154538608,0.93024423063331185,0.94550099584883884,0.95757304002697963,0.96706416173880294],[0.00045659471792566732,0.00059391977290597223,0.00077251467862490591,0.0010047600516114837,0.0013067353309626716,0.001699313291563622,0.0022095711468260409,0.0028726047655751462,0.0037338526364247642,0.0048520584192952897,0.0063030232999991796,0.0081843178381459936,0.010621129862962661,0.01377340661527717,0.017844383015438395,0.023090437639231354,0.029831930090303181,0.038464174610476701,0.049466907503501134,0.06340943312348879,0.080947079200151636,0.1028028427159452,0.12972672495114804,0.16242537887983854,0.20145807256242607,0.24710345894275448,0.2992157390101296,0.35710541429334919,0.41949074661403063,0.48456021169068741,0.55015740231994414,0.61405560089714317,0.67425151487546608,0.7291991352303091,0.77793081253066554,0.82005705386500927,0.85567458382685102,0.88522874698405507,0.90937195743060162,0.92884465072690114],[0.00020304392347201368,0.00026413139956173686,0.00034359124177972978,0.00044694466060878253,0.00058136906032413358,0.00075619275413174722,0.00098353600631382156,0.0012791406795047684,0.0016634422829877448,0.002162952380857599,0.0028120363708932852,0.0036551915401619927,0.0047499523901603094,0.0061705727020129825,0.0080126528300313339,0.010398888929818084,0.013486105220672638,0.017473669095929109,0.022613247158517771,0.029219586019537953,0.037681523148665449,0.048471663325782878,0.062152015685961327,0.079371360014742376,0.10084836275435616,0.12733301702522895,0.15953892480681212,0.19804198127645514,0.24314904300479276,0.29475385461298337,0.35221415089876756,0.41429564559459636,0.47922451118679471,0.54486293435724165,0.60897866938269063,0.66954029250214864,0.72495843440104146,0.7742169530996964,0.81688187228360842,0.85301524244636484],[9.0279249225858125e-05,0.00011744450768842346,0.0001527826133707231,0.00019875155664028106,0.00025854797193820746,0.00033632869147595012,0.00043749846646095849,0.0005690834183763781,0.00074021542874694627,0.00096275985499540498,0.001252128020491792,0.0016283272447675601,0.0021173151164682285,0.002752741525176267,0.0035781816458733844,0.0046499850256585965,0.0060408884768593952,0.0078445599946556834,0.010181250404536303,0.013204716446438117,0.017110522521740498,0.022145694812537774,0.028619440421508574,0.036914185345690485,0.047495442329361676,0.060917911191111895,0.077823716509390128,0.098926944049320911,0.12497713472203052,0.15669416945830958,0.1946696947799221,0.23923780136146464,0.2903309403255106,0.34735368557328467,0.40911953965901054,0.47389354643481801,0.53955830471266997,0.60387803535294504,0.66479480740310171,0.72067676302071504],[4.0138272570014032e-05,5.2216769992765196e-05,6.7929708560614824e-05,8.837052705982525e-05,0.00011496151214264428,0.00014955261622570028,0.00019454991317277071,0.00025308254153966225,0.00032921960045740933,0.00042825183248577041,0.00055705725509527944,0.00072457543775095363,0.0009424221637488857,0.0012256851097876907,0.0015939522966597294,0.0020726387764862025,0.002694693597113679,0.0035027885407935846,0.004552111948556592,0.0059139135497461044,0.0076799661814050237,0.0099681209581803307,0.012929121926583437,0.016754794343330319,0.021687595088882156,0.028031265379807168,0.036161886244114476,0.046537920859843991,0.05970675130047768,0.076303748992983755,0.097038182476044274,0.12265871378894172,0.15389085132343167,0.1913411311715007,0.2353699092984157,0.28594748451402185,0.34252482764938463,0.40396350015071786,0.46856852666405435,0.53424469873301272],[1.7845031612044358e-05,2.3215153590455764e-05,3.0201262568725284e-05,3.9289610537742937e-05,5.1112739765553822e-05,6.6493478437089658e-05,8.6502156416024792e-05,0.00011253100583741426,0.00014639089487341632,0.00019043707628126186,0.00024773261592462193,0.0003222607282103271,0.00041920054635518071,0.00054528509621822486,0.00070926566912990041,0.00092251369661646462,0.0011997999595762549,0.0015603018898525628,0.0020289032115004741,0.0026378665061445399,0.0034289785190046969,0.0044562896850220274,0.005789591994137794,0.0075187996885057199,0.0097594090721674753,0.012659205527665638,0.016406338315465806,0.021238765670336762,0.027454836621093187,0.035424354824327382,0.045598779166190442,0.058518170959989978,0.074811059527388021,0.095181672868675529,0.12037738462848592,0.15112869780571619,0.18805619095150133,0.2315455186609009,0.28160394901262642,0.33772836162926617],[7.9336052544319482e-06,1.0321103255416221e-05,1.3427072869873735e-05,1.7467717634222267e-05,2.2724296746259426e-05,2.9562697116236599e-05,3.8458891468600196e-05,5.003205111531795e-05,6.5087612387580839e-05,8.4673284385328987e-05,0.00011015187942453174,0.00014329600651604444,0.00018641116964421734,0.0002424957552468672,0.00031544890256057626,0.00041034048450557805,0.0005337615827209095,0.00069427916038438189,0.00090302541146798111,0.0011744608330486229,0.0015273608001389371,0.0019860886911204105,0.0025822347113242218,0.0033567185673499767,0.0043624756469611515,0.0056678690098781754,0.0073609902363794477,0.0095550250065828176,0.012394853312396703,0.016065010857612246,0.020799027395514671,0.026889933482566075,0.034701323990029447,0.044677701421366844,0.057351808479533424,0.073345252094461535,0.093357009301654637,0.1181327727056133,0.14840742573200569,0.18481475755040636],[3.5271299711249535e-06,4.5885722485561954e-06,5.9694393818876384e-06,7.7658560867789313e-06,1.0102873033645498e-05,1.3143170644611385e-05,1.7098381417756301e-05,2.2243818256055005e-05,2.8937632888607398e-05,3.764573602969645e-05,4.897421059971169e-05,6.3711468552402769e-05,8.2883076080420879e-05,0.00010782304699127844,0.00014026653882733204,0.00018247035655375314,0.0002373695711477771,0.00030878101823617353,0.00040166761027357872,0.0005224814684020527,0.00067960909540416554,0.00088394845596346042,0.0011496562391987515,0.001495114121226128,0.0019441758954079258,0.0025277732004056809,0.0032859763516101749,0.0042706281146706656,0.0055486909016773606,0.007206468941401316,0.0093548807689011072,0.012135953503598439,0.015730671014487586,0.020368204219274082,0.026336338878537861,0.033992530551701011,0.043774375739340399,0.056207305606695734,0.071905932754877569,0.091563785361017822],[1.568091048940743e-06,2.0399881408577688e-06,2.6538962942634743e-06,3.4525515606833403e-06,4.4915505703816218e-06,5.8432205468391386e-06,7.6016538020920279e-06,9.8892570432741689e-06,1.2865271174925479e-05,1.673685429006444e-05,2.1773498696416603e-05,2.8325784445037265e-05,3.6849772906425086e-05,4.793873520574386e-05,6.2364418636542222e-05,8.1130714255245231e-05,0.00010554344556576292,0.00013730110930977528,0.00017861283908053815,0.00023235172567187478,0.00030225403545982058,0.00039317797207064732,0.00051143961751827299,0.00066524880140742362,0.00086527416359847816,0.0011253749277245386,0.0014635472581797824,0.0019031459064784758,0.0024744574791310948,0.0032167202029380068,0.0041807062197996847,0.0054320050579600597,0.0070551682900580831,0.0091588900831174724,0.011882396448511768,0.015403180416802376,0.019946123172960288,0.025793839266172583,0.033297715208161861,0.042888494188569826],[6.9714098498712296e-07,9.0693695088107239e-07,1.1798683460813574e-06,1.5349349239686278e-06,1.9968541209663739e-06,2.5977816804265149e-06,3.3795500471955621e-06,4.3965803287193421e-06,5.719670488903609e-06,7.4409234063210549e-06,9.6801577235038052e-06,1.2593247543328973e-05,1.6382971144545413e-05,2.1313123282655461e-05,2.7726872378787981e-05,3.607063863302509e-05,4.6925152129434161e-05,6.1045847623141417e-05,7.9415398932502427e-05,0.00010331203463269723,0.00013439836466533914,0.00017483685725625398,0.00022743993020516695,0.00029586497857094971,0.00038486770159588658,0.00050063100246817613,0.00065119174594333203,0.00084699404983080572,0.0011016058840328186,0.0014326459209998141,0.0018629802002683177,0.0024222635607308108,0.0031489191045473634,0.0040926699286183308,0.0053177599300719041,0.0069070221135057921,0.0089669683592899802,0.011634074583470721,0.015082403242206945,0.019532614324514627],[3.099343741390402e-07,4.0320534162002749e-07,5.2454505376910218e-07,6.8240044211942946e-07,8.8776042770248182e-07,1.1549208934280983e-06,1.5024798596729129e-06,1.9546321358059731e-06,2.542853564300758e-06,3.3080920887418232e-06,4.3036181481584417e-06,5.5987327799681534e-06,7.2835914910162586e-06,9.4754795762280049e-06,1.2326975515641202e-05,1.6036570365196422e-05,2.0862481770769404e-05,2.714062318965301e-05,3.5307977426718833e-05,4.5932998560110799e-05,5.9755153493014942e-05,7.7736347038975914e-05,0.00010112779565936151,0.00013155698017939963,0.00017114068827321917,0.00022263194443571503,0.00028961093467656205,0.00037673301208604969,0.0004900507015245017,0.00063743153395654515,0.0008290998082864712,0.0010783383243458387,0.0014023961183252495,0.0018236606384643863,0.0023711679556252386,0.0030825426786522717,0.0040064800255873688,0.0052059050118381999,0.0067619655625214539,0.0087790326634918318],[1.3779034324879879e-07,1.7925667475270803e-07,2.3320179255521118e-07,3.033810330528864e-07,3.9467985328885246e-07,5.1345392539774219e-07,6.6797157718141479e-07,8.6898937782752119e-07,1.1305009358062567e-06,1.4707110327106739e-06,1.9133029011982157e-06,2.4890868584867454e-06,3.2381450483749132e-06,4.212621570398569e-06,5.480352184998481e-06,7.1295861998062296e-06,9.2751291224259169e-06,1.206633348426389e-05,1.5697493752828356e-05,2.0421368361467254e-05,2.6566769159125557e-05,3.4561441025356056e-05,4.4961821469272127e-05,5.8491746950096413e-05,7.6092792048569556e-05,9.8989731631574982e-05,0.00012877565911767971,0.00016752264570086804,0.00021792557533606378,0.00028348905233037278,0.00036877019660216405,0.00047969389661352995,0.00062396190491253219,0.00081158330704396073,0.0010555616909076414,0.001372784151266127,0.001785169460594481,0.0023211476613270443,0.0030175611736524871,0.003922098097226095],[6.1258700104010276e-08,7.9693764267628361e-08,1.0367663723073151e-07,1.3487686431522509e-07,1.7546641984744847e-07,2.2827090675866565e-07,2.9696625764457272e-07,3.8633463023619218e-07,5.0259731085096365e-07,6.5384779998136862e-07,8.5061522783985183e-07,1.1065973197570345e-06,1.4396139331643763e-06,1.8728475407087423e-06,2.4364570060296267e-06,3.1696769792146279e-06,4.1235490348595548e-06,5.3644746368142773e-06,6.9788371955842617e-06,9.0790148594760753e-06,1.1811202412654445e-05,1.5365586452837152e-05,1.9989581606219611e-05,2.6005048228200946e-05,3.3830688528484972e-05,4.4011177403900166e-05,5.7255051152672816e-05,7.4483983632863459e-05,9.6896866599435606e-05,0.00012605313213586735,0.00016398107871868663,0.0002133186761670056,0.00027749654023958854,0.00036097562635189492,0.00046955587114063481,0.00061077672998236931,0.00079443658499475352,0.0010332656472880749,0.0013437966073595051,0.0017474892762742887],[2.7234333629194236e-08,3.5430176983336586e-08,4.6092460166853653e-08,5.9963428306194625e-08,7.8008696133965106e-08,1.0148446830626063e-07,1.3202498881608165e-07,1.7175630717286886e-07,2.2344428100677278e-07,2.906871180443445e-07,3.7816586088614604e-07,4.9197025150981874e-07,6.4002265967177637e-07,8.3262958560068574e-07,1.0831991276514746e-06,1.4091743579147797e-06,1.833247577025967e-06,2.3849399692036965e-06,3.1026566098576196e-06,4.0363598597008268e-06,5.2510472113977595e-06,6.8312756283877694e-06,8.8870472193729207e-06,1.1561465780973007e-05,1.5040696884502516e-05,1.9566924315294516e-05,2.5455203877760583e-05,3.3115386241779429e-05,4.3080632284138323e-05,5.6044501450291054e-05,7.2909187319040734e-05,9.4848245232634245e-05,0.0001233881567016649,0.00016051437136527976,0.00020880914550226113,0.00027163066599878344,0.00035334574904695762,0.00045963200786109553,0.00059787000928580999,0.00077765184827876502],[1.210781346894778e-08,1.5751513581333986e-08,2.0491741177480431e-08,2.6658482927218179e-08,3.4681030982516523e-08,4.5117867749270954e-08,5.8695544110939027e-08,7.6359257568367163e-08,9.9338651233513582e-08,1.2923341419102075e-07,1.6812464217936831e-07,2.187197107966271e-07,2.8454074633234347e-07,3.7016981425566032e-07,4.8156789360145064e-07,6.2648984180304012e-07,8.1502423641592681e-07,1.0602956727041965e-06,1.3793784041542342e-06,1.794484923522264e-06,2.3345122185342689e-06,3.0370533300957575e-06,3.9510142232426889e-06,5.1400181037247943e-06,6.6868341039578568e-06,8.6991385278273343e-06,1.1317009532879504e-05,1.4722676671782122e-05,1.9153203467738546e-05,2.4916985011485809e-05,3.24152075247556e-05,4.2169761205245425e-05,5.4859545126222846e-05,7.136768415503755e-05,9.2842932385151837e-05,0.00012077951652902457,0.00015712094180324885,0.00020439492627366166,0.00026588875485031906,0.00034587708729489047],[5.3828798517037239e-09,7.0027924926202783e-09,9.1101982622315905e-09,1.1851802322001508e-08,1.5418458975392426e-08,2.0058457816106031e-08,2.6094808180300295e-08,3.3947725142803987e-08,4.4163882397030435e-08,5.7454468426897515e-08,7.4744695209052857e-08,9.7238205935765858e-08,1.2650086542137826e-07,1.645697661473405e-07,2.1409503823788125e-07,2.785243352286867e-07,3.6234283825042765e-07,4.7138548598217395e-07,6.1324316543943942e-07,7.9779113928417982e-07,1.0378764940923453e-06,1.3502124630367526e-06,1.7565418759933179e-06,2.2851507220512437e-06,2.9728371769360679e-06,3.8674731457795864e-06,5.0313366041060407e-06,6.5454466529621518e-06,8.5152029642301553e-06,1.1077722023453181e-05,1.441138057556578e-05,1.8748230123256609e-05,2.4390145841240663e-05,3.1729832641699262e-05,4.12781482437241e-05,5.3699641145356379e-05,6.9858770381743798e-05,9.0880012669115849e-05,0.00011822602102426984,0.00015379924159950376],[2.3931154426818226e-09,3.1132946178911829e-09,4.0502030127003037e-09,5.2690626660232156e-09,6.854723400589824e-09,8.9175695668154487e-09,1.1601204349512245e-08,1.5092446573255084e-08,1.9634335924512576e-08,2.5543051936511862e-08,3.3229924535244384e-08,4.323006838839177e-08,5.6239634407197797e-08,7.3164271623534724e-08,9.518217305930753e-08,1.2382609444783062e-07,1.6109005542959177e-07,2.0956815106718099e-07,2.7263513681131978e-07,3.5468135799687148e-07,4.6141837796750586e-07,6.0027658033612751e-07,7.809224232242645e-07,1.0159313521779376e-06,1.3216632134626715e-06,1.719401104572424e-06,2.2368329347703021e-06,2.9099788209167204e-06,3.7856984717785932e-06,4.9249530750291824e-06,6.4070487008694995e-06,8.33515652246357e-06,1.0843493968214935e-05,1.4106666427364026e-05,1.835181933595726e-05,2.3874445774881325e-05,3.1058948615747626e-05,4.0405386267550074e-05,5.2564259907415956e-05,6.8381757112131393e-05],[1.0639289135683537e-09,1.3841054646507911e-09,1.8006352799138532e-09,2.3425147098035964e-09,3.0474662059347856e-09,3.9645643357018642e-09,5.1576520641875087e-09,6.7097851247146466e-09,8.7290138688145128e-09,1.135590509374107e-08,1.4773327472513714e-08,1.9219181789918435e-08,2.5002962187562314e-08,3.2527301312716932e-08,4.231599921463884e-08,5.5050487190536786e-08,7.1617264971805033e-08,9.3169613535268712e-08,1.2120787960036241e-07,1.5768392070975294e-07,2.0513698168341035e-07,2.6687046126092377e-07,3.4718187420937197e-07,4.5166201720802956e-07,5.8758416417578532e-07,7.6441038368027758e-07,9.9445022383111225e-07,1.2937176159945444e-06,1.683045645815551e-06,2.1895367883962424e-06,2.8484495527120098e-06,3.705652852453831e-06,4.8208189284901633e-06,6.2715770384607666e-06,8.158916972539948e-06,1.0614218393226167e-05,1.3808395064396557e-05,1.7963790069918665e-05,2.3369649306431765e-05,3.0402249086049859e-05],[4.7300047131138417e-10,6.1534424799599137e-10,8.0052466433222923e-10,1.0414328894038683e-09,1.3548395338426971e-09,1.7625621208685766e-09,2.292983893618982e-09,2.9830296891696561e-09,3.8807364279281541e-09,5.0485971606846945e-09,6.5679114661037114e-09,8.5444450475828201e-09,1.1115792517076593e-08,1.4460955919195299e-08,1.8812805795460306e-08,2.447429225369567e-08,3.1839534560193839e-08,4.1421257385276513e-08,5.3886483647755697e-08,7.0102968676640682e-08,9.1199608150708923e-08,1.1864502504027583e-07,1.5434980627637863e-07,2.0079950620333805e-07,2.6122767563237722e-07,3.3984096159201086e-07,4.4211194761017162e-07,5.7516011986369258e-07,7.4824747900267139e-07,9.7342329785226569e-07,1.2663629069016828e-06,1.6474588949537613e-06,2.143240681244021e-06,2.788221270020547e-06,3.6272997287093082e-06,4.7188866038037678e-06,6.1389697929630711e-06,7.9864038230516185e-06,1.0389790586241799e-05,1.3516430266052615e-05],[2.1028608484469939e-10,2.7356914126165419e-10,3.5589646887232026e-10,4.6299921098009601e-10,6.0233322921275685e-10,7.8359813665913895e-10,1.0194125277542884e-09,1.3261924104353606e-09,1.7252939918332026e-09,2.2445003714966829e-09,2.9199556369571238e-09,3.7986810019456991e-09,4.9418481459412928e-09,6.4290376255949348e-09,8.363778803434742e-09,1.0880756950863515e-08,1.4155189241191984e-08,1.8415022333589719e-08,2.3956800671025688e-08,3.1166310148168061e-08,4.0545434237349911e-08,5.2747092133774486e-08,6.8620691100889439e-08,8.9271257128785177e-08,1.1613636021401849e-07,1.5108618931240773e-07,1.9655374353725229e-07,2.5570420265221589e-07,3.326552672741465e-07,4.327638073009901e-07,5.6299877288005362e-07,7.3242632700381437e-07,9.5284097049108066e-07,1.2395865923307537e-06,1.6126245983096148e-06,2.0979234683731645e-06,2.7292664647309667e-06,3.5506033144427542e-06,4.6191095458835728e-06,6.0091663997949021e-06],[9.3488780994783339e-11,1.2162310004548723e-10,1.5822410247679624e-10,2.05839734351031e-10,2.6778471531105382e-10,3.4837128982393772e-10,4.5320942022280206e-10,5.8959731921655766e-10,7.6702950843825403e-10,9.9785777107226523e-10,1.298151010184116e-09,1.6888138710177915e-09,2.1970419991448461e-09,2.8582152409483807e-09,3.718360579881461e-09,4.8373562635716061e-09,6.2931001741583418e-09,8.1869326191413473e-09,1.0650691045312186e-08,1.3855887783095481e-08,1.802564972129699e-08,2.3450251081246628e-08,3.0507320589175597e-08,3.9688129748788331e-08,5.1631792244764955e-08,6.7169755231565689e-08,8.7383679717781011e-08,1.1368073931853556e-07,1.4789157919962173e-07,1.923977544841053e-07,2.5029751954147387e-07,3.2562150927900778e-07,4.2361332663591445e-07,5.5109456868820484e-07,7.1693970158624864e-07,9.3269384106014631e-07,1.2133764425994022e-06,1.5785268458736172e-06,2.0535644519302586e-06,2.6715582103584781e-06]],\"type\":\"surface\",\"x\":[52,59.256410256410255,66.512820512820511,73.769230769230774,81.025641025641022,88.282051282051285,95.538461538461547,102.7948717948718,110.05128205128204,117.30769230769231,124.56410256410257,131.82051282051282,139.07692307692309,146.33333333333331,153.58974358974359,160.84615384615384,168.10256410256409,175.35897435897436,182.61538461538461,189.87179487179486,197.12820512820514,204.38461538461539,211.64102564102564,218.89743589743588,226.15384615384616,233.41025641025641,240.66666666666666,247.92307692307693,255.17948717948718,262.43589743589746,269.69230769230768,276.94871794871796,284.20512820512818,291.46153846153845,298.71794871794873,305.97435897435901,313.23076923076923,320.4871794871795,327.74358974358972,335],\"y\":[1.5129999999999999,1.6132820512820512,1.7135641025641024,1.8138461538461539,1.9141282051282051,2.0144102564102564,2.1146923076923079,2.2149743589743589,2.3152564102564104,2.4155384615384614,2.5158205128205129,2.6161025641025644,2.7163846153846154,2.8166666666666664,2.9169487179487179,3.0172307692307694,3.1175128205128209,3.2177948717948719,3.3180769230769229,3.4183589743589744,3.5186410256410259,3.6189230769230769,3.7192051282051284,3.8194871794871799,3.9197692307692309,4.0200512820512824,4.120333333333333,4.2206153846153853,4.3208974358974359,4.4211794871794874,4.5214615384615389,4.6217435897435895,4.7220256410256418,4.8223076923076924,4.9225897435897439,5.0228717948717954,5.1231538461538459,5.2234358974358983,5.3237179487179489,5.4240000000000004],\"opacity\":0.59999999999999998,\"name\":\"Predicted Probability Surface\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## The Guided Tour (Recorded)\n\nRotate the live surface yourself on the previous slide, or rewatch the recorded walkthrough anytime:\n\n<video src=\"../media/week-12/3d-logistic.mp4\" controls preload=\"metadata\"></video>\n\n# The Bayesian Version {background-color=\"#73000A\"}\n\n## Same Formula, Bayesian Machinery\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_bayes <- brm(am ~ hp + wt, data = cars_df,\n                   family = bernoulli(),\n                   chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n::: incremental\n- `family = bernoulli()` is brms's name for a 0/1 outcome: the switch that `family = binomial` flips in `glm()`\n- Everything else is Session 10's `brm()` pattern, compile pause included\n- **The prior:** none stated → `brms` defaults again. Your project's model will use these too, so **say so in your methods**: \"brms default priors, 2 chains × 2,000 iterations, seed 705\"\n- A full **posterior distribution** for each log-odds coefficient\n:::\n\n## Posterior Odds Ratios\n\nExponentiate the posterior summaries: dropping the intercept row, whose posterior is astronomically wide with only 32 cars:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(fixef(model_bayes)[-1, c(\"Estimate\", \"Q2.5\", \"Q97.5\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Estimate               Q2.5       Q97.5\nhp 1.05233926370 1.0168277428244001 1.120707968\nwt 0.00001855298 0.0000000008757284 0.006666486\n```\n\n\n:::\n:::\n\n\n::: incremental\n- Same story as `glm()`: horsepower nudges the odds of a manual up; weight crushes them\n- The payoff is the sentence you're *allowed to say*: \"Given the data and priors, there's a 95% probability the true odds ratio lies in this interval\", and with 32 cars, those honest intervals are huge. Watch them tighten on real data next.\n:::\n\n# Real Data: Chicago Neighborhoods {background-color=\"#1B2A4A\"}\n\n## The Question\n\nWhat separates Chicago's **high-violence** community areas from the rest?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas |> count(high_violence)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  high_violence     n\n  <lgl>         <int>\n1 FALSE            39\n2 TRUE             38\n```\n\n\n:::\n:::\n\n\n. . .\n\n`high_violence` ships in the file (it's in the [codebook](../chicago-data.qmd)): is the area's violent-crime rate above the **citywide median**? 38 above, 39 at or below.\n\n## Making a Binary Outcome\n\nThe line that built it:\n\n```r\nareas |> mutate(high_violence = violent_rate > median(violent_rate))\n```\n\n::: incremental\n- R treats `TRUE` as 1 and `FALSE` as 0, so a logical column drops straight into `glm()`\n- If your project outcome isn't binary yet, it may be one `mutate()` away too\n- One caution: cutting a continuous variable in half **throws away information**; defensible when the yes/no version is the question you actually care about\n:::\n\n## Look First (Always)\n\nOne predictor at a time before the model: unemployment against the outcome, with the fitted logistic curve:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-12-logistic_files/figure-revealjs/chicago-curve-1.png){width=960}\n:::\n:::\n\n\n## Fit It\n\nTwo predictors: unemployment and vacant housing, both plausible markers of concentrated disadvantage:\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nv_model <- glm(high_violence ~ unemployment_rate + pct_vacant,\n               data = areas, family = binomial)\nsummary(v_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = high_violence ~ unemployment_rate + pct_vacant, \n    family = binomial, data = areas)\n\nCoefficients:\n                  Estimate Std. Error z value  Pr(>|z|)    \n(Intercept)        -5.8208     1.3747  -4.234 0.0000229 ***\nunemployment_rate   0.3699     0.1100   3.363  0.000771 ***\npct_vacant          0.2849     0.1428   1.995  0.046007 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 106.73  on 76  degrees of freedom\nResidual deviance:  52.06  on 74  degrees of freedom\nAIC: 58.06\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n## The Coefficients, Translated\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(OR = coef(v_model), confint(v_model)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           OR        2.5 %     97.5 %\n(Intercept)       0.002965276 0.0001115289 0.02846386\nunemployment_rate 1.447590364 1.1934960639 1.84714872\npct_vacant        1.329619347 1.0371047252 1.83804694\n```\n\n\n:::\n:::\n\n\n::: incremental\n- **Unemployment: OR 1.45** [1.19, 1.85]; each additional point of unemployment multiplies an area's odds of high-violence status by ~1.45 (+45%), holding vacancy constant\n- **Vacancy: OR 1.33** [1.04, 1.84]; +33% odds per point, holding unemployment constant\n- For a *ratio*, no effect = **1**, not 0: both intervals exclude it. And these are associations, **not causes**: nobody randomly assigned unemployment to neighborhoods\n:::\n\n## Coefficients Into Cases\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_areas <- areas |>\n  filter(community %in% c(\"Forest Glen\", \"West Garfield Park\")) |>\n  select(community, unemployment_rate, pct_vacant)\n\ntwo_areas |>\n  mutate(p_high_violence = predict(v_model, newdata = two_areas,\n                                   type = \"response\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  community          unemployment_rate pct_vacant p_high_violence\n  <chr>                          <dbl>      <dbl>           <dbl>\n1 Forest Glen                      4.2        2.6          0.0286\n2 West Garfield Park              18.9       20            0.999 \n```\n\n\n:::\n:::\n\n\n. . .\n\nIn plain language: for an area like Forest Glen (4.2% unemployment, 2.6% vacant), the model puts the probability of high-violence status at about **3%**. For one like West Garfield Park (18.9%, 20.0%), it's over **99%**. That's a sentence a chief, or a city council, can actually use.\n\n## The Bayesian Version, Real Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nv_bayes <- brm(high_violence ~ unemployment_rate + pct_vacant,\n               data = areas, family = bernoulli(),\n               chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(fixef(v_bayes)[, c(\"Estimate\", \"Q2.5\", \"Q97.5\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Estimate          Q2.5      Q97.5\nIntercept         0.001792006 0.00007756542 0.02117534\nunemployment_rate 1.492292997 1.21912215721 1.92093080\npct_vacant        1.366238869 1.03527533301 1.87703700\n```\n\n\n:::\n:::\n\n\n. . .\n\nBoth traditions land in the same place: posterior odds ratios near the `glm()` estimates, credible intervals excluding 1. With 77 areas instead of 32 cars, the intervals are usably tight.\n\n## How to Report It: Frequentist\n\n> \"Each one-point increase in the unemployment rate was associated with 45% higher odds of being a high-violence area (OR = 1.45, 95% CI [1.19, 1.85]), holding vacancy constant. Predicted probabilities ranged from about 3% for the least-disadvantaged areas to over 99% for the most.\"\n\n. . .\n\nThe effect (as an odds ratio), the uncertainty, and a **probability a reader can feel**: all three, every time.\n\n## How to Report It: Bayesian\n\n> \"Given the data and priors, each one-point increase in unemployment multiplied the odds of high-violence status by about 1.5 (posterior mean OR 1.49, 95% credible interval [1.22, 1.92]).\"\n\n. . .\n\nSame three ingredients, and this one gets to make a direct probability statement about the odds ratio itself.\n\n## Your Turn (3 minutes, with a neighbor)\n\n::: {.your-turn}\nA reentry study models **re-arrest within 12 months** and reports two log-odds coefficients: **risk score (per point): 0.7** · **completed programming: -0.5**\n\n1. Convert both to odds ratios (Rosetta Stone, or `exp()` in R)\n2. Say each in a sentence a police chief would understand\n3. Audit your neighbor: did they say ***odds***, or slip into *probability*?\n:::\n\n. . .\n\n`exp(0.7)` ≈ 2.0: each risk point roughly **doubles the odds**. `exp(-0.5)` ≈ 0.61: about **39% lower odds**. Neither is a statement about *probability*.\n\n## The Toolbox Is Complete\n\n::: incremental\n- In Session 1 we predicted a robber's next move with a table you couldn't read. **You've now earned the tool the course opened with**: that table is just log-odds, and log-odds are just `exp()` away from sense\n- Descriptives → probability → inference → group comparison → correlation → regression → **logistic regression**\n- Nothing in your final project requires a method you haven't now practiced in both traditions\n- **Checkpoint 4, the final one, is in this week's homework:** fit and interpret *your* final model\n:::\n\n## Today's Lab & Homework\n\n- **Lab 11:** Chicago neighborhoods, then Alaska crashes at night ([lab page](../labs/lab-12-logistic.qmd))\n- **Homework 11:** your final-project model + **Project Checkpoint 4 (final)** ([assignment](../homework/hw-12.qmd))\n- **Code clinic, final half hour:** bring your project code and your two most stuck-on problems. **Presentation order is drawn today.**\n- Homework 11 due **Sunday, Nov 22**; full project due via Canvas **before midnight Sunday, Nov 29**, ahead of **Session 12 (Tue, Dec 1): presentations**, 8 min + 2 min Q&A ([details](../final-project.qmd)). No class Nov 17 or Nov 24\n",
    "supporting": [
      "week-12-logistic_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}