{
  "hash": "d5ed07b8697381ce1978f946d585041e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 12 · Logistic Regression: Chicago Neighborhoods, Then Alaska Nights\"\nsubtitle: \"CRJU 705 · Session 12\"\n---\n\n**Goal:** run the complete logistic-regression workflow from today's lecture — `glm(family = binomial)`, coefficients → odds ratios, odds ratios → predicted probabilities, and the Bayesian version with `brms` — first on the Chicago community areas, then on your own model of intoxicated crashes in the Alaska data.\n\nThis is the last lab with new statistical content: everything after today is your project. Treat this hour as a dress rehearsal — the workflow you practice here is exactly the workflow Checkpoint 4 asks for if your project outcome is binary.\n\n**How labs work:** run the Setup chunk as-is, follow the Walkthrough along with me, then complete the **Your Turn** tasks in your own script. The Exit Ticket gets submitted to Canvas before you leave.\n\n## Setup\n\nOpen RStudio, start a new R script, and run:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)\n\nareas   <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-areas.csv\")\ncrashes <- read_csv(\"https://smourtgos.github.io/crju705/data/crash-ak.csv\")\n```\n:::\n\n\n::: {.callout-warning appearance=\"simple\"}\n`brms` is the same package you installed for Lab 8 — nothing new to install. Same reminder as then: the first `brm()` of a session pauses at `Compiling Stan program...` for a minute before sampling. It is not frozen.\n:::\n\nTwo old friends: the 77 Chicago community areas (Homework 2, and the lecture thread ever since), and the 20,000 Alaska crashes (Labs 5 and 7, Homework 5 and 8's ANOVA cousin). Today the crash data plays the role of *your project dataset*: a binary outcome you care about, predictors you have to build yourself.\n\n## Walkthrough\n\n### Look at the outcome first\n\nOur binary outcome is `high_violence`: is the area's violent-crime rate above the citywide median? It ships in the file, but never trust a variable you haven't checked:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas |> count(high_violence)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  high_violence     n\n  <lgl>         <int>\n1 FALSE            39\n2 TRUE             38\n```\n\n\n:::\n\n```{.r .cell-code}\nareas |>\n  summarize(median_violent = median(violent_rate), .by = high_violence)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  high_violence median_violent\n  <lgl>                  <dbl>\n1 FALSE                   14.1\n2 TRUE                    43.0\n```\n\n\n:::\n:::\n\n\n38 areas above the median, 39 at or below (77 is odd, so the split isn't exactly even). The group medians are wildly different — the flag means what the codebook says it means.\n\nR treats `TRUE` as 1 and `FALSE` as 0, so a logical column drops straight into `glm()` — no conversion needed.\n\n### One predictor, seen\n\nBefore any multi-predictor model, look at the shape of the relationship. This is the lecture's curved hill, on real data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(areas, aes(unemployment_rate, as.numeric(high_violence))) +\n  geom_jitter(height = 0.04, width = 0, size = 2.5, alpha = 0.6) +\n  geom_smooth(method = \"glm\", method.args = list(family = \"binomial\"),\n              se = FALSE, color = \"firebrick\", linewidth = 1.2) +\n  labs(title = \"Probability of high-violence status rises with unemployment\",\n       x = \"Unemployment rate (%)\", y = \"High-violence area (0/1)\")\n```\n\n::: {.cell-output-display}\n![](lab-12-logistic_files/figure-html/look-curve-1.png){width=672}\n:::\n:::\n\n\nLow-unemployment areas pile up at 0, high-unemployment areas at 1, and the fitted curve climbs steeply through the middle — most of the action is between roughly 5% and 15% unemployment.\n\n### Fit the model\n\n`lm()` becomes `glm()` with `family = binomial`. That one argument is the entire syntax difference:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nv_model <- glm(high_violence ~ unemployment_rate + pct_vacant,\n               data = areas, family = binomial)\nsummary(v_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = high_violence ~ unemployment_rate + pct_vacant, \n    family = binomial, data = areas)\n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)        -5.8208     1.3747  -4.234 2.29e-05 ***\nunemployment_rate   0.3699     0.1100   3.363 0.000771 ***\npct_vacant          0.2849     0.1428   1.995 0.046007 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 106.73  on 76  degrees of freedom\nResidual deviance:  52.06  on 74  degrees of freedom\nAIC: 58.06\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\nBoth coefficients are positive with small p-values — but they're in **log-odds**, and nobody thinks in log-odds.\n\n### Exponentiate: log-odds → odds ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(OR = coef(v_model), confint(v_model)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           OR        2.5 %     97.5 %\n(Intercept)       0.002965276 0.0001115289 0.02846386\nunemployment_rate 1.447590364 1.1934960639 1.84714872\npct_vacant        1.329619347 1.0371047252 1.83804694\n```\n\n\n:::\n:::\n\n\nReading it out loud (the skill that matters):\n\n- **Unemployment, OR ≈ 1.45:** each additional percentage point of unemployment multiplies the odds of high-violence status by about 1.45 — 45% higher odds — *holding vacancy constant*.\n- **Vacancy, OR ≈ 1.33:** each additional point of vacant housing raises the odds by about 33%, *holding unemployment constant*.\n- For odds ratios, the no-effect value is **1** (not 0). Both 95% CIs sit entirely above 1.\n\n::: {.callout-important appearance=\"simple\"}\n**The classic mistake:** \"OR = 1.45 means the *probability* goes up 45%.\" No — the **odds** go up 45%. Odds = p/(1−p). The two only look alike when p is small. Say \"odds\" when you mean odds, and use `predict()` when you want probabilities.\n:::\n\n### Predicted probabilities: from effects to cases\n\nOdds ratios describe effects; decision-makers ask about *places*. `predict(type = \"response\")` answers on the probability scale:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_areas <- areas |>\n  filter(community %in% c(\"Forest Glen\", \"West Garfield Park\")) |>\n  select(community, unemployment_rate, pct_vacant)\n\ntwo_areas |>\n  mutate(p_high_violence = predict(v_model, newdata = two_areas,\n                                   type = \"response\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  community          unemployment_rate pct_vacant p_high_violence\n  <chr>                          <dbl>      <dbl>           <dbl>\n1 Forest Glen                      4.2        2.6          0.0286\n2 West Garfield Park              18.9       20            0.999 \n```\n\n\n:::\n:::\n\n\nAbout a 3% predicted probability for Forest Glen; over 99% for West Garfield Park. And the \"by hand\" version, so the machinery isn't a mystery — plug the log-odds prediction into `plogis()` (the inverse of the logit):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- coef(v_model)\nunname(plogis(b[1] + b[2] * 4.2 + b[3] * 2.6))   # Forest Glen's values, by hand\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02856804\n```\n\n\n:::\n:::\n\n\n### The Bayesian version\n\nSame formula, `bernoulli()` family, the Session 8 settings:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nv_bayes <- brm(high_violence ~ unemployment_rate + pct_vacant,\n               data = areas, family = bernoulli(),\n               chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(fixef(v_bayes)[, c(\"Estimate\", \"Q2.5\", \"Q97.5\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Estimate         Q2.5      Q97.5\nIntercept         0.001792006 7.756542e-05 0.02117534\nunemployment_rate 1.492292997 1.219122e+00 1.92093080\npct_vacant        1.366238869 1.035275e+00 1.87703700\n```\n\n\n:::\n:::\n\n\nThe posterior odds ratios land near the `glm()` estimates, and both 95% credible intervals exclude 1. The interpretation you're allowed to say out loud: *\"Given the data and priors, there's a 95% probability the unemployment odds ratio lies in this interval.\"*\n\n## Your Turn\n\nWork in your own script. Comment each answer. **The question:** what predicts whether an Alaska crash involves an intoxicated driver (`intox_any`)?\n\n**1. Build your predictors.** No dataset ships with your analysis variables — Lab 7's lubridate moves, one more time:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrashes <- crashes |>\n  mutate(\n    date    = mdy(date),                         # Lab 5/7 habit\n    hour    = hour(time),\n    weekend = wday(date, week_start = 1) >= 6,   # Mon = 1 … Sat = 6, Sun = 7\n    night   = hour >= 22 | hour < 4              # 10 p.m. – 3:59 a.m.\n  )\n# Sanity checks before modeling — always:\n# a) count(crashes, night) and count(crashes, weekend) — plausible shares?\n# b) mean(crashes$intox_any) — what's the baseline rate you're modeling?\n```\n:::\n\n\n**2. Fit and translate.** Model `intox_any` from `driver_age`, `night`, and `weekend`; then exponentiate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# intox_model <- glm(intox_any ~ driver_age + night + weekend,\n#                    data = crashes, family = binomial)\n# summary(intox_model)\n# exp(cbind(OR = coef(intox_model), confint(intox_model)))\n```\n:::\n\n\nIn comments: (a) interpret the `night` odds ratio in one plain sentence — Lab 7 found intoxication involvement \"nearly doubles\" at night; does the model agree? (b) interpret `weekend` the same way; (c) what do you conclude about `driver_age`? Its interval covers 1 — practice *saying that no evidence is the finding*.\n\n**3. Predicted probabilities for two drivers.** Contrast a 21-year-old driving on a weekend night with a 45-year-old on a weekday afternoon:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# profiles <- tibble(\n#   driver_age = c(21, 45),\n#   night      = c(TRUE, FALSE),\n#   weekend    = c(TRUE, FALSE)\n# )\n# profiles |> mutate(p_intox = predict(intox_model, newdata = profiles,\n#                                      type = \"response\"))\n```\n:::\n\n\nIn a comment: report both probabilities and compare them to the baseline rate from Task 1b. Notice the night OR is ~2 but neither probability is anywhere near \"double 50%\" — odds ratios multiply *odds*, and when p is small, doubled odds is roughly doubled probability, but it does **not** stay that way as p grows.\n\n**4. Odds-ratio translation drills.** No fitting — just fluency. For each coefficient below (from hypothetical logistic models), write one sentence: the odds ratio, the direction, and the percent change in odds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# a) beta = 0.30   (body-camera footage available -> case cleared)\n# b) beta = -1.00  (defense counsel at first appearance -> pretrial detention)\n# c) beta = 0.00   (defendant age -> failure to appear)\n# d) A classmate reads (b) as \"the probability of detention drops 63%.\"\n#    In a comment: what did they get wrong, and how would you fix the sentence?\n```\n:::\n\n\n**5. *(Stretch)* One more predictor.** Add `severity` to your crash model. Do the `night` and `weekend` odds ratios move much? In a comment: why does \"holding the other predictors constant\" matter when you tell the story?\n\n## Exit Ticket\n\nSubmit a short R script to Canvas before you leave, containing:\n\n1. A comment: why `lm()` is the wrong tool for a 0/1 outcome, in one or two sentences\n2. Your fitted crash model plus two interpretation sentences: one **odds-ratio** sentence (the `night` effect) and one **predicted-probability** sentence (your two driver profiles)\n3. A comment stating the difference between odds and probability — and which one an odds ratio multiplies\n4. A comment: which piece of today's workflow you'd use in your final project, and the one thing you most need help with at today's code clinic\n",
    "supporting": [
      "lab-12-logistic_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}