{
  "hash": "8d51379ba065c45ed490f331242d77b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo Walkthrough · Session 8\"\nsubtitle: \"Correlation: covariance, Pearson's r, what r cannot see, and cor.test()\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this page is.** The Session 8 correlation lecture, written down step by step. Every chunk below is self-contained: copy any of them into your own R session and they run as-is. Use this page to catch up after a missed class, or to re-run what happened on screen at your own pace. (The second half of Session 8, midterm review, is at the end of the [slides](../slides/week-10-correlation.qmd).)\n:::\n\n## What you'll build\n\n1. Covariance on real Chicago data, and the units problem that makes its size hard to read\n2. Pearson's r as rescaled covariance, computed by hand before `cor()` does it for you\n3. A calibration grid: what r = 0.1 through 0.9 actually *look* like\n4. Three demonstrations of what r cannot see: identical summaries, curves, and one point that flips a sign\n5. Spearman's rho as the rank-based backup\n6. The real question: which features of Chicago's 77 community areas track violence, tested with `cor.test()`, with the ecological-fallacy guardrail on every claim\n\n## Setup\n\nEverything below needs the tidyverse and the *second level* of the course's anchor data: 2025's incidents added up to the 77 community areas and joined with Census measures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(705)\n\nareas <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-areas.csv\",\n                  show_col_types = FALSE)\n```\n:::\n\n\n## 1 · Covariance: moving together, in raw units\n\nRow by row: do x and y sit on the *same side* of their averages?\n\n$$\\text{cov}(x, y) \\;=\\; \\frac{\\sum_i (x_i - \\bar{x})(y_i - \\bar{y})}{n - 1}$$\n\nBoth above average (or both below) gives positive products and a positive covariance; opposite sides give a negative one. The **sign** is trustworthy. The **size** is not. Watch what happens on real data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov(areas$unemployment_rate, areas$violent_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 107.7543\n```\n\n\n:::\n\n```{.r .cell-code}\ncov(areas$median_income,     areas$violent_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -482660.1\n```\n\n\n:::\n:::\n\n\nIs -482,660 a \"stronger\" relationship than 108? No idea. The first number is in *dollars times crimes per 1,000*, the second in *percentage points times crimes per 1,000*. **Covariance is glued to its units**, so you can't compare across pairs.\n\n## 2 · Correlation rescales it\n\nDivide the covariance by both standard deviations and the units cancel:\n\n$$r \\;=\\; \\frac{\\text{cov}(x, y)}{s_x \\, s_y}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov(areas$unemployment_rate, areas$violent_rate) /\n  (sd(areas$unemployment_rate) * sd(areas$violent_rate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8398579\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(areas$unemployment_rate, areas$violent_rate)   # same thing, one function\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8398579\n```\n\n\n:::\n:::\n\n\nAlways between -1 and +1, no units, comparable: income runs r = -0.71 with violence, so unemployment (0.84) tracks violence more tightly than income does, direction aside. The usual reading bands (about 0.8 and up \"very strong,\" 0.4 to 0.7 \"moderate,\" 0.1 to 0.3 \"weak,\" either sign) are **conventions, not laws**: in messy social-science data, a \"moderate\" r can be a major finding.\n\n## 3 · Calibrate your eye\n\nBefore trusting the bands, see them. Simulate five datasets with known correlations and look:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)   # inline seed: keeps these particular clouds (and their r labels) stable\nr_targets <- c(0.1, 0.3, 0.5, 0.7, 0.9)\n\nr_grid <- map(r_targets, \\(r) {\n  x <- rnorm(150)\n  y <- r * x + sqrt(1 - r^2) * rnorm(150)\n  tibble(label = paste0(\"r = \", sprintf(\"%.2f\", cor(x, y))), x = x, y = y)\n}) |>\n  list_rbind() |>\n  mutate(label = fct_inorder(label))\n\nggplot(r_grid, aes(x, y)) +\n  geom_point(alpha = 0.5, size = 1.4, color = \"navy\") +\n  facet_wrap(~label, nrow = 1) +\n  labs(title = \"Five simulated datasets, 150 points each\",\n       x = NULL, y = NULL) +\n  theme(axis.text = element_blank())\n```\n\n::: {.cell-output-display}\n![](demo-10-correlation_files/figure-html/r-grid-1.png){width=672}\n:::\n:::\n\n\n(The panel labels show each sample's *actual* r: 150 draws don't land exactly on the target, which is Session 4's sampling variability all over again.) By about 0.5 the trend is visible; below about 0.2 your eye mostly sees noise, and it's right. Negative correlations look the same with the tilt reversed.\n\n## 4 · What r cannot see\n\n### Same summaries, four different stories\n\nAnscombe's quartet ships with R (Anscombe, 1973): four little datasets built to share their summary statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanscombe_long <- anscombe |>\n  pivot_longer(everything(), names_to = c(\".value\", \"set\"), names_pattern = \"(.)(.)\")\n\nanscombe_long |>\n  summarize(mean_x = mean(x), mean_y = mean(y), r = cor(x, y), .by = set)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  set   mean_x mean_y     r\n  <chr>  <dbl>  <dbl> <dbl>\n1 1          9   7.50 0.816\n2 2          9   7.50 0.816\n3 3          9   7.5  0.816\n4 4          9   7.50 0.817\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(anscombe_long, aes(x, y)) +\n  geom_point(size = 2.5, color = \"navy\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"firebrick\", linewidth = 0.8) +\n  facet_wrap(~set, labeller = labeller(set = \\(s) paste0(\"Set \", s, \": r = 0.82\"))) +\n  labs(title = \"Same r, four completely different stories\", x = NULL, y = NULL)\n```\n\n::: {.cell-output-display}\n![](demo-10-correlation_files/figure-html/anscombe-1.png){width=672}\n:::\n:::\n\n\nSame averages, same r = 0.82, and only Set 1 is what you picture when someone says \"r = 0.82.\" **Always plot before you correlate.**\n\n### Limitation 1: r only sees straight lines\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)   # inline seed: stable curve\nu_data <- tibble(\n  x = seq(-4, 4, length.out = 50),\n  y = x^2 + rnorm(50, 0, 1)\n)\n\nggplot(u_data, aes(x, y)) +\n  geom_point(size = 2.5, color = \"chocolate3\") +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"chocolate3\") +\n  labs(title = \"A clear relationship that r cannot see\",\n       subtitle = paste0(\"Pearson's r = \", sprintf(\"%.2f\", cor(u_data$x, u_data$y)),\n                         \": the data follow a U-shaped curve\"),\n       x = \"Variable X\", y = \"Variable Y\")\n```\n\n::: {.cell-output-display}\n![](demo-10-correlation_files/figure-html/u-shape-1.png){width=672}\n:::\n:::\n\n\nThink stress and performance: an upside-down U. r near 0 means no **straight-line** relationship, not no relationship.\n\n### Limitation 2: one point can manufacture a correlation\n\nTwenty points of pure noise, then the same twenty plus a single wild point:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)   # inline seed: stable demo; the numbers below depend on it\nbase_data    <- tibble(x = 1:20, y = rnorm(20, 10, 4))   # pure noise\noutlier_data <- bind_rows(base_data, tibble(x = 25, y = 100))\n\nbind_rows(\n  base_data    |> mutate(version = paste0(\"20 points of pure noise: r = \",\n                                          sprintf(\"%.2f\", cor(base_data$x, base_data$y)))),\n  outlier_data |> mutate(version = paste0(\"Same noise + ONE outlier: r = \",\n                                          sprintf(\"%.2f\", cor(outlier_data$x, outlier_data$y))))\n) |>\n  mutate(version = fct_inorder(version)) |>\n  ggplot(aes(x, y)) +\n  geom_point(size = 2.5, color = \"grey35\") +\n  geom_point(data = \\(d) filter(d, y > 50), color = \"firebrick\", size = 4.5) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"navy\") +\n  facet_wrap(~version) +\n  labs(x = \"Variable X\", y = \"Variable Y\")\n```\n\n::: {.cell-output-display}\n![](demo-10-correlation_files/figure-html/outlier-demo-1.png){width=672}\n:::\n:::\n\n\nTwo lessons in one picture. First, the noise-only panel gave r = -0.28: **small samples produce correlations out of nothing**, which is why we test rather than just compute. Second, adding **one** extreme point swung r to +0.42: a single point flipped the sign *and* manufactured a \"moderate positive\" correlation. Neither number describes a real relationship. (Outliers can also work the other way, *hiding* a real correlation.) Defense one is plotting first; you'd catch this instantly. Defense two is a correlation that doesn't care about wild values.\n\n### The rank-based backup: Spearman's rho\n\nReplace each value with its **rank** (1st, 2nd, 3rd...), then correlate the ranks. Spearman asks only: *is the relationship consistently up, or consistently down?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(pearson  = cor(outlier_data$x, outlier_data$y),\n  spearman = cor(outlier_data$x, outlier_data$y, method = \"spearman\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   pearson   spearman \n 0.4235804 -0.1142857 \n```\n\n\n:::\n:::\n\n\nTo Spearman, the wild point is just \"rank 21\": rho drifts from -0.29 to -0.11, still weak, while Pearson flipped sign. When data are skewed or have wild values, check Spearman alongside Pearson.\n\n## 5 · Real data: structure and violence across Chicago\n\nA classic question about places: **which features of a neighborhood track its violence?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas |>\n  select(community, violent_rate, unemployment_rate, median_income, pct_vacant) |>\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  community   violent_rate unemployment_rate median_income pct_vacant\n  <chr>              <dbl>             <dbl>         <dbl>      <dbl>\n1 Rogers Park         21.7               7.1         60916        9.5\n2 West Ridge          12.2               7.3         70823        7.7\n3 Uptown              22.8               4.7         70067        9.1\n```\n\n\n:::\n:::\n\n\nRule from Section 4: plot first. One dot = one community area:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(areas, aes(unemployment_rate, violent_rate)) +\n  geom_point(size = 3, alpha = 0.7, color = \"firebrick\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"navy\") +\n  labs(title = \"Violent-crime rate and unemployment rate, 77 community areas\",\n       subtitle = paste0(\"r = \", sprintf(\"%.2f\", cor(areas$unemployment_rate, areas$violent_rate))),\n       x = \"Unemployment rate (%)\", y = \"Violent crimes per 1,000 residents\")\n```\n\n::: {.cell-output-display}\n![](demo-10-correlation_files/figure-html/unemp-scatter-1.png){width=672}\n:::\n:::\n\n\nAbout as strong as area-level associations get in criminology. And the full menu, in one dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas |>\n  select(violent_rate, unemployment_rate, pct_renter, median_income, median_age) |>\n  pivot_longer(-violent_rate, names_to = \"covariate\", values_to = \"value\") |>\n  mutate(covariate = case_match(covariate,\n    \"unemployment_rate\" ~ paste0(\"Unemployment rate: r = \",\n      sprintf(\"%.2f\", cor(areas$unemployment_rate, areas$violent_rate))),\n    \"pct_renter\" ~ paste0(\"% renter-occupied: r = \",\n      sprintf(\"%.2f\", cor(areas$pct_renter, areas$violent_rate))),\n    \"median_income\" ~ paste0(\"Median income: r = \",\n      sprintf(\"%.2f\", cor(areas$median_income, areas$violent_rate))),\n    \"median_age\" ~ paste0(\"Median age: r = \",\n      sprintf(\"%.2f\", cor(areas$median_age, areas$violent_rate))))) |>\n  ggplot(aes(value, violent_rate)) +\n  geom_point(alpha = 0.6, size = 2, color = \"navy\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"firebrick\", linewidth = 0.8) +\n  facet_wrap(~covariate, scales = \"free_x\") +\n  labs(title = \"Violent-crime rate and four neighborhood measures\",\n       x = NULL, y = \"Violent crimes per 1,000\")\n```\n\n::: {.cell-output-display}\n![](demo-10-correlation_files/figure-html/four-covariates-1.png){width=672}\n:::\n:::\n\n\nStrong positive (unemployment), moderate positive (renters), strong negative (income), and one genuine *nothing* (median age). Real data span the whole menu. Income is also where Pearson and Spearman disagree: the decline is real but **bent** (steep across lower-income areas, nearly flat among the richest), and income is right-skewed, so the rank-based Spearman runs stronger than Pearson because it only asks \"downhill?\", not \"straight line?\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(pearson  = cor(areas$median_income, areas$violent_rate),\n  spearman = cor(areas$median_income, areas$violent_rate, method = \"spearman\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   pearson   spearman \n-0.7069489 -0.8229750 \n```\n\n\n:::\n:::\n\n\n## 6 · These are areas, not people\n\nOur r = 0.84 says: **community areas** with higher unemployment rates record more violent crime per 1,000 residents.\n\n::: {.callout-important appearance=\"simple\"}\n**The ecological fallacy:** using an association between *groups* (areas, states, cities) to make claims about *individuals*. Our data contain **no individuals**. Nothing here says *unemployed people* commit violence.\n:::\n\nSaying it out loud, with area data. ✅ Defensible: \"Community areas with higher unemployment rates recorded higher violent-crime rates.\" ❌ Not defensible: \"Unemployed residents commit more violent crime,\" a claim about individuals these data can't see. ❌ Also not defensible: \"Unemployment drives up violence,\" a claim about cause; concentrated poverty, disinvestment, and policing patterns all lurk behind both variables. Correlation is a pattern, not proof of cause.\n\nThe classic example (Robinson, 1950): across U.S. **states**, more immigrants went with *higher* literacy; across **individuals**, immigrants had *lower* literacy. Immigrants had settled in states with high literacy. Adding people up into areas can weaken, exaggerate, or even **flip** a relationship.\n\n## 7 · Testing r: `cor.test()`\n\nSame question as every test since Session 6. **The null:** the true correlation is 0. *If* it were, how surprising would an r like ours be, with 77 areas? One function does the whole thing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunemp <- cor.test(areas$unemployment_rate, areas$violent_rate)\nunemp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  areas$unemployment_rate and areas$violent_rate\nt = 13.4, df = 75, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.7585749 0.8954023\nsample estimates:\n      cor \n0.8398579 \n```\n\n\n:::\n:::\n\n\nReading it: **r = 0.84**, with a 95% confidence interval of **0.76 to 0.90**. It is an interval for the *correlation*, so it lives between -1 and +1, and zero is far outside it. The p-value is below 2.2e-16: reject the null. Two perspective checks. First, with 77 areas, any r above about 0.22 (either sign) clears p < 0.05, so passing the test is a low bar and **the strength is the story**. Second, these 77 areas are *all of Chicago*, not a sample; read the null as a claim about the *process* that produces neighborhood outcomes.\n\n### When the answer is \"nothing here\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage <- cor.test(areas$median_age, areas$violent_rate)\nage\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  areas$median_age and areas$violent_rate\nt = -0.1336, df = 75, p-value = 0.8941\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.2385791  0.2092774\nsample estimates:\n        cor \n-0.01542445 \n```\n\n\n:::\n:::\n\n\nr = -0.02, and the interval runs from -0.24 to 0.21: **zero is inside**, so we fail to reject. The honest sentence: *these data show no evidence of a straight-line association between median age and violence*. That is **not** the same as proving there is none.\n\n### Several pairs at once\n\n`cor()` takes every numeric column you give it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nareas |>\n  select(violent_rate, unemployment_rate, median_income, pct_vacant) |>\n  cor() |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  violent_rate unemployment_rate median_income pct_vacant\nviolent_rate              1.00              0.84         -0.71       0.81\nunemployment_rate         0.84              1.00         -0.81       0.67\nmedian_income            -0.71             -0.81          1.00      -0.55\npct_vacant                0.81              0.67         -0.55       1.00\n```\n\n\n:::\n:::\n\n\nRead it like a mileage chart: each pair appears twice, and the 1s down the diagonal are each variable with itself. A good first look at a project's variables; then plot and `cor.test()` the pairs that matter.\n\n### How to report it\n\n> \"Across Chicago's 77 community areas, unemployment was strongly associated with the violent-crime rate, r = 0.84, 95% CI 0.76 to 0.90, p < 0.001. This is an area-level association; it does not speak to individuals.\"\n\nDirection, strength, uncertainty, and the level of analysis. Every time.\n\n## Try a variation\n\n1. `pct_no_hs_diploma` is the share of an area's adults without a high-school diploma. *Before computing anything*, write down your guess for the sign and rough size of its correlation with `violent_rate`. Then plot it and run `cor.test()`. Most people guess a strong positive; check what the data actually say, then try `pct_bachelors`.\n2. In the outlier demo, change the wild point from `y = 100` to `y = 40`, then `y = 15`. At what point does Pearson stop being fooled, and does Spearman ever care?\n3. Take a random 15 areas (`areas |> slice_sample(n = 15)`) and rerun the unemployment `cor.test()`. How much wider is the confidence interval with 15 areas instead of 77? Run it a few times: does r bounce around?\n",
    "supporting": [
      "demo-10-correlation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}