{
  "hash": "31c3bc50b544afec38f80ca7662cc658",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 8 · ANOVA: Three Classrooms, Then Real Crashes\"\nsubtitle: \"CRJU 705 · Session 8\"\n---\n\n**Goal:** run the complete ANOVA workflow from today's lecture — the two variances by hand, `aov()` + Tukey's HSD, and the Bayesian version with `brms` + `emmeans` — first on a small classroom example where you can check every number, then on real Alaska crash data.\n\nThe R4DS wrangling thread wrapped up before the break, so there's no new data-skills content today: this lab is pure statistics practice.\n\n**How labs work:** run the Setup chunk as-is, follow the Walkthrough along with me, then complete the **Your Turn** tasks in your own script. The Exit Ticket gets submitted to Canvas before you leave.\n\n## Setup\n\nOpen RStudio, start a new R script, and run:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)\nlibrary(emmeans)\n\ncrashes <- read_csv(\"https://smourtgos.github.io/crju705/data/crash-ak.csv\")\n```\n:::\n\n\n::: {.callout-warning appearance=\"simple\"}\n**First time using `brms`?** Install both new packages before anything else: `install.packages(c(\"emmeans\", \"brms\"))`. And when you run your first `brm()` model of a session, R will sit at `Compiling Stan program...` for a minute before sampling starts. That's normal — Stan is compiling your model into C++. It is not frozen. If instead you get an error mentioning a *compiler* or *toolchain*, flag me down.\n:::\n\nOur walkthrough data are the three classrooms from lecture — typed in by hand, because 15 numbers you can see beat 15,000 you can't when you're learning what a method *does*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclassrooms <- tibble(\n  score     = c(75, 80, 78, 74, 77,    # Class 1\n                88, 90, 92, 85, 87,    # Class 2\n                70, 65, 68, 72, 66),   # Class 3\n  classroom = factor(rep(c(\"Class 1\", \"Class 2\", \"Class 3\"), each = 5))\n)\n```\n:::\n\n\n**The question:** did these three classrooms perform differently, or are the differences just the usual student-to-student bounce?\n\n## Walkthrough\n\n### Look first\n\nAlways. Before any test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_means <- classrooms |>\n  summarize(mean_score = mean(score), .by = classroom)\n\nggplot(classrooms, aes(classroom, score)) +\n  geom_jitter(width = 0.08, height = 0, size = 3, alpha = 0.6) +\n  geom_boxplot(alpha = 0.2, width = 0.3) +\n  geom_point(data = class_means, aes(y = mean_score),\n             shape = 23, size = 5, fill = \"firebrick\") +\n  labs(title = \"Test scores by classroom\",\n       subtitle = \"Dots = individual students · Diamonds = class means\",\n       x = NULL, y = \"Test score\")\n```\n\n::: {.cell-output-display}\n![](lab-08-anova_files/figure-html/look-first-1.png){width=672}\n:::\n:::\n\n\nClass 2 sits high, Class 3 sits low, and the spread *inside* each class is modest. That's the whole ANOVA story in one picture — the rest of the lab is putting numbers on it.\n\n### The two variances, by hand\n\n**Within-group variance** = the average spread inside a class. **Between-group variance** = the spread of the class means themselves.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_stats <- classrooms |>\n  summarize(class_mean = mean(score), class_var = var(score), .by = classroom)\nclass_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  classroom class_mean class_var\n  <fct>          <dbl>     <dbl>\n1 Class 1         76.8       5.7\n2 Class 2         88.4       7.3\n3 Class 3         68.2       8.2\n```\n\n\n:::\n\n```{.r .cell-code}\nwithin_var  <- mean(class_stats$class_var)    # average spread inside a class\nbetween_var <- var(class_stats$class_mean)    # spread of the class means\n\nwithin_var\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.066667\n```\n\n\n:::\n\n```{.r .cell-code}\nbetween_var\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102.76\n```\n\n\n:::\n\n```{.r .cell-code}\nbetween_var / within_var                      # signal-to-noise ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.54151\n```\n\n\n:::\n:::\n\n\nThe class means are about **14.5 times** more spread out than chance bouncing within classes would produce. Strong signal.\n\n::: {.callout-note collapse=\"true\"}\n## Why won't this ratio match `aov()`'s F?\n\nBecause `aov()` scales the between-group signal by the **group size** before comparing it to the noise: a gap between means built on 5 students each is stronger evidence than the same gap built on 2. With equal groups, F = group size × our hand ratio — here, 5 × 14.5 ≈ 72.7. Watch for exactly that number below. Same logic, different units.\n:::\n\n### The frequentist ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_model <- aov(score ~ classroom, data = classrooms)\nsummary(class_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nclassroom    2 1027.6   513.8   72.71 1.96e-07 ***\nResiduals   12   84.8     7.1                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nReading the table against our hand math:\n\n- **Mean Sq Residuals = 7.1** — our within-group variance, exactly\n- **Mean Sq classroom = 513.8** — our between-group variance × 5 (the group size): 5 × 102.76\n- **F(2, 12) = 72.7, p ≈ 0.0000002** — far beyond anything a null world produces. *Something* differs.\n\n### Which classes differ? Tukey's HSD\n\nThe omnibus F never says *which* pairs. Tukey's HSD tests every pair while keeping the family-wise false-alarm rate at 5% (remember the pile-of-t-tests problem from lecture):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(class_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = score ~ classroom, data = classrooms)\n\n$classroom\n                 diff        lwr        upr     p adj\nClass 2-Class 1  11.6   7.114603  16.085397 0.0000456\nClass 3-Class 1  -8.6 -13.085397  -4.114603 0.0006899\nClass 3-Class 2 -20.2 -24.685397 -15.714603 0.0000001\n```\n\n\n:::\n:::\n\n\nAll three intervals exclude 0 with tiny adjusted p-values: every class differs from every other class.\n\n### The Bayesian version\n\nSame formula, Bayesian machinery. Fit once, then let `emmeans` do the summarizing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_bayes <- brm(score ~ classroom, data = classrooms,\n                   chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_post <- emmeans(class_bayes, ~ classroom)\nclass_post\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n classroom emmean lower.HPD upper.HPD\n Class 1     76.8      74.2      79.7\n Class 2     88.4      85.8      91.4\n Class 3     68.2      65.6      71.0\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n:::\n\n\nOne row per class: posterior median and 95% HPD interval for that class's mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(class_post)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate lower.HPD upper.HPD\n Class 1 - Class 2    -11.6    -15.45     -7.71\n Class 1 - Class 3      8.6      4.56     12.67\n Class 2 - Class 3     20.2     16.46     24.01\n\nPoint estimate displayed: median \nHPD interval probability: 0.95 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pairs(class_post)) +\n  geom_vline(xintercept = 0, linetype = 2)\n```\n\n::: {.cell-output-display}\n![](lab-08-anova_files/figure-html/plot-pairs-classrooms-1.png){width=672}\n:::\n:::\n\n\n**The interpretation rule for pairwise differences:** if an interval **crosses 0**, zero (\"no difference\") remains a credible value — no credible difference. If it **excludes 0**, the difference is credible. Here none of the three intervals crosses 0, so the Bayesian analysis agrees with Tukey: all three classes differ.\n\n## Your Turn\n\nWork in your own script. Comment each answer.\n\n**1. Flatten the classrooms.** Erase the group differences but keep the within-class spread:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclassrooms_flat <- classrooms |>\n  mutate(score = case_when(\n    classroom == \"Class 2\" ~ score - 12,\n    classroom == \"Class 3\" ~ score + 8,\n    .default = score\n  ))\n# Now recompute: class means, within_var, between_var, the ratio,\n# and rerun aov() + TukeyHSD() on classrooms_flat.\n```\n:::\n\n\nIn comments: which numbers changed, which stayed the same, and *why*? What does `aov()` conclude now, and what do the Tukey intervals do?\n\n**2. Real data — do injuries differ by crash cause?** The `crashes` data (20,000 real-world-style Alaska crashes, from Lab 5 and Homework 5) record each crash's `primary_cause`. Keep three causes and look first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrash3 <- crashes |>\n  filter(primary_cause %in% c(\"speeding\", \"distracted\", \"wildlife\"))\n\n# a) Compute mean, SD, and n of `injuries` for each cause (.by = primary_cause)\n# b) Make the look-first plot (boxplot + mean diamonds, as in the Walkthrough).\n#    Injuries are small whole numbers, so the boxes will look blocky —\n#    that's the data, not a bug. The diamonds are doing the real work here.\n```\n:::\n\n\n**3. Both traditions on `crash3`.** Run `aov()` + `summary()`, then `TukeyHSD()`. In comments: which pairs differ? One pair should *not* — name it, and report the interval that told you so. Then fit the Bayesian version (this one samples on ~8,800 rows — give it a minute or two) and check `pairs()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# aov() + summary() + TukeyHSD() on crash3\n# then:\n# crash_bayes <- brm(injuries ~ primary_cause, data = crash3,\n#                    chains = 2, iter = 2000, seed = 705, refresh = 0)\n# crash_post  <- emmeans(crash_bayes, ~ primary_cause)\n# pairs(crash_post)\n```\n:::\n\n\nDo the two traditions agree about which pair shows no real difference? And practically: how many *more* people are injured in the average speeding crash than the average wildlife crash?\n\n**4. *(Stretch)* All nine causes.** Rerun `aov()` and `TukeyHSD()` on the full `crashes` data — 9 groups means 36 pairwise comparisons. How many come out significant? Why would running 36 *unadjusted* t-tests instead be a terrible idea? (Lecture's false-alarm table has the number.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n\n## Exit Ticket\n\nSubmit a short R script to Canvas before you leave, containing:\n\n1. One sentence each, in comments: what within-group variance measures, what between-group variance measures, and what F compares\n2. Your crash-cause conclusion, two ways: one frequentist sentence (F and a Tukey pair) and one Bayesian sentence (an HPD interval) — each including the size of the difference in injuries, not just \"significant\"\n3. A comment naming the pair of crash causes that showed *no* credible difference, and what its interval looked like in each tradition\n4. A comment: why is ANOVA-then-Tukey better than running a pile of unadjusted t-tests?\n",
    "supporting": [
      "lab-08-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}