{
  "hash": "8a97fa941c890b25e5817123d1f0604e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demo Walkthrough · Session 4\"\nsubtitle: \"Sampling distributions, the standard error, and the CLT — all by simulation\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this page is.** The Session 4 lecture demos, written down step by step. Every chunk below is self-contained — copy any of them into your own R session and they run as-is. Use this page to catch up after a missed class, or to re-run what happened on screen at your own pace. (The simulations use `set.seed(705)`, so running this page top-to-bottom reproduces the lecture's numbers; run a chunk in isolation and your random draws will differ slightly — that's the point of the session, actually.)\n:::\n\n## What you'll build\n\n1. Theoretical vs. empirical probability, and the law of large numbers arriving on screen\n2. A population you can actually see — plus one sample, and one *nasty* sample from the tail\n3. The sampling distribution of the mean, built by brute force: 1,000 samples, 1,000 means\n4. The **standard error**: measured from simulation, checked against the formula — and the √n rule, why halving your uncertainty costs four times the data\n5. The central limit theorem working on the least normal variable imaginable: TRUE/FALSE arrest data\n6. The payoff of Session 2's IOU: why `var()` and `sd()` divide by n − 1\n\n## Setup\n\nEverything below needs only the tidyverse and two course datasets — 10,000 test scores (a population we get to fully observe, for once) and the 30,000-incident Chicago sample:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(705)\n\npop    <- read_csv(\"https://smourtgos.github.io/crju705/data/population-data.csv\",\n                   show_col_types = FALSE)\ncrimes <- read_csv(\"https://smourtgos.github.io/crju705/data/chicago-crimes-2025.csv\",\n                   show_col_types = FALSE)\n```\n:::\n\n\n## 1 · Theoretical vs. empirical probability\n\nIf the chance of being selected for a jury is 10% and you weren't picked in 10 tries, should you be surprised? Answering that requires separating two kinds of probability: **theoretical** (a fair coin is 50/50 by mathematical reasoning) and **empirical** (flip it and count). Ten flips:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflips_10 <- sample(c(\"heads\", \"tails\"), size = 10, replace = TRUE)\ntable(flips_10) / 10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nflips_10\nheads tails \n  0.6   0.4 \n```\n\n\n:::\n:::\n\n\nWith our seed, six heads — a 60/40 split from a perfectly fair coin. Now 10,000 flips:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflips_10k <- sample(c(\"heads\", \"tails\"), size = 10000, replace = TRUE)\ntable(flips_10k) / 10000\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nflips_10k\n heads  tails \n0.5055 0.4945 \n```\n\n\n:::\n:::\n\n\nWithin about half a percentage point of 50/50. Empirical results fluctuate in small samples but converge toward the theoretical value — the **law of large numbers**. Watch the convergence happen flip by flip:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlln <- tibble(\n  flip = 1:10000,\n  heads = sample(c(0, 1), size = 10000, replace = TRUE)\n) |>\n  mutate(running_prop = cumsum(heads) / flip)\n\nggplot(lln, aes(flip, running_prop)) +\n  geom_line(color = \"navy\") +\n  geom_hline(yintercept = 0.5, color = \"firebrick\", linetype = \"dashed\") +\n  labs(title = \"Proportion of heads in coin flips\",\n       x = \"Number of flips\", y = \"Proportion heads\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/lln-plot-1.png){width=672}\n:::\n:::\n\n\nNote how wild the first few hundred flips are — \"the long run\" can be longer than intuition expects. (So no, ten jury strikeouts shouldn't shock you.)\n\n## 2 · A population we can actually see\n\nIn real research we *never* observe the whole population. Today we cheat: `population-data.csv` holds all 10,000 scores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop |>\n  summarize(mean = mean(score), median = median(score),\n            sd = sd(score), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n   mean median    sd     n\n  <dbl>  <dbl> <dbl> <int>\n1  100.   100.  15.0 10000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqs <- quantile(pop$score, c(0.01, 0.05, 0.50, 0.95, 0.99))\n\nggplot(pop, aes(score)) +\n  geom_histogram(bins = 60, fill = \"grey85\", color = \"white\") +\n  geom_vline(xintercept = qs, linetype = \"dashed\", linewidth = 1,\n             color = c(\"firebrick\", \"goldenrod\", \"navy\", \"goldenrod\", \"firebrick\")) +\n  labs(title = \"The full population, with 1st / 5th / 50th / 95th / 99th percentiles\",\n       x = \"Score\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/pop-hist-1.png){width=672}\n:::\n:::\n\n\n### One sample of 30\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamp <- sample(pop$score, size = 30)\nmean(samp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 101.1614\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(samp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15.77515\n```\n\n\n:::\n:::\n\n\nClose to the truth (mean ≈ 100, SD ≈ 15) but not exact. That gap is **sampling error** — not a mistake, a fact of life. The question that drives the rest of the semester: *how wrong can one sample be?*\n\n### What if we sampled from the tail?\n\nDraw 10 scores from the bottom 5% of the population, and look at them in context:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail_scores <- pop |> filter(score < quantile(score, 0.05))\ntail_sample <- sample(tail_scores$score, size = 10)\nmean(tail_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70.43922\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(pop, aes(score)) +\n  geom_histogram(bins = 60, fill = \"grey85\", color = \"white\") +\n  geom_point(data = tibble(score = tail_sample), aes(y = 0),\n             color = \"firebrick\", size = 3) +\n  geom_vline(xintercept = mean(tail_sample), color = \"firebrick\", linewidth = 1.2) +\n  geom_vline(xintercept = mean(pop$score), color = \"black\",\n             linewidth = 1, linetype = \"dashed\") +\n  labs(title = \"A tail sample (red), seen in context — dashed line is the true mean\",\n       x = \"Score\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/tail-sample-1.png){width=672}\n:::\n:::\n\n\nNow pretend that sample is *all you ever get to see*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tibble(score = tail_sample), aes(score)) +\n  geom_histogram(bins = 5, fill = \"firebrick\", color = \"white\") +\n  geom_vline(xintercept = mean(tail_sample), color = \"navy\", linewidth = 1.2) +\n  geom_vline(xintercept = mean(pop$score), color = \"black\",\n             linewidth = 1, linetype = \"dashed\") +\n  xlim(50, 150) +\n  labs(title = \"The sample alone — its mean (navy) vs. the truth (dashed)\",\n       x = \"Score\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/tail-alone-1.png){width=672}\n:::\n:::\n\n\nIf this were your dataset, you'd report a \"typical\" score of about 70 — and be badly wrong. How often does that happen with a *random* sample? Simulation can answer that directly.\n\n## 3 · Do it a thousand times\n\nThe key move of the whole session: instead of drawing *one* sample, draw **1,000 samples of 30** and keep each sample's mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_means <- tibble(draw = 1:1000) |>\n  mutate(mean_score = map_dbl(draw, \\(d) mean(sample(pop$score, size = 30))))\n\nsample_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 2\n    draw mean_score\n   <int>      <dbl>\n 1     1       97.3\n 2     2      102. \n 3     3       96.0\n 4     4       96.5\n 5     5      101. \n 6     6      106. \n 7     7       98.4\n 8     8       98.4\n 9     9      106. \n10    10       97.7\n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\n(`map_dbl(draw, \\(d) …)` reads as \"for each draw, do this and return one number\" — Session 3's `replicate()`, tibble-flavored. See the [simulation verbs reference](../resources.qmd#simulation-verbs).)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sample_means, aes(mean_score)) +\n  geom_histogram(bins = 40, fill = \"steelblue\", color = \"white\") +\n  geom_vline(xintercept = mean(pop$score), color = \"firebrick\", linewidth = 1.2) +\n  labs(title = \"1,000 sample means (n = 30 each)\",\n       x = \"Sample mean\", y = \"Number of samples\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/sampling-dist-plot-1.png){width=672}\n:::\n:::\n\n\nThis histogram *of means* is a **sampling distribution**. It's centered on the true population mean, and it's dramatically narrower than the population itself:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverlay <- bind_rows(\n  tibble(value = pop$score,               what = \"Population of scores (SD ≈ 15)\"),\n  tibble(value = sample_means$mean_score, what = \"Sample means, n = 30 (SD ≈ 2.7)\")\n)\n\nggplot(overlay, aes(value, fill = what)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 60,\n                 position = \"identity\", alpha = 0.65, color = \"white\") +\n  scale_fill_manual(values = c(\"grey70\", \"firebrick\")) +\n  labs(title = \"The population vs. the sampling distribution of its mean\",\n       x = \"Score / sample mean\", y = \"Density\", fill = NULL) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/overlay-1.png){width=672}\n:::\n:::\n\n\nSame center, radically different spread. Individual scores wander all over; *averages of 30* stay close to home — a mean near 70, like our tail sample's, essentially never happens by random chance at n = 30.\n\n## 4 · The standard error\n\nThe SD of the sampling distribution has its own name — the **standard error** — and its own formula, which our simulation can check:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(sample_means$mean_score)   # SE measured from the simulation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.723601\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(pop$score) / sqrt(30)      # SE from the formula: SD / sqrt(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.733584\n```\n\n\n:::\n:::\n\n\nBoth land at about 2.7. The SE answers: *\"if I re-ran my study, how much would my estimate typically move?\"* — the single number underneath every confidence interval and hypothesis test to come.\n\n### Sample size buys precision (at √n prices)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmany_ns <- expand_grid(n = c(5, 30, 100), draw = 1:1000) |>\n  mutate(mean_score = map_dbl(n, \\(k) mean(sample(pop$score, size = k))))\n\nggplot(many_ns, aes(mean_score)) +\n  geom_histogram(bins = 40, fill = \"navy\", color = \"white\") +\n  geom_vline(xintercept = mean(pop$score), color = \"firebrick\", linetype = \"dashed\") +\n  facet_wrap(~n, labeller = label_both) +\n  labs(x = \"Sample mean\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/se-by-n-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmany_ns |>\n  summarize(simulated_se = sd(mean_score),\n            formula_se = sd(pop$score) / sqrt(first(n)),\n            .by = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n      n simulated_se formula_se\n  <dbl>        <dbl>      <dbl>\n1     5         6.53       6.70\n2    30         2.78       2.73\n3   100         1.50       1.50\n```\n\n\n:::\n:::\n\n\nSimulation and formula agree to within a couple of tenths at every n. And the SE shrinks like 1/√n — from about 6.6 at n = 5 to about 1.5 at n = 100 — so to *halve* your uncertainty you need *four times* the data.\n\n## 5 · The CLT, on the least normal variable imaginable\n\nBack to the 30,000 real Chicago incidents. Whether an incident ended in **arrest** is as far from a bell curve as data gets — every value is TRUE or FALSE:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrimes |> count(arrest) |> mutate(prop = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  arrest     n  prop\n  <lgl>  <int> <dbl>\n1 FALSE  25176 0.839\n2 TRUE    4824 0.161\n```\n\n\n:::\n:::\n\n\nTreat these 30,000 incidents as the population: true arrest proportion **0.161**. Now imagine an analyst who can only pull 100 case files at a time — and repeat that analyst's life 1,000 times:\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrest_props <- tibble(draw = 1:1000) |>\n  mutate(prop_arrest = map_dbl(draw, \\(d) mean(sample(crimes$arrest, size = 100))))\n\nggplot(arrest_props, aes(prop_arrest)) +\n  geom_histogram(binwidth = 0.01, fill = \"steelblue\", color = \"white\") +\n  geom_vline(xintercept = mean(crimes$arrest), color = \"firebrick\", linewidth = 1.2) +\n  labs(title = \"1,000 sample arrest proportions (n = 100 incidents each)\",\n       x = \"Proportion of sampled incidents with an arrest\", y = \"Samples\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/arrest-sim-1.png){width=672}\n:::\n:::\n\n\nA bell curve, out of TRUE/FALSE data. That's the **central limit theorem**: whatever shape the population has — even a two-bar TRUE/FALSE stack — the sampling distribution of a mean or proportion becomes approximately normal as n grows, centered on the true value. It's why polls of ~1,000 people work for a country of 330 million, and why we can attach a standard error to an arrest rate without ever seeing the full population.\n\n### The CLT obeys the √n rule too\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrest_ns <- expand_grid(n = c(25, 100, 400), draw = 1:1000) |>\n  mutate(prop_arrest = map_dbl(n, \\(k) mean(sample(crimes$arrest, size = k))))\n\nggplot(arrest_ns, aes(prop_arrest)) +\n  geom_histogram(binwidth = 0.01, fill = \"navy\", color = \"white\") +\n  geom_vline(xintercept = mean(crimes$arrest), color = \"firebrick\", linetype = \"dashed\") +\n  facet_wrap(~n, labeller = label_both) +\n  labs(title = \"Sample arrest proportions at n = 25, 100, 400\",\n       x = \"Sample proportion arrested\", y = \"Samples\")\n```\n\n::: {.cell-output-display}\n![](demo-04-sampling-distributions_files/figure-html/arrest-by-n-1.png){width=672}\n:::\n:::\n\n\nAt n = 25 a single sample can easily tell you the arrest rate is 8% — or 28%. At n = 400 the estimates cluster tightly, mostly within a couple of points of the truth.\n\n## 6 · Paying off Session 2's IOU: why n − 1\n\nIn Session 2 we noticed `var()` and `sd()` divide by **n − 1**, not n, and filed an IOU. Simulation pays the debt. Draw 5,000 tiny samples (n = 5) and compute each one's variance *both* ways:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_pop <- mean((pop$score - mean(pop$score))^2)   # true population variance\n\nvariance_sims <- tibble(draw = 1:5000) |>\n  mutate(\n    s           = map(draw, \\(d) sample(pop$score, size = 5)),\n    var_div_n   = map_dbl(s, \\(x) sum((x - mean(x))^2) / length(x)),\n    var_div_nm1 = map_dbl(s, \\(x) var(x))          # R's built-in: divides by n - 1\n  )\n\nvariance_sims |>\n  summarize(\n    true_variance   = var_pop,\n    avg_divide_by_n = mean(var_div_n),\n    avg_divide_by_n_minus_1 = mean(var_div_nm1)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  true_variance avg_divide_by_n avg_divide_by_n_minus_1\n          <dbl>           <dbl>                   <dbl>\n1          224.            179.                    223.\n```\n\n\n:::\n:::\n\n\n(`map()` builds a *list column* — each row's `s` holds an entire 5-value sample; the two `map_dbl()` calls then compute one number per sample. Don't sweat the list-column mechanics; watch the averages.) Across 5,000 samples, dividing by n averages about 179 against a true variance of about 224 — a **systematic** underestimate, not occasional bad luck. Why? A sample clusters around *its own* mean, which is always closer to the sample's values than the true population mean is, so measured spread comes up short. Dividing by n − 1 inflates each estimate just enough to land, on average, on the truth. That's all \"unbiased estimator\" means — and it's why R's defaults are built for samples, which is what your data will always be.\n\n## Try a variation\n\n1. **Random ≠ balanced.** Simulate two runs of 100 dice rolls (`sample(1:6, 100, replace = TRUE)`), bar-chart each, and ask a friend which die is loaded. (Neither is.)\n2. **The mystery population.** Run `unknown_pop <- rnorm(1000, 100, 50)` *without plotting it*, sample 30 values, plot only the sample, and write down what you'd conclude about the population. Then peek. Were you right?\n3. In the sampling-distribution chunk, change `size = 30` to `size = 300`. Before running: what should the new SE be, by the formula? Then check the simulation against your prediction.\n4. **Long-run policy math.** A drug field test has a 5% false-positive rate. Run `table(sample(c(\"false positive\", \"correct\"), 100, replace = TRUE, prob = c(0.05, 0.95)))` five times. How much does the false-alarm count bounce around — and what does that mean for judging a unit's performance from one month of data?\n",
    "supporting": [
      "demo-04-sampling-distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}