{
  "hash": "1c73d67a249ceb04a8209fa48f5d1e36",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Practice Problems · Session 11\"\nsubtitle: \"Multiple regression: slopes with units, R², lurking variables, and diagnostics\"\n---\n\n::: {.callout-note appearance=\"simple\"}\n**Ungraded self-checks.** Work each problem in your own R session *before* clicking the solution. These use different data and variables than the homework on purpose — if you can do these cold, Homework 11 (and Checkpoint 3's first regression on your own data) will feel routine.\n:::\n\n\n\nProblems that use data need only this setup — the same 100 cities as the Session 10 practice bank, where poverty and the violent-crime rate ran r = .61. Correlation said the two travel together; regression asks **how much**, and what a second predictor changes. One row = one **city** — every sentence you write stays at that level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)   # Problem 5 only — expect the usual compile pause\nlibrary(car)    # for vif()\n\ncities <- read_csv(\"https://smourtgos.github.io/crju705/data/cities-wide.csv\")\n```\n:::\n\n\n## Problem 1 · One predictor: make the slope speak units\n\nRegress `vcr_2025` (violent crimes per 100,000 residents) on `poverty_rate` (percentage points). Interpret the slope **with units**, say what the intercept means here (and whether any real city lives there), and connect R² to Session 10's r = .61.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncity_m1 <- lm(vcr_2025 ~ poverty_rate, data = cities)\nsummary(city_m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = vcr_2025 ~ poverty_rate, data = cities)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-477.63  -91.04   13.49   94.26  390.25 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   110.298     37.778   2.920  0.00435 ** \npoverty_rate   14.461      1.906   7.586 1.92e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 150.8 on 98 degrees of freedom\nMultiple R-squared:   0.37,\tAdjusted R-squared:  0.3635 \nF-statistic: 57.54 on 1 and 98 DF,  p-value: 1.92e-11\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(cities$poverty_rate, cities$vcr_2025)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3699531\n```\n\n\n:::\n:::\n\n\n- **Slope ≈ 14.5:** each additional percentage point of city poverty is associated with about **14.5 more violent crimes per 100,000 residents**, in this sample. Units on both ends or the number means nothing.\n- **Intercept ≈ 110:** the predicted rate for a city with 0% poverty — no city in the data comes close (the minimum is 4.4%), so it anchors the line rather than describing anywhere real.\n- **R² = .37**, which is exactly .61² — with one predictor, R² is last session's correlation squared: poverty accounts for about 37% of the city-to-city variance in violent-crime rates, leaving 63% to everything else.\n\nA slope is a *rate* with units (outcome units per predictor unit); R² is the share of outcome variance the model captures — two different questions about the same line.\n:::\n\n## Problem 2 · A second predictor: does it earn its keep?\n\nCities differ in police staffing too. Add `police_per_10k` (sworn officers per 10,000 residents) to the model. Compare the poverty slope across the two models, interpret the staffing coefficient with its 95% CI, and check what happens to **adjusted** R². Then write the honest one-sentence conclusion about staffing.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncity_m2 <- lm(vcr_2025 ~ poverty_rate + police_per_10k, data = cities)\nsummary(city_m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = vcr_2025 ~ poverty_rate + police_per_10k, data = cities)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-448.76  -91.34    5.14   85.70  379.28 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     179.978     59.917   3.004  0.00339 ** \npoverty_rate     14.592      1.897   7.694 1.19e-11 ***\npolice_per_10k   -3.232      2.166  -1.492  0.13889    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 149.9 on 97 degrees of freedom\nMultiple R-squared:  0.3841,\tAdjusted R-squared:  0.3714 \nF-statistic: 30.25 on 2 and 97 DF,  p-value: 6.188e-11\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(city_m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   2.5 %     97.5 %\n(Intercept)    61.060105 298.896503\npoverty_rate   10.828022  18.356175\npolice_per_10k -7.530335   1.066661\n```\n\n\n:::\n\n```{.r .cell-code}\nc(adj_m1 = summary(city_m1)$adj.r.squared,\n  adj_m2 = summary(city_m2)$adj.r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   adj_m1    adj_m2 \n0.3635241 0.3713927 \n```\n\n\n:::\n:::\n\n\nThe poverty slope barely moves (14.46 → 14.59) — poverty and staffing are nearly uncorrelated here (r ≈ .05), so there was almost no shared variance to reapportion. The staffing coefficient is **−3.2 violent crimes per 100k per additional officer per 10k residents, 95% CI [−7.5, 1.1], p = .14**: the interval spans zero, and adjusted R² ticks up only trivially (.364 → .371). The honest sentence: \"Holding poverty constant, police staffing showed no reliable association with the violent-crime rate in these cities.\" A new predictor has to earn its coefficient — a CI straddling zero and a flat adjusted R² is the data declining the offer, and *saying so* is a legitimate finding.\n:::\n\n## Problem 3 · The lurking third variable, caught in the act\n\nAcross 90 towns, an analyst finds that towns with more **licensed pawn shops** report far more **burglaries**, and drafts a memo proposing pawn-shop license caps. Simulate the analyst's data — note what actually generates both variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(705)   # inline seed: keeps this particular draw stable\ntowns <- tibble(\n  population = runif(90, 10, 120),                        # thousands of residents\n  pawn_shops = 1 + 0.09 * population + rnorm(90, 0, 1.4),\n  burglaries = 30 + 5.5 * population + rnorm(90, 0, 55)   # per year\n)\n```\n:::\n\n\n(a) Fit `burglaries ~ pawn_shops`. How does the coefficient look — and does anything in the output warn you it's misleading?\n(b) Now add `population`. What happens to the pawn-shop coefficient, and what does that tell the memo's author?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(burglaries ~ pawn_shops, data = towns) |> summary() |> coef() |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   63.323     25.188   2.514    0.014\npawn_shops    48.350      3.217  15.031    0.000\n```\n\n\n:::\n\n```{.r .cell-code}\nlm(burglaries ~ pawn_shops + population, data = towns) |> summary() |> coef() |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   37.007     12.830   2.884    0.005\npawn_shops     1.365      3.347   0.408    0.684\npopulation     5.290      0.329  16.056    0.000\n```\n\n\n:::\n:::\n\n\n(a) About **48 more burglaries per additional pawn shop**, p < .001 by a mile — and *nothing in the output warns you*. The model can only see the variables you gave it.\n\n(b) Holding population constant, the pawn-shop coefficient collapses to ≈ 1.4 with **p ≈ .68** — nothing — while population comes in at ≈ 5.3 burglaries per additional thousand residents. Bigger towns simply have more of *both*. That collapse is \"holding constant\" doing real work: comparing towns of the same size, pawn-shop counts tell you nothing about burglary. And the sobering corollary: regression can only hold constant the lurkers you **measured and included** — the ones you didn't are still at large.\n:::\n\n## Problem 4 · Diagnostics: the residual plot and VIF\n\nBack to the real model, `city_m2` from Problem 2. Make the residuals-vs-fitted plot and run `vif()`. For each: what is it checking, and what does it show *here*?\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(fitted = fitted(city_m2), residual = resid(city_m2)) |>\n  ggplot(aes(fitted, residual)) +\n  geom_hline(yintercept = 0, linetype = 2) +\n  geom_point(alpha = 0.7, color = \"grey30\") +\n  labs(x = \"Fitted violent-crime rate\", y = \"Residual\")\n```\n\n::: {.cell-output-display}\n![](practice-11_files/figure-html/p4-1.png){width=672}\n:::\n\n```{.r .cell-code}\nvif(city_m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  poverty_rate police_per_10k \n      1.002158       1.002158 \n```\n\n\n:::\n:::\n\n\n**The residual plot** checks whether the model's misses are patternless: no curve (the straight-line shape isn't visibly wrong) and roughly even spread across the fitted range. This one is what healthy looks like — a shapeless band centered on zero, no bend, no widening, with the biggest misses (reaching roughly ±400) scattered across the range rather than piling up at one end. Compare Lab 11's Chicago plot, where the spread visibly widened at high fitted values; that's the kind of pattern this plot exists to catch.\n\n**VIF** checks a different disease — predictor redundancy. Both values sit at ≈ 1.00 (poverty and staffing share almost nothing, r ≈ .05), so each coefficient is estimated on its own information. The residual plot audits the *misses*; VIF audits the *predictors* — one model, two separate health checks.\n:::\n\n## Problem 5 · Both traditions, one sentence each\n\nFit the Bayesian twin of `city_m2` with `brm()` (expect the *Compiling Stan program...* pause — normal, not frozen), look at the posterior summaries, and then write the pair of reporting sentences: one frequentist (estimate, CI, p) and one Bayesian (the credible-interval sentence you're allowed to say) about the **poverty** coefficient.\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncity_bayes <- brm(vcr_2025 ~ poverty_rate + police_per_10k, data = cities,\n                  chains = 2, iter = 2000, seed = 705, refresh = 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixef(city_bayes) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Est.Error  Q2.5  Q97.5\nIntercept        178.32     60.45 62.08 294.22\npoverty_rate      14.65      1.97 10.71  18.35\npolice_per_10k    -3.18      2.20 -7.46   1.01\n```\n\n\n:::\n:::\n\n\nThe posterior lands almost exactly on `lm()`'s estimates — expected with `brms` default priors (say so when you report: \"brms default priors, 2 chains × 2,000 iterations, seed 705\") and 100 cities of data.\n\n> **Frequentist:** \"Holding police staffing constant, each additional percentage point of poverty was associated with about 14.6 more violent crimes per 100,000 residents (b = 14.59, 95% CI [10.8, 18.4], p < .001).\"\n\n> **Bayesian:** \"Given the data and priors, there is a 95% probability the poverty coefficient lies between roughly 10.9 and 18.3 — zero is not a credible value.\"\n\nSame formula, nearly identical numbers — what changes is the sentence each tradition licenses, and the Bayesian one makes the direct probability statement the confidence interval never could.\n:::\n\n## Problem 6 · The sentence audit\n\nFour sentences drafted from the Problem 2 model. **Two are defensible; two are not.** Sort them, and fix the broken ones.\n\n> (a) \"Holding police staffing constant, each additional percentage point of poverty was associated with about 14.6 more violent crimes per 100,000 residents (95% CI [10.8, 18.4]).\"\n>\n> (b) \"Poverty drives up violent crime in American cities.\"\n>\n> (c) \"R² = .38, so the model correctly predicts 38% of cities.\"\n>\n> (d) \"Police staffing showed no reliable association with the violent-crime rate in these cities (b = −3.2, 95% CI [−7.5, 1.1]).\"\n\n::: {.callout-tip collapse=\"true\"}\n**Solution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(city_m2) |> round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 % 97.5 %\n(Intercept)     61.1  298.9\npoverty_rate    10.8   18.4\npolice_per_10k  -7.5    1.1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(city_m2)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3840918\n```\n\n\n:::\n:::\n\n\n**Defensible: (a) and (d).** Both state an *adjusted association*, with magnitude, units, uncertainty, and the holding-constant clause — and (d) shows that \"no reliable association\" is a reportable result, not a failure.\n\n**(b) fails twice:** \"drives up\" is a causal verb no cross-sectional model earns (lurkers we never measured are still at large — Problem 3's lesson), and \"American cities\" generalizes a 100-city sample to a population the data can't speak for. Fix: \"In these 100 cities, higher poverty was associated with higher violent-crime rates, holding staffing constant.\"\n\n**(c) misreads R²:** .38 is the **share of variance in the outcome** the model accounts for — not an accuracy rate, and not a count of cities predicted \"correctly.\" Fix: \"The two predictors together account for about 38% of the city-to-city variance in violent-crime rates.\" The audit habit: check every regression sentence for causal verbs, level of analysis, units, and what R² actually is.\n:::\n",
    "supporting": [
      "practice-11_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}